### ISSUE TITLE
Docker pull in 2.3.2 giving errors on tensorflow

### ISSUE THREAD

**Issue by tejahpc** [apptainer/singularity#1023]
## Version of Singularity:

2.3.2 

### Expected behavior

Should run tensorflow from docker pull

### Actual behavior

Throws an Import error
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

### Steps to reproduce behavior

git clone https://github.com/tensorflow/models.git
## Error occurs when using Singularity 2.3.2 using the command:
singularity exec --nv docker://tensorflow/tensorflow:latest-gpu python \ ~/models/tutorials/image/mnist/convolutional.py
# Error: ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

## Using the same command using singularity 2.3.1 works fine
singularity exec --nv docker://tensorflow/tensorflow:latest-gpu python \ ~/models/tutorials/image/mnist/convolutional.py
# This works

## Pulling the image using 2.3.1 and running the image in 2.3.2 works
# This is using 2.3.1
singularity pull docker://tensorflow/tensorflow:latest-gpu
# This is using 2.3.2
singularity exec --nv tensorflow-latest-gpu.img python ~/models/tutorials/image/mnist/convolutional.py
# This works!

## But pulling the image from 2.3.2 and running the image on either 2.3.1 or 2.3.2 gives the import error
# This is using 2.3.2
singularity pull docker://tensorflow/tensorflow:latest-gpu
# On either 2.3.1 or 2.3.2
singularity exec --nv tensorflow-latest-gpu.img python ~/models/tutorials/image/mnist/convolutional.py
# Error: ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

**Comment by vsoch** [comment]
hey @tejahpc ! Could you test using the development branch (the coming up 2.4?) We had a lot of changes to binding the libraries and hopefully the current is will work for you. @GodloveD will be able to take a look into it later or early tomorrow. Thanks!

**Comment by tejahpc** [comment]
Thanks. I won't be able to get to it until late next week. Will try 2.4 and
see whether that fixes it.

**Comment by GodloveD** [comment]
@tejahpc Sorry it took me a little while to get back to you.  I've just tried this using 2.3.2 and I can't replicate this error.  It works just fine in my environment.  I'm going to dig around a little more and I'll let you know if I turn anything up.

**Comment by GodloveD** [comment]
`libcusolver.so.8.0` is in the latest tensorflow container at `/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcusolver.so.8.0`.  It is not one of the libs that is imported with the `--nv` option because it is part of the CUDA suite and not a library associated with the driver.  There is no reason that I can see that pulling with one version and not the other will cause this error.

Could this have anything to do with the `pull` fix for docker meta-data @vsoch?

**Comment by vsoch** [comment]
Yes, that is definitely likely. If the version that @tejahpc is using was before the fix, there is no conceivable way I see it working. I think likely @tejahpc will be able to try development and have the issue resolved (fingers crossed!) :)

**Comment by GodloveD** [comment]
Well, the version that he is pulling is around 3mo old.  So it is possible that it is not in the new format and will still work in 2.3.1

**Comment by 0xaf1f** [comment]
@tejahpc is my colleague, so I'm running in the same environment as him. After
```
git clone https://github.com/tensorflow/models.git
```

I did, for each of versions 2.3.1, 2.3.2, and 2.4-development.gd69e6d8

```
rm -rf ~/.singularity
singularity exec -B $PWD:/mnt --nv docker://tensorflow/tensorflow:latest-gpu python /mnt/models/tutorials/image/mnist/convolutional.py
```
Here's the scoreboard:

version | result
| - | - |
2.3.1 | ✔️ 
2.3.2 | ❌ 
2.4-development.gd69e6d8 | ✔️ 

Not sure what happened with 2.3.2, but the current development is working again.

**Comment by GodloveD** [comment]
I wonder if this is related to the backwards manifest bug. @vsoch do you
think it could be?

**Comment by vsoch** [comment]
Didn't we have this conversation already.. [up there](https://github.com/singularityware/singularity/issues/1023#issuecomment-335215386)? :P

It's not clear to me why the middle version wouldn't work, but the earlier would. It could be the case that you had layers cached and didn't need to download them perhaps? Did it somehow retrieve an old image that did have an old manifest? Either way, TLDR - with the change to the docker manifests (most) docker images that have a manifest list (and not the old version) will not work with older versions of Singularity. There isn't much use in testing it because we know this to be true. We can only adopt to make it work moving forward (which we did). Apologies on behalf of Docker!

**Comment by 0xaf1f** [comment]
>It could be the case that you had layers cached and didn't need to download them perhaps? 

I tried to rule that out by deleting ~/.singularity before each attempt.

**Comment by vsoch** [comment]
What are we debugging? We know the bug.

**Comment by 0xaf1f** [comment]
I was primarily just testing development like you asked and tried to be more careful about the caching when testing the last two versions since @godloved said he couldn't reproduce it before.

If you all know what's going on and the reason for the regression is known, that's all that matters.

**Comment by dtrudg** [comment]
Closing this as we've now merged many fixes to docker layer extraction. Let us know if you have any further issues. Thanks!
