### ISSUE TITLE
Unknown command 'import'

### ISSUE THREAD

**Issue by djarecka** [apptainer/singularity#1036]
What should I use instead of `singularity import` in the dev version?

## Version of Singularity:

current master `2.4-master.g9aa890a`

### Expected behavior

I wanted to import a docker image using `singularity import`.

### Actual behavior

Unknown command 'import'

### Steps to reproduce behavior

Write here.

**Comment by GodloveD** [comment]
Hey.  It's been moved to the `image` command group.  `image.import`.  See if that works for you.

**Comment by djarecka** [comment]
Not sure how to use it. Do I need a local version of the image? Trying to do something similar to your example:

```
singularity create centos7.img
singularity import centos7.img docker://centos:7
```

**Comment by GodloveD** [comment]
Sorry.  Since 2.4 is not officially released yet we don't have docs ready to go/released.  `import` went through some changes and I don't think it's going to work with a URI anymore.  I think it expects an incoming tar stream.  

But there are a few ways to accomplish what you are trying to do in Singularity 2.4.  The most flexible is the new `build` command.  It will do the `create` and the `import` all in one step.

Try this:

```
singularity build centos7.simg docker://centos:7
```

**Comment by djarecka** [comment]
works! thank you!

**Comment by GodloveD** [comment]
:-)
