### ISSUE TITLE
Multi-layer docker image error

### ISSUE THREAD

**Issue by hra0031** [apptainer/singularity#1060]
### Expected behavior
```
Importing: base Singularity environment
Exploding layer: sha256:364f9b7c969aed6ff05b7ced04b1b53b824386288dffb1e6aec41d5a706dd51e.tar.gz
Exploding layer: sha256:de28b9f03aa4e757c01c9beecc72d1acfcb27cfff53e6ff8d0b4f5073a48df75.tar.gz
Exploding layer: sha256:3f23b445366629b3beaf4d41a971c0d2cebabe6da54c0e5d8f7113691b4bb110.tar.gz
```

### Actual behavior
When first layer of docker image is extracted, some folders don't have write permission. Another layer don't have access and fail to extract.
```
Importing: base Singularity environment
Exploding layer: sha256:364f9b7c969aed6ff05b7ced04b1b53b824386288dffb1e6aec41d5a706dd51e.tar.gz
Exploding layer: sha256:de28b9f03aa4e757c01c9beecc72d1acfcb27cfff53e6ff8d0b4f5073a48df75.tar.gz
tar: usr/lib64/libICE.so.6: Cannot create symlink to `libICE.so.6.3.0': Permission denied
tar: usr/lib64/libICE.so.6.3.0: Cannot open: Permission denied
tar: usr/lib64/libSM.so.6: Cannot create symlink to `libSM.so.6.0.1': Permission denied
tar: usr/lib64/libSM.so.6.0.1: Cannot open: Permission denied
tar: usr/lib64/libX11-xcb.so.1: Cannot create symlink to `libX11-xcb.so.1.0.0': Permission denied
tar: usr/lib64/libX11-xcb.so.1.0.0: Cannot open: Permission denied
tar: usr/lib64/libX11.so.6: Cannot create symlink to `libX11.so.6.3.0': Permission denied
tar: usr/lib64/libX11.so.6.3.0: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
Exploding layer: sha256:3f23b445366629b3beaf4d41a971c0d2cebabe6da54c0e5d8f7113691b4bb110.tar.gz
```

### Steps to reproduce behavior

Any Multi-layer docker image with overlaying files in layers. For example: ` singularity --debug shell docker://jdeathe/centos-ssh`

**Comment by GodloveD** [comment]
Hi @hra0031 .  Thanks very much for reporting this.  

In 2.4 we got rid of a bunch of the suid binaries which means we are requiring users to be root to do things they could have done as a normal users in 2.3.  For instance, if you issue the following command you will see the following warning:
```
$ singularity build test2 docker://godlovedc/lolcow
[...snip...]
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
```
The reason for that warning is the same as the problem you are seeing with the `shell` command.  Some files are not owned by root and can't be copied to the new container as a normal user.  In fact you would see all of the same `tar` errors,  except we are sending them to `/dev/null`!

But as the `build` warning suggests.  This is not really a big deal because the files that are not copied are those that are root owned and not readable (and by extension executable) by a normal user.  So unless you try running the container as root, and unless root tries performing an operation that requires one of those files, there is no problem.  

That said, I think we should be sending these errors to `/dev/null` too.  It should not be necessary to issue the same warning because in the case of `shell` and the other action commands it is impossible for the calling user to change to root at runtime.  

What do you think?

**Comment by hra0031** [comment]
Hi @GodloveD and thank you for the response.
I think we are dealing with another problem than you described. Maybe it is better described in #1061.
When I run singularity shell with command `singularity --debug shell docker://jdeathe/centos-ssh` I can see the problem with file extraction.
```
Exploding layer: sha256:e13fd3993c6baf6d09d8f603e64141bdd12a1a2f2d3428e8fc1d6659673d12b7.tar.gz
tar: usr/bin/.wh.localedef: Cannot hard link to `etc/.wh.ld.so.cache': Permission denied
tar: usr/bin/easy_install: Cannot open: Permission denied
tar: usr/lib/.wh.locale: Cannot hard link to `etc/.wh.ld.so.cache': Permission denied
tar: usr/lib64/.wh.gconv: Cannot hard link to `etc/.wh.ld.so.cache': Permission denied
tar: usr/sbin/.wh.build-locale-archive: Cannot hard link to `etc/.wh.ld.so.cache': Permission denied
```
The problem is, that all this folders (usr/bin, usr/lib, usr/lib64...) don't have write permissions (were extracted from another layer). This issue is solving while loop at L43:

https://github.com/singularityware/singularity/blob/3e338d75003f2a0a621c352bb4da2f0fc2ad9e50/libexec/handlers/image-docker.sh#L43-L51

The while loop is setting right permissions to all folders and files, so they can be overridden by another layer.
At this point is all OK but the TAR is providing filenames without buffering, from which it follows that the permissions are corrected before extraction ends. And I think, the TAR at end of extraction restore the permissions back to the original ones.

When I applied fix #1061, everything was working without any error and all files were extracted OK.
I didn't find any root's files in this docker image. I'm testing it on powerful nodes with 24 intel haswell cores, maybe on a slow machine, the permissions correction is slow enough to be processed after the TAR restore they permissions.

Can you test mentioned example with and without #1061 fix? 

Thank you in advance,

Josef Hrabal
IT4Innovations national supercomputing center

**Comment by GodloveD** [comment]
Ah.  Thanks for your patience.  That explanation makes much more sense.

**Comment by dtrudg** [comment]
Closing this as PRs fixing whiteout issues have been merged to development. Let us know if there are any remaining problems. Thanks!
