### ISSUE TITLE
Images from singularity hub not in gzip format

### ISSUE THREAD

**Issue by eriknstevenson** [apptainer/singularity#1089]
## Version of Singularity:

2.3.2-dist

### Expected behavior

Being able to run the `vsoch/hello-world` container from singularity hub.

### Actual behavior

```
$ singularity --verbose run shub://vsoch/hello-world
Increasing verbosity level (2)
Singularity version: 2.3.2-dist
Exec'ing: /usr/lib/x86_64-linux-gnu/singularity/cli/run.exec
Evaluating args: 'shub://vsoch/hello-world'
Progress |===================================| 100.0% 

gzip: ./vsoch-hello-world-master.img.gz: not in gzip format
ERROR Error extracting image, cleaning up.
ERROR: Could not locate downloaded image
ABORT: Aborting with RETVAL=255
```

An identical error occurs when I attempt to pull the image from singularity hub. I have tried with multiple different images with same results as well.

### Steps to reproduce behavior

I've shown all the steps I'm taking in the log above. I suspect this is working fine for others as I don't see a duplicate issue already. Any hints as to what may be happening here would be greatly appreciated. `singularity selftest` shows OK.

**Comment by vsoch** [comment]
hey @narrative ! This message is correct - the new singularity hub does *not* serve gzip format images, and the version of the software you are using expects them to be. You have a few options:

1. until end of 2017, you can pull the same (old gzip image) from the old singularity hub server, `shub://doc.fish/vsoch/hello-world`.
2. You can update your Singularity version to the current release to be able to handle any kind of image format.

What I can't do is change the updated singularity hub images to be the old format - we are highly advocating for squashfs because it's already compressed and more reliable to not degrade over time.

**Comment by eriknstevenson** [comment]
Thanks @vsoch for the quick response! I'll go ahead and upgrade my singularity version.
