### ISSUE TITLE
Singularity pull command replace .img with .simg extesion 

### ISSUE THREAD

**Issue by pditommaso** [apptainer/singularity#1095]
## Version of Singularity:

2.4-dist

### Expected behavior

The name of a pulled image should match the one specified by the user

### Actual behavior

It add the `.simg` extension even if `.img` was specified 

### Steps to reproduce behavior

```
$ singularity pull --name foo.img shub://qbicsoftware/qbic-singularity-megSAP
Progress |===================================| 100.0% 
Done. Container is at: /home/pditommaso/Downloads/foo.simg
```

When the pull is used programmatically, it breaks the script/application execution because it save the image with a name different from the one expected.

**Comment by apeltzer** [comment]
I can second on this unfortunately.

**Comment by pditommaso** [comment]
Let's see what singularity folks says. It doesn't seem to me a good idea to quietly change that name.

**Comment by apeltzer** [comment]
I absolutely agree - thats not good practice if that has been done with intent.

**Comment by pditommaso** [comment]
Still download manually is the best way :)

**Comment by vsoch** [comment]
I disagree a bit. I think an extension is essential to indicate the file type, and given that images going forward are squashfs (.simg), the user should be encouraged (and forced) to use simg. I'll likely change it back due to the disagreement here, but I do think it's important my reasons were shared.

**Comment by pditommaso** [comment]
I understand that there's a different image format in 2.4. Does the pull save the image in the new format regardless the file name provided by the user?

**Comment by apeltzer** [comment]
I can understand that moving people to  `simg` due to the switch to squashfs is indeed a good idea. However, if you specifically state you'd like to have a certain file name when pulling, then I'd personally expect to have exactly this filename instead. By default if you just pull with:

`singularity pull shub://path/to/repo`

I can totally understand in that case the switch to `simg`. I'd suppose a differentiation between naming your output (then taking whatever has been specified by the user) and without naming (then taking `simg`) could be a good solution. 

EDIT: In Singularity hub, this leads for example to having this here 
![screenshot from 2017-10-26 09-56-59](https://user-images.githubusercontent.com/2359510/32041362-11c71648-ba34-11e7-9cf7-d34a46191cfc.png)

`singularity pull --name customname.img shub://qbicsoftware/qbic-singularity-megSAP`
which leads however to a file qbic-singularity-megSAP-master.simg when being pulled with that command.

**Comment by pditommaso** [comment]
Tend to agree.

**Comment by pditommaso** [comment]
I could put a `mv name.simg name.img` just after the pull, but it's a bit ugly.

**Comment by GodloveD** [comment]
+1 if you specify `--name` you should get a file with that exact name.  There are a bunch of reasons why you wouldn't want any file extension at all.  And I don't think Singularity should enforce file extensions.  This is Linux after all, not Windows.

**Comment by pditommaso** [comment]
@GodloveD we may expect that you will fix this ?

**Comment by GodloveD** [comment]
Let's see what @vsoch has to say.  I just wanted to add my $0.02 that I think the user should get what they ask for.

**Comment by alaindomissy** [comment]
The  --name option is too astonishing for me. So I don't use it directly. Also that option is available for singularity pull but not for singularity run. Because of the systematic mv I need after all my pull and run commands I usually wrap them up into a singularitypull and singularityrun that do what I want. I wish I did not have to do that.

**Comment by vsoch** [comment]
I think the tribe has spoken! I feel strongly about a lot of things, but this isn't one of them. I'd say take the following approach:

 - if the file is squashfs, if no name specified  give extension .simg to encourage the user to have that association.
 - if the file is compressed .img.gz and no name command is specified, give the extension .img
 - if any other naming command (hash, commit) is specified, also give the corresponding association for the file
 - if a name is specified, use whatever it is, including the extension (or none)

**Comment by truatpasteurdotfr** [comment]
maybe name is the `basename` without the extension (simg for squashed, img for ext4, xxx for future ones), and we could have a `--filename` which would do what people are expecting ?

**Comment by pditommaso** [comment]
Adding a new option would not be backward compatible.

**Comment by vsoch** [comment]
That's a good suggestion @truatpasteurdotfr , but I think we should stick with one simple `--name` and be open to let the user decide the extension and file.

**Comment by vsoch** [comment]
take a look at #1101 and see if it is to your liking!

**Comment by pditommaso** [comment]
Well, I'm not a compiler :) but I guess it's fine as long as it implements the approach you mentioned in the above comment https://github.com/singularityware/singularity/issues/1095#issuecomment-339638428

**Comment by apeltzer** [comment]
Looks good to me after a quick check :-)

**Comment by dtrudg** [comment]
Closing this, as believed fixed with the merged PR. Thanks!
