### ISSUE TITLE
-n flag changed meaning without warning 2.3 -> 2.4

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#1105]
## Version of Singularity: 2.4

Running containers with nvidia passthrough.

On 2.3: `singularity run -n myimage.img` will pass through nvidia device drivers to container.

On 2.4 `singularity run -n myimage.img` will not pass through nvidia device, and instead isolates container in a private localhost-only network namespace.

### Expected behavior

run/exec command options that work on Singularity 2.3 work for 2.4, or there is a prominent warning about deprecation/changes. Singularity should be chatty on startup any time there is some change like this, or debugging issues is a pain.

Ideally flags are *never* reused for a different purpose without a deprecation/removal period.

### Actual behavior

Scripts that used the 2.3 command with `-n` flag are broken on 2.4 without warning. 

This is the type of thing that will, unfortunately, hinder adoption of Singularity for our HPC users who have no experience of Linux troubleshooting.

**Comment by vsoch** [comment]
Was the intention of `-n` to specify a new network namespace? I think the reason for this deprecated argument is that we've added a whole new suite of container instances, meaning you can start a container as an instance (and it has its entire own namespace). If this is the case, would it be appropriate to add a warning to the user to alert for the new command? Definite apologies for not having it... looks like we missed it!

**Comment by dtrudg** [comment]
In 2.4...
`    -n|--net            Run container in a new network namespace (loopback is
                        only network device active)
`
In 2.3...
`
    -n/--nv             Enable experimental Nvidia support
`

**Comment by vsoch** [comment]
ooooh that is not good. @GodloveD when was the `-n` added to indicate nvidia? I think we should just have `--nv` and maintain the `-n` to be what it was previously, or have it sort of "empty" with a warning message pointing to the update usage.

**Comment by GodloveD** [comment]
`-n` was short for `--nv` when we first added the option.  It looks like @gmkurtzer made an [executive decision](https://github.com/singularityware/singularity/commit/97fc9619187c4bf5becadf926ca9b36ede2d7fb0#diff-16243f794af9b641da58c98a1032b23a) to make it the short version of `--net` instead.

**Comment by dtrudg** [comment]
@vsoch  - the change of meaning in the CLI docs was ea61a3f56375048d1c80cd7fe291298967a5b7b8 and the actual change to the flag is in 97fc9619187c4bf5becadf926ca9b36ede2d7fb0

**Comment by GodloveD** [comment]
Well, what's done is done.  I don't think we should map the short `-n` option back to `--nv` because that change won't take effect until the next release and at that point others may have written scripts using `-n` for `--net`.  

Moving forward we need to be more careful about making changes that affect the user interface. 

Sorry that we made this change.  We shouldn't have.  Don't really know what else to say.  😞

**Comment by olifre** [comment]
> Sorry that we made this change. We shouldn't have. Don't really know what else to say. 😞

I think making this change in general is not a problem. 
The problem is that the release notes did not mention it, so users are not at all aware of the change, unless they read all commits / re-read all manpages / docs etc. 

Of course, if a parameter has a bad name, it should be allowed to change that, but users need to be informed about this change so they are not surprised by sudden breakage (or fatal data loss, depending on the change...) only after the upgrade.

**Comment by dtrudg** [comment]
Per comments in other release notes issue - I think this kind of stuff mostly gets picked up in testing phases and addressed well, as long as testing is easy enough. Singularity is a great project but the 2.4 release honestly feels from the outside like a somewhat rushed big push for some (very nice) technical jumps at the expense of usability (via breaking changes).

HPC is generally a pretty conservative place to be, and scientists are (rightly) much more adverse to their workflows being broken than webdevs using docker.

Trying not to sound too critical here, Singularity is truly awesome for us, and you are all doing fantastic work! It's just that the HPC pitch infers stability in the minds of HPC sysadmins that we don't neccessarily expect if using some other container platform, obviously focused at the fast-moving web/devops world.

**Comment by vsoch** [comment]
>>  the 2.4 release honestly feels from the outside like a somewhat rushed big push for some (very nice) technical jumps at the expense of usability (via breaking changes).

Yes, this is how I feel too. I hope that this kind of time pressure isn't a regular thing, because I don't like that kind of stress much at all. Missteps like this also lead to losing confidence of users, which is the worst thing that can happen for an open source project.

**Comment by bauerm97** [comment]
@dctrud This actually was probably my fault. @gmkurtzer asked me to quickly implement a patch for the network namespace, as it was requested for some demonstration using Singularity. I implemented this with both `-n` and `--net`, not realizing that it would step on the toes of `--nv` option (mostly because this was initially asked to be created as a hack for the demo). Sorry!

**Comment by GodloveD** [comment]
Hey this sucked, but I feel it is water under the bridge now.  I'm closing, but feel free to reopen if necessary.

**Comment by vsoch** [comment]
Water under the bridge! And we are building a boat! We got this :)

**Comment by dtrudg** [comment]
All good for me :-)
