### ISSUE TITLE
singularity import command is not worked in the version 2.4

### ISSUE THREAD

**Issue by zhcf** [apptainer/singularity#1123]
## Version of Singularity:
2.4

### Expected behavior
singularity import should work

### Actual behavior
it does not work

### Steps to reproduce behavior
singularity create /tmp/Debian.img
singularity import /tmp/Debian.img docker://ubuntu:latest

Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /root/.singularity/docker
Importing: base Singularity environment
ERROR  : Import is only allowed on Singularity image files
ABORT  : Retval = 255

**Comment by vsoch** [comment]
hey @zhcf ! Did you completely remove any and all previous versions of singularity, and if so, could you provide a full --debug output of the call? The command `import` has been deprecated to `image.import` so that's a third option to try. The fact that you aren't getting that warning message is telling me we may have some mixed up versions here.

**Comment by dtrudg** [comment]
Hi @zhcf - if you are still having issues, please note you should use `singularity build /tmp/Debian.img docker://ubuntu:latest`. As .@vsoch mentioned, the import command is deprecated. Let us know if any further issues. Thanks!
