### ISSUE TITLE
Create a temporary directory at build time for build artifacts

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1241]
## Version of Singularity:

development

### Desired behavior

Right now, many people cd to `/tmp` in a definition file when they are compiling things at build time.  That way all of the temporary compiled files don't end up in the container.  But doing this has its own issues.  If your def file fails for instance, things might not get cleaned up properly.  

@paulo7777 proposed another idea.  Create a new flag that a user can pass to build (maybe called `--rm-build-files` or something).  When this flag is created Singularity will take the following steps:

- `mktemp -d` a new directory (in addition to the temporary directory that is created to house the container during build).
- bind mount this new directory into the container so it's available during `%post`.  maybe somewhere like `/.singularity.d/build-files` or some such thing.
- `cd` to that location at the start of `%post` on behalf of the user
- at cleanup, delete the new directory so that all of the src and intermediate build files that the user downloaded and compiled go away and never see the inside of the container.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@GodloveD We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Copied to Apptainer issue #490. Closing it under Singularity.
