### ISSUE TITLE
headless OpenGL rendering using nvidia gpus and EGL libs

### ISSUE THREAD

**Issue by arpit15** [apptainer/singularity#1253]
## Version of Singularity:
2.4.2-master.g91881f7

## Problem
I am trying to do headless rendering using Nvidia EGL and OpenGL libs in a singularity container. 

I use [Singularity](https://gist.github.com/arpit15/7664833e2a5f4884d24d471f52299653) and then install Nvidia driver Version 375.26 to generate libOpenGL.so libEGL.so
The program which I am trying to run is in file([eglinfo.c](https://gist.github.com/arpit15/e21186411f9fb45c03a5d71f0a88b67a)) 

I am able to use the libs on my lab computer without singularity. However when I install everything in singularity and try to compile and run the same file I get an error. 

I don't know the source of error as the message from EGL is very sparse. Kindly let me know if you need anything else to debug this problem.

Host: Ubuntu 14.04 
Nvidia driver version 375.26
Guest: Ubuntu 16.04

### Expected behavior

The successful output I get on my lab computer without singularity is in file [eglinfo_output.txt](https://gist.github.com/arpit15/1a818ab4bb72d3bfa1b42a8563f6a219)

### Actual behavior
ERROR: Could not initialize EGL, error 0x3003
### Steps to reproduce behavior
```bash
sudo singularity image.create ubuntu.img
sudo singularity bootstrap ubuntu.img Singularity
sudo singularity exec --writable your_image.img apt install gcc g++ build-essential kmod -y software-properties-common
sudo singularity exec --writable your_image.img ./NVIDIA-Linux-x86_64-375.26.run -a --no-kernel-module -q --install-libglvnd

$singularity shell ubuntu.img
I compiled the eglinfo.c using the following command
$g++ -I. eglinfo.c /usr/lib/x86_64-linux-gnu/libEGL.so /usr/lib/x86_64-linux-gnu/libOpenGL.so -DMESA_EGL_NO_X11_HEADERS
```

**Comment by GodloveD** [comment]
Hey @arpit15!  Sorry you are having trouble.  Is the nvidia driver installed on the host system?  Instead of installing the nvidia driver into the container have you tried using the `--nv` option at runtime?

**Comment by arpit15** [comment]
@GodloveD Great! It works if I use host driver --nv. However this would limit the reproducibility. Can you kindly provide the reason for such a behaviour? 
Thank you for quick response.

**Comment by GodloveD** [comment]
Hi @arpit15!  I'm really glad `--nv` works for you. 

If the `--nv` option works but installing the driver directly into the container does not, it means there is likely something wrong with the nvidia libs installed within the container.  Maybe the driver version inside the container is not an exact match for the driver version running on the host system?  Or maybe you are missing some libs?

The nvidia driver installs kernel modules.  Software interacts with the kernel modules using libraries provided by the driver installation.  Your container shares the kernel with the host system and thus the kernel modules.  So the driver libs in your container must match the version installed on the host system exactly.  This is what the `--nv` option does for you.

Using the `--nv` option doesn't reduce reproducibility.  And it definitely does increase portability.  Consider the two alternatives.

#### installing nvidia drivers into your container:
This only works on a host system that has the exact same nvidia version as what is installed within the container.  So you cannot move your container to another host system unless it has identical drivers.  In other words it's not **portable**.  And if you try to run your container on a system with different drivers or on the same host system after a driver update it is _guaranteed_ to break.  In other words it's not **reproducible**. 

#### `--nv` option:
Now you can move your container to another host system with a different driver version, so it's **portable**.  You can also rerun your analysis without it breaking on a different host or on the same host after a driver update (assuming the newer driver is backward compatible with the older driver).  There is a slight chance that your analysis will run, but it will not be reproducible because backward compatibility is not not maintained on nvidia's end.  But this is a pretty small risk.  nvidia is strongly motivated to maintain backward compatibility with its drivers.  Even if this does happen the `--nv` option is still **more reproducible** than installing the drivers yourself, which is guaranteed to break (and thus not be reproducible) any time the driver version is not an exact match.  

Does that answer your question?  Thanks!

**Comment by arpit15** [comment]
@GodloveD Thanks for the detailed answer. I agree with your answer. It would great if you could point me to a documentation or singularity code which shows how `--nv` works. It would be great to know which libs does it share and how to build programs using the libs of the host. 
For ex: if I understand correctly my libs were compiled with the libs(`/usr/lib/x86_64-linux-gnu/libOpenGL.so`) of the wrong driver installed in my container. However they were run using libs present in the host which are located `/usr/lib64/libOpenGL.so` hostpath. It is unclear to me if my code worked because of backward compatibility maintained by the nvidia driver or it was just a chance thing.

**Comment by GodloveD** [comment]
[This](https://github.com/singularityware/singularity/blob/master/libexec/cli/action_argparser.sh#L125-L152) is where things currently start.  But you should also check out [this PR](https://github.com/singularityware/singularity/pull/1082) because we are going to start doing things differently.  

Basically, we are currently grepping `ld.so.cache` for anything on [this list](https://github.com/singularityware/singularity/blob/master/etc/nvliblist.conf).  But we are going to start using [nvidia-container-cli](https://github.com/NVIDIA/libnvidia-container) if it's installed and using `nvliblist.conf` as a backup.

**Comment by arpit15** [comment]
Thank you! This information cleared all my doubts.

**Comment by henzler** [comment]
Okay,
so I have basically exactly the same problem. However, I used the `--nv` option but for me it still does not work. Therefore, I have opened another issue. [Issue](https://github.com/singularityware/singularity/issues/1635)

**Comment by al3x609** [comment]
I found the fail, is `nvidia-container-cli list `,  this software genera a incomplete list of libs GL, the fix is remove libnvidia-container-tools, works for singularity but is necessary for docker. 

without this tool, the list in /.singularity.d/lib has libGL dependences.

**Comment by GodloveD** [comment]
Oh wow!  Nice catch @al3x609.  I wonder if that is because we are not using the correct flags to get graphics libraries from nvidia-container-cli or if nvidia-container-cli just isn't supplying them?  

@ctmadison is rewriting the `--nv` option for Singularity 3.0 and would probably like to know about this so that he can check that the appropriate flags are set in the code.  

If they are, and nvidia-container-cli is failing, we will need to raise an issue [here](https://github.com/NVIDIA/libnvidia-container/issues/new).

**Comment by al3x609** [comment]
the output for my config of `nvidia-container-cli list --binaries --ipcs --libraries`
```
/usr/bin/nvidia-debugdump
/usr/bin/nvidia-persistenced
/usr/bin/nvidia-cuda-mps-control
/usr/bin/nvidia-cuda-mps-server
/usr/lib64/libnvidia-ml.so.367.128
/usr/lib64/libnvidia-cfg.so.367.128
/usr/lib64/libcuda.so.367.128
/usr/lib64/libnvidia-opencl.so.367.128
/usr/lib64/libnvidia-ptxjitcompiler.so.367.128
/usr/lib64/libnvidia-fatbinaryloader.so.367.128
/usr/lib64/libnvidia-compiler.so.367.128
/usr/lib64/vdpau/libvdpau_nvidia.so.367.128
/usr/lib64/libnvidia-encode.so.367.128
/usr/lib64/libnvcuvid.so.367.128
/usr/lib64/libnvidia-eglcore.so.367.128
/usr/lib64/libnvidia-glcore.so.367.128
/usr/lib64/tls/libnvidia-tls.so.367.128
/usr/lib64/libnvidia-glsi.so.367.128
/usr/lib64/libnvidia-fbc.so.367.128
/usr/lib64/libnvidia-ifr.so.367.128
/usr/lib64/libGLX_nvidia.so.367.128
/usr/lib64/libEGL_nvidia.so.367.128
/usr/lib64/libGLESv2_nvidia.so.367.128
/usr/lib64/libGLESv1_CM_nvidia.so.367.128'
```

the list of nvliblist.conf
```
# exclude writing by non-privileged users.
/usr/bin/nvidia-smi
/usr/bin/nvidia-debugdump
/usr/bin/nvidia-persistenced
/usr/bin/nvidia-cuda-mps-control
/usr/bin/nvidia-cuda-mps-server

# put libs here (must end in .so)
libcuda.so
libEGL_installertest.so
libEGL_nvidia.so
libEGL.so
libGLdispatch.so
libGLESv1_CM_nvidia.so
libGLESv1_CM.so
libGLESv2_nvidia.so
libGLESv2.so
libGL.so
libGLX_installertest.so
libGLX_nvidia.so
libglx.so
libGLX.so
libnvcuvid.so
libnvidia-cfg.so
libnvidia-compiler.so
libnvidia-eglcore.so
libnvidia-egl-wayland.so
libnvidia-encode.so
libnvidia-fatbinaryloader.so
libnvidia-fbc.so
libnvidia-glcore.so
libnvidia-glsi.so
libnvidia-gtk2.so
libnvidia-gtk3.so
libnvidia-ifr.so
libnvidia-ml.so
libnvidia-opencl.so
libnvidia-ptxjitcompiler.so
libnvidia-tls.so
libnvidia-wfb.so
libOpenCL.so
libOpenGL.so
libvdpau_nvidia.so
nvidia_drv.so
tls_test_.so
```
my _ldconfig -p_
````
ldconfig -p | grep GL
	libOpenGL.so.0 (libc6,x86-64) => /lib64/libOpenGL.so.0
	libOpenGL.so.0 (libc6) => /lib/libOpenGL.so.0
	libOpenGL.so (libc6,x86-64) => /lib64/libOpenGL.so
	libOpenGL.so (libc6) => /lib/libOpenGL.so
	libGLdispatch.so.0 (libc6,x86-64) => /lib64/libGLdispatch.so.0
	libGLdispatch.so.0 (libc6) => /lib/libGLdispatch.so.0
	libGLX_nvidia.so.0 (libc6,x86-64) => /lib64/libGLX_nvidia.so.0
	libGLX_nvidia.so.0 (libc6) => /lib/libGLX_nvidia.so.0
	libGLX.so.0 (libc6,x86-64) => /lib64/libGLX.so.0
	libGLX.so.0 (libc6) => /lib/libGLX.so.0
	libGLX.so (libc6,x86-64) => /lib64/libGLX.so
	libGLX.so (libc6) => /lib/libGLX.so
	libGLESv2_nvidia.so.2 (libc6,x86-64) => /lib64/libGLESv2_nvidia.so.2
	libGLESv2_nvidia.so.2 (libc6) => /lib/libGLESv2_nvidia.so.2
	libGLESv2.so.2 (libc6,x86-64) => /lib64/libGLESv2.so.2
	libGLESv2.so.2 (libc6) => /lib/libGLESv2.so.2
	libGLESv2.so (libc6,x86-64) => /lib64/libGLESv2.so
	libGLESv2.so (libc6) => /lib/libGLESv2.so
	libGLESv1_CM_nvidia.so.1 (libc6,x86-64) => /lib64/libGLESv1_CM_nvidia.so.1
	libGLESv1_CM_nvidia.so.1 (libc6) => /lib/libGLESv1_CM_nvidia.so.1
	libGLESv1_CM.so.1 (libc6,x86-64) => /lib64/libGLESv1_CM.so.1
	libGLESv1_CM.so.1 (libc6) => /lib/libGLESv1_CM.so.1
	libGLESv1_CM.so (libc6,x86-64) => /lib64/libGLESv1_CM.so
	libGLESv1_CM.so (libc6) => /lib/libGLESv1_CM.so
	libGL.so.1 (libc6,x86-64) => /lib64/libGL.so.1
	libGL.so.1 (libc6) => /lib/libGL.so.1
	libGL.so (libc6,x86-64) => /lib64/libGL.so
	libGL.so (libc6) => /lib/libGL.so
	libEGL_nvidia.so.0 (libc6,x86-64) => /lib64/libEGL_nvidia.so.0
	libEGL_nvidia.so.0 (libc6) => /lib/libEGL_nvidia.so.0
	libEGL.so.1 (libc6,x86-64) => /lib64/libEGL.so.1
	libEGL.so.1 (libc6) => /lib/libEGL.so.1
	libEGL.so (libc6,x86-64) => /lib64/libEGL.so
	libEGL.so (libc6) => /lib/libEGL.so
````
___

after remove nvidia-container-cli 

````
singularity exec --nv Paraview.5.5.2.simg ls -l /.singularity.d/libs | awk '{ print $9 }'

libcuda.so
libcuda.so.1
libEGL_nvidia.so.0
libEGL.so
libEGL.so.1
libGLdispatch.so.0
libGLESv1_CM_nvidia.so.1
libGLESv1_CM.so
libGLESv1_CM.so.1
libGLESv2_nvidia.so.2
libGLESv2.so
libGLESv2.so.2
libGL.so
libGL.so.1
libGLX_nvidia.so.0
libGLX.so
libGLX.so.0
libnvcuvid.so
libnvcuvid.so.1
libnvidia-cfg.so
libnvidia-cfg.so.1
libnvidia-compiler.so.367.128
libnvidia-eglcore.so.367.128
libnvidia-egl-wayland.so.367.128
libnvidia-encode.so
libnvidia-encode.so.1
libnvidia-fatbinaryloader.so.367.128
libnvidia-fbc.so
libnvidia-fbc.so.1
libnvidia-glcore.so.367.128
libnvidia-glsi.so.367.128
libnvidia-gtk2.so.367.128
libnvidia-gtk3.so.367.128
libnvidia-ifr.so
libnvidia-ifr.so.1
libnvidia-ml.so
libnvidia-ml.so.1
libnvidia-opencl.so.1
libnvidia-ptxjitcompiler.so.367.128
libnvidia-tls.so.367.128
libOpenCL.so
libOpenCL.so.1
libOpenGL.so
libOpenGL.so.0
libvdpau_nvidia.so
````
the source file [libexec/functions.sh](https://github.com/al3x609/singularity/blob/579c41508b4eb824c9f00e77a1fbf2b45fb7c637/libexec/functions#L456)

**nvidia-container-cli** does not take into account the openGL libraries in /lib - /lib64 - /usr/lib - /usr/lib64


your "bind_nvidia_files()" method should take into account both alternatives and not exclude any. (CLI and  nvliblist.conf )

@GodloveD  @ctmadison 

one more thing 
___

My Singularity Récipe does not make Bootstrap from libglvnd project,
this means that I am not installing additional libraries or drivers in the container

````
BootStrap: docker

From: centos:latest
...
````

**Comment by al3x609** [comment]
the response to my issue in libnvidia-container is very clear.

Nvidia use **CLI** and **libglvnd** (image base docker)  for full Hardware acceleration + openGL API support over containers. 
___

then,  *Singularity* uses 
CLI as the main source for (Full acceleration + openGL) and nvliblist.conf like **backup**,  
_but do not use the  [libglvnd](https://github.com/NVIDIA/libglvnd) project_ , 

therefore to my consideration, use CLI if it exists and in the opposite case use _nvliblist_ that does provide all the necessary information. 


As users we have two options.

1.  Bootstrap from nvidia/opengl:1.1-glvnd-runtime-<**distro**> or nvidia/opengl:1.1-glvnd-devel-<**distro**>  
and the standard configuration of singularity. OR
2.  disable the CLI list and work only with **_nvliblist_** for full hardware/GL acceleration.


I think the second option is better because although both allow portable containers, the latter has fewer dependencies and allows creating containers from scratch.

_If I'm wrong, I appreciate corrections._

**Comment by GodloveD** [comment]
Just for others, here is the other issue.

https://github.com/NVIDIA/libnvidia-container/issues/36

**Comment by dtrudg** [comment]
Closing this. For reference, the TLDR here is to build from the nvidia/opengl containers as a base:

https://hub.docker.com/r/nvidia/opengl/
