### ISSUE TITLE
Expose image type (ext3/squashfs) with inspect

### ISSUE THREAD

**Issue by kav2k** [apptainer/singularity#1268]
## Version of Singularity:

2.4.2-dist

### Expected behavior

It is expected that `inspect` (or another `singularity` command) is able to tell that an image is immutable or not.

### Actual behavior

No such information is currently exposed.

In fact, there's no way to determine it using `singularity` itself, other than trying to run a container with `--writeable` and detecting the error.

As a workaround, this produces the required information:
```
SINGULARITY_MESSAGELEVEL=0 /usr/local/libexec/singularity/bin/image-type some_image.simg
```

However, it's desirable to be able to get this information with standard commands.

**Comment by ArangoGutierrez** [comment]
I think we must first discuss how we want to read this info

Here I show a 0.1 proposal for this feature.
```bash
singularity inspect nginx.img 
{
    "org.label-schema.usage.singularity.deffile.bootstrap": "docker",
    "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
    "org.label-schema.usage.singularity.deffile": "Singularity",
    "org.label-schema.schema-version": "1.0",
    "org.label-schema.usage.singularity.deffile.includecmd": "no",
    "org.label-schema.usage.singularity.deffile.from": "nginx",
    "org.label-schema.build-date": "Tue,_23_Jan_2018_17:39:21_-0500",
    "org.label-schema.usage.singularity.version": "2.4.1-release-2.4.g56581cf3",
    "org.label-schema.build-size": "111MB"
    "org.label-schema.image-format": "squash,ext3,tar" << Proposal
}
```

**Comment by vsoch** [comment]
@ArangoGutierrez the specification is here: http://label-schema.org/rc1/ the namespace needs to fall under singularity then some label. I would suggest starting even simpler than that - if the user asks for

```
singularity inspect -f <container> 
```
The ``-f` (or `-if`) would signify image format, and the entrypoint to inspect would use the `SINGULARITY_libexecdir` to target the executable, change the message level to 0 to be quiet, and then call it to return the format. 

```
singularity inspect -f <container> 
SQUASHFS
```
and thus it's basically a wrapper for the command that already exists. For the integration with the other json, since we are transitioning to go it would be ok to wait to re-write that code, although you could follow suit with calling the executable (or using the function I wrote to get the format) and then returning the same thing. Up to you!

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by vsoch** [comment]
This will also eventually be valuable for perhaps using singularity containers with OCI. It was more of an issue before when there were more image types, and now probably it would help to show the version of SIF.

**Comment by vsoch** [comment]
Don't close stalebot, the contributors to this issue have responded and it's the maintainers that have not.

**Comment by pedroalvesbatista** [comment]
@kav2k We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Copied into Apptainer new issue #491. Closing this in the old Singularity repo.
