### ISSUE TITLE
Suggestion: Use bubblewrap for setuid rather than entire singularity binary

### ISSUE THREAD

**Issue by max-mapper** [apptainer/singularity#1270]
I couldn't find any discussion about https://github.com/projectatomic/bubblewrap and had a question.

One potential red flag I noticed about singularity is that in environments where you don't have user namespaces you have to setuid the singularity binary so it can execute things as root (correct me if I'm wrong).

This opens up the entire surface area of singularity to exploits. Bubblewrap addresses this in their readme:

> The bubblewrap authors believe it's much easier to audit a small setuid program

I was wondering if it would make sense to use bubblewrap, or have a smaller surface area binary that gets setuid. I had to ask a university cluster group to setuid the singularity binary, but it would be less of an ask if they just had to setuid a smaller, more auditable program.

Again, correct me if the premise here is wrong, I'm still trying to learn about the security tradeoffs involved with singularity.

**Comment by GodloveD** [comment]
Hey @maxogden.  I'm going to ping our security guru @cclerget here.  He can answer you question better than I can.  But I think that your premise is indeed incorrect.  

The Singularity binary itself is not setuid.  We have one small program that is suid and is then called to escalate and drop privs when the code does things like mount an image.  So the vast majority of the Singularity code is not exposed to attack. <-- **EDIT**: @cclerget set me straight on this point offline by telling me that all C code is exposed when we run as setuid up until we drop privs permanently.  So I guess just having the suid around increases our exposure even when it is not actively used in the code.  

I haven't looked at bubblewrap.  But the way you describe, it sounds like they are taking a similar approach.

**Comment by cclerget** [comment]
Hi @maxogden. As @GodloveD said, Singularity call a setuid binary in order to run privileged operations so the attack surface is still there. Singularity code have been actively audited to reduce attack surface.

After a quick look at bubblewrap code, when running as setuid, they spawn a child running unprivileged which send request over socket to parent (privileged) to execute privileged mount syscall, the parent continue execution with privileges to setup chroot environment. I'm not sure, there is a big difference with number of C line to audit between Singularity and bubblewrap.

Other thing to take into account, bubblewrap requires support of PR_SET_NO_NEW_PRIVS, that's mean kernel 3.5 minimum. As you mention environments that don't support user namespaces, it's likely not to have support for PR_SET_NO_NEW_PRIVS too.

Singularity run on systems which don't support PR_SET_NO_NEW_PRIVS by disabling custom binds

**Comment by dtrudg** [comment]
Singularity has changed a lot with the rewrite in Go for 3.x, and uses a different split priv/unpriv. Coupled with the increased availability of user-namespace in the wild, and the fakeroot option in Singularity I don't think looking at bubblewrap remains relevant. Closing.
