### ISSUE TITLE
squashfs-tools install requirement

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#1279]
See https://github.com/singularityware/singularityware.github.io/issues/166#issuecomment-362283458 passing this forward for @johnbradley

## Version of Singularity:

2.4.2 (RedHat install)

### Expected behavior

The configuration alerts the user that squashfs-tools is not installed and does not allow to finish / complete install.

### Actual behavior

The configure/make/make install process didn't error, and it wasn't revealed until testing with docker pull.

### Steps to reproduce behavior

Find a RedHat OS and install! :)

**Comment by jmstover** [comment]
Hi Vanessa,

  Since mksquashfs isn't a *hard* requirement we ended up not exiting during the `./configure` step. See #1246 and what we changed there.

  At the end of `make` it's going to print out the message:
```
mksquashfs from squash-tools is required for full functionality
```

  But we stopped it from being a hard dependency since mksquashfs is not required to build Singularity.

  This change was merged into development.

**Comment by vsoch** [comment]
ah ok, this is what I saw too, but on Ubuntu. If this is what is seen on redhat, it should be sufficient. @johnbradley did you see this message? And either way, would putting an additional note in the docs help?

**Comment by jmstover** [comment]
> And either way, would putting an additional note in the docs help?

Yeah, the more notes around about it the better.

**Comment by vsoch** [comment]
okay I've added a note to the docs here http://singularity.lbl.gov/install-linux and also the admin docs, closing issue here and will resolve with @johnbradley in the other PR. Thanks @jmstover !
