### ISSUE TITLE
Singularity integration with drone.io

### ISSUE THREAD

**Issue by henrykironde** [apptainer/singularity#1280]
This is a feature request in reference to #https://github.com/singularityhub/singularityhub.github.io/issues/98#issuecomment-357824858

Drone.io article. https://blog.maqpie.com/2017/03/21/build-and-deploy-applications-using-drone-ci-docker-and-ansible/

**Comment by vsoch** [comment]
And to add some note to this, Drone.io is a CI service that is orchestrated with containers, and so the issue here is for controllers for services to create the integration. This likely wouldn't be added right away to Singularity Hub, but to Singularity Registry so that institutions can choose to add it (or not).

**Comment by dtrudg** [comment]
Hi @henrykironde - you recently asked about Jenkins integration on #1342 - are you still interested in drone.io, or settled on Jenkins? Thanks.

**Comment by dtrudg** [comment]
Hi all - since this has been open for some time without follow up I'm going to close it. If there's anything further please feel free to reopen.
