### ISSUE TITLE
glibc error whenever hostfs option is enabled

### ISSUE THREAD

**Issue by robertogonzalezazevedo** [apptainer/singularity#1287]
## Version of Singularity: 2.4.2

I'm running into an issue by enabling **hostfs** option on **CentOS 7** (latest, **7.4.1708**), kernel **3.10.0-693.17.1.el7.x86_64** and **CentOS 6** image/container. It seems that whenever you enable this option container's **glibc** behaves **unpredictably** and fails.

### Expected behavior

It doesn't matter whether you use a **docker image** or a **yum built** image:
(hostfs = **no**)

singularity exec centos6.simg ldd /bin/rpm | head -4
        linux-vdso.so.1 =>  (0x00007ffe7f574000)
	librpmbuild.so.1 => /usr/lib64/librpmbuild.so.1 (0x00007f77bca09000)
	librpm.so.1 => /usr/lib64/librpm.so.1 (0x00007f77bc79d000)
	libmagic.so.1 => /usr/lib64/libmagic.so.1 (0x00007f77bc57e000)

### Actual behavior

(hostfs = **yes**)

singularity exec centos6.simg ldd /bin/rpm | head -4
/usr/bin/bash: /lib64/libc.so.6: version GLIBC_2.14 not found (required by /usr/bin/bash)
/usr/bin/bash: /lib64/libc.so.6: version GLIBC_2.15 not found (required by /usr/bin/bash)

### Steps to reproduce behavior

Enable hostfs (hostfs = yes) in /etc/singularity/singularity.conf.
O.S.: CentOS **7** latest (**7.4.1708**)
kernel: **3.10.0-693.17.1.el7.x86_64**
Image/container: docker (**centos:centos6**) or built by **yum**

**Comment by robertogonzalezazevedo** [comment]
LOGs:
[singularity-exec-mount-hostfs-no.log](https://github.com/singularityware/singularity/files/1699557/singularity-exec-mount-hostfs-no.log)
[singularity-exec-mount-hostfs-yes.log](https://github.com/singularityware/singularity/files/1699558/singularity-exec-mount-hostfs-yes.log)

**Comment by dtrudg** [comment]
Hi @robertogonzalezazevedo - looking at your logs, what is happening is as follows:

- Your host (CentOS 7) looks to be mounting /usr as a separate fs
- Singularity with hostfs on is picking up this /usr to mount into the container (since hostfs is picking up all mounts except /
```VERBOSE [U=0,P=18738]      singularity_runtime_mount_hostfs()        Binding '/usr'(ext4) to '/var/singularity/mnt/final//usr'```
- When you run the container, it's calling `/usr/bin/bash` which is an executable from your mounted-in CentOS 7 /usr partition
- This CentOS 7 bash is trying to use the libs from the CentOS 6 container `/lib64` directory, which are too old for it.

You would need to leave hostfs off here, and manually list the fs to mount in `bind path` entries

**Comment by robertogonzalezazevedo** [comment]
Hi @dctrud - Thanks for your attention. I installed a new server with 2 partitions (**/** and **/scr**) and it's working
