### ISSUE TITLE
what's the purpose of --nv used

### ISSUE THREAD

**Issue by zhcf** [apptainer/singularity#1292]
I have one image test.img which contains the cuda driver and library. These are 2 ways to use the image.
singularity shell  test.img
singularity shell --nv test.img
I found both 2 way can use gpu in the image, so the questions is what's the purpose of the --nv.

**Comment by GodloveD** [comment]
Hi @zhcf.  Good question.  

If you install the libraries from the nvidia driver (like the contents of [this run file](http://us.download.nvidia.com/XFree86/Linux-x86_64/390.25/NVIDIA-Linux-x86_64-390.25.run)) into your container than you can use the GPU on the host system.  But ONLY if the host system has the exact same driver installed.  That is because the driver libraries installed in the container must match the driver kernel module installed on the host system.  So this works, but it breaks portability.  

With the `--nv` option the driver libs are located on the host system and then bind mounted into the container at runtime.  This means you can run your container on a host with one version of the nvidia driver, and then move the same container to another host with a different version of the nivida driver and both will work.  (Assuming the cuda installed in your container is compatible with both drivers.)

Check https://github.com/singularityware/singularity/issues/1253 for more details.  😄

**Comment by zhcf** [comment]
Thank you GodloveD. It is helpful.

**Comment by GodloveD** [comment]
Great.  If you need anything else feel free to reopen.
