### ISSUE TITLE
HOME folder not writable when created in overlay

### ISSUE THREAD

**Issue by slefrancois** [apptainer/singularity#1323]
## Version of Singularity:

2.4.2-dist

### Expected behavior

With auto-bind of home folder deactivated (in singularity.conf), and an overlay added on top of the image, the user's home folder should be writable inside the overlay.

### Actual behavior

User home folder gets created inside overlay, but owned by root.

### Steps to reproduce behavior

```shell
$ singularity shell --nv -o $SREGISTRY_STORAGE/overlay-pytorch.img /Tmp/singularity/nvidia-pytorch:17.12.simg
Singularity: Invoking an interactive shell within container...

Singularity nvidia-pytorch:17.12.simg:~> pwd
/u/<user>
Singularity nvidia-pytorch:17.12.simg:~> ls -la
total 8
drwxr-xr-x 2 root root 4096 Feb 21 18:06 .
drwxr-xr-x 3 root root 4096 Feb 21 18:06 ..
Singularity nvidia-pytorch:17.12.simg:~> touch test
touch: cannot touch 'test': Permission denied
```

**Comment by rherban** [comment]
I realize this issue is quite a bit old, but for reference this is expected behavior, though perhaps counterintuitive.  

When an overlay filesystem is mounted, it still has permissions of the underlying filesystem and until permissions are changed to allow the user to write, they will be unable to do so.
This is exasperated by not mounting the user's homedir and thus leaving them an unwritable $HOME.

A better answer is to use `--contain`:
```
  -c, --contain                use minimal /dev and empty other
                               directories (e.g. /tmp and $HOME) instead
                               of sharing filesystems from your host
```
This gives a writable home that is writable, but doesn't persist between sessions.   If you need home to persist, the overlay file will need to have its permissions tweaked.
