### ISSUE TITLE
Unable to execute, shell into, etc containers after password change (possible noob issue)

### ISSUE THREAD

**Issue by serbinsh** [apptainer/singularity#1332]
## Version of Singularity:

2.4.2

### Expected behavior

Can change server / cluster password and still use existing singularity build and/or containers

### Actual behavior

```
[sserbin@modex singularity]$ ./hello-world.simg
ERROR  : Failed invoking the NEWUSER namespace runtime: Invalid argument
ABORT  : Retval = 255
```

### Steps to reproduce behavior

I will state up front that this may be an issue that results from my less than complete familiarity with Singularity so, if so, I apologize.  However, I recently ran into an issue where I could no longer run / build / shell into, etc singularity containers on my server cluster after a password change.  My institution requires bi-annual (or annual, can't remember) pass changes and I had built singularity as root under then old pass (but possibly as sudo not sudo su -p).  After the change I was getting the above error.

The fix?

I ran ```sudo make install``` again to the custom install dir and then re-ran the commands and everything worked fine.  So, maybe there is a better way to build Singularity such that it doesnt require re-installing after password changes?

Thanks for the help.

**Comment by cclerget** [comment]
@serbinsh You got this error because your Singularity binary hadn't setuid bit set, when Singularity is not executed as setuid binary it uses user namespace, your system seems not support user namespace then you got `Failed invoking the NEWUSER namespace runtime`.

You noticed it worked as expected after running `sudo make install`, that means setuid bit has been set on Singularity binary during `sudo make install`. Your system requires a setuid Singularity installation, so further installation/update of Singularity must use `sudo make install` during installation process.

**Comment by rherban** [comment]
Looks like Cedric's answer sums things up quite accurately, but the issue never got closed.  

Finally putting this issue to bed!
