### ISSUE TITLE
Singularity OCI compliance

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#1369]
The main idea of this project is to align both singularity runtime and image format to the Cloud native computing foundation ([CNCF](https://www.cncf.io/)) open container initiative ([OCI](https://www.opencontainers.org/)) standard.

**The image format:**
 - In order to achieve this milestone SIF will need to include a config.json file with the root filesystem
 - Support to run containers from an OCI container bundle inside a tar file or an open folder.

A runtime configuration; specified as a json file (_config.json_)

**The Runtime spec:**
 - The current runtime will need some re-work to support the OCI lifecycle spec, the most important tweek is going to be around the instance lifecycle.
 - Singularity runtime will need to have the ability to run OCI tar files or open folders bundles, if we decide to go all in on the OCI image format this won't be much of an issue.

Currently, the OCI runtime-spec specifies Five MUST API calls:

 - Create
 - Start
 - Kill
 - Delete
 - Query state

**Comment by ArangoGutierrez** [comment]
A _config.json_ example: 
```json
{
ociVersion: "0.3.0",
platform: {
os: "linux",
arch: "amd64",
},
process: {
terminal: true,
user: {
uid: 1,
gid: 1,
additionalGids: [
5,
6,
],
},
args: [
"sh"
],
env: [
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"TERM=xterm",
],
cwd: "/",
capabilities: [
"CAP_AUDIT_WRITE",
"CAP_KILL",
"CAP_NET_BIND_SERVICE",
],
apparmorProfile: "",
selinuxProcessLabel: "",
},
root: {
path: "rootfs",
readonly: true,
},
hostname: "slartibartfast",
mounts: [
{
destination: "/proc",
type: "proc",
source: "proc",
},
{
destination: "/dev",
type: "tmpfs",
source: "tmpfs",
options: [
"nosuid",
"strictatime",
"mode=755",
"size=65536k",
],
},
{
destination: "/dev/pts",
type: "devpts",
source: "devpts",
options: [
"nosuid",
"noexec",
"newinstance",
"ptmxmode=0666",
"mode=0620",
"gid=5",
],
},
{
destination: "/dev/shm",
type: "tmpfs",
source: "shm",
options: [
"nosuid",
"noexec",
"nodev",
"mode=1777",
"size=65536k",
],
},
{
destination: "/dev/mqueue",
type: "mqueue",
source: "mqueue",
options: [
"nosuid",
"noexec",
"nodev",
],
},
{
destination: "/sys",
type: "sysfs",
source: "sysfs",
options: [
"nosuid",
"noexec",
"nodev",
],
},
{
destination: "/sys/fs/cgroup",
type: "cgroup",
source: "cgroup",
options: [
"nosuid",
"noexec",
"nodev",
"relatime",
"ro",
],
},
],
hooks: {
prestart: [
{
path: "/",
args: [
"/usr/bin/uptime"
],
env: [ ],
}
]
},
linux: {
rlimits: [
{
type: "RLIMIT_NOFILE",
hard: 1024,
soft: 1024,
}
],
resources: {
devices: [
{
allow: false,
access: "rwm",
}
]
},
namespaces: [
{
type: "pid"
},
{
type: "network"
},
{
type: "ipc"
},
{
type: "uts"
},
{
type: "mount"
},
],
devices: null,
seccomp: {
defaultAction: "",
architectures: null,
},
},
}
```

**Comment by ps-account** [comment]
looking forward!

**Comment by GodloveD** [comment]
So, in Singularity 3.1, there is now an OCI compatible variant of the Singularity runtime, and the `oci` command group contains a `mount` sub command, allowing you to expose a SIF as an oci bundle.  

I don't think this is exactly what was envisioned in this issue, but as we developed I think this is the way in which we decided to support OCI.  I'm going to close this, but if it's not fully addressed feel free to re-open and comment.

**Comment by mr-c** [comment]
@GodloveD Thank you for the update. The issue was about compliance with the OCI image spec and the OCI runtime (command line interface) spec.

Can explain with more detail what is meant by "an OCI compatible variant of the Singularity runtime"?
Is that a separate release? Has it been tested against the OCI runtime spec or certified in any way?

Congratulations on supporting OCI image export of SIF. I think this issue is also asking for OCI image import as well.

**Comment by GodloveD** [comment]
Heya @mr-c!  If you download and install the current master or the 3.1.0 release candidate and use the `singularity help oci` command you will find a new command group that will run Singularity in a mode that is much like runC.  It implements the OCI runtime spec.  In fact it actually passes more of the official OCI runtime tests that define the spec than runc does.  (I'm only mentioning runc b/c it is kindof the standard in this department.) Check it out!

This new OCI engine is letting us do things like interact with Kubernetes.  In fact, it's now possible to schedule Singularity containers through K8s.  Check this out!  https://github.com/sylabs/singularity-cri .  

If this issue is asking for OCI import of SIF, Singularity can totally do that.  It's been able to do that for a long time in fact.  That is basically what is happening every time you run a container from Docker.  You can also run containers from bare directories.  This allows you to run an OCI bundle if you want.  

Feel free to hit me back if you have any more questions or comments.  We need to start getting the word out about this stuff!
