### ISSUE TITLE
wishlist: be able to redirect logs (--verbose|--debug) to a file 

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#1457]
## Version of Singularity:
2.4.5-dist (Debian package)

In our tool which wraps singularity, we would like to collect logs from running a singularity command (provided by the user) for the analysis (e.g. which image or instance was actually ran, etc) and keep stderr and stdout "as is" for the user.  ATM I do not see if there is a way to redirect logs into a file.  It would be awesome if that was possible.

**Comment by dtrudg** [comment]
This seems like a fit for a plugin in 3.x

**Comment by fmgvalente** [comment]
Ideally this should accomodate the singularity instance logs as well, which on the version I have installed (2.6.x) are always placed on $HOME/.singularity/logs/... This has caused grievances on systems with a quota. The options I have available to "redirect" those logs are cumbersome at best.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
