### ISSUE TITLE
Make minimal /dev visible

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#147]
There's a lot of cruft in `/dev` that I don't necessarily want users to access - or necessarily share across multiple containers.  I'd like to be able to skip `bind /dev` and add `mount dev = yes` that would:
- mknod `/dev/{zero,null,random,urandom}`
- Mount `/dev/shm`

**Comment by gmkurtzer** [comment]
Good thinking! I added that for a 2.2 milestone.

**Comment by gmkurtzer** [comment]
As I'm going back through these issues I'm noticing that I took "mount dev" to mean something else. Presently in the 'devel' branch, if you specify 'mount dev = no', it won't bind mount /dev into the container. Then someone could add a few devices to the bind path directives instead. Or, we can create an additional configuration parameter to mount dev, so it can be 'yes/no/minimal' and if it is minimal then we just bind several devices automatically.

Thoughts?

**Comment by bbockelm** [comment]
I like the`yes/no/minimal` approach.  I'd suggest we'd really need `{null,zero,random,urandom}` (it's an interesting discussion as to whether we should bind `random` to `urandom` to prevent entropy pool exhaustion - that's probably overthinking things, isn't it?).

I don't know enough about the internals of device nodes to suggest if a bind mount or a `mknod` is more appropriate.

What are your thoughts on `/dev/shm`?

**Comment by gmkurtzer** [comment]
Well, technically Singularity doesn't grant any users additional access above what they already have, so limiting devices becomes more a matter of appeal and connivence rather then security or necessity. Generally speaking, users have the same access to /dev, /dev/shm and even availability to deplete the system of entropy before they entered the Singularity container.

You have a good point about doing a mknod Vs. bind. I was thinking of using bind simply because mknod requires privileges (I believe) which are above and beyond the user namespace context.

Regarding /dev/shm for a minimal approach, I would suggest that it is not necessary.

**Comment by gmkurtzer** [comment]
This has been done, closing issue.
