### ISSUE TITLE
Headless rendering with Qt

### ISSUE THREAD

**Issue by singulaire** [apptainer/singularity#1479]
## Version of Singularity:

2.4.5

## Problem:

I have converted a working docker container into a singularity container. In the container, I am using Qt5's [QOffscreenSurface class](http://doc.qt.io/qt-5/qoffscreensurface.html) to render images in headless mode. While this works smoothly in the original docker container, in singularity I find that the created QOffscreenSurface object is always invalid (as determined by the [isValid() method](http://doc.qt.io/qt-5/qoffscreensurface.html#isValid)). Judging from the Qt documentation, this means the object could not be allocated the system resources that it needs, which are allocated correctly when the code is executed in a similar docker container.

### Expected behavior

Can create QOffscreenSurface objects and use them to render images in headless mode

### Actual behavior

QOffscreenSurface objects are always created invalid, meaning they have not been allocated appropriate resources.

### Steps to reproduce behavior

Create a singularity image from [the following recipe](https://gist.github.com/singulaire/b00058091ee88a880481f039bdc7d5bc).
Run a shell with the --nv flag
Create a QOffscreenSurface object and use the isValid() method.

**Comment by dtrudg** [comment]
Hi @singulaire - how is the similar docker container being built and used? Do you have a DISPLAY variable set in either case and X-Server running on the host?

In the `nvidia-docker` FAQs they state:

>Is OpenGL supported?
>Yes, EGL is supported for headless rendering, but this is a beta feature. There is no plan to support GLX in the near future.
>Images are available at nvidia/opengl. If you need CUDA+OpenGL, use nvidia/cudagl.

Is the base docker image for the working docker case the same as your Singularity recipe, or could you be using the above?

Thanks

**Comment by singulaire** [comment]
The docker image was built on a remote server from [this dockerfile](https://gist.github.com/singulaire/729575d4102973a3fc39de120c2b7f97) under the name `rllab:beta`. It is run using [this shell script](https://gist.github.com/singulaire/ed5d0854ba42fa4d32fc518b0d06eed9) with the command

``GPU=1 image="rllab:beta" ./nvidia-docker run -it --rm -v `pwd`:/rllab -w /rllab:beta  rllab:beta /bin/bash``

To grab the locations of the nvidia kernels and .so libraries, similarly to the function of the --nv flag in singularity. Inside the container, the command

`xvfb-run -s "-screen 0 1400x900x24" bash`

is used to provide a virtual monitor. This last part is done in the singularity shell as well, which sets DISPLAY to the value `:99` in both cases.

The base docker image for both the dockerfile and the singularity recipe is `nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04`

**Comment by dtrudg** [comment]
Hi @singulaire  - could you provide the full output of:

```
singularity -d exec --nv myimage.img nvidia-smi
```

... where myimage.img is your Singularity image? The output will help to troubleshoot.

Also do you have some code which creates a QOffscreenSurface object?

**Comment by singulaire** [comment]
The output is [here](https://gist.github.com/singulaire/f7fb63337073ed546d4940a8a6f8188b).

Additionally, glxinfo gives the following output in the singularity container:

> name of display: :99
> Error: couldn't find RGB GLX visual or fbconfig
> Error: couldn't find RGB GLX visual or fbconfig


I'm afraid I don't have an easily executable piece of code that creates a QOffscreenSurface. The offending code is [this part](https://github.com/CoppeliaRobotics/v_rep/blob/2c06a5448816c33d3da312f614b52500d2541027/sourceCode/3dObjects/visionSensorObjectRelated/offscreenGlContext.cpp#L69) from the V-REP robotics simulator, and is executed when I make [this API call](http://www.coppeliarobotics.com/helpFiles/en/apiFunctions.htm#simGetVisionSensorImage)

**Comment by dtrudg** [comment]
Hi @singulaire - I've done some digging on this. The reason you have this issue is down to a bad interaction between NVIDIA OpenGL libraries and xvfb-run

- Under different OS and NVIDIA driver combinations it has been reported xvfb-run will fail to handle OpenGL/GLX if the NVIDIA driver is present as a full install including NVIDIA's OpenGL libs. (e.g. https://askubuntu.com/questions/738283/xvfb-glx-error-when-using-nvidia-driver or https://devtalk.nvidia.com/default/topic/933227/opengl/nvidia-driver-breaks-xvfb-on-rhel-6/) This is the  `Error: couldn't find RGB GLX visual or fbconfig` you reported above.

 - nvidia-docker, until recently (https://github.com/NVIDIA/nvidia-docker/issues/11), has not supported OpenGL. The NVIDIA OpenGL libraries will not be present in the container, so you will not hit the issue under nvidia-docker - unless you use the new OpenGL support and base images mentioned in the issue.

- Singularity has `--nv` has always supported NVIDIA OpenGL - we bind the NVIDIA OpenGL libraries from the host into the container with the `--nv` option - this is why you see the error.

The simple solution here should actually be to just not use `xvfb-run` for your Singularity container. When you run the container it will pick up DISPLAY if set (or you can set it), and it will then happily use your NVIDIA card for OpenGL/GLX operations with the Xorg server I can see running from your `nvidia-smi` output.

If you really need OpenGL onto an xvfb (which will not use your NVIDIA GPUs) then you would need to remove the OpenGL related libs from `/usr/local/etc/singularity/nvliblist.conf` so they are not mounted into the container with `--nv` and the clash between xfvb and the NVIDIA OpenGL libraries does not occur.

**Comment by singulaire** [comment]
After some attempts, it seems that I am not authorized to access the Xorg server running on the host. Further, I would in the future like to deploy my container in a HPC cluster that doesn't have a running Xserver. Is there a possible way to run a display inside a container, so that a display on the host isn't necessary? Alternatively, is there a way for me to exclude the OpenGL libs from the singularity container without having privileged access on the host (e.g. if I don't have read/write access to /usr/local/etc)?

**Comment by rmbp** [comment]
Hi singulaire,

just wondering if you've got any further with your last issue, im facing a similar problem.

I have a docker container that works fine with `docker run --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" ` but cant seem to get it to work in singularity, and i also want to use it on a HPC cluster where I have no sudo access

**Comment by singulaire** [comment]
Unfortunately, I'm still waiting for a response and have yet to solve the issue.

**Comment by rmbp** [comment]
@dctrud are you able to give any advice?

**Comment by dtrudg** [comment]
Hello - I'm afraid that I changed jobs back in 2018 - but have now returned to working on Singularity. General advice is that if you need to use NVIDIA hardware accellerated OpenGL for display, ensure you are using `nvidia/cudagl` from dockerhub as a base image, and draw to a host `DISPLAY` - do not use `xvfb`

If you are using docker, and you find it works there and not under singularity, it's perhaps likely that your docker container is running as root but you don't have the permissions to use the `DISPLAY` as your own user (which is what the singularity container will run as).

> Further, I would in the future like to deploy my container in a HPC cluster that doesn't have a running Xserver. Is there a possible way to run a display inside a container, so that a display on the host isn't necessary?

This sounds like Xvfb would be required, and you would need to make sure you *do not* use the `--nv` option, or edit the `nvliblist.conf` as described above.
