### ISSUE TITLE
is it possible install singularity and run singularity image without root

### ISSUE THREAD

**Issue by kongdeju** [apptainer/singularity#1545]
hi there ,
       just a as the title. thx !

**Comment by GodloveD** [comment]
Hi @kongdeju!  Singularity should have some limited functionality if you install it as a non-privileged user on a kernel that supports [user namespaces](http://man7.org/linux/man-pages/man7/user_namespaces.7.html) (>=3.8).  However, you are limited to working with sandboxes.  There is no support for the default squashfs file format.  

But... I actually just tested this out with the latest version of Singularity and it seems like it is not working.  So that's a bug.  I filed an other issue on that. #1546

**Comment by GodloveD** [comment]
And as I mentioned on #1546, looks like this issue is already fixed in the release-2.5 branch (which will be used to create the next release).  You should try installing that version if possible.

**Comment by kongdeju** [comment]
Thank you @GodloveD . i will take a try, by the way , Singularity is awesome!

**Comment by GodloveD** [comment]
Let me know if you run into any snags.
