### ISSUE TITLE
Refactor sexec

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#155]
Sexec is begging for a refactoring which will allow us to identify the primary code paths and functionize everything else.

**Comment by gmkurtzer** [comment]
This is in progress... committed a bunch of updates to this front last night.

**Comment by gmkurtzer** [comment]
I did a first pass at this, but will come back and do more. At present sexec forks twice so there is 3 running process at any given time:
1. Management process: responsible for init/setup, and cleanup
2. Mount and namespace process: do the mounts, create and hold open the namespaces
3. Exec process: execute a particular command within the container namespaces

I will be moving these to separate binaries that will do the following:
1. Primary driver: init/setup and cleanup
2. Image prepare: bind loop, etc.. (this will be compiled as either SUID or non-SUID)
3. Namespace and mount process: Do the mounts and create/hold namespaces (SUID or non-SUID)
4. Exec process: set NO_NEW_PRIVS and execute the particular command within the container namespace

This is all pending I can securely pass the information from one to process to another without risk of the SUID bits being manipulated. I have some ideas on that, but still needs more thought. I may end up moving this architecture to a Google doc for easier iteration and collaboration.

**Comment by bbockelm** [comment]
There aren't a lot of portable options for securely passing information between two processes - I guess the best option is to use anonymous sockets with `SCM_CREDENTIALS`.

But then you have to worry about serialization / deserialization errors and careful checking of the remote side's credentials.  Seems like it'd be subtle logic.

I think a better starting point would be:
1.  Continue to decrease the size of `sexec.c`.  I bet it could reasonably be below 500 lines of code.  That would make code review even better.
   - It would be useful to refactor the exec and payload code into a separate function instead of inside a multi-hundred-line code block.
2.  Separate current compilation targets into into child executables (non-setuid) that are either run as root or as the target user.
3.  Remove all global variables and introduce an opaque state handle.  When passing info from one process to another, we'd need to gather all this information and serialize it.  Might as well start on that part now!

**Comment by gmkurtzer** [comment]
I was thinking something really lame, but it might work because it is so simple. Creating a modular system where each "module" is an executable that has a defined standard on where it picks up and where it leaves things... For example, the image mount'ing module will take an image and bind or mount it to a predefined location, and there could be different modules for different image types (e.g. if the image is a directory vs a loop back, one requires no additional escalation while the other does). Both modules end up in the same place with a container file system mounted at the predefined location so the next modules (which may have no SUID or enhanced privs) can pick up from there.

If we want to disable SUID on a particular build, we just don't build the SUID components, or we can split into multiple subpackages. It also means the SUID portions of the code can be very simple, clean, and easily audit-able.

Regarding your points:
1. We are in complete agreement here and agrees with my vision as well.
2. I think the modular system I described is in alignment with this except we don't need to do it via identical binaries with different perms. Each "module" will get the perms that it requires to operate properly.
3. If we pass a serialized state handle from an unprivileged process to a privileged process, how do we validate the data? It seems dangerous to trust the data even if it has been validated..

**Comment by bbockelm** [comment]
Oh - another thing to think about.

There are special rules for `exec`'ing `setuid` binaries (for example, the dynamic linker will ignore the various `LD_*` variables, `malloc.conf` should get ignored, etc).

However, we'll need to make sure to drop _all_ env vars before executing helpers.  Otherwise, the `LD_PRELOAD`-type variables may get inadvertently executed.

**Comment by gmkurtzer** [comment]
Yes, exactly my thinking. I presently have some modulectl code that will end up making sure that the privs are dropped completely before executing the next module. Right now it is implementing basic functionality but that should be easily added.

So on the first pass at this, it seems that more modules then not will end up being SUID, but I am hoping that over time and as development continues we will be able to do more and more without SUID on a conditional basis (by implementing more modules as features are available). I envision an endpoint being where the only module left as SUID is the image mounting module and possibly the overlay module (and making those disable-able).

Have you had a chance to check out the devel branch?

**Comment by gmkurtzer** [comment]
Sexec has been refactored, and the suid form of it statically links libsingularity.so, so I think this issue can be closed. If I missed something or if it needs to be reopened, comment to it and I'll reopen if necessary. 

Thanks!
