### ISSUE TITLE
Best practices web page

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#156]
Create a best practices for creating bootstrap images web page

**Comment by cjprybol** [comment]
Bump on this issue.

I have set of instructions for setting up an image that I have developed by interactively entering a container with `sudo singularity shell --writable --contain container.img` that I would like to know how to integrate into the bootstrapping step.

Is there a way to contain the `RunCmd` inside of the bootstrap files in the same way that the `--contain` flag works for the `singularity shell` command?

My first guess was to just take every command that I had entered when inside of the interactive shell (inside of the container) and put those commands in the bootstrapping `.def` file, prepended with `RunCmd`. That didn't work because the commands that made directories and changed directories would do so on the host, rather than inside of the container, and so it started to install software and files onto the host rather than inside of the container.

Would love some detailed examples on how to proceed with making more complex bootstrapping files!

**Comment by gmkurtzer** [comment]
Do we still need this, or has our documentation updates been sufficient?

Thanks!

**Comment by vsoch** [comment]
This should go in the general bucket of "total beautiful new dump of stuff from head into singularity 2.3 docs"

Just give me a few days notice :)

**Comment by GodloveD** [comment]
This:

http://singularity.lbl.gov/docs-flow

Closing.  😺
