### ISSUE TITLE
Image is built even if a `%post` command fails

### ISSUE THREAD

**Issue by granek** [apptainer/singularity#1597]
## Version of Singularity:

2.5.1-master.gd6e8154

### Expected behavior
According to [Singularity Recipe documentation:](http://singularity.lbl.gov/docs-recipes#sections) 

> if any command fails, the build process will halt

### Actual behavior

Image is built (i.e. build doesn't halt) even if a `%post` command fails, as long as the failing command is followed by a successful command.

### Steps to reproduce behavior
```
echo "BootStrap: docker
From: debian:stretch

%post
  apt-get update
  apt-get install -y --no-install-recommends \
    wget \
    blahblahblah \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*
  echo 'I will valiantly keep the build from failing!'

" > Singularity.nohalt
sudo singularity build nohalt.simg Singularity.nohalt
```

**Comment by dtrudg** [comment]
Hi @granek - as far as I am aware the post section is being run in the manner of a shell script. By default shells don't fail early at the first error, unless you tell them to. You could try `set -e` at the start of your %post block to get shell behavior that exits at the first error.

I'm afraid I can't verify this right now, but might solve your issue.

**Comment by granek** [comment]
Hey @dctrud, I actually had tried including `set -e` at the start of your %post block, but it doesn't have any effect.  Based on several discussions I've read it seems that %runscript runs under sh, not bash.  If %post does also (I can't find any documentation one way or the other), that would explain the ineffectualness of `set -e`.  

There seem to be other hacks to do this, but, I think either the behavior or the documentation should be changed, since the docs clearly say "if any command fails, the build process will halt".  

I would prefer changing the behavior.  I find it disheartening when I wait for an image to build, then bang my head against the computer trying to figure out why the image isn't behaving as expected, only to find that a whole set of software never got installed and the error message is hidden in 1000 lines of build output.

**Comment by GodloveD** [comment]
Hi @granek.  I think this is the line you are looking for.  

https://github.com/singularityware/singularity/blob/master/libexec/bootstrap-scripts/deffile-sections.sh#L153

If you don't like clicking, it is:

```Shell
singularity_section_get "post" "$SINGULARITY_BUILDDEF" | chroot "$SINGULARITY_ROOTFS" /bin/sh -e -x $ARGS || ABORT 255
```

`singularity_section_get` just parses the def file and dumps the contents of a particular section to stdout.  (In this case post).  Then you see that the contents gets piped into the `chroot` command so whatever follows will be executed in the container file system.  Then you will see that the interpreter is `/bin/sh` as you suspect and that all of the commands are already being executed with the `-e` flag.  That's why adding an additional `-e` at the beginning of post does nothing.  

So, all of this seems to work just fine as long as the commands are given individually.  But when you string them together with `&&` that's when you get a _failure to fail_ so to speak.  At least that is what I get when I try to replicate your error.  

So on first hunch it seems like a bug in the shell (which is dash on my Ubuntu machine and may be something else on yours).  But this is where things get squirrelly.  If it's a shell bug, I would assume that this script would trigger it. 

```Shell
#!/bin/sh
set -e -x

blah \
&& true
```  
But it doesn't.

```
$ ./blah
+ blah
./blah: 4: ./blah: blah: not found
```
So, I'm not really sure why we are getting the discrepancy.  😕

Don't really know what to try next.  

BTW, yes you are right the runscript is executed by `/bin/sh` by default.  But only because Singularity forces the shebang at the top.   I think that is silly behavior and I want to change it.  https://github.com/singularityware/singularity/pull/1121  If you agree comment on the PR and say it's a good idea!

**Comment by granek** [comment]
Thanks for your response @GodloveD!  It helped me figure out a solution, which is to just get rid of the "and chains" in my %post block.  They are remnants from a Dockerfile, where there is a reason to chain commands together, but I don't think there is a good reason to have them in a Singularity recipe.  So the following behaves as I expected (i.e. doesn't build an image).

```
echo "BootStrap: docker
From: debian:stretch

%post
  apt-get update
  apt-get install -y --no-install-recommends \
    wget \
    blahblahblah
  apt-get clean
  rm -rf /var/lib/apt/lists/*
  echo 'I will valiantly keep the build from failing!'
" > Singularity.halts
sudo singularity build halts.simg Singularity.halts
```


I also played with your much simpler MWE, and I actually, I think it _is_ a shell thing (not sure if its a bug or a feature).  Reading your response I realized that I didn't explain the issue fully . . . the image only builds if the failing command in %post _is followed by one that doesn't fail_, so if you remove `echo 'I will valiantly keep the build from failing!'` from my original recipe, the build _does_ fail.  And I see the same behavior when I similarly alter your toy example . . .

```
#!/bin/sh
set -e -x
noexistent_command \
&& true
echo 'I did not fail'
```
results in . . .

```
$ ./blah2 
+ noexistent_command
./blah2: 3: ./blah2: noexistent_command: not found
+ echo I did not fail
I did not fail
```

I expected `set -e` would prevent the `echo` command above from being run, which is exactly what happens when you get rid of the "and chain":

```
#!/bin/sh
set -e -x
noexistent_command
true
echo 'I did not fail'
```

results in . . .

```
$ ./blah3 
+ noexistent_command
./blah3: 3: ./blah3: noexistent_command: not found
```
Without the "and chain" blah3 stops at `noexistent_command `, before it gets to the `echo`.

**Comment by donkirkby** [comment]
I just ran into this same problem, and it looks like it's a feature of the shell. From the [dash man page]:

>**Argument List Processing**
>...
>`-e errexit` If not interactive, exit immediately if any untested command fails. The exit status of a command is considered to be explicitly tested if the command is used to control an if, elif, while, or until; or if the command is the left hand operand of an “&&” or “||” operator.

I'm using the same technique as @granek: removing the `&&` chains when I convert from Docker to Singularity.

[dash man page]: http://manpages.ubuntu.com/manpages/xenial/man1/dash.1.html

**Comment by GodloveD** [comment]
Yeah, it looks like this is actually the expected behavior.  So I guess I'll just close the issue.  If anyone thinks it should be re-opened for any reason just holler.

**Comment by Flamefire** [comment]
I just ran into this with singularity 3.1

Can this be VERY explicitly documented? Currently even the official docu to `%post` section uses `apt-get update && apt-get install -y netcat`. Can this be highlighted as an ANTI-PATTERN for singularity definition files as a failing `update` will silently succeed further commands leading to indeterminate behaviour which subverts the whole "reproducible build" argument

**Comment by GodloveD** [comment]
Sure @Flamefire.  Would you like to create a PR [here](https://github.com/sylabs/singularity-userdocs)?  Not sure exactly where it should be documented, but maybe you can suggest a good spot.  

Also, I'd like to point out that builds are never really reproducible.  Put another way, if you are relying on def files as part of your reproducibility strategy you are basically already sunk.  The internet changes.  If you really want reproducibility save and reuse the build artifacts (i.e. the containers themselves).  😄
