### ISSUE TITLE
singularity permission denied

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [apptainer/singularity#1616]
I try to use a docker machine on singularity. I know the machine have the program on a particular directory
I use this command:

```
 singularity  build container2.img docker://broadinstitute/oncotator:1.9.9.0
 singularity exec --home /home/maurizio/Desktop/TEST_ONCOT container.img bash
/root/oncotator_venv/bin/oncotator -h
bash: /root/oncotator_venv/bin/oncotator: Permission denied

```
How can have a permission to run on singularity?

**Comment by dtrudg** [comment]
Hi @bioinfo-dirty-jobs - when you run Singularity you are running as a normal user. The `/root` directory is set to be only accessible to the root user - so things inside can't be run. It's a little odd for a container to install things into `/root` like this one does.

You can get around it by building with a definition file like this...

```
Bootstrap: docker
From: docker://broadinstitute/oncotator:1.9.9.0

%post
chmod 755 /root
```

built like this...

`sudo singularity build oncotator.simg deffile`

The `%post` block there opens up the permissions on the `/root` directory so that you can execute things there.

**Comment by bioinfo-dirty-jobs** [comment]
@dctrud  Thanks so much for your help!!!

**Comment by vitchyr** [comment]
I'm having similar issues where /root is read-only. I tried adding

```
%post
    chmod 777 /root
```

This works on my local computer, but not on a remote cluster where I only have write access to specific directories inside of `/global`. Has anyone else run into this issue?

**Comment by QwertyJack** [comment]
@vitchyr KEEP AWAY FROM `/root`, as [docs](https://www.sylabs.io/guides/3.2/user-guide/definition_files.html?highlight=best%20practice#best-practices-for-build-recipes) goes.
Try another dir, e.g. `/app` or `/opt`.

**Comment by vitchyr** [comment]
@qwertyjack thanks for the suggestion. I actually had the same issue when using `/opt` and needed the same fix.

**Comment by jscook2345** [comment]
@vitchyr 

Can you share your definition file so we can see what you're trying to do? Also, which cluster scheduler are you using? Slurm?

**Comment by QwertyJack** [comment]
Then you must bind `/global` if writing sth.
E.g. `singularity exec -B /global <container> sh -c "echo hello > /global"`
By default only `$HOME` is bound.

**Comment by vitchyr** [comment]
I ended up doing the following which worked.

```
Bootstrap: docker
From: some-image-that-uses-root-and-opt

%post
    mkdir -p /global/path/directories/my/script/uses
    chmod -R 777 /opt
    chmod -R 777 /root
    touch /bin/nvidia-smi #these commands and below have to do with using Nvidia drivers
    touch /usr/bin/nvidia-smi
    touch /usr/bin/nvidia-debugdump
    touch /usr/bin/nvidia-persistenced
    touch /usr/bin/nvidia-cuda-mps-control
    touch /usr/bin/nvidia-cuda-mps-server
    mkdir /etc/dcv
    mkdir /var/lib/dcv-gl
    mkdir /usr/lib64
```

Yes, I am using slurm. I think the hard part is that if I'm using a docker image, then I don't have control over where files insides the docker image are created.

It would have been useful for me if there were more docker-specific warnings/best practices. It might be helpful for other users too, since the ability to wrap a docker image makes Singularity very appealing.

**Comment by QwertyJack** [comment]
`chmod -R 777` seems quite dangerous; perhaps `755` is enough for `/opt`.
I would suggest to move all related files from `/root` to `/opt` if using singularity.

BTW, singularity is a little different from docker. In singularity container the user should not have root access.

**Comment by tashrifbillah** [comment]
> I ended up doing the following which worked.

@vitchyr So, you needed to `singularity build` that recipe you posted, didn't you?

**Comment by tashrifbillah** [comment]
Hi all, please see my related issue below:

I built the following docker image:

```vim
FROM centos:7.5.1804
WORKDIR /opt
RUN touch hi.txt
chmod -R 777 /opt
```

Then,

```
docker build -t test .
docker save HASH test.tar
singularity build test.sif docker-archive://test.tar
```

Finally, when I do:
> singularity shell test.sif

I find `/opt` permission miraculously changed to 775. Is this expected?

**Comment by tashrifbillah** [comment]
The goal is to facilitate users run my docker container with singularity. I can adjust permission of `/opt` for my docker container, but if `singularity shell test` does not retain that, it would be trouble. 

Looking at the above discussion, it appears that if the user is able to `singularity build` my container with `chmod -R 777` in `%post` at their end, then they can possibly retrieve my file permission. However, that won't be an option because he would need sudo which is not possible in HPC.

**Comment by dtrudg** [comment]
@tashrifbillah - please don't try to initiate conversation across multiple issues which have been closed.

I suggest using the slack channel or mailing list for these types of questions, as there isn't a bug in Singularity here - rather it's a usage issue for certain containers. The slack chat and mailing list will be seen by a wide range of users who may be able to help. Nobody will see these closed issues except those subscribed to them.

Go here to join the slack chat or mailing list: https://sylabs.io/resources/community

**Comment by tashrifbillah** [comment]
> as there isn't a bug in Singularity here

@dctrud , GitHub issues are not necessarily meant for pointing out bugs. You can also ask questions on them.

> please don't try to initiate conversation across multiple issues which have been closed.

Is this a rule in place for this repository? Users would look up previous issues before opening a new one and ask questions there.

> Nobody will see these closed issues except those subscribed to them.

I understand that and those subscribers were intended to reach only.

That being said, do you know the answer to my questions? Can you help?

**Comment by dtrudg** [comment]
@tashrifbillah - Projects have varying views on GitHub issues. Some do allow all discussion, some enforce that they are only for tracking bugs. We simply like to encourage use of Slack and mailing lists for questions as this project has a very large number of users, vs the much smaller number of developers who review issues periodically. Also, for applications related questions, the developers are not likely to have experience with a particular docker container / application, while the general user community may well.

Avoiding commenting on closed issues isn't a absolute rule, but please don't expect a fast reply. When the problem is not _exactly_ the same as the initial report it can also be annoying to others subscribed on the thread.

If there is a specific problem with retaining permissions that you are seeing then we need to know things like the singularity version you are using etc. - please use the issue template and a new issue for that specific issue.

More generally, though, a SIF image is read-only and you would not generally expect to need to write into `/opt`. That can only work with Singularity if you use a writable sandbox, or overlay so the `775` would not be expected to cause an issue here, even if it doesn't match the intention.

**Comment by tashrifbillah** [comment]
> please don't expect a fast reply.

I don't know how you got that impression but I am accustomed to contributing to open source projects and so I never will. There is a `Arctic Code Vault Contributor` badge on my profile which should speak in line with that.

> it can also be annoying to others subscribed on the thread.

I would be tempted to believe the others refer to you only. If I don't like to remain subscribed to a thread, there are many ways I can stop watching that including using the mute feature on my gmail. I maintain over a dozen projects concurrently and I would welcome any discussion by any means even on long-buried issues.

> We simply like to encourage use of Slack

Sorry, I don't like that way and I know many who don't either. It's just one more account to maintain with the overwhelming numbers I do already. I would rather ask questions on GitHub with a `[Question]` label upfront.

Anyways, I subscribed to your Google group and asked there.
