### ISSUE TITLE
Network namespaces

### ISSUE THREAD

**Issue by planetA** [apptainer/singularity#1623]
Hello,

the [FAQ](http://singularity.lbl.gov/faq#how-does-singularity-handle-networking) says that network namespaces will be supported in 3.0 release. May I kindly ask on the status update, what features are planned and is there anything to try out at the moment?

In particular, I'm interested in possibility to launch a bunch of singularity containers with mpirun across multiple nodes. Each container should run in its own network namespace, but all the containers should be in the same local network. The containers should be visible to the rest of the containers that were launched together and to the host systems. If think this would require the host system to create a bridge connecting host network interfaces to virtual network interfaces of the guest and proper coordinated configuration of routing. Is something like that planned?

UPDATE.

I noticed that singularity allows to create a new namespace, but the new namespace is empty and is not very useful for applications communication over the network. I'm curious if there are plans to make this option more useful.

**Comment by cclerget** [comment]
Hi @planetA , the plan for 3.0 release is to provide network feature with CNI like setup bridge/tuntap/macvlan/ipvlan and port mapping, so containers running on the same host could communicate each others with a bridge setup by example.
Thanks to CNI plugin system (https://github.com/containernetworking/cni) Singularity containers could run in different kind of network environments setup by admins, Singularity will just use CNI interface to execute CNI plugins, offering great flexibility for admins to install/configure their own plugins/network setup.

Yes with 2.x release you can create a network namespace but usage is very limited since only loopback interface is configured.

**Comment by planetA** [comment]
@cclerget, thanks for the response. Is there any possibility to try this out?

**Comment by cclerget** [comment]
@planetA Not actually and probably not until 3.0 release reaches alpha stage

**Comment by bauerm97** [comment]
@planetA You're welcome to check in on development progress by watching open PR's and checking out the latest `development-3.0` branch in the mean time though!

**Comment by dtrudg** [comment]
Closing - CNI functionality has been available for a while. https://sylabs.io/guides/3.5/user-guide/networking.html
