### ISSUE TITLE
the --home option behaves unexpectedly if your $PWD is $HOME

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1656]
## Version of Singularity:

2.5.1-HEAD.g8fa932b

### Expected behavior

The `--home` option should behave the same no matter where you are.   

### Actual behavior

Compare these two cases:
```
$ cd /tmp/

$ mkdir ~/foo

$ singularity shell -H /home/vagrant/foo ~/ubuntu
Singularity: Invoking an interactive shell within container...

Singularity ubuntu:/tmp> pwd
/tmp
Singularity ubuntu:/tmp> cd
Singularity ubuntu:~> pwd
/home/vagrant/foo
Singularity ubuntu:~> cd ..
Singularity ubuntu:/home/vagrant> ls -l
total 4
drwxrwxr-x 2 vagrant vagrant 4096 Jun 14 02:21 foo
```
And now this
```
$ cd

$ singularity shell -H /home/vagrant/foo ~/ubuntu
Singularity: Invoking an interactive shell within container...

Singularity ubuntu:/home/vagrant> pwd
/home/vagrant
Singularity ubuntu:/home/vagrant> ls -l
total 27320
drwxrwxr-x  2 vagrant vagrant     4096 Jun 14 02:22 foo
drwxrwxr-x  5 vagrant vagrant     4096 May  7 14:14 go
drwxrwxr-x  2 vagrant vagrant     4096 Jun 13 17:50 newhome
drwxrwxr-x  3 vagrant vagrant     4096 Jun 13 20:16 sandbox
drwxr-xr-x  9 root    root        4096 Jun 13 20:20 sing-dev
drwxrwxr-x 17 vagrant vagrant     4096 Jun 13 20:20 singularity
-rwxr-xr-x  1 vagrant vagrant 27942943 Jun 14 02:18 ubuntu
drwxrwxr-x  4 vagrant vagrant     4096 May  7 13:51 versioned
```
In the second case I can see all of the contents of `/home/vagrant`.  In other words, the `--home`  option did nothing to contain my home directory to `/home/vagrant/foo`.

**Comment by DrDaveD** [comment]
This is because the default behavior of --pwd is to mount the current directory at the current place.  It overrides --home.

**Comment by Flamefire** [comment]
This came up again on singularity 3.x. If one specifies `--no-home` one does want that. Otherwise you get into a lot of hard-to-find issues e.g. with Python which has modules in the users home which might be incompatible or at least unexpected inside the container.

There is `--contain`, which does solve this by dropping you into an empty home. But it does have other problems, e.g. Infiniband is no longer working as it needs more stuff from /dev.

The `--pwd` mount is unexpected especially when pwd is $HOME and `--no-home` is used. Futhermore the automic bind of home does prevent providing images with predefined setups/files in the home directory.

I'd therefore request a change of either:
- if $PWD is $HOME and --no-home is given, to not mount $PWD
- add flag --really-no-home which does provide an empty (or container fs defined) home similarly to --contain
- if --no-home is given and $PWD is (sub path of or equal) $HOME issue an error unless --pwd is given (if I'm reading correctly --pwd is mounted, not $PWD although https://sylabs.io/guides/3.2/user-guide/bind_paths_and_mounts.html#system-defined-bind-paths says otherwise)

**Comment by DrDaveD** [comment]
Instead of --really-no-home and even --no-home I recommend instead to create a new directory and use it with `--home <newdir>:$HOME`.
