### ISSUE TITLE
Issue better error when there is not enough space on /tmp to build

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#1680]
## Version of Singularity:

2.5.1

### Expected behavior

Get an error along the lines of:
```
There is not enough space on /tmp to stage building of a singularity image
```

### Actual behavior

The error looks more like:
```
Could not mount Singularity overlay: Invalid argument
```

### Steps to reproduce behavior

Try building, pulling, running, etc a big container from docker hub (like tensorflow) with a very limited amount of /tmp space.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@GodloveD We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Pending issues from the old repo are copied to the new repo (https://github.com/apptainer/apptainer/issues/1392) and cleaned from the old, retired repo.
