### ISSUE TITLE
--contain still mounts the real working dir?

### ISSUE THREAD

**Issue by kenneth59715** [apptainer/singularity#175]
I'm trying to use --contain to tell singularity not to allow access to any outside
dirs within the container:
singularity --debug -v -v -v shell --contain nsguser.im

but it looks like I can still write to the working directory.

Is shell --contain supposed to start a shell in the container without any real
dirs mounted inside?

**Comment by gmkurtzer** [comment]
What is the output of "pwd" from within the directory you started the container in?

Is it (unreachable)? If so, I will fix.

Thanks!

**Comment by kenneth59715** [comment]
It's printing full path to the real dir.
...
VERBOSE [U=505883,P=1]     sexec.c:781:main()                         : Changing to correct working directory: /projects/ps-nsg/home/nsguser/kennethtest/singularity
DEBUG   [U=505883,P=1]     sexec.c:798:main()                         : Setting environment variable 'SINGULARITY_CONTAINER=1'
DEBUG   [U=505883,P=1]     sexec.c:806:main()                         : Setting NO_NEW_PRIVS to prevent future privilege escalations.
VERBOSE [U=505883,P=1]     sexec.c:832:main()                         : COMMAND=shell
DEBUG   [U=505883,P=1]     container_actions.c:98:container_shell()   : Called container_shell(1, **argv)
VERBOSE [U=505883,P=1]     container_actions.c:108:container_shell()  : Exec()'ing /bin/sh...
sh-4.2$ pwd
/projects/ps-nsg/home/nsguser/kennethtest/singularity
sh-4.2$ df -k .
df: ‘/projects/ps-nsg’: No such file or directory
sh-4.2$

**Comment by gmkurtzer** [comment]
What is the output of this command:

```
$ singularity exec -C nsguser.img cd `pwd`
```

**Comment by kenneth59715** [comment]
/bin/cd: line 2: cd: /projects/ps-nsg/home/nsguser/kennethtest/singularity: No such file or directory

**Comment by gmkurtzer** [comment]
Ahh, ok. Good.

Easily fixable. I'll have it taken care of in about 5 minutes and pushed to the 2.x branch getting ready for 2.1.1. :)

Thanks!

**Comment by kenneth59715** [comment]
Cool, thanks!

**Comment by gmkurtzer** [comment]
Fixed and pushed to [2.x 31a0754]. If you can test, that would be fantastic!

Thanks!

**Comment by kenneth59715** [comment]
Okay, will test.  Might not get to it today, though.

**Comment by kenneth59715** [comment]
Okay, I did give it a really quick look.  Looks like it's working!  No homedir or working
dir mounting.  Just /.  So, looks good so far!

Thanks,
Kenneth

**Comment by kenneth59715** [comment]
@rpwagner I ran into this issue.  Could you have the team push this version out?
Thanks,
Kenneth

**Comment by rpwagner** [comment]
@kenneth59715, did you see my comment on issue #168? I've already asked @csirving to push it out and notify you.

**Comment by gmkurtzer** [comment]
@rpwagner I think he is referring to the latest code in the 2.x branch which has two bug fixes in the 2.1 release. (I am really going to need to push 2.1.1 soon!) lol

Thanks!

**Comment by gmkurtzer** [comment]
I am going to close this issue as it seems this is working at this point. Please re-comment on the ticket and let me know if I am mistaken and I will reopen.

Thanks!

**Comment by kenneth59715** [comment]
Hi,

 The systems folks have installed the latest from master, but --contain is not working in that version:
I can still write to the real directory.  For the installed version:

> commit 18657f092c281a0ab196e0953beb752a6f68724a
> Merge: 2ee8182 99be50e
> Author: Gregory M. Kurtzer gmkurtzer@lbl.gov
> Date:   Fri Aug 19 11:27:17 2016 -0700

[nsguser@comet-17-26 singularity]$ /opt/singularity/bin/singularity --version   Unloading compiler-dependent module openmpi_ib/1.8.4
2.2
[nsguser@comet-17-26 singularity]$ /opt/singularity/bin/singularity exec -C nsguser.img cd `pwd`
Unloading compiler-dependent module openmpi_ib/1.8.4
Unloading compiler-dependent module openmpi_ib/1.8.4
/bin/cd: line 2: cd: /projects/ps-nsg/home/nsguser/kennethtest/singularity: No such file or directory
[nsguser@comet-17-26 singularity]$

**Comment by gmkurtzer** [comment]
Oh, they are using an unreleased version?! Hrmm, ok. I would recommend either going backwards to the 2.1.2 tag, or waiting a few more days and resyncing from master. MASSIVE amounts of changes happening in the devel branch and master had some contributions that got ahead of the development curve and I haven't had time to test. I'm pretty sure that has already been fixed in the devel branch.

Thanks!

**Comment by rpwagner** [comment]
We have a tagged release installed for general use. This install for Kenneth is to test features in development.

--Rick

On Aug 22, 2016, at 9:42 PM, Gregory M. Kurtzer <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh, they are using an unreleased version?! Hrmm, ok. I would recommend either going backwards to the 2.1.2 tag, or waiting a few more days and resyncing from master. MASSIVE amounts of changes happening in the devel branch and master had some contributions that got ahead of the development curve and I haven't had time to test. I'm pretty sure that has already been fixed in the devel branch.

Thanks!

**Comment by gmkurtzer** [comment]
Ahhh, that makes sense! And thank you for the testing! In a few more days, I will be merging devel to master, at which point I will need LOTS of testing help! Any volunteers? ;-)

@kenneth59715, can you check to see if it is working for the released version?

**Comment by bbockelm** [comment]
Additionally, it would be super-helpful to put in a PR to `test.sh` for a minimal reproduction of the issue.

**Comment by gmkurtzer** [comment]
@bbockelm Good point! ++!!

**Comment by kenneth59715** [comment]
Perhaps I'm confused on which branch/tag is good.  I did a checkout 2.1.2, installed that,
--contain works, with current dir read-only.
However, --contain --writable gives me an error.  (2.x branch also works with --contain, but
--contain --writable complains.)
[nsguser@comet-ln2 singularity]$ /tmp/kenneth/singularity/install/bin/singularity shell --contain --writable nsguser.img
ERROR  : Only root can mount images as writable
[nsguser@comet-ln2 singularity]
My branch/tag is:
[kenneth@comet-ln2 singularity]$ git branch --list --verbose
- (HEAD detached at 2.1.2) caa7046 Fix #180 (Potential kernel panic when running a container with corrupted ext filesystem)
  2.x                      27594d7 Fixed example bootstraps
  master                   9f8121b [behind 68] Merge pull request #172 from bbockelm/root_privs
  [kenneth@comet-ln2 singularity]$

**Comment by gmkurtzer** [comment]
Hi @kenneth59715 

There was a change in how the --writable flag works after 2.1.0 in that only root is allowed to use that flag. This is because --writable must flock() the image itself, and considering most images existed on NFS/Lustre storage, the flock was failing. So this way it sorta limits the need for flock() for most HPC use-cases.

I think that 2.2 will have several different solutions to this, but that is still in development. :)

Greg
