### ISSUE TITLE
2.5.2 on Ubuntu

### ISSUE THREAD

**Issue by jakirkham** [apptainer/singularity#1750]
Appears version 2.5.2 is missing from Ubuntu. Would it be possible to get it updated?

**Comment by GodloveD** [comment]
I think this is a question for @yarikoptic and @0xaf1f ?  Or they may know who to ask?

**Comment by 0xaf1f** [comment]
There is no dedicated maintainer for singularity in Ubuntu, so they just get whatever floats down from Debian. I guess the Ubuntu developers would want you to report a bug in Launchpad: <https://launchpad.net/ubuntu/+source/singularity-container>. I'm not sure if anybody looks at those, though. Maybe they will if it's something they can handle, like this--updating the package version.

**Comment by yarikoptic** [comment]
yeap, ubuntu eventually will suck it in from debian... some kind of a MOTU should take care about triggering action I believe.  As for NeuroDebian backports -- just uploaded 2.5.2 to replace 2.5.1, should propagate to mirrors within a day, enjoy. AFAIK the issue is resolved and further comments should be directed to the corresponding distribution (e.g. ubuntu)

**Comment by 0xaf1f** [comment]
And as for Debian itself, 2.5.2 was uploaded the day after the release, both in the official stable and oldstable backports repositories.

**Comment by yarikoptic** [comment]
And thank you for that @0xaf1f !

**Comment by GodloveD** [comment]
Thanks for clarifying @yarikoptic and @0xaf1f!

**Comment by GodloveD** [comment]
OK wait.  I'm about to parade my ignorance for all to see.  (But hopefully it will help not just me but somebody else who has the same question.) 

@0xaf1f you said that the official stable debian has 2.5.2 right?  So I just spun up a brand new stretch vm in Vagrant and did the following.  What gives?

```
vagrant@stretch:~$ sudo apt-get update
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Hit:3 http://deb.debian.org/debian stretch Release
Reading package lists... Done

vagrant@stretch:~$ sudo apt-get install singularity-container
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  singularity-container
0 upgraded, 1 newly installed, 0 to remove and 17 not upgraded.
Need to get 138 kB of archives.
After this operation, 986 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 singularity-container amd64 2.2-2 [138 kB]
Fetched 138 kB in 0s (906 kB/s)
Selecting previously unselected package singularity-container.
(Reading database ... 26673 files and directories currently installed.)
Preparing to unpack .../singularity-container_2.2-2_amd64.deb ...
Unpacking singularity-container (2.2-2) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up singularity-container (2.2-2) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...

vagrant@stretch:~$ singularity --version
2.2
```

Based on [this Vagrant box](https://app.vagrantup.com/debian/boxes/stretch64) btw.

^EDITED (got the URL wrong the first time)

**Comment by 0xaf1f** [comment]
> you said that the official stable debian has 2.5.2 right? So I just spun up a brand new stretch vm in Vagrant and did the following. What gives?

I said that stable-backports has it. The package is actually going to be removed completely from stable proper due to our inability to provide security patches for that version.

See https://packages.debian.org/search?keywords=singularity-container&searchon=names&suite=all&section=all
The ones I'm talking about are `stretch-backports` and `jessie-backports-sloppy`.

So on stretch, you'd have to have stretch-backports in your sources.list:

```
# echo 'deb http://ftp.debian.org/debian stretch-backports main' >> /etc/apt/sources.list
# apt-get update
# apt-get -t stretch-backports install singularity-container
```
described at https://backports.debian.org/Instructions/

**Comment by GodloveD** [comment]
Thank you for the clarification!

**Comment by 0xaf1f** [comment]
Sure thing. I wish it was simpler.

**Comment by jakirkham** [comment]
Thanks all. Looks like this got updated. Going to close this out as resolved.
