### ISSUE TITLE
--pid does not work with user namespace inside docker without --privileged

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#1768]
## Version of Singularity:

2.5.2

### Expected behavior

--pid works with unprivileged singularity, inside user namespace, even within docker containing --cap-add=SYS_ADMIN.

### Actual behavior

ERROR  : Could not mount new procfs into container: Operation not permitted

unless the docker container is run with --privileged.

This is due to a kernel limitation that disallows mounting over existing mountpoints.  [This article](https://serverfault.com/questions/897299/how-do-i-mount-a-private-proc-inside-a-namespace-inside-a-docker-container) has a very good explanation of why it happens and includes a workaround, but the workaround removes the extra mounts on top of /proc that docker puts in for a reason.  I think it would be better for singularity to umount in its namespace all the bind mounts that docker adds on top of /proc before attempting to mount a new /proc.

### Steps to reproduce behavior

The easiest way to reproduce is on a system that has [OSG cvmfs installed](https://opensciencegrid.org/docs/worker-node/install-cvmfs/), because it has both unprivileged singularity and unpacked images available.  Then the following command demonstrates the problem:
```
$ docker run -it --rm -v /cvmfs:/cvmfs:ro,slave - --cap-add=SYS_ADMIN centos:7  bash -c 'useradd unprivuser; runuser -s /bin/bash unprivuser -c "/cvmfs/oasis.opensciencegrid.org/mis/singularity/el7-x86_64/bin/singularity exec --pid /cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo:el6 id"'
ERROR  : Could not mount new procfs into container: Operation not permitted
ABORT  : Retval = 255
```

Applying the workaround from the above serverfault article works:
```
$ docker run -it --rm -v /cvmfs:/cvmfs:ro,slave --cap-add=SYS_ADMIN centos:7  bash -c 'for dir in $(awk '"'"'/\/proc\// { print $5; }'"'"' /proc/1/mountinfo ); do umount "$dir"; done;useradd unprivuser; runuser -s /bin/bash unprivuser -c "/cvmfs/oasis.opensciencegrid.org/mis/singularity/el7-x86_64/bin/singularity exec --pid /cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo:el6 id"'
WARNING: Container does not have an exec helper script, calling 'id' directly
uid=1000(unprivuser) gid=1000(unprivuser) groups=1000(unprivuser)
```

Or also using --privileged instead of --cap-add=SYS_ADMIN works, because then docker does not add the extra mounts over top of /proc.

**Comment by dtrudg** [comment]
Hi @DrDaveD - do you have a specific use case where it is beneficial to run singularity in docker with `--cap-add=SYS_ADMIN` but not `--privileged`?

I'm pretty wary of the idea of Singularity un-mounting any protective bind mounts that docker puts in place. They have been put there for a reason, and we likely don't want to impact the security of an outer container runtime from an inner runtime.

AFAIK docker-in-docker has a hard `--privileged` requirement, so I think it's reasonable singularity-in-docker does also.

**Comment by DrDaveD** [comment]
All the information I have seen from docker says to give containers the least amount of privilege you can get away with, and at Fermilab that's the way we have been running unprivileged singularity containers, inside of docker containers.  There are several other capabilities also given to the docker containers, but they're not needed for unprivileged singularity, they're for other applications.

With --pid, /proc is being completely replaced, so the singularity container will never see the unmounted things under /proc, right?  If we don't do this inside of singularity, the workaround is for the system administrator to unmount all those things before user code invokes singularity, and that is the place to be wary about, not inside of singularity.

**Comment by dtrudg** [comment]
Right - assuming all is good the container shouldn't see the unmounted things under /proc, but I'm wary of impacting the security-related flow of another runtime. Also, unpriv'd singularity within docker containers is not a common use case to my knowledge, and we'd add some testing burden verifying correct behavior for a docker specific case in an area which is security sensitive. 

I'll defer to @cclerget to see if he has any thoughts on this, but my working assumption is that this is unlikely to be a near-term priority.

It might be good to have a bit more info on why you are using singularity, unpriv'd inside docker containers with --pid? It's an interesting combination of things, and maybe there's something we need to think about here. 

Thanks!

**Comment by DrDaveD** [comment]
It is a pretty common use case in the WLCG (Worldwide LHC Computing Grid) to run singularity inside of docker.  Docker is configured by system administrators for isolation and control of the operating system environment for jobs, and then pilot jobs from different Virtual Organizations run singularity to isolate between the different user jobs they run (using --contain --ipc --pid) and also to control again the operating system environment.  It's true that so far only Fermilab is running singularity unprivileged this way that I am aware of, because they want to avoid the risks of installing setuid programs.  Red Hat Enterprise Linux 7 only has unprivileged namespaces as a technology preview at this point, but once they promote it to production support I expect this use case to become much more common.   So the need is not necessarily very urgent, but I would like to see this use case be supported in 3.0.

**Comment by bauerm97** [comment]
Hi @DrDaveD , 

Unfortunately I'm not really sure this is even a possibility for us to handle. I believe that since you're running a completely unprivileged singularity binary, we won't be able to unmount those files (notice how in your workaround that operation is happening *with* `CAP_SYS_ADMIN`). Otherwise, you could simply unmount those files in a `runscript`.

However, I think I can propose a different solution to this entire problem, one that seems much more sane to me. Right now, you are running singularity inside of a docker container which was spawned with `CAP_SYS_ADMIN`. This means that the calling user definitively has root on the host already. A potentially easier way to achieve this same effect is to just directly use singularity to do this. You can simply do: 

`sudo singularity exec --drop-caps --pid .../osgvo:el6 adduser->runuser...; id`

This way, you are not forced to run a SUID binary on your system, but rather you're escalating privilege and dropping privilege in the same way as you're doing with Docker. In this approach however, the proc that is immediately executed inside the container will not have any capabilities, which is more secure compared to the docker solution (which enters the container as full root via `CAP_SYS_ADMIN`)

Further, even if it were possible, for singularity to purposely strip security features using privilege while living inside of a specific security context would be incredibly insecure. I would not be comfortable having this feature in Singularity.

**Comment by DrDaveD** [comment]
Hi @bauerm97.   As I said in my first response to @dctrud, this would not be exposing anything privileged because it immediately overwrites all of /proc with a fresh procfs, so the original things hidden by docker are never exposed to the container.

Starting a new unprivileged namespace gives the user privileges in the namespace to both mount and to unmount in that namespace.  I know that's the case because I do it in the underlay feature and have tested it unprivileged.  It umounts something it had previously mounted.  The privilege to do those mounts & unmounts is given up before runscript is invoked (by switching away from the pseudo-root user) so the end user running the container can't do it.

However, having said all that, I ran some tests and see now that it does not have the privilege to umount these specific mounts, for the reason that the article states: those mountpoints are locked in the unprivileged namespace.   So you are right, this request is not something that singularity can do, and I will close this issue.

The idea of using sudo singularity instead of docker is intriguing, but I don't think it is practical for this case, at least not yet because --drop-caps is a 3.0 feature only.  I see there is also an --add-caps at that point so presumably one could select just the capabilities desired (I didn't show all of the desired capabilities in the example), which would help.  I have a question, though: if hiding those things in /proc are a useful security feature in docker, then why shouldn't singularity be doing it too?

**Comment by dtrudg** [comment]
> if hiding those things in /proc are a useful security feature in docker, then why shouldn't singularity be doing it too?

As I understand it, because Singularity forces the user inside the container to be the invoking user, and blocks privilege escalation, you could not do anything in the container with these /proc points unless you invoke it as root... in which case you could access them outside of the container and all bets are off. With docker you are, by default, root in the container with perms to access root-owned files... even if you don't have certain capabilities.... and non-root users may have rights to run containers through orchestration solutions etc. etc.
