### ISSUE TITLE
running Singularity on WSL

### ISSUE THREAD

**Issue by kkmann** [apptainer/singularity#1791]
## Version of Singularity:

2.4.2-dist

### Expected behavior

run singularity pull shub://vsoch/hello-world without error in windows subsystem for linux (Ubuntu 18.04)

### Actual behavior

Throws Error: Called singularity_config_get_value on unitialized config subsystem

Any ideas what is going wrong here? Is WSL supported at all?

**Comment by dtrudg** [comment]
@kkmann - at present, WSL does not implement some of the system calls that singularity uses. Running under WSL is not supported.

I'm not sure if WSL is likely to add support for the missing things Singularity needs. Since they are generally related to mounting filesystems to construct the container, and Windows has a very different filesystem structure, full support may not appear through WSL. We keep an eye on what Microsoft are adding, though.

**Comment by kkmann** [comment]
Thanks for the info, lets hope for the best then ;)

**Comment by rickstaa** [comment]
@kkmann @dctrud For me Singularity appears to be inside WSL2. As explained [here](https://docs.microsoft.com/nl-nl/windows/wsl/wsl2-faq) you are only not yet able to access the GPU. Additionally, the PS does not display the correct path.

**Comment by dtrudg** [comment]
Thanks @rickstaa - WSL2 was mentioned in the more recent issue here: https://github.com/sylabs/singularity/issues/4518
