### ISSUE TITLE
HOME env var is overridden when importing some docker containers

### ISSUE THREAD

**Issue by pescobar** [apptainer/singularity#1812]
## Version of Singularity:

2.5.2-dist

### Expected behavior

don't override HOME when importing a docker container

### Actual behavior

when importing the GATK docker container the env var HOME=/root

### Steps to reproduce behavior

I tried to import the official GATK docker container like this:

```singularity pull --name gatk.img docker://broadinstitute/gatk:4.0.7.0```

and I noticed that HOME is overriden

```
singularity exec gatk.img grep HOME /.singularity.d/env/10-docker.sh
export HOME="/root"
```
IMHO it would make sense that HOME is never overridden in `/.singularity.d/env/10-docker.sh`  when importing a docker container. Or maybe there is an alternative workaround?

**Comment by chrisreidy** [comment]
I have the same problem.  I did a "singularity pull docker://gassmoeller/aspect" which is a Geoscience code.  It puts all the good stuff in /home.  My singularity.conf file for the cluster mounts /home locally which overwrites everything in the image.  I need a workaround too
Chris

**Comment by chrisreidy** [comment]
Update:  I got around the problem by doing a "export SINGULARITY_HOME=/extra/cr/x"  (a directory I created to deflect home away from the container's /home).  Then "singularity shell aspect.simg"

**Comment by DrDaveD** [comment]
You could also use the --home command line option.

**Comment by dtrudg** [comment]
3.x will have `export HOME=${HOME:-"/root"}` in `10-docker2singularity.sh` and since $HOME will be set then it won't take effect.

> I have the same problem. I did a "singularity pull docker://gassmoeller/aspect" which is a Geoscience code. It puts all the good stuff in /home. My singularity.conf file for the cluster mounts /home locally which overwrites everything in the image. I need a workaround too

In fresh versions of Singularity `--nohome` will prevent your `$HOME` being mounted in. See also the bottom replies on #879

**Comment by mr-c** [comment]
@dctrud Please re-open this issue, as I'm not seeing the behaviour you describe; `$HOME` is still being imported from the outside environment regardless of `--no-home` or not:

```
$ docker run -it gassmoeller/aspect /bin/bash
dealii@6adbbacff516:~/aspect$ echo $HOME
/home/dealii
dealii@6adbbacff516:~/aspect$ exit
michael@mrc-tux:~/debian/gffread$ singularity run --no-home  aspect_latest.sif 
dealii@mrc-tux:~/debian/gffread$ echo $HOME
/home/michael
dealii@mrc-tux:~/debian/gffread$ exit
michael@mrc-tux:~/debian/gffread$ singularity version
3.1.1+ds
$ singularity run aspect_latest.sif 
bash: manpath: command not found
bash: register-python-argcomplete3: command not found
dealii@mrc-tux:~/debian/gffread$ echo $HOME
/home/michael
```

**Comment by jmstover** [comment]
@mr-c  ... That should be the case for the `HOME` variable. The `--no-home` flag should just modify the mounting of the users `$HOME`, but touch nothing else.  It was initially designed as a way to ignore the home mounting when the global config says to mount the users `$HOME`, and `--contain` couldn't be used because of the other effects of `--contain`.

**Comment by mr-c** [comment]
@jmstover The issue is about not overriding the value of $HOME set by the container itself; the provided solution does not fix the problem; therefore the issue should be re-opened.

**Comment by jmstover** [comment]
`export HOME=${HOME:-"/root"}`  ... will change the overwrite of HOME... But it's going to depend on the Docker file whether that's a fix. Some Dockerfiles I've seen have `HOME=/root` in the metadata and stuff is expected to be able to write to that location.

The `--no-home` option was for this part:  `My singularity.conf file for the cluster mounts /home locally which overwrites everything in the image. I need a workaround too` -- from @chrisreidy , not the environment variable part.

**Comment by dtrudg** [comment]
@mr-c - I'm confused a bit here. What is the original issue expecting to happen?

> Expected behavior
> don't override HOME when importing a docker container

> Actual behavior
> when importing the GATK docker container the env var HOME=/root

> IMHO it would make sense that HOME is never overridden in /.singularity.d/env/10-docker.sh when importing a docker container. Or maybe there is an alternative workaround?

From my look at this, this is what `export HOME=${HOME:-"/root"}` in the environment file we add does... if `$HOME` is set as we enter the container, then it isn't going to be overridden here.

> The issue is about not overriding the value of $HOME set by the container itself

This seems to be the opposite of the of the above?

**Comment by jmstover** [comment]
@dctrud 
`this is what export HOME=${HOME:-"/root"} in the environment file we add does...`

I don't think this is going to do what you're wanting... In the `gatk` example, they're explicitly setting `HOME=/root` in the manifest. This means that 10-docker (IIRC) is setting a HOME value. If you set that in the 90-environment file, then you're going to still be setting it's value to `/root` as that's what it was set to at that time.

You would need to have the Go code set an env like `ORIG_HOME=$HOME` ... then in the `91-environment` file do:
```
export HOME=${ORIG_HOME:-/root}
```

You can't use HOME though... as that will be overwritten with:
```
HOME=/root
```
In the manifest, if you do the setting at the top of `10-docker`, and in `9?-environment` it's already set to a `/root` value.

**Comment by dtrudg** [comment]
@jms If I build the container in question into a SIF then....

```
dave@piran~> singularity shell gatk.sif
Singularity> env | grep HOME
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
HOME=/home/dave
```

This comes from hitting ....

```
Singularity> less /.singularity.d/env/10-docker2singularity.sh
#!/bin/sh
export PATH="/gatk:/opt/miniconda/envs/gatk/bin:/opt/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export HOME=${HOME:-"/root"}
```

In `/singularity.d/env` there are _no_ other lines in any file that affect `$HOME`

```
Singularity> grep "HOME" /.singularity.d/* -R
/.singularity.d/env/10-docker2singularity.sh:export HOME=${HOME:-"/root"}
/.singularity.d/env/10-docker2singularity.sh:export JAVA_HOME=${JAVA_HOME:-"/usr/lib/jvm/java-8-openjdk-amd64/"}
```

This seems to be the behaviour the orignal poster was asking for on the issue. They _did not_ want `$HOME` to be `/root` - while @mr-c is asking for it to be set to `/root` - or am I wildly wrong here?

**Comment by jmstover** [comment]
Then they fixed their Docker container finally, as `10-docker2singularity` used to have a `HOME=/root` in it. It still stands that anywhere a Docker container is explicitly setting HOME, that will not do what you're wanting.

I believe you are correct on what @mr-c is asking. Which is honestly the correct behaviour if we attempt to 1:1 a Docker container. In the container his prompt is `dealii@mrc-tux` ... which is a different user name than outside. But he'd want to overwrite that `HOME` in the `%environment` section IMO, and cut out the host environment from affecting it.

**Comment by dtrudg** [comment]
> Then they fixed their Docker container finally, as 10-docker2singularity used to have a HOME=/root in it.

That's not the case - `10-docker2singularity still` *does* pick up that `HOME=/root` bit but the way we write `10-docker2singularity` now only sets that if the var is not already set, it is not a direct export of the `HOME=/root`

```
Singularity> grep "HOME" /.singularity.d/* -R
/.singularity.d/env/10-docker2singularity.sh:export HOME=${HOME:-"/root"}
```

This was because people wanted to be able to override anything that a docker container was setting in its environment.

**Comment by dtrudg** [comment]
Okay - I've chatted with @jmstover  out of band a bit on this one - it's getting a bit confusing on the thread here.

I'm confident that the original request on this issue from @pescobar, that `$HOME` should *not* get set to `/root` is satisfied in the current version of Singularity`, so I'm going to close this specific issue.

@mr-c - if you are requesting the opposite behavior (`$HOME` should be `root` in the container), please could you open a separate issue to track it without the confusing thread here. I don't think we would want to follow that though, since the default position of Singularity is "you are the same user in the container as outside", which I'm guessing most people assume to include `$HOME`

This does indeed cause non-docker like behavior with containers that may set `$HOME` - but if `$HOME` is set or `USER` is used, then docker containers are often expecting that home dir to be writable, which it is not by default with Singularity.

As a workaround here we can get `$HOME` to be `/root/` in the container via the `-H /root` option. `--no-home` would also be needed to ensure that the host `/root` is not mounted over the `/root` in the container.

```
singularity shell --no-home -H /root gatk.sif
```

However on this container `/root` is `700` perms, so it's not possible to get in there anyway. Confirmed this is the case under docker too

```
(gatk) root@36ed35dd1752:/gatk# ls -lah /
...
drwx------   1 root root 4.0K Jul 30  2018 root
...
```

Note also that we document that installation of things to `/root` in the container won't really work in our best practices, where we do talk about things that are not 1:1 with docker

https://sylabs.io/guides/3.4/user-guide/singularity_and_docker.html#best-practices

Thanks.
