### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by dlevitas** [apptainer/singularity#1835]
## Version of Singularity:

2.5.2

### Expected behavior

Build Singularity Image

### Actual behavior

Tried:
`singularity build $HOME/fmriprep-1.1.4.simg docker://poldracklab/fmriprep:1.1.4`

Error message:
`ERROR: You must install squashfs-tools to build images
ABORT: Aborting with RETVAL=255`

### Steps to reproduce behavior

Try to build this from an HPC (Red Hat Enterprise Linux Server release 6.10 Santiago).

### What I've Attempted
 The Singularity version is already on my HPC, so the only thing I downloaded were the [squashfs-tools](https://sourceforge.net/projects/squashfs/files/squashfs/squashfs4.3/), which are in my HOME directory and added to my PATH. My issue seems somewhat similar to #1079, but I still haven't been able to resolve the issue on my end. 

Thank you.

**Comment by jmstover** [comment]
When Singularity is ran it will set the `PATH` to one which includes system paths only.

With 2.5.x, if mksquashfs isn't installed on the system, we error.

Singularity 2.6.0 allows for the specification of the mksquashfs binary at configure time. The path given is hard coded into the build scripts, and executed when `singularity build` is called.

So:

* squashfs-tools must be installed system wide
* If squashfs-tools is not installed system wide, at the `configure` stage the path to a mksquashfs binary can be specified using `--with-mksquashfs` (2.6.0)
* If we can't find a `mksquashfs` binary, we error because we can't make the squashfs filesytem used for the image format.

This is the behavior on the 2.x branch.
