### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by czka** [apptainer/singularity#197]
I have recently uploaded Arch Linux PKGBUILD (sort of RPM or BSD port spec) for Singularity to AUR [1]. Now I would like to help with Arch Linux bootstrapping in Singularity, if you are interested too.

I gather I'd need to provide an appropriate libexec/mods/linux_build_arch.smod file. What else would be needed? The existing Arch Linux Docker image creation script [2] should be a good starting point. I'm wondering how to go about the "udev doesn't work in containers, rebuild /dev" part. I guess #147 is related. Can you see any other problematic parts in the script?

Does [3] include all the currently supported definition file keywords?

[1] https://aur.archlinux.org/packages/singularity-container/
[2] https://github.com/docker/docker/blob/master/contrib/mkimage-arch.sh
[3] http://singularity.lbl.gov/#bootstrap

**Comment by gmkurtzer** [comment]
Fantastic!

Yes, the primary file to create and work with would be linux_build_arch.smod as it currently stands but for 2.2, I've been brainstorming enhancing the bootstrap'ing capabilities considerably. I'm almost done with the backend work (please check out the 'devel' branch to see current status) and will be moving on to the bootstrap mods right after.

You probably won't have to work with the UDEV issues in Singularity because /dev is basically a bind mount from the host (unless someone uses --contain, and in that case the bootstrap infrastructure already builds the bare minimum devices necessary). The general gist of the script seems fine, but various aspects are redundant with what Singularity already does. I would recommend looking at the redhat and debian modules and just fill in the API with those bits necessary for Arch. If you have any specific questions just let me know (I'll leave this issue open for that purpose).

One other thing to consider is that I would like to allow bootstrap's to happen as users. Right now it only works for the busybox module (because I believe YUM and APT check getuid()). If it could be done with Arch, I think that would be a big win for users using Arch with Singularity!

It is my intention to maintain the current bootstrap support as we move forward, so working on linux_build_arch.smod is not a wasted effort. I'll keep this thread open so we can circle back as necessary to get the required bits into the 2.2 release.

BTW, if you use Slack and want an invite, send me your email.

Thanks!

**Comment by czka** [comment]
I'll focus on the smod for 2.x. I'll probably might have something to show next week or so. I'm OK with shell scripting, but the Singularity (and Docker) bootstraping internals are still not 100% clear to me so I might be proceeding slowly.

Is inheriting host's /etc/localtime a good idea or not? How about the locale - should it rather be en_US.UTF-8, the host's setting, else? This will depend on a use case for sure, but I wonder what is the common practice with Singularity images in this regard.

Thanks for the invitation to Slack, but I don't need it at the moment. GitHub tickets are just fine. This way the message exchange is nicely bound to the project itself.

**Comment by gmkurtzer** [comment]
As I mentioned, please feel free to ask me if you have any questions. I'm happy to help.

/etc/localtime is probably best as a bind path actually. That way it is always the same as the host's... But this brings up a compatibility question that I am not familiar enough with. Is the timezone data format _always_ compatible?

We are also on IRC at #singularity on irc.freenode.net if you have any quick questions (depending on who happens to be watching their IRC window at that moment).

**Comment by bbockelm** [comment]
Not saying that we have to copy others, but how does Docker handle `/etc/localtime`?

I _do_ know that various distros have different ways of specifying the timezone info.  I'd be a bit nervous about a mechanism that only works on a few distros or only "half enables" a timezone in a particular container.

**Comment by gmkurtzer** [comment]
The Docker camp will usually hard code the /etc/localtime in the Dockerfile, or they will bind /etc/localtime from the host into the container (but I'm not sure if there is a potential here for issue).

On the other hand (as I'm reading the 'date' manpage, and I can't believe I forgot this...), there maybe a much better way to handle this! The environment variable `TZ` if set in the user's host environment would pass transparently through into the container where it will also work there. So that is probably the most portable way of handling it.

Thoughts?

**Comment by bbockelm** [comment]
Are you thinking we should set `TZ` appropriately if not already present?  Is there a reasonably nice way to detect the correct value of `TZ` from `/etc/localtime`?

I.e., `/etc/localtime` is a file in RHEL6 and a symlink in RHEL7.

**Comment by gmkurtzer** [comment]
I was thinking that inside the container `/etc/localtime` should be set to something sane. Perhaps `UTC` or something specific for a particular use-case.

But it really wouldn't matter if the user had `TZ` set. So what we should do is document that `TZ` should always be set in order to handle and/or implement some magic to set it if it is not set in etc/init:

```
if [ -z "${TZ:-}" ]; then
    TZ=`date +%Z`
    export TZ
fi
```

**Comment by bbockelm** [comment]
ah yes, that would work!  I was thinking about deriving the Olson timezone (`America/Chicago`), not the compact format (`CDT`).

Yeah, I like this approach.

**Comment by gmkurtzer** [comment]
The timezone feature has been committed: [devel a72a79c]

@czka were there any other questions or comments you had for this thread? If not, can you close.

Thank you!

**Comment by czka** [comment]
In my opininion, ideally:
- Locale: def files should accept a keyword for setting an arbitrary number of locales, supporting the format like in these examples: "en_US.UTF-8 UTF-8", "zu_ZA ISO-8859-1", "gl_ES@euro ISO-8859-15". Because GNU/Linux supports multiple locales while POSIX Shell does not support arrays, and strings with spaces are hard to iterate on, this could eg. be a variable with comma-seperated list of locales. Eg. Locale='en_US.UTF-8 UTF-8,zu_ZA ISO-8859-1,gl_ES@euro ISO-8859-15'.
  - Another keyword for default LANG should be there as well. Eg. Lang=pl_PL.utf8.
- Timezone: def files should accept a keyword for setting it to a single string in Olson format. Eg. Timezone='America/Chicago'.

Bootstrap should pass those as variables to a smod file. Each smod would apply them in a distro-specific way. Arch does this as follows: https://wiki.archlinux.org/index.php/Installation_Guide#Locale, https://wiki.archlinux.org/index.php/Installation_Guide#Time_zone. I order to iterate over $Locale, one could use a following syntax in his smod:

```
Locale='en_US.UTF-8 UTF-8,zu_ZA ISO-8859-1,gl_ES@euro ISO-8859-15'

IFS=,
for l in $Locale; do
  echo "doing the distro-specific thing with locale $l"
done
unset IFS
```

Output:

```
doing the distro-specific thing with locale en_US.UTF-8 UTF-8
doing the distro-specific thing with locale zu_ZA ISO-8859-1
doing the distro-specific thing with locale gl_ES@euro ISO-8859-15
```

Until such keywords are supported in def files, I think I'll settle for en_US.UTF-8 UTF-8 and UTC I guess. I shall yet medidate on this tough ;).

@gmkurtzer: Question about the Setup keyword - http://singularity.lbl.gov/#bootstrap reads that it "creates the necessary starting point, files, and components for an OS to be bootstrapped". But I can't find any related code, besides this, in linux_build.smod:

```
Setup() {
    return 0
}
```

There's no trace of `Setup` in bootsrap.exec, functions, bootstrap.sh. Can you tell me how it gets called to do the stuff?

**Comment by gmkurtzer** [comment]
I hope this isn't a stupid/ignorant question, but shouldn't locales be defined within the container by means of the package manager's installation of the relevant packages?

Regarding LANG and Timezone, I feel these should be runtime options rather then hard coded into the container. Granted a particular container may have to have the Locale support built into the container for proper rendering of a particular LANG or timezone, but I feel these should be defined by the user calling the container.

You are right about the Setup keyword. I moved that functionality to PreSetup which is automatically called by the bootstrap driver (bootstrap.sh) so Setup is technically no longer "required'. But I left it there so that a particular smod could define and use it if desired, but this is another case where the code moves faster then the documentation and I surely need help with the docs. lol

Thanks!

**Comment by czka** [comment]
> shouldn't locales be defined within the container by means of the package manager's installation of the relevant packages?

I don't know about other distros, but on Arch this is done **manually**. See the https://wiki.archlinux.org/index.php/Installation_Guide#Locale I mentioned before.

> Regarding LANG and Timezone, I feel these should be runtime options rather then hard coded into the container.

OK. Still, the Arch installation process requires (or at least recommends) these to be set permanently, system-wide, as described in their installation guide. But maybe that's just Arch.

> I surely need help with the docs. lol

The problem with that is that the person who knows what documentation changes are needed is the code changes author :).

**Comment by gmkurtzer** [comment]
Yep, so the locales should be defined and configured at bootstrap time. It would in theory also be possible to have it checked/updated by the container's `/environment` file as well if we want runtime support, but I think that is overkill.

Yes, I also agree that both Lang and Timezone configuration must be set globally and permanently, but they should also be able to be overridden by the user. So the global configuration should be something very simple and portable. For example, earlier I suggested UTC for the timezone.

Haha, yes! You have a good point there about the documentation. I am working on it! :-D

**Comment by czka** [comment]
Preliminary Arch def and smod uploaded in a681f16. It creates a working image, but some issues crop out:
1. Installation of `filesystem` package triggers the following warnings:

```
(...)
( 4/87) installing filesystem
warning: /usr/var/singularity/mnt/etc/hosts installed as /usr/var/singularity/mnt/etc/hosts.pacnew
warning: /usr/var/singularity/mnt/etc/resolv.conf installed as /usr/var/singularity/mnt/etc/resolv.conf.pacnew
warning: directory permissions differ on /usr/var/singularity/mnt/root/
filesystem: 755  package: 750
warning: directory permissions differ on /usr/var/singularity/mnt/var/tmp/
filesystem: 755  package: 1777
( 5/87) installing glibc
(...)
```

This is apparently due to PreSetup intitializing those 2 files and 2 dirs in advance.

Is it always a good idea to copy /etc/resolv.conf and /etc/hosts files from the host system? I really don't know. Thoughts?

Not sure about 1777 vs 755 on /var/tmp. But 755 (rwxr-x**r-x**) on /root doesn't seem OK.
1. I can ping as root, but can't as a regular user:

```
Singularity.arch.img> id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),19(log)
Singularity.arch.img> ping -c1 google.com
PING google.com (216.58.209.46) 56(84) bytes of data.
64 bytes from waw02s05-in-f14.1e100.net (216.58.209.46): icmp_seq=1 ttl=53 time=92.7 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 92.755/92.755/92.755/0.000 ms
```

```
Singularity.arch.img> id
uid=1000(user) gid=100(users) groups=100(users),10(wheel),14(uucp),24(rfkill),50(games),996(docker),1002(plugdev)
Singularity.arch.img> ping google.com
ping: socket: Operation not permitted
ping: socket: Address family not supported by protocol
```

Is that as expected?

**Comment by gmkurtzer** [comment]
We can change how these directories are created (or rather when) to ensure we get the right permissions.

Hrmm, I agree that it may not be a good idea to copy resolv.conf and hosts from the host system. This should be changed.

Actually yes, pinging technically requires root for ICMP and as a result /usr/bin/ping is usually SUID root or it has extended Linux capabilities to allow it privilege to ping. Considering Singularity containers are not "trusted" (e.g. they are provided by the user), no privilege escalation is allowed inside of them... Long story short, yes... Pings are expected to fail.

Is a681f16 a PR or a commit to your local fork? Feel free to send me a PR for that.

Thanks!

**Comment by czka** [comment]
> it may not be a good idea to copy resolv.conf and hosts from the host system. This should be changed.

On the other hand, if these files are not copied you'll probably have to provide the means to set the DNS and known host names via def file. Maybe just document how to do it using RunCmd's with some echo's (or InstallFile, if the user really wants the files identical as on his host)? That should be good enough I guess.

> We can change how these directories are created (or rather when) to ensure we get the right permissions.

Do you need a separate ticket for that? What are the permissions on /root and /var/tmp on the machines you have at hand? I only have Arch here.

> /usr/bin/ping is usually SUID root

Right! I forgot that. Thanks for explaining this.

> Is a681f16 a PR or a commit to your local fork?

It's on my fork for now. I'll send you a PR when it's done.

**Comment by gmkurtzer** [comment]
I would suggest that in addition to documentation we create templates using things like public DNS services and a generalized hosts file so that when --contain is passed, there is a sane starting point.

A separate ticket would be helpful to make sure it doesn't slip through the cracks.

Excellent, looking forward to the PR! Thanks!

**Comment by czka** [comment]
I'm done, PR against brach 2.x submitted.

The issues we touched on here and which don't yet have their own tickets are inheriting/or not the resolv.conf and hosts file from the host, and the localization. I can open 2 new tickets for these and close this one. OK?

**Comment by gmkurtzer** [comment]
Just merged your PR. Looks great!

Yes, I think that closing this issue and creating two new ones reflecting the specific issues you identified would be great.

Thanks again!

**Comment by czka** [comment]
I have come up with a generic solution suggestion in #203. I'm curious what you think about it. Too bad I can't help implementing it. I don't know C. Shell and Python only.
