### ISSUE TITLE
bind fails when specifying a symlink instead of a file

### ISSUE THREAD

**Issue by ctmadison** [apptainer/singularity#1988]
## Version of Singularity:

Singularity 3.0

### Expected behavior

file is bound into container

### Actual behavior

FATAL:   exec /.singularity.d/actions/shell failed: no such file or directory

### Steps to reproduce behavior

./singularity  -v shell -B /lib64/libcuda.so ~/centos.sif

**Comment by GodloveD** [comment]
@ctmadison please verify that this works for you now and close if it does. 

EDIT:  Actually, I will close and you can re-open if it doesn't work.

**Comment by ctmadison** [comment]
Reopening - container specific

**Comment by DrDaveD** [comment]
Does the container image have /.singularity.d/actions/shell?  An old container might not.  I made a pr #1971 to support a missing /.singuarity.d/actions/exec for the exec command with old images, but I think that trying to do something similar for the shell command would be considerably more complicated because the shell helper is considerably more complicated.

**Comment by cclerget** [comment]
Ok after some tests, it seems this is not image specific but rather the file/directory bound into container, so if you bind by example host directory `/lib64` or `/lib` in container like `singularity shell -B /lib64 centos.sif` you will override `/lib64` container binary loader that's why you can end with error `exec /.singularity.d/actions/shell failed: no such file or directory` because it uses the host binary loader and fail to execute shell script. So to avoid that with `--nv` flags you will need to bind libraries like that `/lib64/nvidia.so:/.singularity.d/libs/nvidia.so` and set environment variable `LD_LIBRARY_PATH=/.singularity.d/libs:$LD_LIBRARY_PATH`. There is nothing that can be done to prevent those kind of bind

**Comment by cclerget** [comment]
@ctmadison I will close the issue. Re-open if the above solution for `--nv` doesn't work.
