### ISSUE TITLE
Document all directories and files which are automatically mounted

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#1992]
Singularity documentation should clearly lay out exactly which directories/files are automatically bind-mounted into the container when running `singularity run/exec/shell ...`. We should be able to explicitly call out these files when running with any combination of flags **e.g. --contain**

**Comment by jscook2345** [comment]
@bauerm97 

Where should this go? I can think of lots of places.

* In sub-command help (`singularity help run`, `singularity help exec`)
* In the user docs
* In the admin docs (in the section on the config, since you can say not to auto mount them)
* A debug/verbose message during `run` or `exec`. ex:

<pre>
 auto mounting /tmp
 auto mounting /var/tmp
 auto mounting ...
</pre>

**Comment by rgiannico** [comment]
Nice feature! 
@jscook2345 I'd very much like to have it under a debug/verbose message during "run" and "exec"! What do you think?

**Comment by jscook2345** [comment]
@ikaneshiro @cclerget What do you think about this as a new feature for 3.1?

**Comment by GodloveD** [comment]
Should this issue be moved to sylabs/singularity-userdocs?  Is it better documented on the website?
