### ISSUE TITLE
Bind container path to a folder inside $HOME

### ISSUE THREAD

**Issue by staeglis** [apptainer/singularity#2085]
Hi,

is it possible to mount inside the container a container path to a folder inside $HOME?

Cheers,
Stefan

**Comment by bauerm97** [comment]
Hi @staeglis , can you elaborate on what exactly you're looking to do? If you want to mount a folder within $HOME which exists on your host, that should be automatically done for you by simply running the command:

`singularity run/exec/shell <image_path> ...`

You should see your $HOME has been automatically mounted unless your system administrator has configured Singularity differently. More generally, if you want to mount a path on your host to inside your container, you can use the `-B/--bind` flag:

`singularity run/exec/shell --bind /path/on/host:/path/in/container <image_path> ...` and you'll see that `/path/on/host` will exist in the container as `/path/in/container`. Let me know if this helps solve your problem, cheers!

**Comment by staeglis** [comment]
Hi @bauerm97,

there exist a folder /var/lib/folder int the container file system that I want to access via $HOME/.folder/ inside the container. Your solutions works only with folders stored in the host file system the container.

Cheers,
Stefan

**Comment by dtrudg** [comment]
binding from within the container to another location in the container isn't something I think we wish to support. Is there a reason why a symlink cannot be used?

I'm going to close the issue as it has been stale for some time. If you would like to re-open please could you give detail of the use case here, and why a bind is needed rather than some other approach, like a symlink?
