### ISSUE TITLE
3.0: CWD different when using `--writable`

### ISSUE THREAD

**Issue by jmstover** [apptainer/singularity#2089]
## Version of Singularity:
v3.0.0-alpha.2-272-g5fb1529

### Expected behavior
I... don't know what behavior is wanted here ...  I would assume that the `pwd` of `/root` is the wanted behavior because I am using `sudo` 

### Actual behavior

```
$ sudo singularity exec -B /usr/local --nv --writable ../sbox_test/ pwd
/root
$ sudo singularity exec -B /usr/local --nv ../arnold/ pwd
/home/jason/tmp/sing/render_test
```

**Comment by cclerget** [comment]
@jmstover Hmm debug output could explain the difference

**Comment by jmstover** [comment]
@cclerget ... This looks to be because the noted behavior in #2088 .

Because `--writable` is used, it can't mount the CWD I'm in, and so the working directory falls back to $HOME.

I don't think this is behavior that should happen. The behavior should be consistent no matter what flags are used. `--writable` isn't mutually exclusive to bind mounts.

**Comment by cclerget** [comment]
@jmstover Ok but to keep that consistent with `--writable` that implies to create CWD path directly into container image. I think Singularity should stay away from writing anything in container image directly and additionally that requires sandbox/ext3 image to do that, so it's hard there to keep that behaviour consistent with all image format.

**Comment by jmstover** [comment]
Right. But now 3.0 is correctly mounting the CWD you're in. So now if you use the `--writable` flag you cannot count on that same behavior working.

**Comment by GodloveD** [comment]
I agree with @jmstover that this will likely be very unexpected behavior to the user.  Is there any way at all around this @cclerget ?

**Comment by cclerget** [comment]
@GodloveD @jmstover Ok here an example with `CWD=/home/username/testing`, now if we are trying to keep this behaviour, as Singularity v3 won't create dir/files in container image (especially RO FS), we need to create `/usr/local/var/singularity/mnt/session/home/username/testing`, then check if `/home/username/testing` exists in container, if not test `/home/username`, if not test `/home`, stop if we reach `/`, there is high probability `/home` exist in container and will be bound, so we could have `/usr/local/var/singularity/mnt/session/home/` bound to `/usr/local/var/singularity/mnt/container/home/`. Problem partially solved **but** what if a user want to add a user in the image, create a new home ? Change will be lost because writes occurs in the session directory. CWD home is just an example but that could be apply and break things with many other directories depending of CWD.

IMO I think the consistent behaviour here should be : don't touch or hack anything and let the user decide what he want/need to mount in container image with `-B` flag when using `--writable`

**Comment by jmstover** [comment]
I can... somewhat, get behind this reasoning.

`--writable` is really only useful with sandbox's. And really, when setting it up. So if a directory was needed, then I can see bind mounting it in with `-B`. The biggest issue I can see coming up is that because we are *not* making directories, some bind mounts will fail if the directory doesn't already exist in the container.

I can leave this up to a Documented behavior difference when using `--writable`.

@GodloveD , how are you on it?
