### ISSUE TITLE
`singularity <unknown command>` returns 0 for an exit status

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2146]
## Version of Singularity:

$ singularity --version
singularity version v3.0.0-alpha.2-310-g3812cec2-dirty

### Expected behavior

$ singularity bob
$ echo $?
1

### Actual behavior

$ singularity bob
$ echo $?
0

### Steps to reproduce behavior

See above.

This is causing a few false positives with the integration tests. At the very least the `selftest` command, which is not implemented, is passing when it's test runs.

**Comment by GodloveD** [comment]
With cobra, an unknown command is handled.  Suggestions are streamed to std out.  So there is no error and the exit status is properly 0.  I think we need to check the std out to see if the command behaved as expected and not rely on the error code.

**Comment by jmstover** [comment]
@GodloveD ... and this breaks job scripts where you're expecting a non-zero code on failure from the previous command.

Sorry, but a non-existent command is a failure and should properly return that exit code.

For example, if I have a script that does:
```
set -e

if singularity -q instnace start /its/my_image.sif mi; then
   [ do something when that instance is up ]
else
  [ handle instance failure ]
fi
```

I don't expect that if block to run if I misspell "instance' ... in fact, with `set -e` I expect the script processing to stop. But if the program is returning that all is good, well... that `set -e` is worthless.

**Comment by jmstover** [comment]
Is there anyway to use `Command.RunE`, so the error gets propagated?

https://github.com/spf13/cobra/issues/67

**Comment by phpHavok** [comment]
@jmstover Following your lead, I think I have this working now for the main cases. All of the following commands, for example, will return usage along with a status code of 1 (instead of 0) due to being "incomplete":
`singularity`, `singularity instance`, `singularity capability`, `singularity keys`

Furthermore, completely nonsensical commands like these will also return usage plus status code 1:
`singularity meow`, `singularity instance blah`, `singularity capx`

@jscook2345 I have a PR incoming soon.
