### ISSUE TITLE
consider versioning the extracted directory for the release tarball

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2215]
## Version of Singularity:

3.0.0

### Expected behavior

    curl -LO https://github.com/sylabs/singularity/releases/download/v3.0.0/singularity-v3.0.0.tar.gz
    tar -xzf singularity-v3.0.0.tar.gz
    ls singularity-3.0.0

### Actual behavior

    curl -LO https://github.com/sylabs/singularity/releases/download/v3.0.0/singularity-v3.0.0.tar.gz
    tar -xzf singularity-v3.0.0.tar.gz
    ls singularity

Several users in the FOSS slack requested this for a few reasons:
* Most common practice.
* Easier to make RPMs / system packages.

**Comment by jmstover** [comment]
I believe @yhcote already has a fix in the works for this to get around my quick hack to get a `make dist` target in place before release.

**Comment by tri-adam** [comment]
Just to be clear, in order to successfully build the Go source, the source must be present in `src/github.com/sylabs/singularity` within the Go workspace. We can make the tarball whatever folks prefer, but it will need to be `mv`ed to the appropriate place. That's a Go limitation (see https://golang.org/doc/code.html for an explanation.)

**Comment by bauerm97** [comment]
Agree with @tri-adam here, this isn't something we wish to change to be honest. This is a byproduct of Golang

**Comment by dtrudg** [comment]
With go modules - is this something to reconsider since we can have the source in a directory named for the version?

**Comment by jscook2345** [comment]
@mem 

Thoughts?

**Comment by dtrudg** [comment]
Marking for 3.8. No reason not to do this no we are on non-GOPATH go modules for some time.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by DrDaveD** [comment]
This is still relevant, and in fact Sylabs implemented it for their 3.8.0 in their [pr 25](https://github.com/sylabs/singularity/pull/25).   Also see changes they made to the rpm spec in their [pr 21](https://github.com/sylabs/singularity/pull/21).
