### ISSUE TITLE
Ability to change signing key passphrase

### ISSUE THREAD

**Issue by kav2k** [apptainer/singularity#2240]
## Version of Singularity:

v.3.0.0 (dist)

### Expected behavior

After creating a keypair using `singularity keys newpair` there should be a way to change the key passphrase, e.g. something like `singularity keys encrypt <fingerprint>`.

### Actual behavior

There are no built-in tools to change the passphrase.

### Steps to reproduce behavior

Run `singularity keys --help` and hmm a lot.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@kav2k We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Old Singularity repo issues are now closed. If this is still critical please open a new issue in Apptainer repo.
