### ISSUE TITLE
How to set aliases in the container during execution?

### ISSUE THREAD

**Issue by Amir-Arsalan** [apptainer/singularity#2273]
I have been trying to set some aliases in my container but I haven't been able to do it successfully. While building the container I put the alias in `%post` and things work fine. However, after the container is built and I `exec`ute it the alias declaration in `%environment` or `%runscript` does not work. I put the alias in a bash script in the container and run the bash script but it still does not work. Does anyone know what I'm doing wrong and how I can set aliases within a container?

I am using Singularity 2.6

**Comment by jmstover** [comment]
I just tested the following:
```
%runscript
    alias p1=pwd
    echo "PWD: $(pwd)"
    echo "P1: $(p1)"

```
And for output got:
```
PWD: /home/jason/tmp
P1: /home/jason/tmp
```

What do your aliases look like, and how are you calling them in your definition file?

I don't think putting an alias in the `%environment` section will work though with how the command gets executed. i.e. The alias doesn't follow the `exec` call.

But if defined in the runscript it should be seen.

**Comment by Amir-Arsalan** [comment]
@jmstover Basically I just need to do `alias python3=python3.6`. It works fine if I put it in `%post` but even if I put it in `%runscript` when I do `singularity exec myContainer.simg python3 --version` it still prints `3.5.2` instead of `3.6.7`.

**Comment by Amir-Arsalan** [comment]
It looks like Docker has something like **ENTRYPOINT**. I'm looking for something similar in Singularity.

**Comment by Amir-Arsalan** [comment]
Here's the definition file I used :

```
BootStrap: docker
From: ubuntu:16.04

%post
# Set up some required environment defaults
apt-get -y update && apt-get -y install software-properties-common && yes '' | add-apt-repository ppa:deadsnakes/ppa
apt-get -y update && apt-get -y install make \
                                        cmake \
                                        vim \
                                        curl \
                                        python3.6 \
                                        python3.6-dev \

curl https://bootstrap.pypa.io/get-pip.py | python3.6

alias python3=python3.6 #Here's where I declare the alias

python3 -m pip install -U pip
python3 -m pip install --upgrade pip
python3 -m pip install -U setuptools
python3 -m pip install  scipy \
                        numpy \
                        transforms3d \
                        matplotlib \
                        Pillow

# I also create a file containing a bash script to declare the alias
cd /
mkdir bash_aliases && cd bash_aliases
echo "alias python3=python3.6">bash_aliases.sh
chmod +x bash_aliases.sh


%runscript
alias python3=python3.6

# bash /bash_aliases/bash_aliases.sh # You may uncomment this as well
```

**Comment by Amir-Arsalan** [comment]
@jmstover Is this behavior normal? Could it be a bug?

**Comment by jscook2345** [comment]
@Amir-Arsalan 

When you use the command `singularity exec`, the `%runscript` section is not executed. It is only executed if you use the command `singularity run` or when you execute the container directly`./container.simg`.

The best option would be to set the alias in the shell start-up scripts for your container. If you're using bash, those would be `.bashrc`, `.bash_profile`, or `.profile` depending on your Linux distribution.

**Comment by jscook2345** [comment]
@Amir-Arsalan 

Additionally, if you want something like `ENTRYPOINT`, you can use the `%runscript` like the following:

<pre>
BootStrap: docker
From: ubuntu:16.04

%runscript
    alias l=ls
    l "$@"
</pre>

If you than build with:

    sudo singularity build alias.sif alias.def

and run with:

    ./alias.sif
    ./alias.sif --help

You will see that the alias `l` is getting its arguments correctly. I think from this you can do what you're looking to accomplish. If not, please let me know! Thanks!

**Comment by Amir-Arsalan** [comment]
@jscook2345 I also tried adding a line in `.bashrc`  for the alias but for some reason the changes that I make to the file do not get saved there! I tried `echo "alias python3=python3.6" >> ~/.bashrc` but it didn't work; after the container is made the `.bashrc` is untouched. I also tried creating `~/.bash_aliases` but that file is also not saved in the home directory. Do you know why it's not possible to add anything to `.bashrc` or create a file there when building the container?

That's why I decided to make my own `.sh` file and call it in `%runscript`.

**Comment by jscook2345** [comment]
@Amir-Arsalan 

Where were you trying to add things to the bashrc (which section)? I was able to do so with no issues.

**Comment by Amir-Arsalan** [comment]
@jscook2345 I did it in the `%post` section. I'm not sure if it makes a difference but I'm using Singularity 2.6 though. Did you literally use exactly the script that I used to write into `.bashrc`?

**Comment by jscook2345** [comment]
@Amir-Arsalan 

Sorry. I made a mistake. :) Going through things a bit too fast.

During the %post section (sudo singularity build), the home directory for your user does not exist yet. You're running as root, not a user. So if you tried to create a `bashrc`, it would be for root. 

When you run `singularity run|exec`, it will mount your home directory by default, so that is where the user home directory is 'created'. A lot of other directories (`/tmp` for example) are also mounted into the container.

So instead of of a `.bashrc` you could create a file in another location that you could source when running.

I hope that answers your question and does not confuse you. Please let me know if you have further questions!

**Comment by Amir-Arsalan** [comment]
@jscook2345 I don't want to source the `.bashrc` file manually. Can I source the  new `.bashrc` in the `%environment` section? Basically, I want the sourcing to be done automatically. How can I do that?

**Comment by Amir-Arsalan** [comment]
@jscook2345 I've tried `source` in both `%environment` and `%post` but it doesn't work. During `%post` I get the following error:

`/bin/sh: 2: source: not found`

But I don't get any complains when I put `source` in `%environment` but the alias is not declared after all. So I'm still stuck :confused:

**Comment by jmstover** [comment]
@Amir-Arsalan ... Okay, you're using a Debian base.  `/bin/sh` on Debian is Dash. This is a POSIX shell, 

Instead of `source` use `.`  (just a period). So, instead of: `source myfile` you'll have  `. myfile`

For processing the `%environment` settings, we are using `.` to source the files. `source` is not technically POSIX compliant, so may not work on a `/bin/sh` if it is fully compliant.

**Comment by Amir-Arsalan** [comment]
@jscook2345 @jmstover Sorry that this is taking too long to get resolved. But I tried `.` and it still does not work. Here's what I do:

```
#%environment
 ./bash_aliases

%post
.
.
.
cd /
echo "alias python3=python3.6" > bash_aliases
chmod +x bash_aliases
.
.
.
```

Have you tried building an image and making sure that something like this works? If that is the case, I'm afraid I'm still not doing something right. Could you please help me write the right script?

**Comment by Amir-Arsalan** [comment]
The weird thing is it executes the script in `%environment` when executing the container but the aliases are not set. I figured this after I forgot to create the alias file and Singularity threw me an error saying it cannot find that file, when executing the container.

**Comment by jmstover** [comment]
Hi @Amir-Arsalan ... 
Okay, after some digging I think I found it.

I believe you will *need* to put the alias in the `%runscript` section, not in the environment. Aliases are not expanded in a non-interactive shell... which is what `exec` will do. So no aliases set prior to the exec, will be available to the command that `exec` is executing.

I just reread an earlier post as well ... I missed something:
> I put it in %runscript when I do singularity exec myContainer.simg python3 --version

This is expected behavior. `exec` doesn't load the `%runscript` ... it calls the application directly. So, it's going to call `python3` as it exists in the container filesystem. To replicate the exec behavior with a `%runscript` you can do something like:

```
%runscript
    alias python3=python3.6
    ${@}
```

**Comment by Amir-Arsalan** [comment]
@jmstover Sorry to come back with unexpected issues every time, but have you tried this yourself? I still cannot get this to work in practice. Could you please share the definition file content of the container that you've built and works as expected?

**Comment by jmstover** [comment]
@Amir-Arsalan ... Okay ... here we go ... I was using the alias directly in the runscript, not as being passed in.

So, this is a highly specific use case for this here... But:

```
%runscript
    alias python3=python3.6
    # Expect that 'python3' is passed in, and needs expanded
    eval ${@}
```

We need the `eval` in there to evaluate the expanded `$@` value, and replace any aliases, etc...  Yeah... I totally wasn't thinking here.

But an example run I have with this gives:
```
$ singularity run alias.sif python3 --version
python3 is aliased to `python2.7'
python3 direct:
2.7.5 (default, Jul 13 2018, 13:06:57)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
python3 expanded:
Python 2.7.5
```

This was from a testing `%runscript` of:
```
%runscript
    alias python3='python2.7'
    type python3
    echo "python3 direct: "
    python3 -c 'import sys; print sys.version'
    echo "python3 expanded: "
    eval ${@}
```

Please note ... you will normally not want to do this, and it's only useful in the case where you could have an alias/function being part of what you're passing in.

The `eval` can also mess up other things ... Like you can not do: 
```
singularity run alias.sif python3 -c 'import sys; print sys.version'
```
... but you can do:
```
singularity run alias.sif python3 ./version.py
```
where `version.py` contains those same commands.

**Comment by Amir-Arsalan** [comment]
@jmstover Thank you. But what I've been always trying to achieve since I started this post was to "automatically" set the aliases so that when I use `exec` and run a Python file with `python3` it automatically runs with Python 3.6. From the examples you gave it looks like I am not able to do this in an automatic fashion. Please correct me if I'm wrong.

**Comment by jmstover** [comment]
@Amir-Arsalan ... With the eval in there, this should act as you're wanting.

But there's not an easy automatic way to do it as you're attempting just because of shell behavior, and how singularity itself behaves.

From our point of view, if you want to do something like this then in `%post` you would setup a symlink for python3 -> python3.6 ... It would probably look something like in `%post`:

```
# python3 is usually a symlink, remove old and recreate
PY3=`which python3`
rm -f ${PY3}
ln -sf `which python3.6` ${PY3}
```

So, in this way, you're setting the python3 symlink to point at python3.6 instead of python3.5 when the image is built.

There are cases for using aliases ... but here, you should probably just be setting the link up yourself.

Then, `singularity exec [...] python3 [...]` would behave as you're expecting.

**Comment by Amir-Arsalan** [comment]
@jmstover The reason that I did not use symlink is because it's been highly discouraged to do that when you install a non-built-in version of Python. Besides, I have to go back and forth between Python 3.5 to run a little piece of code and mostly use Python 3.6 to do my stuff. That's why I prefer Aliases. 

Anyhow I put the followings in `%runscript` but it still does not work when I use the container with `shell` or `exec` but it worked with `run` for the first time. It's not that important to me if I cannot get it to work when I `shell` into the container but I need it for when I use the container with `exec`. Also, I feel that the recent documentation does not talk that much about `exec` anymore. Is it discouraged to use `exec` for some reason? Can I do everything I want with `run` that I can do with `exec`? Maybe I can simply use `run` instead!

**Comment by jmstover** [comment]
@Amir-Arsalan 
>  but I need it for when I use the container with exec

It will never work with an alias if you're trying to use `singlarity exec` without changing the symlink in image. It just how the Singularity runtime image acts. When you run:  `singularity exec [image] id` ... it's going to exec `id` directly, not calling any other scripts besides sourcing the environment (and aliases don't carry down).

But, what happens when you run:  `singularity run [image] id` ... is that `/.singularity.d/runscript` is called, and everything after the [image] is passed as a paramater... So the equivalent call would be:  `/.singularity.d/runscript id` 

So `exec` is going to call what you pass directly. `run` is going to pass what you give as options to the `runscript` file. They're two different run modes.

**Comment by Amir-Arsalan** [comment]
@jmstover So I can still do whatever I execute with `exec` with `run` and the only difference would be the script in `%runscript` would run first. Am I correct?

**Comment by jmstover** [comment]
In this case yes. `singularity run` executes `/.singularity.d/runscript` ... so, you just need to write the runscript in such a way that it handles the input you'll be giving it correctly.

**Comment by tashrifbillah** [comment]
```
Bootstrap: docker
From: centos:latest


%post
# steps for installing miniconda3
# miniconda3 successfully installed

echo "alias ls=\"ls --color\"" >> /.bashrc
...
...

%environment
source /miniconda3/bin/activate # this works
source /.bashrc # this does not work

```

I successfully built the image as follows:

> singularity build alias_img Singularity

Then, tried to run it:

> singularity shell --contain alias_img

My set alias is not effective although `miniconda3` environment is set.

Following the above suggestion, I tried adding `%runscript`:

```
Bootstrap: docker
From: centos:latest


%post
# steps for installing miniconda3
# miniconda3 successfully installed

echo "alias ls=\"ls --color\"" >> /.bashrc
...
...

%environment
source /miniconda3/bin/activate # this works

%runscript
alias ls="ls --color" # does not work either
eval ${@}
```

As before, my set alias is not effective although `miniconda3` environment is set.

As the last effort, I tried putting:
> alias ls="ls --color" >> /.bashrc or /.bash_profile or /.profile

Finally, out of luck.

@Amir-Arsalan @jmstover any suggestion for me?

**Comment by Amir-Arsalan** [comment]
@jscook2345 @jmstover Any updates on this?
