### ISSUE TITLE
[Bug]: File not found when pulled from docker

### ISSUE THREAD

**Issue by scchess** [apptainer/singularity#2281]
## Version of Singularity:

2.5.2

### Expected behavior

Pulled docker from https://hub.docker.com/r/biocontainers/fastqc. The program "fastqc" is in the docker for running.

### Actual behavior

The file is not found.

### Steps to reproduce behavior

singularity pull --name fastqc.img docker://biocontainers/fastqc
./fastqc.img
/bin/sh: 1: fastqc: not found

Please note `fastqc` is definitely in /usr/local/bin. Dockerfile definition is at: https://github.com/BioContainers/containers/blob/master/fastqc/0.11.5/Dockerfile.

**Comment by jscook2345** [comment]
From what I am seeing, fastqc is soft linked to a file that does not exist in the container:

    $ file /usr/local/bin/fastqc
    /usr/local/bin/fastqc: broken symbolic link to /tmp/FastQC/fastqc

The directory FastQC does not exist under `/tmp` because `/tmp` is always mounted by Singularity. How difficult would it be to install the software under `/opt` or somewhere else instead?

The workaround for this would be to change the `mount tmp` option in the `singularity.conf` so temp directories are not mounted by default.

**Comment by scchess** [comment]
I'll just copy the software to another folder, saving all the configuration issues.
