### ISSUE TITLE
--pwd silently ignored when directory doesn't exist in the container

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2307]
## Version of Singularity:

Current 3.x master branch

### Expected behavior

When using a --pwd option for a directory that doesn't exist in the container, I expect an error message and a failure like in version 2.6.0

### Actual behavior

When the directory doesn't exist in the container the option is silently ignored.

### Steps to reproduce behavior

Run `singularity exec --pwd /nonexistentdir imagename bash` for any image.

**Comment by jmstover** [comment]
Isn't this expected behavior? You're telling it to `chdir()` to a directory that doesn't exist, so it then falls back to setting the working directory to `$HOME`. If you also run with `--no-home` then it falls back to `/` as the working directory.

Debug output gives:
```
DEBUG    [U=1000,P=10514]    addCwdMount()            can't go to container working director: chdir /lala: no such file or directory
```

I agree, there could be an error message. But I think with how the logic is for setting the container path, it's the same logic ran whether `--pwd` is used or not. It just changes what the initial path attempted is instead of using the CWD from the host.

**Comment by DrDaveD** [comment]
No I don't think it is right to silently ignore an option that a user asked for.  2.6.0 had it right in my opinion.  An alternative would be to at least print a warning, not a debug message, but people usually ignore warnings so I think an error makes more sense.
