### ISSUE TITLE
Permission Issues Related to Docker Config.json Gives Misleading Errors

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#2314]
## Version of Singularity:
```
singularity version
3.0.0-274.g224e2e91
```

### Expected behavior
```
$ singularity build test.sif docker://ubuntu
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/home/ian/.docker/config.json": Permission Denied.
```
Or something similar.

### Actual behavior
```
$ singularity build test.sif docker://ubuntu
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: error getting username and password: error reading JSON file "/home/ian/.docker/config.json": error unmarshaling JSON at "/home/ian/.docker/config.json": unexpected end of JSON input
```

### Steps to reproduce behavior
Log into docker to create a ~/.docker/config.json
Try to build any container from dockerhub

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@ikaneshiro Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

**Comment by kmuriki** [comment]
Pending issues from the old repo are moved to the new repo (https://github.com/apptainer/apptainer/issues/1391) and cleaned from the old, retired repo
