### ISSUE TITLE
Add CI check for buildcfg dependency for any packages in pkg/

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2316]
In order to make sure that all packages in `pkg` will be usable to external projects, we'll add a CI check to enforce that `buildcfg` only be used in strictly internal packages. 

`buildcfg` cannot be a direct OR indirect dependency of *any* package in `pkg/`.

**Comment by bauerm97** [comment]
Can be accomplished via the following command: 

`! go list -f '{{.Deps}}' ./pkg/... | grep "buildcfg"`

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@bauerm97 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Moved to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1157
