### ISSUE TITLE
Move minimum number of viable packages from internal/pkg to pkg

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2320]

**Comment by bauerm97** [comment]
Currently I've found external references to these packages. Minimally these *must* be exported:

- [x] github.com/sylabs/singularity/src/pkg/jsonresp
- [ ] github.com/sylabs/singularity/src/pkg/build/types
- [x] github.com/sylabs/singularity/src/pkg/client/library
- [x] github.com/sylabs/singularity/src/pkg/util/user-agent

**Comment by tri-adam** [comment]
The only one I can think of that isn't obvious is we are using the code from https://github.com/sylabs/singularity/tree/master/src/pkg/build/types/parser, but had to modify it due to `buildcfg` dependencies. That lives at https://github.com/sylabs/remote-build/tree/master/internal/pkg/parser at the moment.

**Comment by bauerm97** [comment]
@yhcote has expressed interest in exposing these packages:

- [x] github.com/sylabs/singularity/internal/pkg/sypgp
- [x] github.com/sylabs/singularity/internal/pkg/signing

**Comment by sashayakovtseva** [comment]
CRI needs those to work:

- [x] src/pkg/client/library
- [x] src/pkg/client/shub
- [x] src/pkg/signing
- [x] src/pkg/sypgp
- [x] src/pkg/util/loop
- [x] src/pkg/util/user-agent
