### ISSUE TITLE
Plugin configure command

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2325]
`singularity plugin configure <name>`

This command should in some form provide an easy way to facilitate configuration of an installed plugin. This is in reference to the *plugin's* configuration, for instance if a plugin has defined a configuration file this should make it easy to update the values in that config.

**Comment by GodloveD** [comment]
Trying to figure out how to implement a test case with a POC fuse overlayfs plugin.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@bauerm97 We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Migrated to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1160
