### ISSUE TITLE
Create installation tests

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2341]
For the 3.1 release, it would be good to test that each installation build artifact works as expected

**Comment by GodloveD** [comment]
@jscook2345 this has been in the queue for quite some time.  Is it still relevant?  Are there any build artifacts that we are _not_ testing through e2e framework at this point?

**Comment by ArangoGutierrez** [comment]
I think that it is being tested now at 
https://github.com/sylabs/singularity/blob/master/e2e/suite.go#L57 

I am happy to close this issue

**Comment by jscook2345** [comment]
@GodloveD @ArangoGutierrez 

This was more aimed at verifying our installation procedure works. Checking that man pages were installed, singularity is in the path, our config file exists and has correct perms, etc.

Not *all* of that is tested right now.

**Comment by dtrudg** [comment]
Believe only the man pages aren't tested here now

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
> @GodloveD @ArangoGutierrez
> 
> This was more aimed at verifying our installation procedure works. Checking that man pages were installed, singularity is in the path, our config file exists and has correct perms, etc.
> 
> Not _all_ of that is tested right now.

Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

**Comment by pedroalvesbatista** [comment]
@jscook2345 We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
