### ISSUE TITLE
dist/debian/changelog stuck at version 2.4.2

### ISSUE THREAD

**Issue by AEI-SXSmirror** [apptainer/singularity#2354]
## Version of Singularity:

3.0.1, 3.0.0

### Expected behavior

`debian/changelog` should reflect the actual version, being constantly updated with every release.
`debian/*` should allow packaging (after copying the subtree from `dist/debian` into `debian/` proper) without major changes.
BTW, pre-3.0.0 versions had a `debian/` subtree, although with a `changelog` file that lacks timestamps.

### Actual behavior

First line of `dist/debian/changelog` reads `singularity-container (2.4.2-1) unstable; urgency=high` and is dated Nov 22, 2017.
I suspect other files of the `debian/` subtree need to be modified as well.

### Steps to reproduce behavior

`head -n10 dist/debian/changelog`

**Comment by DrDaveD** [comment]
More than changelog is stuck; nobody has updated the debian packaging for 3.0.x at all yet.

**Comment by GodloveD** [comment]
Well, I guess we all know what version 3.0 got forked off of. lol

**Comment by jscook2345** [comment]
Neuro-debian maintainer @yarikoptic has been building Debian packages for Singularity. Perhaps we can work with him to improve our Debian packaging files.

**Comment by yarikoptic** [comment]
Yeah, will look into building fresh version (unless someone in Debian team beats me to it), thanks for the buzz

**Comment by jscook2345** [comment]
@yarikoptic 

No rush. We appreciate even having some debian packages to review. We were just wondering if you could look over our debian files and make any suggestions if they are broken? 😄

**Comment by GodloveD** [comment]
ping @0xaf1f !

**Comment by 0xaf1f** [comment]
I've been working on it on and off, but it's not so straightforward. I think the packaging at

  https://salsa.debian.org/hpc-team/singularity-container/merge_requests/1

"works", but it's not suitable for uploading to Debian because of the bundled Go dependencies. And it's also very sloppy because it tries to beat `mconfig` into cooperation. I've been advised by the Debian Go team to instead use the standard Go build system.

**Comment by yarikoptic** [comment]
Thank you @0xaf1f for working on that!
 I wish I had some clue in Go (packaging) to assist, and indeed all those bundled depends is a curse for Debian proper -- would need to be stripped and maintained indepedently.  I would need though to decide on how to deal with them for NeuroDebian backport builds. heh heh.

**Comment by 0xaf1f** [comment]
I'm clueless about Go packaging, too, but the Debian Go team is very helpful. The problem is that I haven't been consistent in working on it to keep getting back to them with new questions. However...if the Sylabs guys want to talk about signing up with Debian Pro :stuck_out_tongue: , I'm sure we could get it done more quickly.

>  I would need though to decide on how to deal with them for NeuroDebian backport builds. heh heh.

cheater :expressionless: 

Anyway, yeah, that's where things are now.

**Comment by GodloveD** [comment]
Thanks very much for the late night update guys!!  I'm going to ping @yhcote (creator of `mconfig`) on this thread too just in case there is anything you guys can discuss.

**Comment by 0xaf1f** [comment]
I don't know if the problem is with `mconfig` itself or the way it's been set up here. The reason for my packaging acrobatics when trying to use it arises from the way the source repository is organized and the way it needs to be repositioned in order to build properly.

**Comment by dtrudg** [comment]
I'm going to close this as it hasn't been updated in a year. The current situation AFAIK is that there is a debian packaging in `unstable`. Those changes haven't been sent upstream, and might not be suitable, so what's in our own git repo is untouched from 2.x.
