### ISSUE TITLE
build from tarball does not work

### ISSUE THREAD

**Issue by bmcgough** [apptainer/singularity#2379]
## Version of Singularity:

3.0.1

### Expected behavior

I should be able to download a tar.gz archive of Singularity and build from that. We use EasyBuild to manage software on our cluster. I discovered this within EasyBuild, but have reproduced it outside by manually building from the tarball as below.

### Actual behavior

I get errors like this:

```
../src/cmd/singularity/cli.go:9:2: cannot find package "github.com/sylabs/singularity/src/cmd/singularity/cli" in any of:
        /usr/local/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli (from $GOROOT)
        /root/singularity/src/github.com/sylabs/singularity/src/cmd/singularity/cli (from $GOPATH)
```
It looks like the make step is adding 'src' to the GOPATH to find the packages, but in the tarball those are at /vendor.

### Steps to reproduce behavior

1. Download and unpack release tarball of singularity.
2. run `cd singularity && ./mconfig --prefix=/root/singularity-test`
3. run `export GOPATH=/root/singularity && cd builddir && make`

**Comment by jmstover** [comment]
Hi Ben,

  That isn't the correct way to build for Go. You'll need to build like:

```
export GOPATH=/root/go
mkdir -p ${GOPATH}/src/github.com/sylabs   # <--- This here is *required* :/
cd ${GOPATH}/src/github.com/sylabs
tar xf ~/singularity-3.0.1.tar.gz
cd singularity
./mconfig --prefix=/root/singularity-test
make -C builddir/
make -C builddir/ install
```

**Comment by bmcgough** [comment]
I can customized EasyBuild to do this. Thanks.

**Comment by remyd1** [comment]
Hi there,

I would like to do something similar to @bmcgough . I used the zip version from github (wget https://github.com/sylabs/singularity/archive/master.zip / but you can do the same with the .tar.gz (you will have to remove the "mv singularity-master singularity" in the script below)) and downloaded the go archive in a tar.gz (wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz). My install script is:

```
#!/bin/bash

export VERSION=1.11 OS=linux ARCH=amd64
GOPATH=${HOME}/go

strgopath="export GOPATH=${GOPATH}"
strpath="export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin"

eval $strgopath
eval $strpath

if ! grep -q GOPATH ~/.bashrc; then
    echo "$strgopath" >> ~/.bashrc
    echo "$strpath" >> ~/.bashrc
fi

source ~/.bashrc

SINGDIRSRC="${GOPATH}/src/github.com/sylabs/singularity"

# some cleaning
if [ -f /usr/local/go/VERSION ]; then
    go_version=`cat /usr/local/go/VERSION`
    if [[ $go_version == "go$VERSION" ]]; then
        rm -rf /usr/local/go
    fi
fi
rm -rf $GOPATH/src/github.com/sylabs

cd /tmp
#wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz
tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz
mkdir -p ${GOPATH}/src/github.com/sylabs
cd ${GOPATH}/src/github.com/sylabs
#git clone https://github.com/sylabs/singularity.git
unzip /tmp/singularity_v3.0.1.zip
mv singularity-master singularity
cd singularity
go get -u -v github.com/golang/dep/cmd/dep
cd ${SINGDIRSRC}
./mconfig
make -C builddir
make -C builddir install
```


I am doing `go get` in my script, I think it can be avoided somehow.

And of course, you need a `VERSION` file. In my case, it just contains:

```
3.0.1-73.ga50b5b35
```
But this would be necessary to replace it automatically with a github hook, instead of writting it manually at each version in the tarball release.


Best regards,
Rémy.

**Comment by jscook2345** [comment]
@remyd1 

Can you open this in another issue and refer back to this closed one as similar? 

Additionally, can you better describe what help you're looking for?
