### ISSUE TITLE
"New release is coming to town" ?

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#239]
Was trying to create/work with centos container using 2.1.2 but can't even get "yum update" working (see e.g. http://pastebin.com/Vy6sKHRx) so wondered if should switch to bleeding edge which seems has changed the format of the def files

**Comment by gmkurtzer** [comment]
I've seen that YUM error before but I can't recall what the cause was. Do you have a reliable reproducer I can try and debug? I would guess it has something to do with the YUM cache directory not being writable or available. Maybe an strace on YUM will shed a hint?

The very soon to be released 2.2 is backwards compatible with the previous def files but the new format is much more logical and reliable.

**Comment by yarikoptic** [comment]
well -- seems to be reproducible as long as you generate centos image on debian or ubuntu image. tru_tru@IRC reproduced it as well.

**Comment by gmkurtzer** [comment]
Yeah, I am pretty sure this is an incompatibility with the RPM DB formats that the different version of rpmlib or bdb is producing. Aside from exporting and importing the RPM DB, I don't think there is anything to do to fix this, nor do I think it is a Singularity bug. :(

**Comment by yarikoptic** [comment]
there was 2.2 release so I guess this issue is resolved ;)
