### ISSUE TITLE
install bash completion file in a sane location by default

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2411]
## Version of Singularity:

3.0.1

### Expected behavior

Bash completion is installed to `/etc/bash_completion.d` and works as expected after building and installing Singularity from source.

### Actual behavior

By default, Singularity installs the bash completion file at `/usr/local/etc/bash_completion.d/singularity`.  The user must then either source the bash completion file (and add the command to source the file in their `~/.bashrc`) or must copy/move the file to `/etc/bash_completion.d` so that it works as expected.  

We may as well install the Singularity binaries in `/usr/local/bin/singularity/bin` or some other silly path and then advise users to adjust their `$PATH` variable according.  That would obviously be ridiculous.  So why are we doing the same ridiculous thing with the bash completion file?  It should go into the directory where Linux is already configured for it to work just like the Singularity binaries.

**Comment by jmstover** [comment]
The location it's installed is controlled by the `SYSCONFDIR` value. If you want to install these under `/etc` then you run:

```
./mconfig --prefix=/usr/local --sysconfdir=/etc
```

But, that's going to place everything under /etc ... You will have `/etc/singularity/singularity.conf`; `/etc/singularity/nvliblist.conf`; and so on. The bash completion file isn't a special case that should be handled differently IMO.

**Comment by GodloveD** [comment]
@jmstover I think your comment gives further evidence that the current process is broken and should be fixed.  There is not even a good way for a user to install the bash completion file in the appropriate location via `./mconfig`.

And in my opinion, the bash completion file _should_ be treated specially.  Because bash completion only works as expected when files are installed where they are supposed to be.

**Comment by jmstover** [comment]
Then I would suggest we put is under `$(DOCDIR)/examples/singularity.bash` ... let the user put it where they want to. I mean when I installed TMUX it put it at:
  `/usr/doc/tmux-2.1/examples/bash_completion_tmux.sh`
Or when I installed `createrepo` it put it at:
  `/usr/etc/bash_completion.d/createrepo.bash`
Which is `$prefix/etc` ... since I didn't specify the `--sysconfdir` value. 

The bash completion file isn't special.

> Because bash completion only works as expected when files are installed where they are supposed to be.

No... that's just for automagic sourcing of it so you don't need to think about it. But if you install Singularity under /usr/local ... there's nothing stopping you from doing:
```
echo ". /usr/local/etc/bash_completion.d/singularity" >> ~/.bashrc
. ~/.bashrc
```

**Comment by dtrudg** [comment]
I think the general expectation is that if I specify `--prefix`, or it is set to its default `/usr/local` that *nothing* will be installed outside of prefix unless I explicitly ask. 

I believe I'm supporting Jason's view here. Since this has gone un-commented for over a year I'm going to close. We can look into it further if it has other interest.
