### ISSUE TITLE
Persist data from container runs

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#2413]
## Version of Singularity:

3.1 (hopefully)

### Expected behavior

The goal is to be able to support persistent storage on a per-container exec or instance. The tricky part is how to control access between data on the host and data that should be container specific and persistent between container runs and/or instances.

This should have two sub features to add:

1. Provide a mechanism for a persistent caching directory on a per container basis (possibly SIF UUID or container name). One possible option for location could be `~/.singularity/cache/${UUID}`. 
2. Using the above foundation as a base mechanism for creating a caching location for state between container executions, if we can create recipe/build/definition file keys to automatically bind and persist data into the cache above. Note that it might also be good to have another option in the recipe file to also bind against a host located bind point (e.g. `/run`).

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
