### ISSUE TITLE
Temporary files in /tmp/sbuild-* are not cleaned up after unsuccessful or aborted singularity builds

### ISSUE THREAD

**Issue by MInner** [apptainer/singularity#2420]
Hi, thank you for an amazing work! I was experiencing a similar error #2305 and stumbled upon 16Gb of root-owned partial builds in `/tmp/sbuild-*` folders. They were not properly reported by either `du` or other utilities (with user privileges) since they had `drwx------.  4 root  root` permissions. This is probably due to me experimenting and `sudo singularity build` failing to finish the build. It still should clean these temporary folders after unsuccessful or aborted build, I guess.

**Comment by jmstover** [comment]
I think there was an actual reason for not cleaning up after a failed build. It allows for the user to go into the build structure to do better debugging on the issue that caused a failure instead of it being wiped out.

@ikaneshiro 
I think the cleanup comes from a `defer` call ... and since the build fails, the function doesn't exit clean, so the defer is never made. If this does get changed, I would love for there to be a way to keep the behavior of not removing it on error.

**Comment by MInner** [comment]
@jmstover Could one get a shell into a failed "half-baked" build somehow using this `sbuild` folder? I did not find any mentions of this in docs, but that'd be very useful for figuring out the cause of failure. Or a 'shell on failure' options? Also, as an alternative, build might clean up previous build folder if the name of `def` file and output image is same. Or keep last k failed builds, but not all.

**Comment by ikaneshiro** [comment]
@jmstover Thats correct and that's something ill patch.

I think adding a CLI flag is good option, something like `--no-cleanup` maybe? @MInner Maybe instead of opening up a shell automatically, outputting the specific `sbuild` folder name used during the failed build so that it's easy to locate and inspect?

**Comment by jmstover** [comment]
@MInner 
Sorry, I missed the update....

> Could one get a shell into a failed "half-baked" build

In theory yes depending on the stage it failed at. You can just do:
```
sudo chroot /tmp/sbuild-########/fs/ /bin/sh
```
