### ISSUE TITLE
SINGULARITY_CACHEDIR -> SINGULARITY_CACHEPATH?

### ISSUE THREAD

**Issue by lukasheinrich** [apptainer/singularity#2471]
Hello,

In roder to make use of multiple filesystems and exploit the range of volatility in the image layers  it would be interesting to us if the SINGULARITY_CACHEDIR could be expanded to a list of paths SINGULARITY_CACHEPATH, in which not all paths must be writable. An immediate use case would be to store layer tarballs on a read-only filesystem (such as cvmfs) while any non-cached layers would be written to a (say the first) writable path in SINGULARITY_CACHEPATH

e.g.

SINGULARITY_CACHEPATH=/cvmfs/atlas.cern.ch/imagelayers:/local/disk/imagelayers

running an image "lukasheinrich/myanalysis" based on "atlas/analysisbase" via

```
singularity exec docker://lukasheinrich/myanalysis /bin/bash
```
would then be able to find most layers on /cvmfs and download the remaining layers to /local/disk/imagelayers

I think such a scheme could be quite interesting for many applications.

cc @afortiorama

**Comment by dtrudg** [comment]
This one is something that is rather difficult to fit with the requirement that a cache of layers be private to a user (since other users should *not* have any access to cached layer for containers they wouldn't be able to pull from an access-controlled location).

I'm going to close this request at scale. If there is continued interest, it'd be good to have it opened with some more complete ideas about the flow with which layers could be merged, and how private images would be addressed.
