### ISSUE TITLE
make test fails when current directory is on NFS

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2483]
## Version of Singularity:

Current master branch

### Expected behavior

Expect make test to succeed

### Actual behavior

This output when the current directory is an NFS filesystem on a centos7 VM:
```
-- FAIL: TestSingularityActions (50.50s)
   --- FAIL: TestSingularityActions/Persistent_Overlay (3.14s)
       --- FAIL: TestSingularityActions/Persistent_Overlay/overlay_create (0.18s)
           actions_test.go:388: FATAL:   container creation failed: mount error: can’t mount overlay filesystem to /var/singularity/mnt/session/final: invalid argument
                <nil>
           actions_test.go:389: unexpected failure running ‘test -f /dir_overlay’
       --- FAIL: TestSingularityActions/Persistent_Overlay/overlay_find (0.09s)
           actions_test.go:396: FATAL:   container creation failed: mount error: can’t mount overlay filesystem to /var/singularity/mnt/session/final: invalid argument
                <nil>
           actions_test.go:397: unexpected failure running ‘test -f /dir_overlay’
FAIL
```

### Steps to reproduce behavior

From the top level directory of singularity source code on an NFS filesystem:
```
$ sudo singularity build container.sif examples/busybox/Singularity
$ mkdir overlay_test
$ sudo singularity exec --overlay overlay_test container.sif sh
FATAL:   container creation failed: mount error: can't mount overlay filesystem to /var/singularity/mnt/session/final: invalid argument
```

However it works if overlay_test is in /tmp.  I believe the problem is related to #1797 and the fact that NFS is not suitable as an overlay upper layer.  Surprisingly, however, it does seem to work with an --overlay directory at /dev/shm/overlay_test, even though that's a tmpfs filesystem without extended attribute support.

**Comment by DrDaveD** [comment]
Tagging @cclerget

**Comment by cclerget** [comment]
Hi @DrDaveD, tmpfs support extended attribute when kernel is configured `CONFIG_TMPFS_XATTR`, between overlay doesn't require that upper layer support extended attributes. Regarding this error, well this is expected because overlay code checks type of filesystem : https://github.com/torvalds/linux/blob/62393dbcbe0f3001691e4bd479a25beb5941f2ed/fs/overlayfs/util.c#L108, so remote filesystems are simply not supported as upper layer.

**Comment by DrDaveD** [comment]
Ok so the thing to do is to change the test to not put the temporary overlay dir in the current directory but in /tmp.  Right?

**Comment by cclerget** [comment]
Yes, I'll defer to @ArangoGutierrez to apply the fix. Thanks @DrDaveD !

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by DrDaveD** [comment]
'make test' currently passes when run in an NFS directory, closing.
