### ISSUE TITLE
Hardware Authentication Device Support

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#2486]
It would be nice if we could leverage hardware authentication devices for `sign`/`verify`. For example, YubiKey or that sort of thing.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@tri-adam We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Old Singularity repo issues are now closed. If this is still relevant please open a new issue in Apptainer repo.
