### ISSUE TITLE
singularity instances don't close when slurm allocation finished

### ISSUE THREAD

**Issue by amrabdelaziem** [apptainer/singularity#2488]
## Version of Singularity: 

3.0.

### Expected behavior

instances should terminate when the allocation finished 

### Actual behavior

I can list instance in singularity. However, there is no actual process on the system. Also, I can't create another instance with the same name

### Steps to reproduce behavior

1- first I allocate node 

`$srun -N1 --time 1:00:00 --pty bash
`

2- start an instance 

```
$singularity instance start rstudio_server.img rstudio
INFO:    instance started successfully
```
```
$singularity exec instance://rstudio rstudio-server start
```

3- Wait until the allocation finish or scancel the job from another shell

4- ssh to the allocated node and run singularity instance list you will find the instance still running:

```
$ singularity instance list
INSTANCE NAME    PID      IMAGE
rstudio          158087   /scratch/RStudio_Server/rstudio_server.img
```
5- Try to create new instance with the same name

```
$ singularity instance start rstudio_server.img rstudio
FATAL:   instance rstudio already exists

```
6- Try to get a shell inside this instance

```
$ singularity shell instance://rstudio
ERROR  : Failed to enter in pid namespace: No such file or directory
```

7- Try to stop the instance and list again

```
$ singularity instance stop -F rstudio
Stopping rstudio instance of /scratch/RStudio_Server/rstudio_server.img (PID=158087)
```
```
$ singularity instance list
INSTANCE NAME    PID      IMAGE
rstudio          158087   /scratch/RStudio_Server/rstudio_server.img
```
8- Try to grep for the pid on the system and you will never find it!
```
$ ps -p 158087
   PID TTY          TIME CMD

```
I have another issue related to this. I have followed this link to https://www.sylabs.io/2018/10/spark-on-singularity/ run spark multiple workers. 
I have reserved nodes by slurm, then I put nodes in slaves file, and start spark multiple workers,
but when slurm finish the allocation, the instances on workers nodes and master node remain running.
 
Please Help

**Comment by jmstover** [comment]
Hi @amrabdelaziem ,

  From the looks of it, this is SLURM interaction with how Singularity is tracking the instances. Singularity keeps a list of instances in:  `/var/run/singularity/instances/[user]/[name].json`

  What appears to be happening, is that the SLURM job is being killed and so every pocess in the job tree is killed, but it isn't cleaning out the tracking area that Singularity uses to track the instances. To Singularity, an instance *is* running because that's what it sees.

  Think of this similar to where a process writes out a `*.pid` file ... and gets killed. A `status` check only looks for the existence of a `.pid` file to see if it's running, because on _normal_ execution, that will be cleared when you stop the process.

  So... by not running:  `singularity instance stop rstudio`  ... before the job end, you're leaving behind a file that makes Singularity think that a instance exists and is running.

**Comment by amrabdelaziem** [comment]
@jmstover 

Thank you for your reply, I have tried it, and when I had deleted the /var/run/singularity/instances/[user]/[name].json, the instance cleared from `$singularity instance list`.
But, what do you think? is there any way to make `$singularity instance stop`  delete this file automatically? As if not, every user should request root privlages to delete this files 

Another request, do you test second issue in this post? I think it is related to this behaviour.
Thanks

**Comment by jmstover** [comment]
If you run:  `singularity instance stop -a -F`  -- It _should_ clean out everything for your user.

As for Spark, I think this is the same issue. It looks like SLURM is exiting, but a `instance stop` is not being called on the instances before SLURM exits... so the job process tree gets killed, and it's leaving the instance `.json` file around.

**Comment by jmstover** [comment]
Hi @amrabdelaziem ,

  Okay, been talking with the guy that wrote the Instance code this morning. `singularity instance stop -a -F` will _not_ get rid of the stale file like I was expecting... :/

  The cleanup code is in the *parent* process ... and since that is getting killed by SLURM the cleanup code never runs. 

  We've been chatting, and he's going to look to see if there's another way to go about it that fits into the security model, and will allow a user the ability to remove a stale file.

For the moment, are you ever running multiple jobs on the same node? If no, you could maybe setup a prolog script to clear it out.

**Comment by amrabdelaziem** [comment]
Hi @jmstover,

Yes, `singularity instance stop -a -F` did nothing :) 

No, I am not running multiple jobs on the same node and am not sure if I can write prolog script to clear it out 

Regarding spark, this is the issue:
```
$srun -w nodelist -t 00:05:00 singularity instance start \
--bind $(mktemp -d run/`hostname`_XXXX):/run \
--bind dropbear/:/etc/dropbear \
--bind log/:/usr/local/spark/logs \
--bind work/:/usr/local/spark/work \
--bind ../spark/slaves:/usr/local/spark/conf/slaves spark.sif spark-2
srun: job 793288 queued and waiting for resources
srun: job 793288 has been allocated resources

INFO:    instance started successfully

INFO:    instance started successfully

INFO:    instance started successfully

INFO:    instance started successfully

INFO:    instance started successfully

```
```

$ for i in `cat nodelist` ; do  ssh $i singularity instance list; done
INSTANCE NAME    PID      IMAGE
spark-2          55853    /scratch/radwanaa/spark/spark.sif
spark            52767    /scratch/radwanaa/spark/spark.sif
INSTANCE NAME    PID      IMAGE
spark-2          63362    /scratch/radwanaa/spark/spark.sif
spark            60688    /scratch/radwanaa/spark/spark.sif
INSTANCE NAME    PID      IMAGE
spark-2          33417    /scratch/radwanaa/spark/spark.sif
spark            30532    /scratch/radwanaa/spark/spark.sif
INSTANCE NAME    PID      IMAGE
spark-2          51751    /scratch/radwanaa/spark/spark.sif
spark            49108    /scratch/radwanaa/spark/spark.sif
INSTANCE NAME    PID      IMAGE
spark-2          65041    /scratch/radwanaa/spark/spark.sif
spark            62554    /scratch/radwanaa/spark/spark.sif

```
When the allocation had finished, I ran `singularity instance list` again, and I found them there, so I have tried to stop them, but faced the same beaviour:

```
$ for i in  `cat nodelist` ; do  ssh $i singularity instance stop -F spark-2; done
Stopping spark-2 instance of /scratch/radwanaa/spark/spark.sif (PID=55853)
Stopping spark-2 instance of /scratch/radwanaa/spark/spark.sif (PID=63362)
Stopping spark-2 instance of /scratch/radwanaa/spark/spark.sif (PID=33417)
Stopping spark-2 instance of /scratch/radwanaa/spark/spark.sif (PID=51751)
Stopping spark-2 instance of /scratch/radwanaa/spark/spark.sif (PID=65041)

```
```

$ for i in `cat nodelist` ; do  ssh $i singularity instance list; done
INSTANCE NAME    PID      IMAGE
spark-2          55853    /scratch/radwanaa/spark/spark.sif
spark            52767    /scratch/radwanaa/spark/spark.sif
INSTANCE NAME    PID      IMAGE
spark-2          63362    /scratch/radwanaa/spark/spark.sif
spark            60688    /scratch/radwanaa/spark/spark.sif
INSTANCE NAME    PID      IMAGE
spark-2          33417    /scratch/radwanaa/spark/spark.sif
spark            30532    /scratch/radwanaa/spark/spark.sif
INSTANCE NAME    PID      IMAGE
spark-2          51751    /scratch/radwanaa/spark/spark.sif
spark            49108    /scratch/radwanaa/spark/spark.sif
INSTANCE NAME    PID      IMAGE
spark-2          65041    /scratch/radwanaa/spark/spark.sif
spark            62554    /scratch/radwanaa/spark/spark.sif

```
```

$ for i in  `cat nodelist` ; do  ssh $i ps -p 55853 52767 63362 60688 33417 30532 51751 49108 65041 62554; done
  PID TTY      STAT   TIME COMMAND
  PID TTY      STAT   TIME COMMAND
  PID TTY      STAT   TIME COMMAND
  PID TTY      STAT   TIME COMMAND
  PID TTY      STAT   TIME COMMAND
$ 

```
I think we need to fix this bug in the next releases.
Thank you

**Comment by jmstover** [comment]
@cclerget @bauerm97 ... Mentioning you two here.

**Comment by al3x609** [comment]
By default Slurm send a SIGTERM signal to the job-steps, then wait 30s and send SIGKILL to the step 0.
you have two options for  handle system signals in your Job: e.g
- setup a prolog script to clean tmp files.
- trap the SIGTERM  in a script and cleanup the child job-steps.

```
#!/bin/bash
#SBATCH --time=01:00:00  # walltime
#SBATCH  -w, --nodelist=node1,node2
#SBATCH --qos=test
#SBATCH --ntasks-per-node=1 
#SBATCH -J test_singuarity_instances

# define the handler function
# note that this is not executed here, but rather
# when the associated signal is sent
term_handler()
{
        echo "function term_handler called.  Exiting"
        # do whatever cleanup you want here ...
        exit -1
}

# associate the function "term_handler" with the TERM signal
trap 'term_handler' TERM

srun  singularity instance start \
--bind $(mktemp -d run/`hostname`_XXXX):/run \
--bind dropbear/:/etc/dropbear \
--bind log/:/usr/local/spark/logs \
--bind work/:/usr/local/spark/work \
--bind ../spark/slaves:/usr/local/spark/conf/slaves spark.sif spark-2
```

**Comment by amrabdelaziem** [comment]
Dear @al3x609,
Thanks for your reply,
I have tried what you suggest, but it didn't work with me
```
#!/bin/bash
#SBATCH --time=01:00:00  # walltime
#SBATCH  -w, --nodelist=node1,node2
#SBATCH --qos=test
#SBATCH --ntasks-per-node=1 
#SBATCH -J test_singuarity_instances

# define the handler function
# note that this is not executed here, but rather
# when the associated signal is sent
term_handler()
{
        echo "function term_handler called.  Exiting"
        # do whatever cleanup you want here ...
       /usr/bin/rm  /var/run/singularity/instances/radwanaa/rstudio1
        exit -1
}

# associate the function "term_handler" with the TERM signal
trap 'term_handler' TERM
srun  singularity instance start rstudio_server.img rstudio1 --task-epilog= "rm -f /var/run/singularity/instances/radwanaa/*" 
srun singularity exec instance://rstudio1 rstudio-server start

```
This is the error I got 
```
NFO:    instance started successfully
slurmstepd: error: execve(): exec: No such file or directory
srun: error: node: task 0: Exited with exit code 2
ERROR  : Failed to enter in pid namespace: No such file or directory
```
To be clear that is what I need:
1- when slurm finish the job, files in `/var/run/singularity/instances/radwanaa/ ` are cleard automaticly without ask root privlages to delete them, to allow users to create new instance with the same name again.
2-  If i ran 
```
$ srun ssh node singularity instance start /scratch/dragon/intel/radwanaa/RStudio_Server/rstudio_server.img rstudio4
INFO:    instance started successfully
$ srun ssh node singularity exec instance://rstudio4 rstudio-server start
```
When `scancel` the job 
```
srun: Force Terminated job 815431
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 815431.7 ON cn605-19-l CANCELLED AT 2018-12-27T15:40:13 ***
Killed by signal 15.
srun: error: node: task 0: Exited with exit code 255
```
The instance keep running on the node with the following status
```
   PID TTY          TIME CMD
199530 ?        00:00:00 sinit
```
Thank you

**Comment by al3x609** [comment]
Hi @amrabdelaziem , You should adapt this example for that you needer , 

```
#!/bin/bash

#SBATCH  --job-name=instance.job
#SBATCH  --time=00:02:00  
#SBATCH  --qos=test
#SBATCH  --output=%j.out
#SBATCH  --error=%j.err


instance_name=rstudio1
image="/absolute/path/for/image.img"

# define the handler function
# note that this is not executed here, but rather
# when the associated signal is sent
# the trap signal only works for abnormal end of the script, example: scancel, etc...
term_handler()
{
        echo "function term_handler called.  Exiting"
	singularity instance stop $instance_name
        exit -1
}

# associate the function "term_handler" with the TERM signal
trap 'term_handler' TERM


srun singularity instance start $image $instance_name
srun singularity exec instance://$instance_name rstudio-server start

sleep 120 &
wait

# normal exit after wait for job allocation
 srun singularity instance stop $instance_name
exit 0
```

___

* you cannot remove the JSON file without root privileges
`/usr/bin/rm  /var/run/singularity/instances/radwanaa/rstudio1 `

  only the (suid) Singularity binary can perform this action in a normal account

* After deploying an instance, it is necessary to create some mechanism so that the Jobs does not finish immediately, since slurmctrld considers that the script has already finished and eliminates any remaining process.

 -> the sleep time is the same for SBATCH allocation in seconds.
 ``` 
  sleep 120 & 
  wait 
``` 

the only fail with Singularity is that  only check for files inside   `/var/run/singularity/instances/[user]/[name].json` 
and it does not verify that the process is actually running.

* about this:

> ...
> trap 'term_handler' TERM
> srun  singularity instance start rstudio_server.img rstudio1 --task-epilog= "rm -f /var/run/singularity/instances/radwanaa/*" 
> srun singularity exec instance://rstudio1 rstudio-server start

> This is the error I got
> 
> NFO:    instance started successfully
> slurmstepd: error: execve(): exec: No such file or directory
> srun: error: node: task 0: Exited with exit code 2
> ERROR  : Failed to enter in pid namespace: No such file or directory


this happens because the task-epilog remove the JSON file, then you try exec a command inside a NULL instance.
> singularity cannot find json file with the pid (sinit) -> pid namespace

___

with 
`sacct -v -j $job_ID`
you can monitor all job allocation, batch sections and job-steps.

___

* procure allocate nodes with a sbatch script not with srun, because if the network fail you will lost your Job.

* with `srun singularity ...` it creates jobsteps, 
and slurmctld will take care of propagating the signals to the child processes

* 
with `singularity ...` no work steps are created, just implement a new namespace pid, then you must manually propagate the signal for all the scripts that you run.  e.g

```
#!/bin/bash 

_term() { 
  echo "Caught SIGTERM signal!" 
  kill -TERM "$child" 2>/dev/null
}

trap _term TERM

echo "Doing some initial work...";
test_service start &

child=$! 
wait "$child"

```


The above is not intended to be the definitive solution, just a way to deal with integration mechanisms with singularity to workload managers  such as Slurm and may vary depending on the configuration of the cluster, Slurm, Singularity workfilow, etc..

**Comment by cclerget** [comment]
Hi @amrabdelaziem, I submitted a PR to fix some issues with instance termination, if you can give it a try ? Thanks. With this fix, if your instance process doesn't stop gracefully that means spark ignore TERM signal or take very long time to interrupt. Another solution could be to use user namespace instead if your system support it, so you will have control on instance files with the counterpart to use directory/sandbox image instead of SIF image.

Between we can't let control on instance files to users for security reasons when instances are run with setuid workflow, this is a real pain to handle securely and error prone.
