### ISSUE TITLE
PGP Key Import Command

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#2516]
Currently, the only way to get a public/private PGP key pair in Singularity is to use the `singularity keys newpair` command. While this works, it has some pretty major limitations:

* It doesn't allow folks to use their pre-existing PGP keys.
* It doesn't allow folks to move their PGP keys to another system.

_Technically_, this can be achieved with some hacking around with the `~/.singularity/sypgp/pgp-public` file. But this is terribly unfriendly.

I propose we create a couple of new commands:

* `singularity keys import` to import a key pair into Singularity
* `singularity keys export` to export a key pair from Singularity

**Comment by GodloveD** [comment]
So, now we will have `import`, `export`, `push`, and `pull`.  Seems a bit confusing imho.  I could see a user wondering what is the difference between an `import` and a `pull`.  Similarly, what is the difference between an `export` and a `push`.  

Is there a way to name the commands so that their function becomes more immediately apparent?  Or would it be a good idea to create a new flag to the `push` and `pull` commands that exports or imports the keypair instead of pushing and pulling from the key store?  Just trying to brainstorm here.

**Comment by ekivolowitz** [comment]
Perhaps this?
```
$ singularity keys load <path_to_file_to_add>     # load from file
$ singularity keys unload  <path_to_output_file>  # unload into file
```
I'm not so sure about the unload command, but I think that load would be a more intuitive name.

**Comment by tri-adam** [comment]
> So, now we will have `import`, `export`, `push`, and `pull`. Seems a bit confusing imho. I could see a user wondering what is the difference between an `import` and a `pull`. Similarly, what is the difference between an `export` and a `push`.

Yeah, I agree it's confusing. `import`/`export` work with public/private keys in local files, `push`/`pull` are used to share public keys via the Key Service.

For comparison's sake `gpg` uses the following terminology: 

```
     --import                import/merge keys
     --export                export keys
     --receive-keys          import keys from a keyserver
     --send-keys             export keys to a keyserver
```

Not sure that's really all that clear either!

> Is there a way to name the commands so that their function becomes more immediately apparent? Or would it be a good idea to create a new flag to the `push` and `pull` commands that exports or imports the keypair instead of pushing and pulling from the key store? Just trying to brainstorm here.

Maybe `import_from_file` and `export_to_file`? Think it might be confusing to overload `push` and `pull`... those commands don't work with files, nor private key material.

> Perhaps this?
> 
> ```
> $ singularity keys load <path_to_file_to_add>     # load from file
> $ singularity keys unload  <path_to_output_file>  # unload into file
> ```
> I'm not so sure about the unload command, but I think that load would be a more intuitive name.

Yeah, `load` is pretty obvious. Perhaps `save` would be complimentary to it?

**Comment by jchavezlavalle** [comment]
How about : 

```
$ singularity keys upload <path_to_file_to_add>
$ singularity keys download <path_to_output_file>
```

**Comment by GodloveD** [comment]
Hmm.  I think that `upload` and `download` are even more confusing since those are the the functions carried out by push and pull.  

While I'm not sure that `gpg` has the greatest idea with their their terminology, at least there is precedent there?  There is something to be said for precedent.  Like the ability to blame others?  😺
