### ISSUE TITLE
Extend PREPEND and APPEND to arbitrary env variables

### ISSUE THREAD

**Issue by blakedewey** [apptainer/singularity#2526]
## Version of Singularity:

2.6-current master

### Expected behavior

Any environment variable can be appended, prepended or replaced based on the environment variable set outside of the container.

Example:

SINGULARITYENV_PREPEND_PYTHONPATH=/front/of/pythonpath prepends to PYTHONPATH
SINGULARITYENV_APPEND_PYTHONPATH=/back/of/pythonpath appends to PYTHONPATH
SINGULARITYENV_PYTHONPATH=/new/pythonpath replaces PYTHONPATH

### Actual behavior

The behavior is only supported for PATH

### Steps to reproduce behavior

Setting SINGULARITYENV_PREPEND_PYTHONPATH outside of the container adds PREPEND_PYTHONPATH to the container.

**Comment by GodloveD** [comment]
I wonder if this functionality could be added by writing a specific runscript or by placing specific entries in the `%environment` section.

**Comment by blakedewey** [comment]
I think a runscript could be a possibility. My use case is a development container, where, for ease of quick changes, the python source code is kept out of the container. Therefore, I have to add my source code to the `PYTHONPATH`, but cannot overwrite it, as the container's `PYTHONPATH` is still also needed. 

I was hoping for an internal solution, as I also utilize `singularity exec` and `singularity shell` in the course of debugging, which I think would skip any runscript.

**Comment by GodloveD** [comment]
It might be possible to make some creative entries in the `%environment` section so that this works with the `exec` and `shell` commands as well.  I'm not sure when host variables are transposed into the container, so it may or may not work as expected.

**Comment by blakedewey** [comment]
I found @vsoch has actually explored this a bit in #860, although it might be a little out of date. It looks like the simplest option is a script in  `/.singularity.d/env/` that will parse the required environment variables. Since Singularity will pass through `SINGULARITYENV_PREPEND_PYTHONPATH` as `PREPEND_PYTHONPATH`, I can look for environment variables that start with "PREPEND" or "APPEND" and add them to the required environment variable.

I think this will work as a current solution, but I would still argue that this may be a possibly useful feature to think about going forward. It does allow for much more control, especially in cases where containers are run with `--cleanenv`.

**Comment by GodloveD** [comment]
Yeah, I think this is basically what I was suggesting.  Adding entries to `%environment` will write to `/.singularity.d/env/90-environment.sh`.  So you could put you entries there.

I think the problem with making this a default or built-in feature is that it is pretty python centric.  If we do this for python then maybe we should do it for Julia, or Rust, or MATLAB, or Octave, or...  You get the idea.  It's probably better for the users to write the functionality that they need into a container rather than imposing it upon them and trying to anticipate every need imho.

**Comment by vsoch** [comment]
It's not necessarily Python, R, centric! Given that a container is read only and we can never anticipate some future user's needs, it's a reasonable suggestion to want to append or prepend some additional path to any variable that is already existing in the container. This seems like a simple enough suggestion to take the (currently existing) ability to prepend to the PATH and extend it to be allowed for a general variable that might be wanted. The argument for having generalization is exactly that we *can't* anticipate the needs.

The one concern and question that would need to be discussed is if this poses any potential harm or risk? If not, it's a reasonable feature request.

**Comment by dtrudg** [comment]
I'm going to close this one, as to my knowledge we haven't had any further specific requests for it in the past year.

We do need to review ENV var handling (hopefully for 2.6) but I think the goal should be on making it consistent across what we have, rather than adding new things.

Also, blanket handling of `PREPEND_` and `APPEND_` prefixes would be worrying to me, as we are likely to hit some instance at some point where those are part of an ENV var that some app or container uses. Adding another to pass them through verbatim when needed stacks up more complexity.

I think the script suggestion is fine for now, and we can look at this again if it's something multiple people ask for.
