### ISSUE TITLE
can't mount image /proc/self/fd/8: failed to find loop device

### ISSUE THREAD

**Issue by ryzenX** [apptainer/singularity#2540]
## Version of Singularity:

3.0.2-96.gd61d61e2

### Expected behavior

I want to run singularity image

### Actual behavior

When i want to run singularity image i have this error :
FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/8: failed to find loop device: could not attach image file too loop device: No loop devices available

### Steps to reproduce behavior

create Singularity file like this :
https://github.com/truatpasteurdotfr/singularity-alpine/blob/master/Singularity

build image with this command :
sudo singularity build alpinelinux.img Singularity

and try to run like this :
singularity run alpinelinux.img

I have no this error with stable version 3.0
But with last master version it's not work in my computer

i see same problem in gitbuh :
https://github.com/sylabs/singularity/issues/2282

i'm on archlinux, i have brtfs filesystem (not NFS) and i have not enable ecl (i not modify conf file)

**Comment by jscook2345** [comment]
@ryzenX 

I've had this happen on a VM with opensuse where I upgraded the kernel but did not reload the vagrant VM.

Are you running your build in a VM?

**Comment by ryzenX** [comment]
yes i'm on VM with virtualbox
But i not use Vagrant 

i must downgrade linux kernel (if yes, what version linux kernel i must use) ? or may be have other solution ?

**Comment by cclerget** [comment]
@ryzenX Did you reboot your VM to load updated kernel ? Same happens to me after upgrade, you need to reboot to fix that, to ensure this is not a Singularity you can try to load an image :

```
sudo losetup -f alpinelinux.img
losetup -a
```

If you have an error or you don't see an image associated with a loop device, that means kernel module autoload can't find a module for your running kernel since the upgrade remove it from `/lib/modules` to replace it with upgraded kernel version

**Comment by ryzenX** [comment]
ok, i rebooted my vm and it's work.
thanks
