### ISSUE TITLE
Deny pull permissions for non administrative users

### ISSUE THREAD

**Issue by marcels2017** [apptainer/singularity#2544]
Hello,

Currently, we use singularity 2.5.2 and I'm wondering if it's possible to deny the pull function for non administrative users.

**Comment by cclerget** [comment]
Hi @marcels2017 , since pull is simply a http download, denying from Singularity won't prevent users to download and run images. I don't know if it's what you need but there is few directives in `singularity.conf` allowing you to apply some restrictions :

-  `limit container owners`: Only allow containers to be used that are owned by a given user (default empty)
- `limit container groups`: Only allow containers to be used that are owned by a given group (default empty)
- `limit container paths`: Only allow containers to be used that are located within an allowed path prefix (default empty)
- `allow container squashfs`: Limit usage of image containing squashfs filesystem (default yes)
- `allow container extfs`: Limit usage of image containing ext3 filesystem (default yes)
- `allow container dir`: Limit usage of directory image (default yes)

**Comment by marcels2017** [comment]
Hi @cclerget,

Our containers are stored in a shared file system and we want prevent users to waste the storage with. I think the only useful solution is to set a quota on the storage. Nevertheless, thanks for the tips!

**Comment by anthonypj** [comment]
We would also like a way to deny pull to non-admin users, so something like "limit pull group". I know we can restrict the use of containers, and that users could download images via other http methods, but we'd rather users did not waste their time, or system bandwidth and storage, by pulling down images,. Restricting "pull" would help with this.

**Comment by dtrudg** [comment]
I believe this is the only request we've had for this functionality. As @cclerget pointed out it's very easy to circumvent. Users can directly download with a different tool, they could also install a non-setuid version of singularity and pull with that. Because of this I'm not very inclined to add the feature.

I'd encourage that if you wish to limit users to specific containers / locations the config options mentioned are used.
