### ISSUE TITLE
Problems with 3.0.3-rc1

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#2550]
I noticed these problems with 3.0.3-rc1 so far:

1. The list of PRs doesn't exactly match the [3.0.3 RC milestone](https://github.com/sylabs/singularity/milestone/16): it left out pr #2535 and added pr #2533.

2. Pr #2533 breaks unprivileged mode and unprivileged installs.  It should only do the checks when not running in UserNamespace mode, if then.  Even running a root-installed singularity.conf with the exec -u option breaks.

Attn: @singularity-maintainers

**Comment by DrDaveD** [comment]
Note that PR #2558 addresses the second part of this issue, but not the first.

Was #2533 intentionally included in 3.0.3 or was it accidental?  Should it stay?  If it should stay then it should be added to the 3.0.3 RC milestone tag.  Also #2535 should get pulled in to the release.

**Comment by DrDaveD** [comment]
@GodloveD What about the first problem in this issue?  I don't think the issue should be closed yet, but it won't let me reopen it.

**Comment by GodloveD** [comment]
Heya @DrDaveD.  Thanks for the heads up.  Yes, #2533 was included in the RC1 on purpose. I didn't add it to the milestone because I actually didn't notice the milestone until I saw your issue (just now).  Sorry.  😄 

And I'm happy to add #2535 to RC2 as well.  I should be tagging that release in a few minutes after I get caught up on messages such as these.  Thanks!
