### ISSUE TITLE
[Question] Is there plugin spank/slurm support for singularity 3. *?

### ISSUE THREAD

**Issue by al3x609** [apptainer/singularity#2561]
Or, what recommendations can you give me for the interaction between slurm / openmpi / + singularity?

thanks.

**Comment by jscook2345** [comment]
@al3x609 

This should work right out of the box, there shouldn't be a need for any plug-ins. What are you having issues with?

**Comment by al3x609** [comment]
Hi, I have not had any problem, it's just a matter of functionality. for example.

from the user's perspective, to require a service in a HPC cluster,

`srun singularity run --nv /path/to/image.sif [args]`

but it would be something more useful if there is a plugin for slurm that allows.

`srun --image image.sif [args]
`
that allows implicitly, simplify the integration with Slurm.

I know that this plugin exists for version 2.* of Singularity, but it is not compatible with version 3.* and I am not sure if Sylabs has developed that code.

**Comment by jscook2345** [comment]
@al3x609 

After a bit of feedback from the devs, it appears that was implemented by a contributor.

As of right now there is no plan to focus on the plug-in because SLURM works well out of the box.

If a contributor wants to provide something we'd be happy to work with them and setup a repo for it as well!
