### ISSUE TITLE
singularity says dir not exist when using HPC job scheduler?

### ISSUE THREAD

**Issue by xiaozhah** [apptainer/singularity#2576]
singularity exec -H /tmp/homie --bind ~/test_wine:/mnt WineSingularity_latest.sif ls -a /tmp/homie/

it says

>.  ..  .bash_history  .cache  .config  .fontconfig  .local  .wget-hsts	.wine

However using HPC job scheduler like this:

bsub -n 4 -q testv3 -oo %J.log singularity exec -H /tmp/homie --bind ~/test_wine:/mnt WineSingularity_latest.sif ls -a /tmp/homie/

It says 

>ls: cannot access '/tmp/homie/': No such file or directory

Actually in host machine `ls -a /tmp/homie` works well

 Why? how to fix it? THANK YOU

Doc have this statement

>Are there any special requirements to use Singularity through an HPC job scheduler?

>Singularity containers can be run via any job scheduler without any modifications to the scheduler configuration or architecture. This is because Singularity containers are designed to be run like any application on the system, so within your job script just call Singularity as you would any other application!

**Comment by xiaozhah** [comment]
bsub -n 4 -q testv3 -oo %J.log singularity exec -H /tmp/homie --bind ~/test_wine:/mnt WineSingularity_latest.sif ls -a /tmp/

the /tmp is from the server /tmp, this is the reason. But I have to use /tmp, any idea?

**Comment by xiaozhah** [comment]
If compile Wine in Singularity instead of apt-get in Ubuntu, then everything OK

I make a Wine 64-bit Image in [xiaozhah/WineSingularity
](https://www.singularity-hub.org/collections/2252)


Or using isolated manner `--containall`

`bsub -n 4 -q testv3 -oo %J.log singularity exec --containall --bind ~/test_wine:/mnt WineSingularity_latest.sif wine /mnt/test_speed/perfectNum.exe`

**Comment by mem** [comment]
Sorry this didn't receive a reply before.

I'm going to assume that the queue you are using causes the command to run on a remote node. If that's correct, does the remote node have or have access to /tmp/homie?

When you use the -H flag, the directory that you specify is created if it does not exist, so the error you are seeing should not happen. I verified this with singularity 3.4.

As to why /tmp works and /tmp/homie doesn't, like I said, if the directory doesn't exist, it gets created. If it does exist (in the host) it's mounted.

The problem you are having is because /tmp is special: if it's so configured (and by default it is), singularity will mount the host's /tmp directory in the container, and this happens _after_ the home directory is created if necessary. This means that /tmp/homie is created and then /tmp is mounted, causing /tmp/homie to disappear.
