### ISSUE TITLE
Question: cgroups native integration

### ISSUE THREAD

**Issue by JiaLiPassion** [apptainer/singularity#2615]
## Version of Singularity: 

3.0.3

### Question

Here are several questions about  `cgroups native integration` from user.

1. Will singularity support all resources configuration, memory/CPU/diskIO/devices?
2. Singularity exec a.out (will a.out belong to the specified cgroup which singularity created)?
3. If the answer is yes, is singularity using some RPC api to get the limitation (max/min) of resources(CPU/memory)? 

@cclerget  @GodloveD, please check it, thanks!

**Comment by cclerget** [comment]
Hey @JiaLiPassion , regarding your questions :

1. Yes it support all resources
2. Yes and cgroups are available for root user only
3. No singularity just apply configuration from the provided file (if I understand your question correctly)

Hope that helps !

**Comment by JiaLiPassion** [comment]
@cclerget, thank you very much, I will forward the answer to the user.

**Comment by JiaLiPassion** [comment]
@cclerget, the user has a follow up question, 

> * Singularity exec a.out (will a.out belong to the specified cgroup which singularity created)?
> * Yes and cgroups are available for root user only

About this question and answer, the user want to confirm, the `root` here is `root cgroup` not `root user`, is that correct?
And in user's use case, user will  setup `cgroup settings` and apply to a `job scheduler,` and then use this `job scheduler` to launch a `shell` to run `singularity command`, so in this scenario,  singularity will run in the cgourp which is created by the `job scheduler`, is that correct?

Thanks.

**Comment by cclerget** [comment]
@JiaLiPassion `root` mean root user here. The "root cgroup" is common to all processes in `/sys/fs/cgroup` divided in subsystems. Singularity doesn't create cgroup (and will run under defined cgroup like here the job scheduler) unless specified by a root user via `--apply-cgroup` option, so when `--apply-cgroup` is not present, Singularity will just run like any other applications within the user environment/constraints. `--apply-cgroup` is useful for micro-service use cases, as there is no need for HPC use cases because it requires root privileges and it's often handled at higher level by the job scheduler, that's why Singularity doesn't touch cgroup by default.

**Comment by JiaLiPassion** [comment]
@cclerget, got it, thanks for the detailed explanation!
