### ISSUE TITLE
Errors on any incorrect `%`

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#2646]
## Version of Singularity:

```
3.0.1-752.g456a1a62
```

### Expected behavior:

Container builds without any errors.
Or at least warns you about invalid sections.

### Actual behavior:

The build fails, complaining about `invalid section(s)`:

```
$ sudo singularity build test.sif test.def 
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Unable to create build: unable to parse spec test.def: While parsing definition: test.def: invalid section(s) specified: {hello, hello
```

*(The def file)*
```bootstrap: library
bootstrap: library
from: alpine:3.8

%runscript
cat /hello-world

%post
cat << EOF > /hello-world

USAGE:
    ./somthing.sh %{option}... %bar

%{hello world}
%hello world

EOF
```

### Steps to reproduce this behavior:

Try building a container with the provided def file.

**Comment by jscook2345** [comment]
I'm not sure I agree with this, but maybe I don't understand your use case.

Could you tell me why you think the image should be built even though the definition of the image is invalid?

**Comment by gmkurtzer** [comment]
It seems that Singularity is erring out on a valid definition file due to parsing issues.

Very interesting find on a wacky edge case! In over 3 years nobody has noticed it before as previous versions of Singularity would also be susceptible to this, but the effect would have been to silently stop parsing the section at the first %{hello world}.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@WestleyK We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
