### ISSUE TITLE
[docker] [python] we need proper tests

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#271]
The entire set of functions (primarily Docker) that use the included python modules need tests! Specifically:
- bootstrapping an image with python2/python3
- Testing the functions individually to retrieve information about Docker registry
- Testing on non Docker registries (eg, gcr.io)

This would likely encompass:
- Editing the .travis.yml to set up python2/python3 environments
- Adding tests to the bottom of tests.sh, or better, having a proper suite of python function tests.

**Comment by bauerm97** [comment]
While we're at it, can we discuss what's necessary to pull any docker image that's listed on docker hub even if it's not hosted on the default registry? This would be a very nice feature because it's not always easy to figure out where the image is actually located, and the work around takes 10-15 minutes every time you want to do it.

**Comment by flx42** [comment]
@bauerm97 solving issues #272 and #273 might be enough to solve your problems

**Comment by vsoch** [comment]
This is definitely done - we have testing for python 2 and 3, and we can pull from any Docker Hub registry.
