### ISSUE TITLE
[docker][python] import: namespace is not always used

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#272]
```
$ sudo singularity import cuda.img docker://nvidia/cuda:8.0
nvidia/cuda:8.0
Error getting tags using url https://registry-1.docker.io/v2/nvidia/cuda/tags/list
Bootstrap initialization
No bootstrap definition passed, updating container
Executing Prebootstrap module
Executing Postbootstrap module
ERROR: Container does not contain the valid minimum requirement of /bin/sh
```

I think the patch is simple, something like that:

``` diff
diff --git a/libexec/python/docker/api.py b/libexec/python/docker/api.py
index 66e58dd..fd8c646 100644
--- a/libexec/python/docker/api.py
+++ b/libexec/python/docker/api.py
@@ -151,6 +151,7 @@ def get_manifest(repo_name,namespace,repo_tag="latest",registry=None,auth=True):
     token = None
     if auth == True:
         token = get_token(repo_name=repo_name,
+                          namespace=namespace,
                           permission="pull")

     response = api_get(base,headers=token,default_header=True)
@@ -209,6 +210,7 @@ def get_layer(image_id,namespace,repo_name,download_folder=None,registry=None,au
     token = None
     if auth == True:
         token = get_token(repo_name=repo_name,
+                          namespace=namespace,
                           permission="pull")

     if download_folder != None:
```

Edit: colors!

**Comment by vsoch** [comment]
Can you do a PR or something to more clearly show the difference? Sorry I'm having trouble understanding what you want to to change, and why. Thanks.

**Comment by flx42** [comment]
I can't do a PR right now, I don't have corporate approval yet, hopefully I will be able soon.
Here's the patch: https://github.com/flx42/singularity/commit/6e9585109085a6fa008f6a58435aa484b4922d2c
It's simple enough that you can do the changes yourself if that looks fine.

Without this patch, `get_token` will default to `library` for argument `namespace`:
https://github.com/flx42/singularity/blob/6e9585109085a6fa008f6a58435aa484b4922d2c/libexec/python/docker/api.py#L48
So, it doesn't work for non-official images as shown above.

**Comment by bauerm97** [comment]
I'm not exactly sure what this will solve, could you clarify a bit? If you look at the output that you pasted here:

`Error getting tags using url https://registry-1.docker.io/v2/nvidia/cuda/tags/list`

It appears that it is still querying using the "nvidia" namespace that you claim is being lost. The issue however, is that the nvidia/cuda image is not hosted on https://registry-1.docker.io/ but rather a different registry. The way this works right now AFAIK is because get_token simply concatenates the registry address + the repo name if the namespace var isn't present and submits an https request to that string. If the image name contains a "/" it probably just never assigns a namespace, however if the image name doesn't contain a "/" then it defaults to "library" namespace.

```
repo_name == cuda/nvidia -> namespace == none -> https://registry-1.docker.io/v2/nvidia/cuda/tags/list
repo_name == centos -> namespace == library -> https://registry-1.docker.io/v2/library/centos/tags/list
```

In order for us to enable pulling _any_ image from docker hub, we need to figure out what registry server the image is hosted on, then submit the https request to that webserver

**Comment by flx42** [comment]
> It appears that it is still querying using the "nvidia" namespace that you claim is being lost.

It's lost for `get_token`, and this is what my dirty patch is fixing (I verified it works). We ask a token for `library/cuda`, and then try to use it for querying the tags of `nvidia/cuda` and we get a 401 error.

Basically, this is what's happening currently:

``` sh
# Token is fetched from library/cuda
$ TOKEN=$(curl -s 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/cuda:pull' | jq -r '.token')
$ http https://registry-1.docker.io/v2/nvidia/cuda/tags/list Authorization:"Bearer $TOKEN"
HTTP/1.1 401 Unauthorized
Content-Length: 143
Content-Type: application/json; charset=utf-8
Date: Thu, 27 Oct 2016 23:55:52 GMT
Docker-Distribution-Api-Version: registry/2.0
Strict-Transport-Security: max-age=31536000
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:nvidia/cuda:pull",error="insufficient_scope"

{
    "errors": [
        {
            "code": "UNAUTHORIZED", 
            "detail": [
                {
                    "Action": "pull", 
                    "Name": "nvidia/cuda", 
                    "Type": "repository"
                }
            ], 
            "message": "authentication required"
        }
    ]
}
```

We need to do the following instead:

```
$ TOKEN=$(curl -s 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:nvidia/cuda:pull' | jq -r '.token')
$ http https://registry-1.docker.io/v2/nvidia/cuda/tags/list Authorization:"Bearer $TOKEN"
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 27 Oct 2016 23:57:14 GMT
Docker-Distribution-Api-Version: registry/2.0
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked

{
    "name": "nvidia/cuda", 
    "tags": [
        "6.5-devel-ubuntu14.04", 
        "6.5-devel", 
        "6.5-runtime-ubuntu14.04", 
        "6.5-runtime", 
        "6.5-ubuntu14.04", 
[...]
```

> The issue however, is that the nvidia/cuda image is not hosted on https://registry-1.docker.io/ but rather a different registry. 

I don't think that's true, see above.

**Comment by bauerm97** [comment]
@flx42 ahh I see what's happening. I hadn't dug much into that section of the code and had just assumed that the http request would always have a proper token. Since you seem to have this implemented locally already, would you mind testing a simple build based off of a few different images? Can you try pulling this image "tensorflow/tensorflow:latest" as well as "cern/cc7-base"? I'm curious what happens each time.

UPDATE:

@vsoch tested and it appears to be able to pull all images on docker hub now, even though certain images such as tensorflow are actually hosted on grc.io

**Comment by vsoch** [comment]
@flx42 thanks for the clarification - this is hugely helpful! I can get this tested soon.

**Comment by gmkurtzer** [comment]
Ohh, this is fantastic. Thanks everyone!

**Comment by vsoch** [comment]
Thanks @flx42, this was such a great PR!! Docs are updated: http://singularity.lbl.gov/docs-docker

**Comment by flx42** [comment]
@bauerm97: the tensorflow/tensorflow image is hosted on DockerHub **and** on gcr.io, when using `tensorflow/tensorflow`, the image is fetched from DockerHub. Actually, at one point the two repos where not properly synced.

**Comment by bauerm97** [comment]
@flx42 It could also be that registry-1.docker.io actually provided some redirect functionality and is able to pull from third party registries that are allowed to host content. Or as you said, it might just be hosted on both. Either way, now that this token issue is fixed it works like a charm. Very good catch, I think we all really appreciate that pulling all images from docker hub works now.

**Comment by davidhrbac** [comment]
This is very important improvement. Should be mentioned in 2.2.1 release notes - https://github.com/singularityware/singularity/releases/tag/2.2.1

**Comment by gmkurtzer** [comment]
I fixed the release notes, thanks @davidhrbac.
