### ISSUE TITLE
Error debootstrap "While performing build: while running engine: exit status 255"

### ISSUE THREAD

**Issue by titansmc** [apptainer/singularity#2743]
## Version of Singularity:

  singularity --version
  singularity version 3.0.3-1.el7

/tmp mount as : 
  /dev/mapper/VG00-lv_tmp on /tmp type ext4 (rw,nosuid,relatime,seclabel,data=ordered)

### Expected behavior

Finish the build

### Actual behavior

````
+ apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu bionic/main Translation-en [516 kB]
Fetched 516 kB in 1s (500 kB/s)         
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
+ DEBIAN_FRONTEND=noninteractive apt install -y cmatrix cowsay fortune lolcat
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package cmatrix
E: Unable to locate package cowsay
E: Unable to locate package fortune
E: Unable to locate package lolcat
FATAL   [U=0,P=96989]      StartProcess()                post proc: exit status 100
DEBUG   [U=0,P=96980]      Master()                      Child exited with exit status 255
FATAL   [U=0,P=92200]      run()                         While performing build: while running engine: exit status 255
````

### Steps to reproduce behavior

Build an image with debootstrap like:
  sudo singularity --debug build fun.sif ~/Singularity.boot

Environment is CentOS 7.6 (but also fails in my Ubuntu 18.04 with singularity version 3.0.1-240.g78d57bef)

````
cat Singularity.boot 
Bootstrap: debootstrap
OSVersion: bionic
MirrorURL: http://us.archive.ubuntu.com/ubuntu/

%help
  A container with a bunch of fun programs installed.

%environment
  export LC_ALL=C.UTF-8
  export LANG=C.UTF-8
  export PATH=/usr/games:"$PATH"

%post
  apt update
  DEBIAN_FRONTEND=noninteractive apt install -y cmatrix cowsay fortune lolcat
  echo "export PATH=/usr/games:$PATH" >> "$SINGULARITY_ENVIRONMENT"

%test
  export PATH=/usr/games:"$PATH"
  command -v cowsay >/dev/null 2>&1 || { echo >&2 "I require cowsay but it's not installed.  Aborting."; exit 1; }
  command -v fortune >/dev/null 2>&1 || { echo >&2 "I require fortune but it's not installed.  Aborting."; exit 1; }
  command -v cmatrix >/dev/null 2>&1 || { echo >&2 "I require cmatrix but it's not installed.  Aborting."; exit 1; }

%runscript
  fortune | cowsay
````

**Comment by jscook2345** [comment]
I was able to reproduce this with `centos 7.6.1901.01`, checking with `ubuntu` next next.

**Comment by jscook2345** [comment]
@titansmc 

So it looks like this may be an intended behavior of `debootstrap`. From the debian wiki (https://wiki.debian.org/Debootstrap):

<pre>
Debootstrap can only use one repository for its packages. If you need to merge packages from different repositories (the way apt does) to make a rootfs, or you need to automatically customise the rootfs, then use Multistrap. 
</pre>

When bootstrapping the system (using `debootstrap`), only one repository is present in /etc/apt/sources.list (http://us.archive.ubuntu.com/ubuntu bionic main). A full system has many more.

All the packages you're requiring in `%post` are not in that repository. They are in the `universe` repository.

It seems this was a problem someone else came across in the past because there is a way around this by manipulating `/etc/apt/sources.list` to contain the `universe` repository in our examples directory in the source.

<pre>
sed -i 's/$/ universe/' /etc/apt/sources.list
</pre>

I've verified this allows you to build on ubuntu, at least. I only changed the `%post` section:

<pre>
%post
  cat /etc/apt/sources.list
  sed -i 's/$/ universe/' /etc/apt/sources.list
  cat /etc/apt/sources.list
  apt update
  DEBIAN_FRONTEND=noninteractive apt install -y cmatrix cowsay fortune lolcat
  echo "export PATH=/usr/games:$PATH" >> "$SINGULARITY_ENVIRONMENT"
</pre>

**Comment by jscook2345** [comment]
@titansmc 

Any luck using my suggestion above?

**Comment by titansmc** [comment]
Sorry @jscook2345 , I missed your answer. Now it is building the image, my fault.

Thanks for the support.
