### ISSUE TITLE
We shouldn't be messing with env vars from docker

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2753]
## Version of Singularity:

bc646de5e6a1334646ee3d63f64e41f711c20374
### Expected behavior

This is the Dockerfile for `godovedc/lolcow`.  Note the assignment of `LC_ALL`

```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y fortune cowsay lolcat

ENV PATH /usr/games:${PATH}
ENV LC_ALL=C

ENTRYPOINT fortune | cowsay | lolcat
```

With Singularity 3.0.3 I can build `godlovedc/lolcow` at the command line like so:

```
sudo singularity build test1 docker://godlovedc/lolcow
```
Now these are the contents of `/.singularity.d/env/10-docker2singularity.sh`

```
$ singularity exec test1 cat /.singularity.d/env/10-docker2singularity.sh
#!/bin/sh
export PATH="/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export LC_ALL="C"
```
That's swell. 
### Actual behavior

But with the current master, after building the container in the same way:
```
$ singularity exec ~/test1 cat /.singularity.d/env/10-docker2singularity.sh
#!/bin/sh
export PATH="/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export LC_ALL=${LC_ALL:-C}
```
That ain't cool.  I specified in the original Dockerfile that `LC_ALL=C`, so I want it to be `C`, not `C` or something else depending on what `LC_ALL` happens to be at any moment in time.  What gives?

**Comment by cclerget** [comment]
@GodloveD The problem with docker environment variables is that they are used for different purpose depending of images/maintainers, some image allows and/or requires to pass environment variables to run, because they define in Dockerfile something like :

`ENV MYSERVER=""`

And expect to run image like `docker run -e MYSERVER=XXXXXX`

We need to handle those cases at some point. An approach like it's already done with `PATH` could be to exclude standard environment variables or provide a similar `--env` argument like docker to explicitly define environment variable value at run.

**Comment by GodloveD** [comment]
Could the case above be handled with `export SINGULARITYENV_MYSERVER=XXXXXX`?

**Comment by cclerget** [comment]
No it won't work because `SINGULARITYENV_XXX` are mapped to `XXX`, so if we want to explicitly override a docker env, we could allow something like `DOCKERENV_XXX` to have in `10-docker2singularity.sh` :

`export MYSERVER=${DOCKERENV_MYSERVER:-""}`

Between the issue was a blocker during singularity CRI tests/demo, so singularity CRI should handle that in same way if we take `DOCKERENV_XXX` approach.

**Comment by jmstover** [comment]
If we went a `DOCKERENV_XXX` approach, wouldn't you need to to something like:

```
ENV LC_ALL=C

LC_ALL=${DOCKERENV_LC_ALL:"C"}
```
So, use whatever is given in the manifest as the default value if a matching `DOCKERENV_*` var doesn't exist?

**Comment by cclerget** [comment]
@jmstover Actually build process take all environment variables from manifest and add all ENV in `10-docker2singularity.sh`, so no need to change anything on docker side

**Comment by dtrudg** [comment]
This is subsumed by #5040
