### ISSUE TITLE
Singularity instances persist after Torque job completes

### ISSUE THREAD

**Issue by isaiahtaylor** [apptainer/singularity#2759]
## Version of Singularity:

```bash
singularity version 3.0.3-582.ge13861e
```

### Expected behavior

I expected Singularity instances to be killed once a Torque session completes.

### Actual behavior

Singularity instances persist even after a Torque job exceeds wall time or is exited early.

### Steps to reproduce behavior

1. Que a job
2. `singularity instance start ubuntu.sif ubuntu1`
3. exit the job
4. Start a new job
5. `ps aux | grep ubuntu1`

### Cause

`ps -ejf | grep -E "[your user]|UID"` will show you that there were two processes created after opening a Singularity instance: `Singularity instance: $USER [instance name]` and `sinit`, who's parent ID is the PID of the singularity instance. However, the Singularity instance process has parent ID of 1 (`PPID`), no associated terminal (`TTY: ?`), and a different session ID (`SID`). I assume this is because it was made using `setsid`. However, since there is no associated session, when the Torque session ends after the wall time runs out, the main thread exits, or the user exits the interactive session, the Singularity instance persists.

I looked into #2512, but I do not think that it solves this particular issue, as the process would not have received any signal after the original session ends. Correct me if I am wrong in this.

**Comment by al3x609** [comment]
I have the same issue with Slurm job manager. I think that singularity should be search inside `/var/run/singularity/instances/$USER/*` and remove unused pid files before run a new instance. @cclerget

**Comment by jmstover** [comment]
@iptaylortechnical  Can you test with 3.1.0? #2512 should theoretically fix this. Torque is killing all processes from the job when you exit. That includes the `instance`. But, since it doesn't "cleanly" exit (i.e. instance stop), the state file isn't removed. So a `instance list` ran on the same node will show a running instance that doesn't actually exist.

What #2512 should do is catch extra signals, like SIGTERM, and exit and cleanup when that signal is received. Schedulers usually send a SIGTERM first, then send a SIGKILL to anything that's still running.

-J

**Comment by isaiahtaylor** [comment]
@jmstover I'll try rebuilding and testing this next week. However, `ps` was also showing the process, not just `instance list`

**Comment by mem** [comment]
This should be fixed now, no? @cclerget?

**Comment by cclerget** [comment]
Partially, it remains to add some instance file cleanup if instance has been killed, #4332 is also related to this one
