### ISSUE TITLE
The full host environment is imported

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#276]
The full environment of the parent shell is inherited inside the container. What is the rationale behind this?

It might be better to enter a container with a clean environment by default, otherwise your new environment might be clobbered by all the mess you potentially did in your shell before launching singularity. We might lose some of the reproducibility aspect of containers, for instance:

```
$ PATH=/usr/sbin:/usr/local/bin:/usr/bin:/sbin:/bin singularity exec cuda.img nvcc -V
WARNING: Could not chdir to home directory: /home/fabecassis
/.exec: line 3: exec: nvcc: not found

$ PATH=/usr/local/cuda/bin:/usr/sbin:/usr/local/bin:/usr/bin:/sbin:/bin singularity exec cuda.img nvcc -V
WARNING: Could not chdir to home directory: /home/fabecassis
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
```

This example is rather trivial, but think about environment variables that can actually impact performance, like `MALLOC_OPTIONS`.

Also, if you use `mount home = yes`, your `.bashrc` file will be parsed and you will get you environment associated with your home, without having to inherit it.
If you don't mount your home, your host environment is actually probably useless now.

**Comment by bauerm97** [comment]
Hi @flx42 I can't speak for the rationale behind why this is done but hopefully I can give some ideas for how we can better handle this.

For one of our use cases at my HPC, the environment variables carrying over into the container is very important. SLURM receives a job from a perl module that is from an outside source, we cannot control what this perl module submits to us. Inside the shell script submitted to SBATCH (SLURM's way to handle job submission) from the perl module contains a line running another shell script. We inject singularity exec into the script submitted to SBATCH, and then it runs. However, in the script sent to SBATCH, there are some environment variables submitted and we are not _supposed_ to change the format of this file since it is from an outside maintainer. Therefore, we find it very useful that these environment variables are carried over into the container.

That being said, I can also see many use cases where you would not want this behavior to be the case, and I think that this is good functionality to add in. Perhaps we could add a config option as well as a flag for runtime. Something like this might be a good idea

Command:
`
singularity run --clean-env container.img
`

singularity.conf:
`
allow isolated environment = yes / no`

Continuing this idea however, maybe we can arrive at a solution where a user is allowed to choose exactly what is isolated from the host at runtime/buildtime of an image. This way users could isolate user namespace when they want root in the container, PID namespace if they want PID 1, etc... Right now linux makes these namespaces available:

```
Cgroup      CLONE_NEWCGROUP   Cgroup root directory
IPC         CLONE_NEWIPC      System V IPC, POSIX message queues
Network     CLONE_NEWNET      Network devices, stacks, ports, etc.
Mount       CLONE_NEWNS       Mount points
PID         CLONE_NEWPID      Process IDs
User        CLONE_NEWUSER     User and group IDs
UTS         CLONE_NEWUTS      Hostname and NIS domain name
```

It would be really great if we could assign each of these namespaces a symbol and allow them to be passed at runtime. For instance:

```
singularity run --isolate CNMP container.img
singularity run --isolate PUC container.img
```

Where each letter corresponds to the namespace the user wishes to isolate. This could create some interesting scenarios such as the possibility for a user to build container images without sudo on the host. Maybe this should be put into a separate issue for further contemplation however. Thoughts everyone?

**Comment by gmkurtzer** [comment]
Hi @flx42.

Inheriting from the primary environment is part of the design of Singularity. This allows things like proper usage of MPI, X11, and even interaction with the resource manager possible. But with that said, there are a couple of ways to help control what gets passed into the environment (e.g. `/etc/singularity/init` for system wide changes or `$HOME/.singularity-init`). In there you can set/unset/override any environment variable.

Now, it would also be pretty straight forward to create a function as @bauerm97 suggested but I fear this would break a lot of things. What about having the ability to override just a single variable?

BTW, I don't think that needs to be a toggle within the singularity.conf, as it is technically possible to do now:

```
$ env -i singularity exec cuda.img nvcc -V
```

But I have a feeling in an actually clean environment, other problems will occur (e.g. not knowing where the home directory is).

As far as the shell parsing the user's dot files... When are you seeing that? When calling the `shell` Singularity subcommand or also on `exec`?

**Comment by flx42** [comment]
@bauerm97: yes, I understand there are use cases where it matters, I'm not saying it should be impossible to add environment variables when you need to.
I think your proposal is interesting and could really provide good modularity.

@gmkurtzer:

> Now, it would also be pretty straight forward to create a function as @bauerm97 suggested but I fear this would break a lot of things. 

It could be disabled by default, and obviously you still need default values for some variables like `PATH`, and `HOME`.

> BTW, I don't think that needs to be a toggle within the singularity.conf, as it is technically possible to do now:
> $ env -i singularity exec cuda.img nvcc -V

Sure, and I can also set cgroups by hand, then `chroot`, etc. ;)
I'm just saying than an option that improves reproducibility seems always useful for a container solution, Singularity could clean the environment but then load the environment used when building the image, or the environment provided by the Docker config (currently ignored).

> As far as the shell parsing the user's dot files... When are you seeing that? When calling the shell Singularity subcommand or also on exec?

Well, if you start bash, it will try to read `$HOME/.bashrc`, that's what bash does :). Either through `singularity exec /bin/bash` or `singularity shell`.

**Comment by gmkurtzer** [comment]
@flx42: I still don't think an option like this should be system wide, if anything it would have to be a runtime flag and/or an environment variable toggle that can be set directly in environment or in ~/.singularity-init.

Regarding Bash doing what it does.. lol.. Yes, you are right. In an earlier version of Singularity it would actually sense for Bash and call it with `--noprofile` and `--norc` to work around that, but then people had other things defined in there that they wanted parsed (can't make everyone happy). But... it is always easier to source then de-source so maybe that feature should return.

TGIF! ;)

**Comment by flx42** [comment]
>  I still don't think an option like this should be system wide, if anything it would have to be a runtime flag and/or an environment variable toggle that can be set directly in environment or in ~/.singularity-init.

Sure, fine for me. As long as it's possible without using magic incantations :)

**Comment by DrDaveD** [comment]
Regarding a default value for $HOME, as of yesterday with the merging of pr #251, singularity now always sets $HOME at the same time it generates the /etc/passwd entry for the user.

**Comment by gmkurtzer** [comment]
I've been running through my mind and even tried some code on this @flx42, and I haven't come up with an implementation that I feel is satisfactory. I think the best bet would be to clear the environment before calling Singularity like:

``` bash
[gmk@centos7-x64 modules-v2]$ env -i singularity exec /tmp/Centos-7 env | wc -l
18
[gmk@centos7-x64 modules-v2]$ singularity exec /tmp/Centos-7 env | wc -l
66
```

**Comment by flx42** [comment]
@gmkurtzer OK, I didn't have time yet to experiment with this myself, I will reopen if I have a solution to suggest. Thank you!

**Comment by jakirkham** [comment]
Just chiming in to say I agree with the OP. Though also acknowledge this is tricky to change midstream ( Singularity 3.0.0? ;) ).

In my personal use case, have an issue where the system sets `XDG_RUNTIME_DIR` to `/run/user/XXX` (where `XXX` is a user specific ID). Though things like Jupyter will try to write there, which causes issues. That said, there are a host of other cases where this doesn't make sense (e.g. `PATH`).

Returning to the issue at hand, have a couple suggestions.

First it would be nice to see these options (e.g. `--clean-env` and `singularity.conf`) in [the `singularity run` docs]( http://singularity.lbl.gov/docs-run ), which didn't seem to mention this. Probably also for `singularity exec`, `singularity shell`, and [config file docs]( http://singularity.lbl.gov/docs-config ), which also don't note it. Only found this info in this issue after a fair bit of searching. Would like to see this info be a bit more prominent given its impact.

Second one idea to improve this situation further would be to have some sort of pass through environment variable section in Singularity recipe file. By default this could pass through everything as is. However users could specifically list what environment variables they would like to pass through and everything else would be unset before running the container. Perhaps there is a `none` or `false` option that disables all pass through of environment variables. This gives image builders some more control when they might not have access to the end user's settings. Thoughts?

**Comment by vsoch** [comment]
hey @jakirkham I've added a brief page on flags, that minimally will alert the user to look for the options:

http://singularity.lbl.gov/action-flags

It is linked from shell, exec, run. If you have any suggestions or tweaks to make, please PR to the repo! 

https://github.com/singularityware/singularityware.github.io

Thanks!

**Comment by jakirkham** [comment]
Great, thanks, @vsoch. Already the docs are a nice improvement.
