### ISSUE TITLE
add arguments for definition sections 

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2765]

**Comment by GodloveD** [comment]
for instance `from one` in a `%files` section should reference a particular container in the multi-stage build def file.

**Comment by al3x609** [comment]
Hi @GodloveD, Is there  a man-page for multi-stage build? or Is it a future feature to 3.1* branch?

**Comment by GodloveD** [comment]
Heya @al3x609 we are planning this feature for 3.2.  What would you like to use multi-stage builds do?  Any ideas you have would be greatly appreciated.

**Comment by al3x609** [comment]
ok, I developed a remote visualization  platform for HPC environments, with singularity 3.1 and spython API python. Many times we need to compile very large software from sources,

and it is important that the images remain small, since they will be stored in NFS. Given the above information, it is about optimizing the singularity files while keeping them easy to read and maintain, compiling in a base container and only loading the binary files into production.

another approach, is that with multi-stage builds, we can create a base image with all requeriments for compile process, and an  inherited image only with the required software for deploy micro-services over containers.

**Comment by GodloveD** [comment]
I think these are great ideas.  And I think they are very much the kinds of things that @ikaneshiro has in mind as he's spec-ing this feature out.

**Comment by jscook2345** [comment]
@ikaneshiro ping! Feel free to hash out these ideas and merge them into you PR / issue. Once done, please close this up. Thanks!

**Comment by ikaneshiro** [comment]
Fixed by #3156
