### ISSUE TITLE
implement more intelligent parsing for def file section keywords/headers

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2767]

**Comment by GodloveD** [comment]
may or may not be part of the same work, but also must keep in mind that options to bash must be parsed as well.

See #2656 and #2438

**Comment by jscook2345** [comment]
@ikaneshiro I think this is meant for you. Could you hash out what this is intended to do so I know more about it? Thanks!

**Comment by ikaneshiro** [comment]
@jscook2345 The intention of this is to allow multiple definitions in the same file. This will enable us to easily parse multistage definitions. Currently our parsing looks for the first instance of colon separated pairs(indicating a header) or `%section`. In order to detect the start of the next definition we need a stronger way to detect the header. One potential option is to make `Bootstrap` a reserved keyword that the parser will use as indication that a new definition is starting. Other options include using a new delimiter like `#BUILDSTAGE` or using a new format but i'd like to stay away from those options unless absolutely necessary.
