### ISSUE TITLE
[feature request] args for build stage, new flag "--from"

### ISSUE THREAD

**Issue by al3x609** [apptainer/singularity#2773]
In a definiton file,  i.e:

```

BootStrap: localimage
From:  ${arg}

...

%runscript
echo "test"

______________________________________________________________

singularity build --from /path/to/image test.sif test.def 

```

I see the need for this new argument, in the case of moving the images between directories, it also helps to build containers from a more abstract layer, such as a python API.

**Comment by jscook2345** [comment]
@ikaneshiro ping!

**Comment by Flamefire** [comment]
This can be kinda emulated by the `--update` option and a copy. So    
`singularity build --from /path/to/image test.sif test.def `    
becomes    
`cp -r test.sif /path/to/image && singularity build --update /path/to/image test.def `

Would be great if the requested feature was implemented though

**Comment by mem** [comment]
My understanding of the issue is the case where the original image might be located in arbitrary locations, and you don't want to hardcode those locations in a .def file.

Is that more or less it?

Wouldn't the same be achieved by generating the .def file?

```
Bootstrap: local
From: @BASE_IMAGE@
```

and then `sed -e 's,@BASE_IMAGE@,/path/to/image,' template.def.in > test.def`?

What's the advantage in having singularity do this for you?

**Comment by dtrudg** [comment]
Closing as there was no follow-up on the use-case vs templating the file as suggested above. Please feel free to reopen if you can provide some more information.
