### ISSUE TITLE
Move /.singularity.d functions to SIF metadata and action binds

### ISSUE THREAD

**Issue by gmkurtzer** [apptainer/singularity#2787]
Currently the container metadata and action scripts are all located within the container image at `/.singularity.d/`. We should be using SIF metadata for this and binding the action scripts into the container at run-time.

This will make metadata pulls from the container a lightweight process and as an example, allow us to leverage things like the runscript from outside the container, and execute it via a pipe. It will also allow Singularity to count on the exact version and placement of the action script being called (as opposed to going through a list of predefined locations searching for where it might be).

One possible option for the action scripts is to always have the container try to execute a given one, (perhaps `/action`) and the proper action is always binded in at runtime depending on the Singularity verb passed. This would entail `singularity run ...` binding the `run` action script into the container's `/action` location, and then we can exec that location (`/action`). Lastly, if we need to free ourselves from `/bin/sh`, the actions could be static binaries built for the host architecture.

**Comment by GodloveD** [comment]
I think the action scripts are already being bind mounted in at runtime.  Will defer to @ikaneshiro on that for further details.  As far as the metadata goes, we discussed that extensively at last face to face.  I think that we could not figure out a way to inject the metadata into the the container at runtime because the order of operations is all screwed up?  In particular, scripts in the `env` subdir must be sourced at container initiation, and must be sourced in a very specific order.  I remember this being an issue.  I also remember that we tried to figure out an alternate way to represent the data, (by manually figuring out what the environment would look like at runtime and saving the final product in a json or something) but we concluded that would be _very_ difficult to do properly and would also break things like script sourcing in the `env` files.  We don't currently provide an alternative for things like this and they can be critical to people's workflows.

I can only remember the jist of this discussion and not the details.  Hopefully @ikaneshiro and @bauerm97 can remember more of the ins and outs and fill in the particulars.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@gmkurtzer Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
