### ISSUE TITLE
RFE: Stage Caching for Multistage Builds

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#2808]
Cache each stage of a multistage build and reuse it if there are no changes to the `definition` of that stage. 

One way this can be implemented is by cleaning the `definition` of data unrelated to the build(e.g. comments) and storing a hash of the definition with the stage bundle in the cache. This will allow the build system to quickly identify if a stage can be reused from the cache. This will require the addition of a `--no-cache` option to force all stages of the build to be rebuilt.

**Comment by gdolle** [comment]
It may also be useful to precise the stage to be build from the command line.
```
singularity build --stage devel container.def
```
I think it'd be nice to add the possibility to store stage files in the host side via an option (in case cache is erased).
Something like
```sh
# Create files from stage devel and store output files in hello/ directory.
singularity build --export ./hello/ --stage devel container.def
# Use files in %files section if available in hello/ directory.
singularity build --import ./hello/ --stage final container.sif container.def
```
This may require to add a new section to specify what files are used in other stages, for instance
```
Stage: devel
%files export
     file1
     file2
```

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@ikaneshiro Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
