### ISSUE TITLE
Collect URLs under a single package

### ISSUE THREAD

**Issue by mem** [apptainer/singularity#2824]
There seem to be a growing number of URIs embedded in the code (https://singularity-hub.org, https://cloud.sylabs.io/, https://build.sylabs.io, ...). These should be either configuration (with defaults) or they should be collected under a single package to make it clear what our external dependencies are.

**Comment by mem** [comment]
This is still relevant.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@mem We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This old Singularity repo issue is not relevant and now closed. If its still an issue please open a new issue in Apptainer repo.
