### ISSUE TITLE
manifest error when pulling a docker image

### ISSUE THREAD

**Issue by LaHaine** [apptainer/singularity#2825]
## Version of Singularity:

3.1.0-107.gd291d85.el7

### Expected behavior

download this image like other images from docker hub

### Actual behavior
````
FATAL:   Unable to pull docker://netdisco/netdisco: conveyor failed to get: Error reading manifest latest in docker.io/netdisco/netdisco: manifest unknown: manifest unknown
````

### Steps to reproduce behavior
`singularity pull netdisco.sif docker://netdisco/netdisco`

**Comment by cclerget** [comment]
Hi @LaHaine looks like this image doesn't have latest tag, try with `docker://netdisco/netdisco:latest-do`

**Comment by LaHaine** [comment]
Indeed, could singularity detect this automatically?

**Comment by chrisdembia** [comment]
The error message could be clearer; something like "no matching tag"?

**Comment by scalavision** [comment]
And what if the docker image doesn't have a tag?

Like the `scratch` image for instance? :

* https://hub.docker.com/_/scratch?tab=tags

**Comment by mem** [comment]
Braindump: because of the way this is implemented, it's actually hard to modify the error (most of the interaction with the docker registry happens in external code; singularity's code just sets things up so that the external code can know what to fetch). It's worth nothing that it's _singularity_ that's adding the "latest" tag if nothing is specified. Here we are following docker's behavior:

```
$ docker pull netdisco/netdisco
Using default tag: latest
Error response from daemon: manifest for netdisco/netdisco:latest not found
```

the error is the same: the tag does not exist, yet the error is taking about a missing manifest. Note the message about using default tag "latest".

I do think the error is confusing, but that's true in general for all our errors.

Suggestions to improve the error message within those constraints are welcomed.

**Comment by hangzh-msft** [comment]
If your image does not have a tag named latest, docker pull will complain that it cannot find the manifest. For instance, if your myimage has 2 versions in the repositories, versions 1 and 2. You might be assuming that 2 is the automatic latest. But docker pull does not take that assumption. If you run command
` docker pull netdisco/netdisco:2`
It should work. 
Hope it helps.

**Comment by jvmops** [comment]
I just had this error. I misspelled image name at CI-CD script and I was pulling the image that did not exist.

**Comment by dagobit** [comment]
Just check if you have no typo and the image is named correctly

**Comment by v3ritas1989** [comment]
Go to docker hub and open the repo
 
https://hub.docker.com/r/username/repo

 open the tab tags, there you will see all available version tags. You can also copy the correct pull command from there

**Comment by AJFeng** [comment]
> Go to docker hub and open the repo
> 
> https://hub.docker.com/r/username/repo
> 
> open the tab tags, there you will see all available version tags. You can also copy the correct pull command from there

This works for me
