### ISSUE TITLE
Cache Docker images in a reasonable manner

### ISSUE THREAD

**Issue by bbockelm** [apptainer/singularity#283]
We really need a place to cache generated Docker image before the first person tries to utilize the Docker image URLs in a large workflow (and ends up pulling the same image 1000 times for 1000 jobs).

Here's what I'm thinking:
1.  Cache image `foo:bar` in `~/.singularity/docker_cache/foo:bar.img`.
2.  If image is greater than X hours old (perhaps 48 by default, configurable), then `singularity` will regenerate the image.
3.  If `singularity` decides to update the image, it takes a POSIX lock on the file.
4.  Once the lock is acquired, double-check the timestamp on the image file.
5.  If the timestamp is still out-of-date, then generate a new image to `foo:bar.img.tmpXXXXX` (a file made with `mkstemp`.  Once complete, rename to the permanent filename.

I think this can all go into the python code; for reference, here's an example I've done previously in using POSIX locks in python: https://github.com/opensciencegrid/gratia-probe/blob/master/common/gratia/common/GratiaWrapper.py#L69

Besides the normal `singularity` client, my hope would be then to integrate this into the SLURM plugin.  This way, the Docker file would be built at submit time client-side and all nodes in the job will already have the pre-made binary.

**Comment by vsoch** [comment]
@gmkurtzer how does this sound to you? We could have a global cache with subdirectories, one of them being Docker as @bbockelm has suggested! I could write the python code to handle the Docker cache, and then (other kinds) could be written to where appropriate!

A few things to talk about:
- if the user is generating a Singularity image via a Docker bootstrap (meaning some custom install or runscript) then running the command to produce an image..
  - 1. with the same name: would not overwrite even with changes if < 48 hours, which would be very confusing
  - 2. with a different name: would generate something new in the cache that might be exactly the same

so we have to decide what is the true "unique id" and how to make sure usage with cache does not mislead the user about the image being used.

What would be most appropriate I think is to support what we had chat about, some kind of singularity "overlay" or "import" so that whenever the Docker registry pulls layers, a base image is created (with the Docker layers, says user custom inputs) and then that image is used/bootstrapped from the cache. This means that the additional commands (runscript and installs) would never be cached, unless they are part of the original image being bootstrapped. Thoughts?

**Comment by vsoch** [comment]
And in the future when we have singularity hub, the additional commands (runscript and installs) would be cached in a .singularity/singularity_cache as they are pulled from singularity hub, thought of akin to Docker images.

**Comment by bbockelm** [comment]
I do want some level of caching (maybe X=1 hour instead of 48?): I want to allow for the case where 1,000 worker nodes launch simultaneously.

The problem with generating a unique ID is that all 1,000 hosts would need to be able to map the ID from the user-specified name simultaneously -- seems dicey.

I was thinking that we could do this narrowly for `~/.singularity/docker_cache`; once we are satisfied / learn all our mistakes, we could then apply them toward an improved `~/.singularity/singularity_cache`.

**Comment by flx42** [comment]
As the first step, I believe you can simply reuse the IDs of Docker layers and images.
You can have a single folder where you download all the compressed Docker layers. If a file already exists: don't download it again, it hasn't changed. No need to use timestamps, unless you want to implement a cleanup policy.
This will save you from downloading the same layers over and over again, but you still need to extract the archives. But since Docker images have IDs too, you can use the same strategy again. If you already have an image folder for this ID, don't download or extract anything.

```
~/.singularity/layers/<layer_id>.tar
~/.singularity/images/<image_id>/[rootfs]
```

For Docker images that are extended, it gets trickier, but maybe we should start from here?

**Comment by vsoch** [comment]
I'm down, and definitely could implement this easily (at least for Docker). @gmkurtzer any thoughts?

**Comment by gmkurtzer** [comment]
Heya guys. Sorry for the delay!

First off I want to mention that the idea of the runtime Docker support I initially considered to be specifically volatile. That is why it deletes it when the process completes. But... With that said... I like this model and it applies to all temporary caching of images. For example not only caching a Docker image, but also caching an image executed from an archive (e.g. tar.gz), or downloaded via http(s).

It seems to me that we need to support a generic image, container and file caching mechanism for containers with Docker being a primary use case. Everything that has been articulated above makes sense to me, I would just like to see it as a general (not Docker specific) implementation.

Thoughts?

**Comment by bbockelm** [comment]
@vsoch - there are some fixups needed for #314 (see #331), but I think I'm going to close this ticket since the basic idea is there.

**Comment by vsoch** [comment]
great! Yes, we still need to make sure two processes can't do things with the same file, and I think when @gmkurtzer gets back we should talk about the difference between the automatically set /tmp cache and the layers/images cache (they are different, but sometimes one may accidentally be used in place of the other)
