### ISSUE TITLE
plugin/hooks: custom URI handling

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2835]
Plugins should be able to introduce handlers for custom URI's not supported in singularity by default. There are several places this needs to be introduced:

- `singularity push`
- `singularity pull`
- `singularity run/shell/exec/instance start`
- `singularity build`
- Definition files [Might be tough with current handling, may be best for a second or third pass]

The example use case for this is to support `oras://` as a URI to enable pushing/pulling SIF artifacts to/from OCI container registries. See #2831

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@bauerm97 We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Migrated to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1160
