### ISSUE TITLE
`oci start` locks my Vagrant VM centos7 shell

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2845]
## Version of Singularity:

master, using https://github.com/sylabs/singularity/pull/2818 code to test PR

### Steps to reproduce behavior
Open a term
<pre>
$ vagrant ssh
$ cd /tmp
$ singularity pull docker://alpine
$ sudo singularity oci mount alpine_latest.sif /tmp/alpine_latest
$ sudo singularity oci create -b /tmp/alpine_latest oci_alpine
$ sudo singularity oci start oci_alpine

ssh session locks
</pre>

Open another term
<pre>
$ vagrant ssh
$ sudo singularity oci state oci_alpine
$ sudo singularity oci kill --force oci_alpine

previous term's ssh is now usable
</pre>

Note that my `oci mount` is in `/tmp` where I'm running. Not sure if that would be an issue. Perhaps I'm doing something else wrong?

**Comment by jscook2345** [comment]
I tried killing it with other signals and that did not appear to work.

**Comment by cclerget** [comment]
@jscook2345 This is the expected behaviour if you start in a terminal and `terminal: false` in `config.json`, because I/O streams file descriptors are passed as is to runtime when `terminal: false` and since runtime continuously read stdin for input, it screw up your current terminal. But `create/start/kill/delete` are not really intended to be run directly from terminal (except if you set `terminal: true`) or by user but rather from an application like singularity CRI.

**Comment by jscook2345** [comment]
Thanks @cclerget ! I figured it was something like that!
