### ISSUE TITLE
Invalid shub URI

### ISSUE THREAD

**Issue by mxmlnkn** [apptainer/singularity#2847]
## Version of Singularity:

3.1.0-1

### Expected behavior

I expected the [documented](https://www.sylabs.io/guides/3.0/user-guide/appendix.html#build-shub) behavior to work:

![Screenshot_2019-03-11_13-53-08](https://user-images.githubusercontent.com/6842824/54125338-03282a80-4405-11e9-81c5-56af297c85e5.png)

### Actual behavior

Got error message: `FATAL: Invalid shub URI`

### Steps to reproduce behavior

```
Bootstrap: shub
From: shub://singularity-hub.org/singularityhub/busybox
```
singularity build ...

Note that it works without the documented `shub://` prefix! So I guess the documentation should be changed from

`From: shub://<registry>/<username>/<container-name>:<tag>@digest`

to:

`From: [<registry>/]<username>/<collection-name>[:<tag>][@digest]`

Note also that the line directly below is bugged, i.e., it should be changed from:

`registry is optional and defaults to ``singularity-hub.org`

to:

`registry` is optional and defaults to `singularity-hub.org`

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@mxmlnkn We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
