### ISSUE TITLE
Refactor SyPGP Package

### ISSUE THREAD

**Issue by tri-adam** [apptainer/singularity#2848]
Once #2786 is complete, the code residing in `pkg/sypgp` should be moved to `internal`, since it mostly deals with UI and Singularity-specific internals.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@tri-adam We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by pedroalvesbatista** [comment]
I think we call this issue, since [PR 3922](https://github.com/hpcng/singularity/pull/3922) addresses it.
