### ISSUE TITLE
plugin/hooks: add appropriate hooks for exposing CVMFS transparently

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2864]
cc @DrDaveD 

As we discussed during the break at SUG19, we should investigate and understand how to add a set of plugin hooks which can give something like CVMFS the appropriate features to transparently and automatically mount itself into the container. Once we have an understanding of the specific hooks, I will update title and post to reference them

**Comment by DrDaveD** [comment]
Adding @sfiligoi

**Comment by bauerm97** [comment]
@DrDaveD Thank you!

**Comment by poquirion** [comment]
That would be great! We use https://github.com/cooperative-computing-lab/cctools to get cvmfs working and that can leads to problems when kernel calls are involved...

**Comment by DrDaveD** [comment]
Over the last few days I have learned that libfuse added an extremely helpful new relevant [feature](https://github.com/libfuse/libfuse/pull/291) not very long ago in release [3.3.0](https://github.com/libfuse/libfuse/releases/tag/fuse-3.3.0) that will make this quite easy for singularity to do along with an upgrade of [cvmfs to fuse3](https://sft.its.cern.ch/jira/browse/CVM-1710).   An option could be added to singularity, I suggest `--fusecmd 'command'`, that would open /dev/fuse, associate that file descriptor N with the mountpoint that is the last parameter to 'command', and replace the last parameter with /dev/fd/N.   Then it will execute the command unprivileged inside the container, and if the command starts a FUSE filesystem daemon based on libfuse >= 3.3.0, it will just work.  

As a shorthand, there could also be a new `--fusemount type:source:destination[:options]` that translates to `--fusecmd 'mount -t type -o options source destination`.   At that point, a cvmfs plugin could be added as simply another shorthand option that translates `--cvmfs repo1[:repo2:...:repoN]` to a series of `--fusemount cvmfs:repoN:/cvmfs/repoN` options.  On the other hand we could skip having a cvmfs plugin and just use --fusemount options.

As a proof of concept, I wrote [fuse-premount.c](https://github.com/sylabs/singularity/files/3035529/fuse-premount.c.txt) which does what I'd like singularity --fusecmd to do, and tested it in a fedora 29 container with fuse3-libs installed and sshfs with this [patch](https://github.com/libfuse/sshfs/pull/166).  It is able to do an sshfs fuse mount without using the setuid-root fusermount3 (I proved it with `rpm -e --nodeps fuse3`).  @jblomer has also tested fuse-premount with a development version of cvmfs based on fuse3-libs and shown that it works.

**Comment by DrDaveD** [comment]
When running non-setuid (for example on a RHEL 7.6 system that allows unprivileged namespaces but doesn't have cvmfs installed), if the fuse package is installed the --fusecmd option could instead invoke the setuid-root command fusermount to open the file descriptor and mount the generic fuse mountpoint.  This is slightly more complicated, but not very, as implemented in libfuse's [fuse_mount_fusermount()](https://github.com/libfuse/libfuse/blob/fuse_2_9_5/lib/mount.c#L345) and [receive_fd()](https://github.com/libfuse/libfuse/blob/fuse_2_9_5/lib/mount.c#L248).  They use the SCM_RIGHTS feature of unix domain sockets to return a file descriptor from fusermount, which can then be treated the same way as the file descriptor from /dev/fuse and passed through as /dev/fd/N.  

This doesn't fundamentally add additional capabilities over what a user could do without the option, since a user could do the fuse mount outside of the container and bind mount it into the container, but it's a very convenient interface for something like cvmfs because all the cvmfs implementation could be inside the container installed as normal with an rpm (for instance), and it can be mounted where it expects to be mounted at /cvmfs inside the container.

**Comment by DrDaveD** [comment]
[fuserpremount.c](https://github.com/sylabs/singularity/files/3040686/fuserpremount.c.txt) is a proof of that concept.
