### ISSUE TITLE
PGP Key Export Command

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2866]
Splitting #2516 into two issues as #2781 is only handling PGP Import functionality. Quoting from #2516:

Currently, the only way to get a public/private PGP key pair in Singularity is to use the `singularity keys newpair` command. While this works, it has some pretty major limitations:

* It doesn't allow folks to use their pre-existing PGP keys.
* It doesn't allow folks to move their PGP keys to another system.

_Technically_, this can be achieved with some hacking around with the `~/.singularity/sypgp/pgp-public` file. But this is terribly unfriendly.

I propose we create a couple of new commands:

* ~`singularity keys import` to import a key pair into Singularity~
* `singularity keys export` to export a key pair from Singularity

**Comment by jchavezlavalle** [comment]
On GPG there are 2 different commands for either exporting a private key and another command for exporting a public key:

for instance, for exporting a public key on gpg: (needs just `--export` command)
```
$ gpg --export  9B19CCFCA7B8DDE324E03753D144FCB921E59147 > /path/to/folder/key.asc
```
while on secret/ private keys: (uses the `--export-secret-key` command)
```
$ gpg --export-secret-key 9B19CCFCA7B8DDE324E03753D144FCB921E59147 > /path/to/folder/key.asc
```
(With 9B19CCFCA7B8DDE324E03753D144FCB921E59147 being the full fingerprint of course)

Since on Singularity we are just assuming a single command for exporting either public/private keys, I suggest the following syntax (feel free to comment if there's a better way to handle this):

For private keys:
```
$ singularity key export --private --fingerprint 9B19CCFCA7B8DDE324E03753D144FCB921E59147 --path /path/to/folder  
```
For public keys:
```
$ singularity key export --public --fingerprint 9B19CCFCA7B8DDE324E03753D144FCB921E59147 --path /path/to/folder
```

Please any ideas/suggestions on this are highly appreciated :) thanks!

**Comment by tri-adam** [comment]
As discussed in the meeting, how about this for private keys:

```
$ singularity key export --secret 9B19CCFCA7B8DDE324E03753D144FCB921E59147 /path/to/folder
```

For public:

```
$ singularity key export 9B19CCFCA7B8DDE324E03753D144FCB921E59147 /path/to/folder
```
