### ISSUE TITLE
plugin/example: --rdma flag to automatically expose Mellanox devices in container

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#2873]
As we discussed at SUG19, we can use the following Mellanox libraries to build a plugin to natively expose RDMA functionality in the container via a `--rdma` flag:

- https://github.com/Mellanox/k8s-rdma-sriov-dev-plugin.git
- https://github.com/Mellanox/rdmamap

@paravmellanox

**Comment by paravmellanox** [comment]
rdmamap.GetRdmaCharDevices() from https://github.com/Mellanox/rdmamap will give list of desired devices, to map to container.
Also, same device name can be used to setup rdma cgroup limits if needed available in OCI https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#rdma

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@bauerm97 We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Migrated to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1160
