### ISSUE TITLE
RFE: Singularity Build Time Secrets

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#2909]
Singularity should have a way to manage secrets so that they're available at build time but excluded from the final image. Specifically being able to manage deploy-keys easily and in a similar manner as other other workflows.

**Comment by b-hahn** [comment]
I'd be quite interested in this feature as well, has there been any progress by any chance?

**Comment by jsolbrig** [comment]
This would be fantastic if it can be done.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@ikaneshiro We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Copied to https://github.com/apptainer/apptainer/issues/792
