### ISSUE TITLE
`singularity` options `quiet` vs `silent`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2923]
## Version of Singularity:

3.1.0

To me, `silent` should suppress all output and `quiet` should suppress only errors. What do you think?

**Comment by GodloveD** [comment]
I agree.

**Comment by bauerm97** [comment]
I agree with this. Where are you seeing behavior that is different? Other than `singularity --silent/--quiet --help`, I think this is the case. Is that an incorrect assumption?

**Comment by mem** [comment]
--silent sets log level to -3 and --quiet sets log level to -1

level -3 logs fatal and error
level -1 logs fatal, error, warning and log.

Since the sylog API does not provide a way to log with level log, level -1 effectively means fatal, error and warning. There are places logging warnings, but not that many when compared to errors (the difference is a factor of 20).

I guess what you are saying is that --silent should log only fatal and --quiet should log only error, leaving warnings to --verbose (along with verbose messages).

That does not sound right.
