### ISSUE TITLE
refactor `singularity --help` options text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2926]
## Version of Singularity:

3.1.0

* `help for singularity`

change to: `prints the description and a list of available options and commands for singularity`

* `path to the file holding your sylabs authentication token`

change to: `Use the given file as your Sylabs authentication token`

* `version for singularity`

change to: `prints the version for Singularity`

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
