### ISSUE TITLE
Discuss: Container vs. Image

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2929]
## Version of Singularity:

3.1.0

The word `container` is used very often in the help documentation where the word `image` should really be used. Do we want to fix these individually or should we *only* call something an `image` when we absolutely must.

ex, `download a container from the container library` should probably be download an image from the image library`.

How do we want to settle on this usage?

**Comment by jscook2345** [comment]
I think I am guilty of this to! I'm not 100% certain where to use the terms myself. :)

**Comment by dtrudg** [comment]
I might go for `container image` here.... :thinking:

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
