### ISSUE TITLE
`singularity version` and `singularity --version` do not follow semver

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2937]
## Version of Singularity:

3.1.0

### Expected behavior

Version commands print a semantic version

### Actual behavior

$ singularity --version
singularity version 3.1-1.el6

$ singularity version
3.1-1.el6

**Comment by bauerm97** [comment]
```
mibauer@ubuntu:~/go/src/github.com/sylabs/singularity$ make -C builddir/ -j4
make: Entering directory '/home/mibauer/go/src/github.com/sylabs/singularity/builddir'
 GO clean -cache
 GO singularity
    [+] GO_TAGS "containers_image_openpgp apparmor selinux seccomp"
 GEN etc/bash_completion.d/singularity
 GEN singularity.conf from /usr/local/etc/singularity/singularity.conf
 GO cmd/starter/c/starter
make: Leaving directory '/home/mibauer/go/src/github.com/sylabs/singularity/builddir'
mibauer@ubuntu:~/go/src/github.com/sylabs/singularity$ sudo make -C builddir/ install
[sudo] password for mibauer: 
make: Entering directory '/home/mibauer/go/src/github.com/sylabs/singularity/builddir'
 INSTALL /usr/local/bin/singularity
 INSTALL /usr/local/etc/bash_completion.d/singularity
 INSTALL /usr/local/etc/singularity/singularity.conf
 INSTALL /usr/local/libexec/singularity/bin/starter
 INSTALL SUID /usr/local/libexec/singularity/bin/starter-suid
 DONE
make: Leaving directory '/home/mibauer/go/src/github.com/sylabs/singularity/builddir'
mibauer@ubuntu:~/go/src/github.com/sylabs/singularity$ singularity version 
3.1.0
```

Unable to reproduce on Ubuntu 18.04

**Comment by GodloveD** [comment]
This is what I'm currently getting with version (oh just look below):
```
$ singularity --version
singularity version 3.3.0-1

$ singularity version
3.3.0-1
```
So I'm thinking this is no longer an issue?

**Comment by jmstover** [comment]
This is technically correct. When you build from RPM, the spec file includes the line:

```
./mconfig -v %{version}-%{release}
```

`%{release}` is defined as:
```
Release: %{_rel}%{?dist}
```

For a packaged binary, the Release, and Dist are as much of the version as the Singularity version.

If I build from source, the version is just `3.3.0` ... But if I build a RPM, it's either `3.3.0-1` or `3.3.0-1.el6` ... depending on if the `%{dist}` macro is defined or not

**Comment by GodloveD** [comment]
So... don't change?  I'm happy to close (again) if others can live with this behavior.  😸

**Comment by GodloveD** [comment]
Looking over the semantic version spec, it seems like we may want to denote this [with a plus sign](https://semver.org/#spec-item-10)?  But it also seems like the `-1` (e.g. `3.3.0-1`) is not following semantic versioning.  Even though it's a totally common practice.  But maybe I'm just misreading or missing something.

**Comment by jmstover** [comment]
Reading over that thing... It looks like if you give a damn, then use the plus... So it would be like:
```
3.3.0+1.el6
````
Where `1` is the `_rel` value, and `el6` is the `dist` value. The `1.el6` would fit as a build identifier.

The only change needed to make that happen on the RPM side would be to change the `-v` value to `./mconfig` in the Spec file.

**Comment by GodloveD** [comment]
@jscook2345 ping-a-roo.  What say you?

**Comment by jscook2345** [comment]
I think we should follow the semver spec as closely as we can without breaking the ability to update RPMs by name. There are several versions of the spec, so perhaps how we do things is in one but not another spec.

**Comment by mem** [comment]
Two things here:

- 3.3.0-1 means "prerelease", so this would sort _before_ 3.3.0
- 3.3.0+1 means "metadata" and should not affect ordering

when building from a cloned repository, you get something like "3.3.0-151.abcdefg", so under semantic versioning this would be a prerelease of 3.3.0, so that has to change. Best option is likely "3.3.0+151.abcdefg".

when building from a release, you get "3.3.0", so that's fine.

The more problematic question is actually "3.3.1". Under semantic versioning those are backwards compatible bug fixes, where "bug fix" means "internal change fixing incorrect behavior". No new functionality of any kind.

Going from "3.3.0" to "3.4.0" means "new backwards compatible API" and "existing features marked as deprecated" (but not removed!).

The interesting question here is "what's singularity's API?" The CLI or the exported Go functions? We have clients for both.

**Comment by dtrudg** [comment]
This is okay IMHO - we want to show the package version etc, which may well not be semver compat. If there's an EPEL package we want to see it's version in error reports.

Also - at this point, Singularity does not follow semver semantics, we just have a version number that looks like semver.

Closing as it has been quiet since Sep 2019
