### ISSUE TITLE
--nv not working with --writable

### ISSUE THREAD

**Issue by matus-pikuliak** [apptainer/singularity#2944]
## Version of Singularity:

3.1.0-1

### Expected behavior
```
$ singularity shell --nv --writable tensorflow.sandbox
Singularity tensorflow.sandbox:~> nvidia-smi
```
I expect this to print `nvidia-smi` output.

### Actual behavior
```
$ singularity shell --nv --writable tensorflow.sandbox
WARNING: NVIDIA binaries may not be bound with --writable
Singularity tensorflow.sandbox:~> nvidia-smi
bash: nvidia-smi: command not found
```

### Steps to reproduce behavior

I installed 3.1.0 from GitHub release and built tensorflow docker image with:
```
singularity build --sandbox tensorflow.sandbox docker://tensorflow/tensorflow
```
Note that without the `--writable` flag it works fine. This problem might be related to #2088.

**Comment by GodloveD** [comment]
The libraries should still be bind mounted in.  Can you check?  It's just` nvidia-smi` and other binaries that are not bind mounted in with the `--writable` flag. 

The binaries are intentionally excluded with the `--writable` flag because of security considerations.  The reason is very complicated and I probably cannot explain it.  I defer to @cclerget.  But they are really just a convenience anyway because they do not have to strictly match the version of the installed kernel module and you can just install them into the container without breaking portability if you really need them.  

I'm going to close this because I'm pretty sure this is the expected and desired behavior, but we can re-open if I'm wrong.
