### ISSUE TITLE
Identify 'official' and 'default' containers in `singularity search`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2948]
## Version of Singularity:

3.0.1

When I search for lolcow, I get about 20 answers. I can't tell the difference except the username who created them.

If we could mark our 'official' or 'default' containers that would be great to help users who just want to `singularity search alpine ; singularity pull <result from search>`

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
