### ISSUE TITLE
`singularity search` should provide info about a specific container

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2949]
## Version of Singularity:

3.0.1

Lets say I found a container with `singularity search lolcow`.
<pre>
        library://ilumb/default/lolcow
                Tags: latest
</pre>

It would be good if I did `singularity search library://ilumb/default/lolcow:latest` to get any information on that container, including what the definition file used was, how to `pull` it, when it was updated, if it has vulnerabilities, etc.

More data is good.

**Comment by Flamefire** [comment]
Getting the definition file from a container without pulling it completely would be very useful!

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
