### ISSUE TITLE
Add an `--open` option to `singularity search`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2950]
## Version of Singularity:

3.0.1

Related to, or possibly alternative to: #2949 

Similar to how it would be good to get extra info by doing `singularity search <container in library>` instead of `singularity pull container`, perhaps we should have an option called `--open` that opens up the library page for that container in a browser?

`singularity search lolcow`
`singularity search --open library://ilumb/default/lolcow:latest`, opens your default browser to the Library page with that container. That could provide more data for the user who is still skeptical and provide an easy way to access our container library.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
