### ISSUE TITLE
apply-cgroups option not working on SLES 11 or RHEL 6.10

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2969]
## Version of Singularity:

3.1.0 release tarball
(running on SLES 11 and on RHEL 6.10)

### Expected behavior

The `apply-cgroups` option works as expected.  

### Actual behavior

The error is the same for both distros listed above.

```
$ sudo singularity shell --apply-cgroups cgroups.toml ubuntu.sif
FATAL:   container creation failed: Failed to apply cgroups ressources restriction: cgroups: cgroup mountpoint does not exist
```
Is this option even expected to work with these old distros?

**Comment by cclerget** [comment]
@GodloveD I believe both support cgroups but cgroups is not enabled by default and consequently mount points are not mounted, that's why Singularity cgroups complains about missing cgroup mountpoint. On CentOS 6 it can be tested with :

```
yum install libcgroup
service cgconfig start
```

Should mount all cgroups subsystems in `/cgroup`. Another note, all systemd based distribution have cgroups enabled by default.

**Comment by GodloveD** [comment]
Thank you for the clarification @cclerget.  This works on RHEL after starting the service.
