### ISSUE TITLE
refactor `singularity help help` text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2979]
## Version of Singularity:

3.1.0

* `Help about any command`

change to: `Display helpful information about singularity`

<pre>
Usage:
  singularity help [command] [flags]
</pre>

change to:

<pre>
Usage:
  singularity help [help options...] [command]
</pre>

<pre>
Description:Help provides help for any command in the application.
Simply type singularity help [path to command] for full details.
</pre>

change to

<pre>
Description:
  Display the help for a given command.

  If no commands are given, the help for `singularity` itself will be shown with a list of global options and commands.
</pre>

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
