### ISSUE TITLE
refactor `singularity help cache` text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3006]
## Version of Singularity:

3.1.0

<pre>
Description:
  Manage your local singularity cache. There are 3 types of cache; library, oci, and blob.
  You can list/clean using the spicific types.
</pre>

change to:

<pre>
Description:
  Manage items in the local Singularity image cache.

  There are several different types of items stored in the cache. These include:
    blob: who, what, when, where, why, how
    library: who, what, when, where, why, how
    oci: who, what, when, where, why, how

  The cache defaults to the directory "${HOME}/.singularity/cache"
</pre>

I use items generically. Perhaps it should be 'images', though I know we are storing docker layers, so that seems wrong.

The who/what/when/where/why should contain
* How do files get in that cache? What command/options creates them? What command/options use them? What type of files are they?

* There should be mention of environment variables that affect this. Maybe in the examples?

*
<pre>
Available Commands:
  clean       Clean you local Singularity cache
  list        List your local Singularity cache
</pre>

change to:

<pre>
Available Commands:
  clean  Remove items from the cache
  list      Show items in the cache
</pre>

We describe what the cache is above, we can just shorten it to 'the cache'.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
