### ISSUE TITLE
help command invalid-sub-command returns help for command with successful exit code

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3017]
## Version of Singularity:

3.0.1

<pre>
$ singularity help cache bob
Manage your local singularity cache

Usage:
  singularity cache <subcommand>

Description:
  Manage your local singularity cache. There are 3 types of cache; library, oci, and blob.
  You can list/clean using the spicific types.

Options:
  -h, --help   help for cache

Available Commands:
  clean       Clean your local Singularity cache
  list        List your local Singularity cache

Examples:
  All group commands have their own help output:

  $ singularity cache
  $ singularity cache --help

$ echo $?
0
</pre>

I would expect this to fail similar to `singularity help bob` with `Unknown help topic [bob]` and a -1 exit code.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
