### ISSUE TITLE
refactor singularity help cache clean text

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3019]
## Version of Singularity:

3.0.1

* `Clean your local Singularity cache`

changed to: `Remove items from the Singularity cache`

* Description

change to:
<pre>
Remove blob, library, and oci items from the cache. By default only the blob items will be removed from the cache unless the --all option is used.
</pre>

* `clean all cache (will overide all other options)`

change to: `Remove all items from the cache (overrides all other options)`

* `specify a container cache to clean (will clear all
                       cache with the same name)`

change to: `Remove all items from the cache associated with a named image`

Does that cover it all plus the warning?

* `clean cache type, choose between: library, oci, and
                       blob (default [blob])`

change to: `Remove specific items from the cache (Default: 'blob')`

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
