### ISSUE TITLE
Container execution while restricting direct access (i.e. copy of container img)

### ISSUE THREAD

**Issue by serious-steve** [apptainer/singularity#302]
Hi folks,

 I've been bringing this up in the google group but this might be the better place to discuss my feature request.

I'd like to contribute the following functionality "group containers" to singularity:

- "Group Containers" are meant to be provided to users for execution only by our admin team
- Container image files must not be readable/copyable (due to licensed SW)
- Desired functionality: singularity shell / singularity exec in ro-mode

Greg has already proposed a way to implement this here: 
https://groups.google.com/a/lbl.gov/d/msg/singularity/VLVnK04joEw/fzKIgV2eBgAJ

I implemented the functionality proposed by Greg:
- Try to read the container file as calling user
- On fail: check if the singularity/singularity.conf has set 'execute group containers' enabled. Default is off
- If disabled -> Fail
- Else: check if root owns the container image. If no -> Fail
- Else: Obtain all groups of the calling user. Compare whether the container file is in any of those.
- If no -> FAIL 
- Else: allow privileged fopen (readonly)

The SUID feature must be enabled for this to work.
I will issue a pull request and combine that with this issue somehow...

**Comment by serious-steve** [comment]
I've not written tests yet as first I'd like feedback on the code/the way I implemented this.
This is the link to the branch: https://github.com/c1t4r/singularity/tree/group_containers

**Comment by bauerm97** [comment]
So I've taken a look at your implementation and I think that for the most part the logic looks good. However, I'm curious about the reason why you decided to split the logic for this feature into two files. It looks like this feature is only going to be used when calling `rootfs_image_init`, therefore it might make more sense to move all the logic into `rootfs/image/image.c` for now.

The other thing is, right now when you use sudo singularity create to make an image, it has read permissions for all users and groups, even though it's owned by root. This means you're going to have to edit permissions on the images in order for them to cooperate with this feature anyway. My question is: would it be enough for you to simply `chmod 0750 container.img` and `chgrp containergroup container.img`? All users not in the group will fail to open the container for reading and error out, while users in the group will be able to open it for reading and will continue on as normal. See my testing below (note that I am a member of docker usergroup on my computer):

```
mibauer@depc403:~/devel_singularity/testgroup$ ls -l group*
-rwxr-x--- 1 root docker 805306399 Nov  9 12:16 group2.img
-rwxr-x--- 1 root root   805306399 Nov  9 12:16 group.img
mibauer@depc403:~/devel_singularity/testgroup$ singularity exec group.img /bin/bash
ERROR  : Could not open image (read only) group.img: Permission denied
ABORT  : Retval = 255
mibauer@depc403:~/devel_singularity/testgroup$ singularity shell group2.img
Singularity: Invoking an interactive shell within container...

Singularity.group2.img>
```

@c1t4r thoughts on this?

**Comment by bbockelm** [comment]
So the problem here is TOCTTU - time of check to time of use - attacks.  See the discussion about user bind mounts to get a hint of what might go wrong.

Basically, you need to do two things:
- check image is owned by a specific user/group.
- mount image.

However, you need to make sure the image you checked in the first step is the same as the one in the second step.

Your current pseudo-code doesn't seem to do this, meaning that someone could change a symlink after a filesystem check but before mount, allowing the mount of arbitrary images.

Is there a way to mount first, then check the image permission?  Can you somehow link the mounted image back to a certain file?

**Comment by bauerm97** [comment]
@bbockelm I think that all of this code isn't really necessary for this feature. Essentially, we already have this functionality in singularity since the fopen() call to open the image will handle the permission checking. I'll paste the testing that I wrote out in an earlier comment, this is compiled from the current master branch.

```
mibauer@depc403:~/devel_singularity/testgroup$ ls -l group*
-rwxr-x--- 1 root docker 805306399 Nov  9 12:16 group2.img
-rwxr-x--- 1 root root   805306399 Nov  9 12:16 group.img
mibauer@depc403:~/devel_singularity/testgroup$ singularity exec group.img /bin/bash
ERROR  : Could not open image (read only) group.img: Permission denied
ABORT  : Retval = 255
mibauer@depc403:~/devel_singularity/testgroup$ singularity shell group2.img
Singularity: Invoking an interactive shell within container...

Singularity.group2.img>
```

**Comment by serious-steve** [comment]
Hi Michael & Brian,

 thanks a lot for your feedback :)

The splitting into rootfs.c and image.c was due to rootfs.c already using the config parsing and I hesitated to introduce it in image.c as well. But your'e right it might me more reasonable and readable to put all code into image.c ...

@bauerm97 it does not work on my setup with singularity (2.2) - is the code enabling this relatively new?

> stefan@meltingpot ~ $ ls -lah vre
> -rwx--x--- 1 root adm 1,1G Oct 13 12:55 vre
> stefan@meltingpot ~ $ singularity shell vre
> ERROR  : Could not open image (read only) vre: Permission denied
> ABORT  : Retval = 255

Pretty sure I checked this and came up with my implementation because I couldn't make this work... :(

Update: from what I see in the diffs when comparing branches my deb should be build on current master...strange...

**Comment by bauerm97** [comment]
@c1t4r the code enabling this is inherit in how singularity works with .img files. If you notice the line in src/lib/rootfs/image/image.c: `if ( ( image_fp = fopen(source, "r") ) == NULL )` we open the file with `fopen(source, "r")`. This means we need `r` permissions on a file to open it, not just `x` permissions. The error in your test is thus in your file permissions. Try `chmod 0750 vre` or `chmod g+r vre` and you should now be able to use it as expected. Your permissions should look like this:

-rwx**r**-x--- 1 root adm 1,1G Oct 13 12:55 vre

as opposed to what you currently have:

-rwx**-**-x--- 1 root adm 1,1G Oct 13 12:55 vre

Your issue does highlight another issue however, and that is that we haven't documented anywhere (AFAIK) that this is a currently usable function. Maybe it would be helpful to document that the calling user will need read permissions on the image file in order to use it. This also means that if one of the users groups has the permission to read it they can also freely use the container. Thoughts on adding this to the documentation?

**Comment by serious-steve** [comment]
@bauerm97  suuure I've misread your file mask.
However, the idea was essentially to not grant any read permissions for users. Because then users of the group can copy and take the SW on their personal computers where we have licenses just for our HPC site.

@bbockelm thanks for pointing out this TOCTTU thingie... need to read more to understand that fully....

**Comment by bauerm97** [comment]
@c1t4r Ok, I see where you're coming from. However, I'm not sure if the functionality you're looking for is ever going to be safe to implement. Assuming we implement your code, what is stopping the user from doing a singularity exec container.img /bin/bash and just copying the contents of the image that way? Or doing the same and reading through the contents of the folder where the rootfs is located.

Would a better solution maybe be to just allow users to mount the location of said licensed software into any users image? I'm not sure of the specifics of how this licensed SW is set up, but I'm assuming you only have group `x` bit set and no read bits set anywhere. If you just bind mount the software into any container, the permissions on the licensed SW will never change, thus nobody will be granted any extra access to the software than the should be allowed. Does that work?

**Comment by serious-steve** [comment]
@bauerm97  I get your point as well. The user can basically dump the contents of the running container but as I understand he will be bound to standard POSIX ACLs. 
Meaning he wont be able to access certain files (e.g. binaries/libs we protect using setgid wrappers) and making their SW work again will be a PITA as compared to copying one single file which is hassle free and seduces to seed a working environment containing licensed SW.
As much as I like the idea of portability and BYOE for OS environments - we need to prove to our licencees that we undertake some efforts to prevent pirating from happening.
If there's an easier way to accomplish that and still being able to run proprietary singularity containers I am very glad to learn about it :)

As far as your proposal of the bind mounts is concerned... maybe this would be an option.
But in our wider context I'd prefer images containing all dependencies since we actually plan to migrate environments further into the cloud (e.g. OpenStack/Docker) and provide interactive subsequent use.

Ok...maybe time to brainstorm a bit more :D

**Comment by bauerm97** [comment]
@c1t4r Another thing you could potentially do is specify the path to your licensed SW in the config file. You specify `bind path = /path/to/SW/` and tell users if they want the SW available to simply make that directory available in the container. Then if they want to have the software available, it's able to be seen at /path/to/SW and they will still be bound to POSIX ACLs that are defined for the SW. I'm not sure if there's a better solution yet, and as @bbockelm mentioned, doing it this way and circumventing the ACLs is a bit dodgy.

**Comment by bbockelm** [comment]
@bauerm97 -

You're right - I forgot that loopback devices operate on file descriptors, not file names.  Been a long time since I've poked around that code.

However, the implementation in @c1t4r's branch still separates the permission check (on the filename - see https://github.com/c1t4r/singularity/commit/35b40715577d9173d59f5185a89a64c6a2825f86#diff-010219e86e1cd3f158f8c94481095f34R95) from the file descriptor.

The fix is simple though - switch from doing a `stat`-then-`open`, to a `open`-then-`fstat`.

Brian

**Comment by bauerm97** [comment]
@bbockelm So you think we would be safe to do this:

1) fopen image with escalated privileges
2) fstat the return fd from fopen
3) compare fstat group to calling userids groups
4) close file if check in 3 fails, otherwise continue as normal

**Comment by bbockelm** [comment]
I think (3) also needs to validate the `st_uid` field is 0 (i.e., the file is owned by root).

That said, I missed originally the proposal about the container being owned by one of the groups the user is a member of.  Why go this route as opposed to having a single `singularity` group - and check to see if the image is owned by that group and the root user?

**Comment by bauerm97** [comment]
You are correct with that, forgot to write that down.

@c1t4r Is interested in building licensed software into containers on his HPC, therefore he might have multiple groups (ie SW_1, SW_2) to allow only certain users to use each. This won't work with the `singularity` group as far as I can tell.

**Comment by bbockelm** [comment]
Gotcha.  A closely related use case would be to only allow sysadmin-prepared images (without adding every single user to a given group).

**Comment by serious-steve** [comment]
@bauerm97 Thanks for the clarification I couldn't have expressed it better myself :)

Thus I conclude the procedure should be like this:

1) fopen image with escalated privileges
2) fstat the returned fd from fopen
3) ensure fstat owner is root
4) compare fstat group to calling userids groups
5) close file if check in 3) or 4) fails otherwise continue as normal

Another related question of mine:
Is it save to omit the drop_privilege calls in case of ABORT?
I saw this in the existing code but rather ensured the dropping in all code pathways...

**Comment by bauerm97** [comment]
@c1t4r To touch on your question about ABORT and dropped privileges, I'm not entirely sure. @gmkurtzer do you have an answer for this?

To touch more on this topic in a wider sense, does it really make sense for us to have this be a config option? It would seem to make sense that if you have `x` permissions on an image, you should be able to execute the image. By leveraging the `r` permission (like we do now) it seems like we are following the letter of POSIX ACL compliance, but not necessarily the spirit (that a user with `x` permission should be able to execute the file). Either way, I think the logic you present is close to perfect, however I question why we require the file to be owned by root. I think as long as the calling user has `x` or `r` permission they should be allowed to use the image, regardless of who owns the image. This would make our solution a little more general.

1) fopen with privileges
2) check if calling user has `x` or `r` permission on file (either from groups, owner, or other)
3) if user has no permissions from 2) fail, otherwise continue as normal

We could also easily implement what @bbockelm suggested:

1) fopen with privileges
2) check value of `allowed container group`
3) if value not null, check if container is owned by value and break if not
4) repeat 2) & 3) until value is null
5) check if calling user has `x` or `r` permission on file (either from groups, owner, or other)
6) if user has no permissions from 5) fail, otherwise continue as normal

**Comment by serious-steve** [comment]
@bauerm97 & @bbockelm thanks for your proposals.

Both allow two my use cases:
The first one is allowing exclusive execution of containers for a particular group of users.
The second one is execution of containers which are side-licensed (number of users doesn't matter)
In either case containers should not be readable at a file system level.

What @bbockelm  suggested seems slightly more flexible.

But how should singularity behave in a whole?
IMO 'x' containers should allow `exec/run/shell` but not `export`
'r' containers should allow `export`, too

I found that my implementation does not allow `export` which surprises me.. 
It seems to fail where I check the root ownership ... need to check why is that so.

_Update:_ 
My bad, I overlooked that `singularity export` needs root by any means...

_Update 2:_

So please tell me if I should already start implementing the way @bbockelm proposed or we still specify this further. I'd rather avoid writing code in vain ;)

**Comment by bauerm97** [comment]
@c1t4r Just saw your updated post. I've had some free time at work today so I quickly tried my hand at implementing the logic I proposed in my past comment. I'm not sure that it's what we'll end up going with, but it was just in my mind and I wanted to put it into code ;) [Check it out here, please give me feedback on my implementation.](https://github.com/bauerm97/singularity/tree/group-containers) (Please note that I haven't tested it yet, so I'm not sure it will actually work right off the bat)

As for the broader discussion on how singularity should behave w.r.t. permissions on the image, I'm with you that `x` containers should allow the "execute" class of commands. However, I think that @gmkurtzer needs to be the one to make that decision. For the mean time my branch makes the assumption that if the user has either `r` or `x` permissions then they are allowed to use the file. It is a very easy change though to swap that to any set of permissions we want.

_EDIT: It compiles! Can't do more rigorous testing now because I have to go home._

_EDIT 2: Ok seriously last edit, but it works and the tests pass, however I haven't played around with image and permissions yet, the tests don't cover this_

**Comment by serious-steve** [comment]
@bauerm97 Great :+1:  I looked at your changes. A few comments:
- `src/util/file.c:` declaration of `int` within `for`-loop fails to build (C99 incompatible)
- `image.c:` now the image is fopened in privileged mode even if the user has read permission. Maybe doesn't matter because images require privileged mode but I recall some users requesting user space images as a feature...
- still need to understand how `has_perm` function works...

I will run/test the implementation now and update my post accordingly...

**Comment by bauerm97** [comment]
@c1t4r good catch on the int declaration, that wasn't meant to stay there, was just pseudo codeish.

Yes I opened the image always first, but then we check if the user has permissions using has_perm and fail out if they don't.

has_perm takes a stat strict and analyzes the st_mode bit field. When you do `chmod 0755` for instance, that gives rwxr-xr-x permissions on the file. Now the permission field looks like this `000111101101`. Now if we pass 5 into the has_perm, it will be implicitly converted to `101` and then will be bitwise anded to `111`, `101` and `101`. Check out usage of st_mode from fstat if you want to read more

**Comment by serious-steve** [comment]
@bauerm97  thanks I believe I understood the permission mask now ;)
Meanwhile I'm polishing the code in `image.c` plus adding some verb msgs - yours did not work on all cases when I tested it (no offence). 

One thing for clarification though: When the container file permissions have the first bit of the 12bit field (o+x) set we mean to allow access to every calling user regardless of the `container group` settings?
Plus doesn't strictly speaking `others` mean anyone but the group of the container? But that would be a bit strange isn't it?

_Update:_
OK I will continue on this on monday and post again ;) have a nice weekend...

**Comment by bauerm97** [comment]
@c1t4r Good catch on finding cases that didn't work. No offence taken, because the testing I performed consisted of not testing it. If you're doing work on my branch, please throw me a pull request with what you've added and I'll merge it into my branch so that we can eventually submit a unified PR to master here.

In regards to the point about o+x being set, I'm not really sure about how that should work. It would be pretty easy to only look at the `other` bit if the group of the file is not found in the groups of the user. But again, that would seem to be something that has a standard to comply with. I'm not sure if @gmkurtzer or @bbockelm will know the proper way to do things, but I guess we can figure that out with a few tests on other files pretty quickly.

My thinking with `container group` (needs a better name) was that any container in this group would be able to be run regardless of permissions by anyone. Further, **only** containers in this group will be able to be run on the system. This was feeding off of @bbockelm suggestion to have a group that containers need to be a part of to be run on the system.

**Comment by serious-steve** [comment]
> My thinking with container group (needs a better name) was that any container in this group would be able to be run regardless of permissions by anyone. Further, only containers in this group will be able to be run on the system. This was feeding off of @bbockelm suggestion to have a group that containers need to be a part of to be run on the system.

Yes, that was the other interpretation of your proposal that I had in mind. 
Do I get it right that the both features would operate exclusively i.e. either using a dedicated `container group` or using the proposed x/r permissions? Guess I'll recheck your original code I might understand it better after having that in mind ;) ...

If that's what you proposed: I think it would be better to have the possibility to use both features simultaneously, maybe at the cost of having another config flag to control the permission flag handling.

**Comment by bauerm97** [comment]
> If that's what you proposed: I think it would be better to have the possibility to use both features simultaneously, maybe at the cost of having another config flag to control the permission flag handling.

@c1t4r Not quite sure what you have in mind here. Do you mean that if `container group` is set and the container is that specified group, then it should still do the permission check? If that's what you mean it's actually very simple to implement. We can have it always work that way by simply changing this

```
if ( config_gname == NULL ) {
        if ( ( has_perm(4, image_stat) != 0 ) && ( has_perm(1, image_stat) != 0 ) ) {
          singularity_message(ERROR, "Calling user does not have proper permissions to access image, aborting...\n");
          ABORT(255);
        }
      }
```

to this:

```
        if ( ( has_perm(4, image_stat) != 0 ) && ( has_perm(1, image_stat) != 0 ) ) {
          singularity_message(ERROR, "Calling user does not have proper permissions to access image, aborting...\n");
          ABORT(255);
        }

```

Or if we want it as a config option we can change it instead to this (maybe the best option?):

```
if ( singularity_config_get_bool("proper_config_name") || config_gname == NULL ) {
        if ( ( has_perm(4, image_stat) != 0 ) && ( has_perm(1, image_stat) != 0 ) ) {
          singularity_message(ERROR, "Calling user does not have proper permissions to access image, aborting...\n");
          ABORT(255);
        }
      }
```

**Comment by serious-steve** [comment]
Hi @bauerm97 thanks for your patience...

I want to explain it better: 
When using the `group container` feat I had in mind that both admins and users can grant/deny access to a group of containers.
Admin: add/remove the container group line in singularity.conf 
Owners: can set group permissions on owned containers hereby allowing all users to execute them. Think of it as creating a public container but protect it until you are finished.
Owners will not need to be put into groups for this to work.
For executable containers owners will need to grant 'r' or 'x' AND admins need to enable the group.

I implemented it in the way I had in mind. I did some testing but not sure how to write proper tests for it (with this group stuff and modifying singularity.conf)
While you can check the code in general I'll test some more ;)

https://github.com/bauerm97/singularity/compare/master...c1t4r:group-containers-3rdtry?expand=1

thanks 

_Update:_ as to why I mentioned a second config option... @gmkurtzer wrote in the google group post that he would like the privileged fopen disabled by default so we'd have to control it via bool setting. My current code can be easily extended that way...

**Comment by bbockelm** [comment]
Ok, I took a stab at something similar to this and posted it as PR #350.

To avoid re-implementing POSIX permissions (which, FWIW, unexpectedly bypass ACLs and file attributes), I made it such that we dropped privileges to a specific user (user `singularity` and that user's primary GID).  Images have to be accessible by that user and owned by either the UID or pGID.

**Comment by serious-steve** [comment]
I build current master where https://github.com/singularityware/singularity/pull/350 got merged.
I found that the `protected mode` and `singularity user` option gives me the possibility to offer containers which are executable but not readable. Great! Thanks a lot :+1: 
Hence I'm closing this issue.
