### ISSUE TITLE
discuss: change options for singularity inspect

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3049]
## Version of Singularity:

3.1.0

`--helpfile` to `--help-script`
`--deffile` to `--definition`
`--runscript` to `--run-script`
`--test` to `--test-script`
`--environment` to `--environment-script`

add a `--all` option to show all

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. If singularity --version says singularity-ce, then please open a new issue at https://github.com/sylabs/singularity, otherwise please open a new issue at https://github.com/apptainer/apptainer.
