### ISSUE TITLE
add --force option to singularity push

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3064]
## Version of Singularity:

3.1.0

If you cannot overwrite an image by pushing, than it would be good to have a force option that will force the overwrite.

**Comment by dtrudg** [comment]
Forcing overwrite via push doesn't really fit in a model where things are stored by content-hash and then optionally tagged like our library. We never overwrite something with some different content, since we work from the hash. Tags are just moved to point to different images.

I'm not clear if this is relevant to `shub` or something else?
