### ISSUE TITLE
Verify should Fail if You Dont Have a Public Key

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#3113]
## Version of Singularity:

```
3.1.0-547.gcfdb43ad3.dirty
```

### Expected behavior

If you have a public key:

```
$ singularity verify alpine_latest.sif 
WARNING: sylabs-token files are deprecated. Use 'singularity remote' to manage remote endpoints and tokens.
Verifying image: alpine_latest.sif
INFO:    Container is signed
Data integrity checked, authentic and signed by:
	Sylabs Admin <support@sylabs.io>, KeyID EDECE4F3F38D871E
```

If you dont have that public key:

```
$ singularity verify alpine_latest.sif 
WARNING: sylabs-token files are deprecated. Use 'singularity remote' to manage remote endpoints and tokens.
Verifying image: alpine_latest.sif
Container is signed by a untrusted use: "Sylabs Admin <support@sylabs.io>, KeyID EDECE4F3F38D871E"

If you trust this user, you should pull the public key, run:

     singularity key pull EDECE4F3F38D871E
```

*Or something like that...*

### Actual behavior

```
$ singularity verify alpine_latest.sif 
WARNING: sylabs-token files are deprecated. Use 'singularity remote' to manage remote endpoints and tokens.
Verifying image: alpine_latest.sif
INFO:    Container is signed
Data integrity checked, authentic and signed by:
	Sylabs Admin <support@sylabs.io>, KeyID EDECE4F3F38D871E
```

### Steps to reproduce behavior

```
$ singularity verify alpine_latest.sif 
```

**Comment by tri-adam** [comment]
Here's what I was thinking @WestleyK :

```
$ singularity verify alpine_latest.sif 
WARNING: sylabs-token files are deprecated. Use 'singularity remote' to manage remote endpoints and tokens.
Verifying image: alpine_latest.sif
FATAL: This image is signed with key `EDECE4F3F38D871E`, but this key is not present in your local keyring.

To add this key to your local keyring, run:

    singularity key pull EDECE4F3F38D871E

Running this command instructs 'singularity' to trust this key in future. Run 'singularity key pull -h' for more information regarding the implications of this action.
```

**Comment by GodloveD** [comment]
This looks good to me.

**Comment by gmkurtzer** [comment]
The previous method was better. If someone does a `singularity verify` and the key is not local, it should check the `remote` to see if it is there, and if it is, it should be downloaded temporarily and used.

If to test/validate every key, one has to pull it to the local key ring first, then it makes it impossible to revoke the key from the server side. Only keys that should be implicitly and always trusted should be pulled, and that decision is not one to be made lightly, much less forced every time.

Please go back to prior behavior with showing the full key fingerprint on verify.

Thanks!

**Comment by GodloveD** [comment]
>Only keys that should be implicitly and always trusted should be pulled, and that decision is not one to be made lightly

I think this is actually the point.  Right now the entire verify process is being taken very lightly.  Singularity is completely happy to "verify" your container regardless of whether or not you have decided to explicitly trust the key being used.  In this model, whether or not you actually want to download the key and add it to your keyring becomes a secondary and almost trivial consideration.  A user may think that the only purpose for downloading and saving the key is the cache it and speed up the verification process next time.  Which seems totally unimportant since the verify command is so fast when using a key that is not saved.  

I understand your point that it is more "user friendly" to do this automatically.  But to a user who is not already well-versed in the PGP sign and verify workflow (aka me 😸 ) skipping the step of actually asking the user if they trust the key before verifying it for them will confuse the process.  

In any case this method still makes the user _aware_ of the keystore and alerts them that there is a process to obtaining a key and signaling to Singularity that we explicitly trust the key.

**Comment by tri-adam** [comment]
Alright. After many discussions, I'm going to try and summarize a proposed way forward. The default behaviour will be as @gmkurtzer suggests:

> If someone does a singularity verify and the key is not local, it should check the remote to see if it is there, and if it is, it should be downloaded temporarily and used.

The one addition to this will be that when a verification is done with a key that is not in the local keyring, an `INFO` message will be printed to clearly indicate that this is the case. Something like:

```
INFO: the key required to verify this image is not present in your local keyring, and thus not trusted
INFO: retrieving key with fingerprint 0xABCD to perform verification...
```

In order to address this:

> If to test/validate every key, one has to pull it to the local key ring first, then it makes it impossible to revoke the key from the server side.

Keys that are present in the local keyring will be checked for an update on each `verify` command.

Finally, there must be a flag to disable any automatic pulling of keys. In this case, the `verify` command will never interact with a Key Server, and will only use the local keyring. This is useful for a user who wishes to have `verify` pass only when a corresponding key is present in their local keyring (CI workflow, PKI infrastructure, etc.) It will also be useful for users who wish to prevent network activity for some reason (they are offline, or concerned about latency, etc.)
