### ISSUE TITLE
Singularity explicit umask (0022) denying write permission to Group owners of cache sub-folders.

### ISSUE THREAD

**Issue by manish-nuance** [apptainer/singularity#3164]
## Version of Singularity:

singularity version 3.1.0-161.ga00e557

### Expected behavior
Currently, singularity creates sub-folder under {SINGULARITY_CACHEDIR}/[shub/hash | net/hash] with explicite umask while downloading images. Which denies the write permission to Group Users.

Umask should be configurable.

ls -ld /local/cache/shub
drwxrwxr-x 3 users users 4096 Mar 28 06:53 /local/cache/shub

ls -ld /local/cache/shub/hash
drwxrwxr-x 3 users group_users 4096 Mar 28 06:53 /local/cache/shub/hash

### Actual behavior
Once sub-folders are created and when other member of same group_users tries to download container images it denied with permission issue..

singularity shell shub://sregistry/container
INFO:    Downloading shub image
FATAL:   open /local/cache/shub/hash/container.sif: permission denied

ls -ld /local/cache/shub
drwxr-xr-x 3 users group_users 4096 Mar 28 06:53 /local/cache/shub

ls -ld /local/cache/shub/hash
drwxr-xr-x 3 users group_users 4096 Mar 28 06:53 /local/cache/shub/hash

### Steps to reproduce behavior
export SINGULARITY_CACHEDIR=/local/cache
singularity shell shub://sregistry/container

**Comment by dtrudg** [comment]
The cache is not safe for use across multiple systems concurrently, this is due to both limitations of the current code, and locking / atomicity of operations that we'd need on filesystems and which is hard to guarantee in a generic HPC environment.

In addition, the cache can hold sensitive data specific to a user, so in 3.5.2 to prevent information leaks, permissions have been locked down further.

The preferred way to allow shared use of images would be to `singularity pull` commonly used images to a shared location, and run them from there. The SIF files are immutable and can be shared without any concurrency issue.
