### ISSUE TITLE
Building using --section flag does not allow spaces between sections

### ISSUE THREAD

**Issue by jchavezlavalle** [apptainer/singularity#3190]
## Version of Singularity:

`SingularityPRO version 3.1-2.el6`

### Actual behavior

When running: (notice the space after the comma between sections)

```
$ sudo singularity build --section help, runscript nginx.sif nginx.def
Usage:
  singularity [global options...] build [local options...] <IMAGE PATH> <BUILD SPEC>
```

### Expected behavior

```
$ sudo singularity build --section help, runscript nginx.sif nginx.def
INFO:    Starting build...
INFO:    Adding help info
INFO:    Creating SIF file...
INFO:    Build complete: nginx.sif
```

**Comment by GodloveD** [comment]
I don't think that is expected to work.  Should we expect this to work with quotation marks?

**Comment by ikaneshiro** [comment]
It takes a comma separated string like these:
`$ sudo singularity build --section help,runscript test.sif defs/sections.def`
`$ sudo singularity build --section "help,runscript" test.sif defs/sections.def`

Since this isn't a common syntax for a flag, as far as I know, the comment on the flag should include an example so it's clear.
