### ISSUE TITLE
key list output should start at one

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3199]
## Version of Singularity:

3.1-2

### Expected behavior

```
$ singularity keys list
Public key listing (/home/justin/.singularity/sypgp/pgp-public):

1) U: Sylabs Admin () <support@sylabs.io>
   C: 2018-11-01 18:20:02 -0400 EDT
   F: 8883491F4268F173C6E5DC49EDECE4F3F38D871E
   L: 4096
   --------
2) U: Justin Cook (test) <justin@sylabs.io>
   C: 2019-04-03 09:59:08 -0400 EDT
   F: DDAFFF474C3788E23986CB3F7922FD42029A6B27
   L: 4096
   --------
```

### Actual behavior

```
$ singularity keys list
Public key listing (/home/justin/.singularity/sypgp/pgp-public):

0) U: Sylabs Admin () <support@sylabs.io>
   C: 2018-11-01 18:20:02 -0400 EDT
   F: 8883491F4268F173C6E5DC49EDECE4F3F38D871E
   L: 4096
   --------
1) U: Justin Cook (test) <justin@sylabs.io>
   C: 2019-04-03 09:59:08 -0400 EDT
   F: DDAFFF474C3788E23986CB3F7922FD42029A6B27
   L: 4096
   --------
```

**Comment by WestleyK** [comment]
Honestly, I agree with this. A couple hundred years ago when I was first making newpair / signing containers, I was expecting the list to start from `1`. It confused me a bit when the list started at `0`.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Old Singularity repo issues are now closed. If this is critical please open issue under new Apptainer repo.
