### ISSUE TITLE
key list output should include note describing what each field is

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3200]
## Version of Singularity:

3.1.0-2

```
0) U: Sylabs Admin () <support@sylabs.io>
   C: 2018-11-01 18:20:02 -0400 EDT
   F: 8883491F4268F173C6E5DC49EDECE4F3F38D871E
   L: 4096
   --------
```

It would be good to let the user know what `U`, `C`, `F`, and `L` mean here. Not sure what the best way is.

**Comment by WestleyK** [comment]
Yeah, it will probably be a good idea to documented this in the help menu for `key list`. BTW, this is documented [here](https://www.sylabs.io/guides/3.1/user-guide/signNverify.html#generating-and-managing-pgp-keys).

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 @WestleyK Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Old Singularity repo issues are now closed. If this is critical please open an issues in the Apptainer repo.
