### ISSUE TITLE
Consider changing --fakeroot option name to --rootless

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#3210]
The community's name for what's being done in #2718 is rootless containers, so I suggest changing the name from --fakeroot to --rootless.

**Comment by cclerget** [comment]
I can't really agree with this change because strictly speaking rootless means for something not involving root or any privileges, and it's not the case with fakeroot as it requires a setuid installation, so people expecting true rootless feature like runc would be disappointed that installation doesn't allow them to specify `--disable-suid` in order to use this feature. IMO fakeroot is fine and describes pretty well what it does without bringing confusion.

**Comment by DrDaveD** [comment]
The existing implementations of rootless containers also requires a setuid root program, so I don't see the difference.  In both cases, the user that invokes it is not root.  I do agree that fakeroot is more descriptive, but it's going against established terminology.  Googling for "rootless container" gives information about this type of container, but "fakeroot container" gets you to the Debian build environment.

**Comment by cclerget** [comment]
I see your point but we already have somewhat rootless with `-u` flag. I think it could be even more confusing for new comer reading https://rootlesscontaine.rs/, and discover they can't setup network (fakeroot allow it thanks to setuid workflow), cgroup can't be used (hope to unlock this in a near future).

**Comment by DrDaveD** [comment]
ok, I close the issue.
