### ISSUE TITLE
Changes not reflected while running `exec` with `--apply-cgroups` flag

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3221]
## Version of Singularity:

3.1-2

### Expected behavior

The changes made to cgroups.toml are reflected when we are running `exec` with `--apply-cgroups` flag

### Actual behavior

Does not reflect the changes.

### Steps to reproduce behavior

$ cd /etc/singularity/cgroups
$ sudo nano cgroups.toml
Make the changes to a variable called swappiness 
$ sudo singularity exec --apply-cgroups /etc/singularity/cgroups/cgroups.toml lolcow.sif cowsay moo

$ cat /sys/fs/cgroup/memory/memory.swappiness

**Comment by cclerget** [comment]
@sushma-98 cgroup associated with container process is in `/sys/fs/cgroup/memory/singularity/<pid>/memory.swappiness`, replace pid by the process ID of container process.

**Comment by j-guitart** [comment]
I open again this issue because I think cgroups do not work properly with Singularity instances. I tried setting processor affinity, and only the initial process (sinit) gets the correct affinity. Processes created later with 'singularity exec' get the default affinity, they do not inherit sinit process affinity.

Version of Singularity
3.4.2

Steps to reproduce behavior

$ cd $HOME/singularity/etc/singularity/cgroups/
$ cat cgroups.toml
[cpu]
  cpus = "0-17,36-53"
  mems = "0"

$ singularity instance start --writable-tmpfs --apply-cgroups $HOME/singularity/etc/singularity/cgroups/cgroups.toml image.sif instance-1

$ singularity exec instance://instance-1 ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0 269476 13312 ?        Sl   16:04   0:00 sinit

$ singularity exec instance://instance-1 taskset -cp 1
pid 1's current affinity list: 0-17,36-53 ## affinity is correct

$ singularity exec instance://instance-1 /usr/sbin/sshd

$ singularity exec instance://instance-1 ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0 269476 13312 ?        Sl   16:04   0:00 sinit
root       355  0.0  0.0  69940  1204 ?        Ss   16:29   0:00 /usr/sbin/sshd

$ singularity exec instance://instance-1 taskset -cp 355
pid 355's current affinity list: 0-71 ## this is the default affinity, not the affinity in the cgroups file

The same happens even if new process is started by running:
$ singularity exec --apply-cgroups $HOME/singularity/etc/singularity/cgroups/cgroups.toml instance://instance-1 /usr/sbin/sshd
