### ISSUE TITLE
Add inherit keyword to bootstrap definition

### ISSUE THREAD

**Issue by ch741** [apptainer/singularity#323]
I've been implementing this feature which is similar to a C #include but with some added processing/checking in case of incompatible bootstrap definitions. It takes the Inherited definition and inserts it in place of the inherit line. This is done recursively and it checks whether the definition has already been included previously to avoid going into an infinite loop. Also everything is done in temporary definitions which helps with debugging.

After it's done inserting definitions it checks for the keywords BootStrap, OSVersion and if multiple exist but differ, ie. apt and yum, it exits with an error. If they all match it deletes all apart from the first occurrences. For the MirrorURL and UpdateURL keywords it's the same except there's no check if they differ. The package Include keywords are read and all packages are merged into a single Include.

The various sections are in the order of the inherits and are left unchanged apart from the removal of comment lines. Currently singularity processes only one section so this was modified to allow having multiple %runtime, %posts etc. Here's a short example to better explain:

``` bash
#inherit.def
Inherit: scientific.def
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

#UpdateURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/updates/$basearch/

%runscript
    echo "This is what happens when you run the container with an inherit command..."

%post
    echo "This container inherits from another container"
    yum -y install bash-completion 
```

``` bash
# scientific.def
BootStrap: yum
OSVersion: 7
MirrorURL: http://ftp.scientificlinux.org/linux/scientific/%{OSVERSION}x/$basearch/os/
Include: yum

%runscript
    echo "This is what happens when you run the container..."


%post
    echo "Hello from inside the container"
    yum -y install vim-minimal
``` 

The resulting inherit.def.tmp would be:

``` bash
BootStrap: yum
OSVersion: 7
MirrorURL: http://ftp.scientificlinux.org/linux/scientific/%{OSVERSION}x/$basearch/os/
Include: vi yum 
%runscript
    echo "This is what happens when you run the container..."
%post
    echo "Hello from inside the container"
    yum -y install vim-minimal




%runscript
    echo "This is what happens when you run the container with an inherit command..."
%post
    echo "This container inherits from another container"
    yum -y install bash-completion
```

As @vsoch pointed out clarification is needed for how to allow for multiple or optional %runscript sections. Like in a case when one definition starts a service in the %runscript. I thought of adding an optional parameter to the inherit keyword such as:

``` 
Inherit: centos.def [on|off]
```

With multiple %runscripts there's also the issue with passing arguments to the runscript and how that would be handled. If the above is expanded then anything after on|off could be parsed as arguments to the runscript:

``` 
Inherit: centos.def on|off arg1 arg2 ....
```

Does that make sense or would there be a better way? The repository is [here](https://github.com/ch741/singularity/tree/inherit).

**Comment by vsoch** [comment]
This is a great idea! When we move from a standard definition into something like a docker bootstrap, the include gets a bit fuzzier, and we need to make sure that we have it well defined across all these types. For example, what is happening on the back end with a Docker include? Does that mean pulling layers from multiple images, and then selecting CMD/ENTRYPOINT based on the runscript preferences?

The reason I bring this up is because the more important use case - bootstrapping multiple singularity images (for example from singularity hub) needs to have this logic defined. In my mind, the first thing that we need to know is getting to the bottom of how we pull the images. Are they in layers? How are the layers defined? I would think that those layer things (somehow) map nicely onto this idea of includes. For example, if there is some include that would be a subset of software, that logically would be some layers (.tar.gz) that you dump into the image to add that software. So TLDR: this is a great idea and let's keep moving forward, but first I think we should figure out this simpler core functionality to guide our development of this feature that uses it. Thoughts?

**Comment by gmkurtzer** [comment]
I just committed a fix to get-section.c which will parse multiple sections in a single file, thus making that runscript above parseable. I'll check on this shortly!

Thanks!

**Comment by GodloveD** [comment]
This was/is a great idea but it has gotten quite stale.  I'm actually not sure if it is still all that relevant given the multi-stage build stuff and the work that has since been done to build from existing images on disk and whatnot.  I'm going to close but anyone feel free to re-open (or better submit a PR!) if there is still interest in supporting this feature.
