### ISSUE TITLE
Define reference performance benchmarking test

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#3284]
As suggested by @tri-adam in a meeting, let's brainstorm and define a reference performance benchmarking test. This will allow us to understand how the performance of Singularity is changing as we iterate over versions and potentially across different hardware/software.

An example suggestion by @tri-adam for what we _could_ do is create some well-defined standard SIF image which we average the execution time of a `singularity exec [...]` across 1000 runs.

**Comment by ArangoGutierrez** [comment]
+1

**Comment by jscook2345** [comment]
This should probably be kicked off by CI.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@bauerm97 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
