### ISSUE TITLE
Improve test coverage of internal/app

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3315]
## Version of Singularity:

Improve test coverage of internal/app.

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
?   	github.com/sylabs/singularity/internal/app/starter	[no test files]
total:	(statements)	0.0%
`

### Steps to reproduce behavior

Write here.

**Comment by gvallee** [comment]
Need to improve coverage for both `internal/app/singularity` and `internal/app/starter`

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@gvallee Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
