### ISSUE TITLE
RFE: Singularity cp command

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#3391]
Allows you to copy files between the container and host. Currently the only way to transfer files is to bind in a writable directory. This will need further investigation and potentially additional features added to singularity images to give containers a writable component in their SIFs in order to facilitate this.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@ikaneshiro Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Copied to Apptainer https://github.com/apptainer/apptainer/issues/790
