### ISSUE TITLE
all calls to exec.Command should go through the cmd package

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3441]
We have a lot of calls to `exec.Command` that would be better done with a single wrapper around that functionality. A single location that calls exec.Command could help increase both traceability and debugging.

I would like to suggest the `cmd` package I added in my `help test` PR.

**Comment by mem** [comment]
This should  also deal with the code duplication around handling exit failures. A basic function to wrap exec.Command, and then another wrapper around that with zero/non-zero exit codes. The second wrapper should take a testing.T argument to log / report failures. It should log both the command that ran and its output.

**Comment by jscook2345** [comment]
@mem implemented a command tool at `internal/pkg/test/exec/exec.go`. Let's start by replacing the default library calls of `exec.Command` with our own helper there. Once we've done that we can improve the helper's handling of failures.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
