### ISSUE TITLE
add option to admin config to disallow option --allow-unsigned

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3442]
Per @mem 

```
That's also important: it should be possible to specify --allow-unauthenticated=false in the global configuration file without possibility to override.
```

**Comment by dtrudg** [comment]
Not convinced this is useful as there are so many ways around it due to the ability to move SIF files around easily, install a user-owned non-setuid singualrity etc. In discussions around signing and ECL over the past year it has always come to the conclusion that control at the point of consumption, i.e. ECL enforcement is best.
