### ISSUE TITLE
No verbose output when compiling a plug-in

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3450]
## Version of Singularity:

3.2.0rc2

```
[vagrant@localhost singularity]$ singularity --verbose plugin compile examples/plugins/test-plugin
[vagrant@localhost singularity]$ singularity --debug plugin compile examples/plugins/test-plugin
DEBUG   [U=1000,P=9132]    func53()                      sourceDir: /home/vagrant/singularity/examples/plugins/test-plugin; sifPath: /home/vagrant/singularity/examples/plugins/test-plugin/test-plugin.sif
DEBUG   [U=1000,P=9132]    buildPlugin()                 Runnig: /usr/bin/go build -o /home/vagrant/singularity/examples/plugins/test-plugin/plugin.so -buildmode=plugin -mod=vendor -tags containers_image_openpgp sylog apparmor selinux seccomp -gcflags=all=-trimpath=/home/vagrant/singularity -asmflags=all=-trimpath=/home/vagrant/singularity /home/vagrant/singularity/examples/plugins/test-plugin
```

I expected something similar to the debug output for the verbose output of the command. Since the command outputs nothing by default some verbose output may be nice.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Migrated to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1160
