### ISSUE TITLE
improve error when getting remote status of a URL that does not exist

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3458]
## Version of Singularity:

3.2.0rc2

I think the following error can be improved when using a URL that does not exist.

```
$ singularity remote list
NAME         URI              GLOBAL
SylabsCloud  cloud.sylabs.io  YES
bob          bob.sylabs.io    NO

$ singularity remote status bob
FATAL:   while getting asset configuration: error making request to server:
        Get https://bob.sylabs.io/assets/config/config.prod.json: dial tcp: lookup bob.sylabs.io on 10.0.2.3:53: no such host
```

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. If singularity --version says singularity-ce, then please open a new issue at https://github.com/sylabs/singularity, otherwise please open a new issue at https://github.com/apptainer/apptainer.
