### ISSUE TITLE
Documentation of -S and -W are meaningless

### ISSUE THREAD

**Issue by EvanTheB** [apptainer/singularity#3467]
> -S, --scratch strings        include a scratch directory within the container that is linked to a temporary dir (use -W to force location)
> -W, --workdir string         working directory to be used for /tmp, /var/tmp and $HOME (if -c/--contain was also used)

I can only find the above description of these settings. (man page, --help, and readthedocs, https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_run.html#singularity-run).

What is a "scratch directory"?
What is a "temporary dir"?
How can one 'working directory' be used for all of "/tmp, /var/tmp and $HOME"?

What does -S do without -W?
What does -W do without -c?

**Comment by al3x609** [comment]
e.g /scratch mount directory option is made for cluster environments where  /scratch is mount point  for the nfs  with the same name  for big storage devices or infiniband networks.
- working directory is about of change the default behavior at the moment of mount directories from host OS.  this replace the standard mount points for a preferred temporal directory, this can help to keep isolate environment inside the containers.
 these options exist because the applications need write some "temporal"  files to disk and if you need keep this file after "exit" of the container.

- -c option is a shortcut for isolate the container and mount only the minimal requirements. 
`use minimal /dev and empty other directories (e.g. /tmp and $HOME) instead of sharing filesystems from your host` 

the above is only a little interpretation from a singularity user, 
I appreciate opinions from developers.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@EvanTheB Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Old Singularity repo issues are now closed. If this is still critical please open a new issue in Apptainer repo.
