### ISSUE TITLE
automate the generation of help files for testing singularity help commands

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3476]
We need to automate the generation of help files for testing singularity help commands. This can be done using the `gotest.tools/golden` package, but will require a little experimentation first.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
