### ISSUE TITLE
create `oci list` command

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3494]
It would be nice to have the state of all `oci` containers without having to know their name.  This is becoming evident during testing of `oci` as its common to forget to `kill` / `delete` an `oci` container.

**Comment by jscook2345** [comment]
I've seen a few requests for this now and it would likely make testing a bit easier. What do you think @cclerget ?

**Comment by cclerget** [comment]
@jscook2345 Not a big deal, will put that in the todo list.

**Comment by dtrudg** [comment]
This is related to https://github.com/sylabs/singularity/issues/3099 - I think we need one or the other. Closing #3099 and keeping this open for now.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Captured in the new Apptainer repo https://github.com/apptainer/apptainer/issues/1159
