### ISSUE TITLE
oci exec should fail when the namespace cannot be joined

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3496]
This was originally found by @sushma-98 and I'm verifying it is an issue today.

In this case, the container c6 is a centos6 container and I'm running on a SLES11SP4 VM.

```
$ sudo singularity oci exec c6 cat /etc/centos-release
WARNING: seccomp requested but not enabled
/bin/cat: /etc/centos-release: No such file or directory

$ sudo singularity oci exec c6 cat /etc/os-release
WARNING: seccomp requested but not enabled
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
```

Instead of doing an `exec` there should be a failure here instead.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Captured in the new Apptainer repo https://github.com/apptainer/apptainer/issues/1159
