### ISSUE TITLE
Clarify the semantics behind the image cache

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3525]
## Version of Singularity:

Master

### Expected behavior

Protect from deleting user's data when cleaning the cache and the location of the cache is specified by the user. Right now, everything in the location is deleted. For instance, if the user sets the environment variable to point at the home directory, everything in the home directory is lost. Furthermore, even after reading the documentation, I was expecting that Singularity will create a directory in the location that I specify through the environment variable and Singularity to handle this directory.

### Actual behavior

The user can specify right now an environment variable to change the location of the image cache. The current implementation had a problem: when the cache is cleaned, everything in the cache (files and directories) are simply deleted, including the user's data.

### Steps to reproduce behavior

Set the environment variable to your home; clean your cache; the content of your entire home directory is gone.

**Comment by gvallee** [comment]
To address the problem I did an implementation where I separate the base directory, i.e., the location specified by the users and if not specified, `$HOME/.singularity` is used and within the base directory, a root directory where the cache is. The cache would therefore be managed by Singularity with the intent of not being exposed to the user. By doing so, we can ensure that when cleaning the cache, the content of the root can safely be deleted.
To summarize:
- Have a `basedir` which is the base directory of the cache and exposed to users. If the users specifies a base directory through the environment variable, the `basedir` of the cache is what is specified by the user. We never delete the content of `basedir` since exposed to the user and therefore we assume it may contain user's data.
- Have a `root` directory within `basedir`, which is not exposed to the user and can therefore be safely deleted by Singularity.

This approach had push-back, especially about the semantic of the `root`; it was unclear why it is necessary. This ticket also aims at clearly figure out why and what would be the best approach.

Ultimately the questions are:
- Do we want to protect ourselves and ensure that will not delete user's data?
  - If so, is using a `root` directory a good approach?
  - If not, I think we need to really about the documentation around the environment variable. Do we agree that clear documentation is a must?

**Comment by gvallee** [comment]
Another option would be to:
- not have a root directory
- when cleaning the cache, we never delete everything in the cache, instead we iterate over the sub-caches (e.g., library, oci, shub) and only delete everything in these sub-caches.

I personally have a slight preference for the first option since it keeps all the sub-caches in a directory we create (`based` vs. `root`), which keeps everything clean if users misunderstand the semantic of the environment variable to specify a custom location for the cache. For example, if the user decides to use the home directory for the cache, a `root` directory will be created in the home directory and everything kept there, instead of having a bunch of sub-directories which names do not include singularity appears in the home directory, potentially challenging the user in understanding what these new directories are about.

**Comment by gvallee** [comment]
Comment the reasoning why we can change the location of the cache; basically be able to choose the storage location for the cache as well as sharing caches.

**Comment by gvallee** [comment]
After the meeting, I write a description of what we agreed on and make sure that @mem and @gvallee agree about the write-up and if so, revisit the implementation to match it. For now, when a user specifies a location for the cache, we will create a `cache` sub-directory.

**Comment by gvallee** [comment]
Why do we need an environment variable to let users set their own cache location?
- users may need to set their cache in a volume with a lot of free space since caches can quickly become huge,
- users may want to share their cache with others,
- users may want to have different caches for different projects.

For similar reasons, it is beneficial to keep the cache location separate from the rest of user-specific Singularity files. In other words, `$HOME/.singularity` usually contains `cache`, `instances` and `sypgp`. It is beneficial to manipulate the `cache` directory separately.

We two options:
1/ Use the concept of base directory and cache root directory. If the user uses the environment variable to specify the cache's location, the base directory will be the directory specified through the environment variable and the cache root, a `cache` directory in the base directory. If the users does not set the environment variable, the base directory is `$HOME/.singularity`. When cleaning the cache, the cache root, not the base directory, is wiped out.
2/ Use a single directory model that can be specified by the user through the environment variable. If the environment variable is not set, we default to `$HOME/.singularity/cache`. We never delete the entire content of the cache directory, instead we only delete the directories of the sub-caches (e.g., library, oci, shut).

**Comment by mem** [comment]
With the goal of simplifying both the documentation and the implementation, can we drop the "root directory" and keep only a "cache base" directory?

`SINGULARITY_CACHEDIR` specifies the "singularity cache base directory", with a default of "${SINGULARITY_USER_DIR}" (there's no SINGULARITY_USER_DIR in the current implmementation), which in turn defaults to "${HOME}/.singularity". It's confusing to call this variable `SINGULARITY_CACHEDIR` and define it as "cache base", but in this case backwards compatibility has to be taken into account.

The "cache directory" is created in "${SINGULARITY_CACHEDIR}/cache" and this is the only directory that the cache code interacts with. Code needs to acknowledge the suboptimal name "SINGULARITY_CACHEDIR" and explicitly state that the name exists for backwards compatibility and that it refers to the directory that will contain the actual cache directory.

In short:

* `SINGULARITY_USER_DIR` specifies the location for singularity's user configuration and data. It defaults to `${HOME}/.singularity`
* `SINGULARITY_CACHEDIR` specifies the _base directory_ for the singularity cache. It defaults to `${SINGULARITY_USER_DIR}`.
* The singularity cache directory is not user-configurable and it's always set to `${SINGULARITY_CACHEDIR}/cache`.

The reason for wanting this sort of separation is because XDG specifies the existence of a cache directory at `$HOME/.cache`, and users might want to point SINGULARITY_CACHEDIR to `${XDG_CACHE_HOME}/singularity` (and `SINGULARITY_USER_DIR` to `${XDG_CONFIG_HOME}/singularity`). At some point in the future we might want to support that structure ourselves.

Purely for the record: the Unix-way to solve the problem that `SINGULARITY_CACHEDIR` is solving is by creating a symlink from `${SINGULARITY_USER_DIR}/cache` to the actual location where the user wants to have the cache directory (e.g. `/local/${USER}/singularity/cache`).

**Comment by gvallee** [comment]
I agree with that terminology and these semantics. It will be very clear and protect users from shooting themselves in the foot. I will prepare a PR only for this and make sure I capture everything.

As a note, as I agree that the UNIX-way to solve the problem is to use symlinks, I have to admit that in the context of very large HPC system, the use of environment variables to select the location of a directory meant to store a lot of data (and potentially share it) is normal practice.

**Comment by gvallee** [comment]
Note: a very good point was raised during a discussion with @mem and @ikaneshiro that we need to address in the context of this issue: https://github.com/sylabs/singularity/pull/3682#discussion_r290849226
