### ISSUE TITLE
Include CI Tests For Latest Go Version

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#3529]
Have a CI job that runs against the newest version of go available will be beneficial as it gives us a chance to catch any potential future errors that we could encounter by upgrading officially to a new version of go. This will most likely be apparent with the new features related to go modules over the next couple releases.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@ikaneshiro Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Copied into the new Apptainer repo issue https://github.com/apptainer/apptainer/issues/1156
