### ISSUE TITLE
push should tell what remote endpoint is being used

### ISSUE THREAD

**Issue by rherban** [apptainer/singularity#3540]
## Version of Singularity:

3.2rc1

### Expected behavior
We should print the remote endpoint name when doing remote actions.  In this case, I'm not sure what the default was, but I wasn't able to login to it (or the token was expired).  After creating a new token, doing a `remote login`, then `remote use SylabsCloud`, I was finally able to upload.

[rherban@test]:~$ singularity push -U simple.sif library://rherban/default/simple.sif
WARNING: Skipping container verifying
Pushing simple.sif to SylabsCloud as rherban
FATAL:   creation did not succeed: 401
	Unauthorized

### Actual behavior

[rherban@test]:~$ singularity push -U simple.sif library://rherban/default/simple.sif
WARNING: Skipping container verifying
FATAL:   creation did not succeed: 401
	Unauthorized

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
