### ISSUE TITLE
ABORT: Failed creating template password file

### ISSUE THREAD

**Issue by shwina** [apptainer/singularity#36]
I created a `demo.img` on a CentOS host, and I am trying to run `singularity shell demo.img` on an Arch machine. I am met with the following error:

ERROR: Template passwd not found: /tmp/.singularity-1000.2049.19923486/mnt//etc/passwd
ABORT: Failed creating template password file

Any suggestions as to what this might be about?

Edit: `demo.img` is created using `centos.def` found in the examples directory. I am using the master branch

**Comment by gmkurtzer** [comment]
Hi,

I have not tested with Arch Linux yet, but it sounds like /etc/passed doesn't exist in the image. Has it been properly bootstrapped?

Try to do a:

$ sudo singularity mount demo.img /mnt 

And see if the image has been properly bootstrapped. Additionally I will use this issue as the base for doing proper image sanity and print warnings instead of errors. 

Thanks!

**Comment by gmkurtzer** [comment]
Was the problem that the image wasn't bootstrapped?

**Comment by gmkurtzer** [comment]
BTW, I just refactored some code to make the error messages more clear.

**Comment by shwina** [comment]
I'm not entirely sure. When I mounted the `.img`, I was able to find `/etc/passwd`. I suspect my problem was that I needed to install as root (which I wasn't doing).

**Comment by gmkurtzer** [comment]
Ahh ok. Hopefully my code refacorization will catch this condition properly. Just to confirm, is it working properly now?

**Comment by shwina** [comment]
Yes, I'm able to `singularity shell` into a container on Arch :-)

**Comment by gmkurtzer** [comment]
Fantastic. Thank you for the confirmation!
