### ISSUE TITLE
Make no setuid the default on RHEL8 and other OSes with kernel >= 4.18

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#3612]
With the advent of RHEL8 and other operating system distributions that require a linux kernel >= 4.18, unprivileged FUSE mounts inside of namespaces are allowed.  With that feature, singularity should be able to run completely unprivileged by default, and I suggest that it do so for the sake of reducing customer risk.  It would require implementing the use of fuse-overlayfs and squashfuse.

**Comment by jscook2345** [comment]
@bauerm97 ping!

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by DrDaveD** [comment]
I think this is a high priority feature request, strategic for the future of singularity.

**Comment by pedroalvesbatista** [comment]
@DrDaveD We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by ngam** [comment]
> @DrDaveD We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

Any update on this? @DrDaveD @pedroalvesbatista

**Comment by DrDaveD** [comment]
The fuse-overlayfs and squashfuse work is on the roadmap, but still to be done.

**Comment by DrDaveD** [comment]
Continued in apptainer/apptainer#416
