### ISSUE TITLE
[docker] Export environment of imported images

### ISSUE THREAD

**Issue by flx42** [apptainer/singularity#364]
When importing a Docker image, we use the environment of the Docker container. This would be useful when containers install binaries/libraries at non-standard paths.
We probably need to write the output of `get_config(manifest, "Env")` to a file in the rootfs. Maybe `/environment` or a different file.

**Comment by chrisgorgo** [comment]
[docker2singularity](https://github.com/singularityware/docker2singularity) grabs the environment variables from the Docker image (for example set by `ENV` statements in Dockerfile) and exports them in the converted Singularity image. See: https://github.com/singularityware/docker2singularity/blob/master/docker2singularity.sh#L128

This might not be the case if you use singularity directly to boostrap images from docker hub (instead of using docker2singularity).

**Comment by flx42** [comment]
I see, it should be only a few lines of python code to get the same behavior then.

**Comment by vsoch** [comment]
+1

And generally a bigger issue to think about is how to preserve other meta data for the container

**Comment by oschulz** [comment]
I'm working on something similar here: https://github.com/oschulz/singularity-utils/blob/dev/bin/docker2singularity.py

It converts Docker containers to Singularity (FS-directory or SquashFS) via either Docker itself or via docker2aci (no Docker installation/privileges required). It does parse Docker (and ACI) manifests and creates an "/environment" file. Still under development, but already usable (at your own risk ;-) ).

**Comment by vsoch** [comment]
Thanks! We have this functionality in Singularity, eg:

      singularity run docker://ubuntu:latest

Which also does not need the docker daemon. We are just finishing up the environment variable stuffs.

**Comment by oschulz** [comment]
@vsoch , thanks - I was aware of `singularity run docker://...`, but was missing the ENV support. One question, if I may - is there an easy way to import a docker container into a directory (not a .img) without docker and sudo? Also, it would be nice to have a unified way that can both use Docker (to use the local Docker cache and local images) and also go without (for users without Docker access).

As for the ENV handling - will this be done via Python or C? If Python, I'd be glad to contribute the code I have so far (if you still need it).

**Comment by vsoch** [comment]
Hey @oschulz I hear ya! For your first question - the env support (I hope) will be coming along soon. The setup will be implemented in C, and the python bit to add docker support is actually already written, but dependent on that. You can probably guess it means just writing the Docker `ENV` to a file that the C bits know to source.

For directory vs. image, you should be able to exchange the two simultaneously. I usually use images for most things, and directories when debugging as an easy way to look around.

As for the "without docker and sudo" this should be implemented by the core singularity software - right now you can do this as I mentioned with the example, and the missing bit is the addition of the environment.

To use the local docker cache and images, right now our most complete solution is using [docker2singularity](https://github.com/singularityware/docker2singularity). Another way is using the standard command and bootstrapping/importing via a [locally running registry](https://github.com/singularityware/singularity/issues/429#issuecomment-269085751). This again will be perfected when the environment bit is fixed. @bauerm97 any updates on this? 

Beyond that, the other strategy I have thought about is converting a [Dockerfile to Singularity spec file](https://github.com/singularityware/singularity/blob/master/libexec/python/docker/converter.py), although this hasn't been robustly tested or used.

I suspect after the holiday these things will pick up! It was a busy and exciting end of year, and likely many of us are taking a little breather :)

**Comment by oschulz** [comment]
Hey  @vsoch,

> As for the "without docker and sudo" this should be implemented by the core singularity software

mea culpa - I hadn't realized that `singularity import` also works with directories as the target (that I then can turn into SquashFS images, all without sudo), not only with ext3 images. I'd tried it before, but must have done something wrong back then. I'll stick with my singularity-utils conversion via docker2aci until the ENV handling is sorted out, then I'll happily switch to `singularity import`.

> It was a busy and exciting end of year, and likely many of us are taking a little breather :)

And a well deserved one - Singularity is awesome! It's what I had been looking for for quite a while now, and it'll help us a lot with several projects next year.

**Comment by vsoch** [comment]
No worries, the software is changing so quickly likely something that didn't work now does, or vice versa, haha. And so great to hear that Singularity will be helpful!! If you do cool stuff please share, always love to hear these things :smile:

**Comment by chrisgorgo** [comment]
I'm not sure thus is the right place to ask this question @oschulz, but how
did you deal with permissions (many Docker images have files owned by root)
when creating singularity images without root permissions? Also doesn't
mounting squashfs require root as well?

Sorry for the questions, but I'm (like probably many users) very interested
in creating singularity images from docker hub without sudo or Docker
deamon.

On Dec 25, 2016 8:05 PM, "Vanessa Sochat" <notifications@github.com> wrote:

No worries, the software is changing so quickly likely something that
didn't work now does, or vice versa, haha. And so great to hear that
Singularity will be helpful!! If you do cool stuff please share, always
love to hear these things 😄

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/singularityware/singularity/issues/364#issuecomment-269144858>,
or mute the thread

**Comment by oschulz** [comment]
Hey @chrisfilo 

> I'm not sure thus is the right place to ask this

Hm, maybe we should take this discussion over to the Google group. :-)

> but how did you deal with permissions (many Docker images have files owned by root) when creating singularity images without root permissions?

I use `tar --exclude=dev` to extract the output of `docker2aci`. All files are owned by the user afterwards, of course, but that doesn't matter to singularity. When I turn the root-fs directory into a SquashFS image, I use `mksquashfs -all-root` - so in the image, all files are owned by root, again. If you like, try out my [docker2singularity.py](https://github.com/oschulz/singularity-utils/blob/master/bin/docker2singularity.py) - the following should just work ([docker2aci](https://github.com/appc/docker2aci) needs to be installed):

    docker2singularity.py -u ubuntu:14.04 ubuntu-14.04.sqsh

With the `-u` option, it uses `docker2aci` and doesn't require any privileges (docker2aci is easy to build and yields a static binary, so easy to deploy). Without the `-u` option, it requires a Docker installation and will use the docker cache and `docker export`, in a very similar fashion to the "official" [docker2singularity](https://github.com/singularityware/docker2singularity). I wasn't aware of the latter, when I wrote mine - I really should rename my docker2singularity.py to avoid confusion. As soon as `singularity import` has full ENV support, docker2aci won't be needed any longer.

> Also doesn't mounting squashfs require root as well?

It requires Singularity to be installed with suid-root flag (the default, when installed by a sysadmin), but I hope that'll be the case for most installations (as Singularity is necessarily somewhat limited without suid-root). But the users doesn't need any special privileges.

I do consider SquashFS an ideal image format for compute-containers (it seems to be very popular with the NERSC/Cori/Shifter people too, for good reason). SquashFS images are also easy to modify for normal users without any privileges:

* Unpack via `unsquashfs orig-image.sqsh`
* Use [`proot -S squashfs-root`](https://github.com/proot-me/PRoot/blob/master/doc/proot/manual.txt) to chroot to the FS directory as a pseudo-root user (proot uses ptrace, doesn't need root privileges)
* Install packages, etc.
* Repack via `mksquashfs squashfs-root mod-image.sqsh -all-root`

> (like probably many users) very interested in creating singularity images from docker hub without sudo or Docker

Definitely - after all, most users in an academic computing environment will have neither sudo nor Docker access, and might also be unable to start a VM in which they could have Docker and sudo.

**Comment by chrisgorgo** [comment]
Thanks for your reply. This is very interesting. I'm curious why are you
setting ownership of all files inside the singularity container to root.
I'm docker2singularity.sh I took the opposite approach - making all files
inside the container world readable and browsable. The idea was to make the
converter more robust - some docker images are built with the assumption of
using root user inside them. I wonder what are your thoughts.

On Dec 26, 2016 6:16 AM, "Oliver Schulz" <notifications@github.com> wrote:

Hey @chrisfilo <https://github.com/chrisfilo>

I'm not sure thus is the right place to ask this

Hm, maybe we should take this discussion over to the Google group. :-)

but how did you deal with permissions (many Docker images have files owned
by root) when creating singularity images without root permissions?

I use tar --exclude=dev to extract the output of docker2aci. All files are
owned by the user afterwards, of course, but that doesn't matter to
singularity. When I turn the root-fs directory into a SquashFS image,
I use mksquashfs
-all-root - so in the image, all files are owned by root, again. If you
like, try out my docker2singularity.py
<https://github.com/oschulz/singularity-utils/blob/master/bin/docker2singularity.py>
- the following should just work (docker2aci
<https://github.com/appc/docker2aci> needs to be installed):

docker2singularity.py -u ubuntu:14.04 ubuntu-14.04.sqsh

With the -u option, it uses docker2aci and doesn't require any privileges
(docker2aci is easy to build and yields a static binary, so easy to
deploy). Without the -u option, it requires a Docker installation and will
use the docker cache and docker export, in a very similar fashion to the
"official" docker2singularity
<https://github.com/singularityware/docker2singularity>. I wasn't aware of
the latter, when I wrote mine - I really should rename my
docker2singularity.py to avoid confusion. As soon as singularity import has
full ENV support, docker2aci won't be needed any longer.

Also doesn't mounting squashfs require root as well?

It requires Singularity to be installed with suid-root flag (the default,
when installed by a sysadmin), but I hope that'll be the case for most
installations (as Singularity is necessarily somewhat limited without
suid-root). But the users doesn't need any special privileges.

I do consider SquashFS an ideal image format for compute-containers (it
seems to be very popular with the NERSC/Cori/Shifter people too, for good
reason). SquashFS images are also easy to modify for normal users without
any privileges:

   - Unpack via unsquashfs orig-image.sqsh
   - Use proot -S squashfs-root
   <https://github.com/proot-me/PRoot/blob/master/doc/proot/manual.txt> to
   chroot to the FS directory as a pseudo-root user (proot uses ptrace,
   doesn't need root privileges)
   - Install packages, etc.
   - Repack via mksquashfs squashfs-root mod-image.sqsh -all-root

(like probably many users) very interested in creating singularity images
from docker hub without sudo or Docker

Definitely - after all, most users in an academic computing environment
will have neither sudo nor Docker access, and might also be unable to start
a VM in which they could have Docker and sudo.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/singularityware/singularity/issues/364#issuecomment-269201488>,
or mute the thread

**Comment by oschulz** [comment]
Hey @chrisfilo,

> I'm curious why are you setting ownership of all files inside the singularity container to root. I'm docker2singularity.sh I took the opposite approach - making all files inside the container world readable and browsable.

Well, the files have to belong to some user-id, and typically system files belong to root. I don't want them to belong to the UID that owned the root-FS directory from which the container was created - after all, that UID may have no meaning for the user of the SquashFS container image. That doesn't mean that the files aren't browsable/readable to anyone - they (mostly) keep the original permissions they had in the Docker container.

You make a good point, though: Maybe I should put in an additional `chmod -R ugo+rX` during conversion, to really makes sure all files are accessible (in case some are read-only root, and the Docker container assumed a root-user).

**Comment by vsoch** [comment]
We had a few use cases when extracting layers into an image where the permissions were unset, causing permission denied and making the bootstrap fail. [Here are the functions](https://github.com/singularityware/singularity/blob/0377f196f8a1e3e0400ee3f0516ad78a07a8f6e9/libexec/python/utils.py#L255) we wrote to adjust for this - basically choosing a desired level of permissions, and if the file is missing or incorrect, we fix it. I'm terrible with permissions so I apologize for lack of shortness/elegance in the code, but in case it is helpful for this issue, wanted to share!

**Comment by oschulz** [comment]
Thanks, I've added the wider chmod to my docker2singularity.py. @vsoch , I see that you're doing the chmod with Python-loop - I wonder if that has comparable performance to calling `chmod -R ...` via subprocess? Do you know if it's faster, slower or about the same?

**Comment by chrisgorgo** [comment]
For reference, this is what is being done in docker2singularity.sh: https://github.com/singularityware/docker2singularity/blob/master/docker2singularity.sh#L147

**Comment by vsoch** [comment]
@oschulz I'm not sure about speed (likely a small difference?) but the general sentiment has been to try and limit or [tightly control](https://github.com/singularityware/singularity/issues/384),[2](https://github.com/singularityware/singularity/pull/171), [3](https://github.com/singularityware/singularity/pull/394) child processes (eg, for [tar extraction](https://github.com/singularityware/singularity/pull/358#issuecomment-267110955)). I think it likely has to do with some chance of not catching somthing, or a security loophole. I'm not totally sure, but if there is a way to do (insert thing here) that doesn't need a child process, I've been choosing that one.

**Comment by oschulz** [comment]
@vsoch good point, especially if people run import/bootstrap with sudo or it uses higher privileges internally.

**Comment by gmkurtzer** [comment]
Closing this... unprivileged docker hub imports work in the development branch now.
