### ISSUE TITLE
while performing build: conveyor failed to get: pinging docker registry returned:

### ISSUE THREAD

**Issue by pavankulka** [apptainer/singularity#3642]
## Version of Singularity:

3.0.1

### Expected behavior

Expecting to build a singularity sandbox for ubuntu

### Actual behavior

:pkulkar2:85 > singularity build --sandbox ubuntu/ docker://ubuntu-latest
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: pinging docker registry returned: Get https://registry-1.docker.io/v2/: dial tcp 34.206.236.31:443: i/o timeout

**Comment by vsoch** [comment]
Try:

```bash
 singularity build --sandbox ubuntu/ docker://ubuntu:latest
```

**Comment by vsoch** [comment]
The format for the uri (unique resource identifier) is `docker://<registry>/<namespace>/<image>:<tag>@<version>` with defaults as:

 - registry: https://registry-1.docker.io/v2
 - namespace: library
 - tag: latest

So you are asking for just the image (ubuntu) and tag (latest) and defaulting to library at the Docker Registry. Your original command was asking for an image called `ubuntu-latest` instead of image "ubuntu" and tag "latest".

**Comment by rherban** [comment]
The error is indicative of network issues while trying to contact Docker hub. 

As Vanessa points out, the image you specified doesn't exist, but `docker://ubuntu:latest` is the proper way to pull.

**Comment by rherban** [comment]
@pavankulka I'm hoping the provided suggestions took care of your question and I'm going to close the issue.  If you still have a question, just re-open and let us know.
