### ISSUE TITLE
Query a container before initialization from within a plugin

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#3689]
## Version of Singularity:

3.2.1

### Expected behavior

There should be a way to query information about a container before running the plugin.  For instance, it would be nice to peek inside of a container and see what the environment looked like or to test for the presence of some libraries or something before determining what behavior a plugin should take.  

### Actual behavior

@AdamSimpson has provided feedback indicating that there doesn't seem to be a simple way to do this.  

In some instances, maybe we can fill this need by allowing plugin authors to query metadata contained in the SIF before running the plugin.  But for other applications (i.e. determining a container's environment or contents) this would be inadequate.  I propose allowing plugin authors to run arbitrary code/commands on the host system at the very start of execution.  That way a plugin author could run the equivalent of `singularity exec <container> env | grep SOME_VAR` on the host before actually starting the container.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@GodloveD We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Migrated to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1160
