### ISSUE TITLE
Local installation of singularity?

### ISSUE THREAD

**Issue by shwina** [apptainer/singularity#37]
Is it (technically) possible to have a completely local (non-root) installation of singularity for running containers? Creating and bootstrapping images requires `sudo`, but I've noticed that unless singularity is installed with `sudo make install`, I run into the following error when trying to run containers (via `singularity shell`)

```
ABORT: Could not escalate effective user privledges!
```

**Comment by gmkurtzer** [comment]
Unfortunately you must be root to install Singularity because the installation makes some configuration changes that requires root privilege on the host. I've done everything I can to stream line this (via Makefile.am hacks and RPM/DEB builds) but in the end, somewhere there has to be root to install. Orrrrr... You can only run it as root (which you don't want).

Sorry, there is no way around it.

**Comment by shwina** [comment]
Cool - I suspected as much. Maybe make this explicit in the setup instructions (that you need to be root when running `sudo make install`? The impression I got was that the only reason the `sudo` was there was because the installation was to `/usr/local`).

**Comment by gmkurtzer** [comment]
Yes good idea. I will update the documents accordingly!

**Comment by shwina** [comment]
Thanks!
