### ISSUE TITLE
Add ability to configure progress output frequency

### ISSUE THREAD

**Issue by mikegray** [apptainer/singularity#3726]
## Version of Singularity:

3.0.3

### Expected behavior

Would like to have some progress output during `push` or `pull`, but to be able to dial back the frequency of the communication.

### Actual behavior

When using `push`, the progress seems to be updating on the order of milliseconds which would be good for local feedback and usage for a small transfer. For a large transfer that could take minutes, I would be fine with updates every second. For a transfer that is happening from a remote build service, I do not need to be updated more than every second. Here is a log from a remote build where we end up sending a lot more information than needed across the web socket, and saving a lot more information than needed in the build log:
[log.txt](https://github.com/sylabs/singularity/files/3286728/log.txt)

### Steps to reproduce behavior

Execute a remote build.

**Comment by jscook2345** [comment]
I think having a progress option for all commands would be useful. It could be hidden using `--quiet`.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@mikegray Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Transferred this issue into the new Apptainer repo https://github.com/apptainer/apptainer/issues/1161
