### ISSUE TITLE
Better cache strategy is needed

### ISSUE THREAD

**Issue by QwertyJack** [apptainer/singularity#3730]
## Version of Singularity:

3.2.0

### Expected behavior

Better cache for build.

### Actual behavior

Actually no cache during build.

### Steps to reproduce behavior

Create a define file and build it for times. Every time it executes all the command.

For Dockerfile, each layer is cached so that it will use the cache if the Dockerfile remains unchanged.
Eg, call `wget` in a layer and docker will do it once while Singularity keeps downloading every time.

**Comment by QwertyJack** [comment]
Similar to #2808. Cache for each command in `%post` is also useful.

**Comment by dtrudg** [comment]
Hi QwertyJack. Singularity differs in architecture from docker etc. in that it has no concept of layers by design. This has various benefits related to the single-file format of the SIF container, which is consequently very easy to move around and directly use, and also enables embedded signatures, encryption support, etc.

As you point out with a link to #2808, caching for multi-stage builds may offer a (partial) solution here. Each stage in a multi-stage build ends is really a container rather than a layer - but some degree of caching is intended by the proposal in #2808. I do not believe there is any intention to cache individual commands in `%post` blocks at present (replicating layer style caching of docker).

**Comment by QwertyJack** [comment]
Thanks for your reply.
As I mentioned, call wget in `%post` will download the file every time I try to build, which is time consuming and  unnecessary.

**Comment by dtrudg** [comment]
Closing - this is a result of the design of Singularity, which does not use layers during build and at runtime.
