### ISSUE TITLE
fake root requires Singularity to be installed as root

### ISSUE THREAD

**Issue by jeffcbecker** [apptainer/singularity#3753]
## Version of Singularity:

3.3.0-rc1

### Expected behavior

76> singularity build --fakeroot test_centos_basic_fakeroot.sif test_centos_basic.def

successful build

### Actual behavior

INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:8ba884070f611d31cb2c42eddb691319dc9facf5e0ec67672fcfa135181ab3df
Copying config sha256:b9a1b1f0b2baaec83946a26d7045e4028f11eccc8b0e5b3514568e56a391beb2
1.05 KiB / 1.05 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
FATAL:   While performing build: while running engine: fakeroot feature requires to install Singularity as root

### Steps to reproduce behavior

See above.
Note, I su'd to root to do make install. Does setuid need to be allowed. I configured with nosuid? I want to be able to leverage Linux namespaces, and not require suid.

**Comment by jeffcbecker** [comment]
A simple lolcow example also failed

$ ~/mylocal/sing3.3.0rc1/bin/singularity build --fakeroot --sandbox lolcow lolcow.def
INFO:    Starting build...
FATAL:   While performing build: while running engine: fakeroot feature requires to install Singularity as root

**Comment by cclerget** [comment]
Hi @jeffcbecker , yes a setuid installation is required to use fakeroot feature because it needs to leverage setuid workflow in order to write corresponding user namespace mappings for container process allowing it to emulate the root user when running inside container. To my knowledge all container runtime taking advantage of that (the so called rootless mode) requires to install newuidmap/newgidmap tools which are itself setuid binaries. Additionally fakeroot allow users to create container network with `--fakeroot --net` which also requires privileges at some point to bring up the network inside container.

Back to your issue, look at `~/mylocal/sing3.3.0rc1/libexec/singularity/bin/` if `starter-suid` is installed and have setuid. Also did you use `./mconfig --disable-suid` at compilation time ?

**Comment by jeffcbecker** [comment]
I did use ./mconfig --disable-suid at compilation time. I'll rebuild with suid enabled. At our site we'd like to avoid suid as much as possible. After starter-suid is used to build fakeroot container, when is suid needed after that? We'd like to run container foo with "singularity exec --userns foo some-foo-binary" and not invoke any suid flows within that execution.

**Comment by jeffcbecker** [comment]
After rebuilding with suid enabled, I get the following:

$ ~/mylocal/sing3.3.0rc1/bin/singularity build --fakeroot --sandbox lolcow lolcow.def
INFO:    Starting build...
FATAL:   unable to run imgbuild engine as non-root user or without --fakeroot
FATAL:   While performing build: while running engine: exit status 255

Am I missing something?

**Comment by DrDaveD** [comment]
@cclerget It would be useful if singularity --fakeroot could fall back to running newuidmap/newgidmap if it is run as unprivileged and those other setuid tools are available.

**Comment by cclerget** [comment]
> $ ~/mylocal/sing3.3.0rc1/bin/singularity build --fakeroot --sandbox lolcow lolcow.def
INFO: Starting build...
FATAL: unable to run imgbuild engine as non-root user or without --fakeroot
FATAL: While performing build: while running engine: exit status 255

@jeffcbecker That means Singularity `starter-suid` is not running with setuid bit set, there is something wrong with installation, check that `nosuid` mount flag is not set on your home partition.

> It would be useful if singularity --fakeroot could fall back to running newuidmap/newgidmap if it is run as unprivileged and those other setuid tools are available.

@DrDaveD I will look if that can be implemented easily without involving too much complexity with actual workflows which are already complex enough to follow

**Comment by GodloveD** [comment]
@DrDaveD I'm actually not sure if we want to fall back to using newuidmap/newgidmap if Singularity is installed without suid enabled.  If I understand, these programs must also be install with suid enabled, and are not installed by default common Linux distros.  So we would just be passing off the responsibility of suid to another program that we do not control, and we have not vetted.  What happens when users think they are running Singularity securely and a CVE is discovered for newuidmap/newgidmap?  We don't control the way that they file, patch, and announce CVEs, so systems could be vulnerable and we wouldn't have any power to patch them.  

Singularity does not currently call any external binaries that have suid enabled and I think we want to keep it that way.  If any vulnerabilities are discovered in Singularity we want them to be _our_ vulnerabilities.

**Comment by jeffcbecker** [comment]
@cclerget , you're right - our home file system is mounted nosuid. In general, it's our security policy to mount all file systems nosuid. Only a few file systems (e.g. /) don't have this set. Thus, even if we can find a place where we can run suid, this will be limited to system admins. So we can build base containers (e.g., CentOS, Ubuntu) for users with fakeroot, and then give them to users to modify, as long as they don't need suid. Not sure if this is a workable model

**Comment by DrDaveD** [comment]
@GodloveD On the contrary, with modern operating systems (e.g. RHEL8) singularity should be able to do everything without setuid, and that will become the expectation (see issue #3612).  In RHEL8 podman will be the competition, supplied by Red Hat, and that includes Red Hat supplying newuidmap & newgidmap for rootless containers.  At that point singularity will hardly have to worry about any CVEs; leave that to the much simpler setuid programs supplied by Red Hat, which also have a much larger user base to find problems.

**Comment by GodloveD** [comment]
>singularity should be able to do everything without setuid

I get what you are saying, but there is always (at least in the foreseeable future) going to be an suid or a linux capability or some sort of priv escalation somewhere to set up the uid/gid mappings.  The only question is whether that priv escalation happens within Singularity itself or we put the responsibility on someone else.  I think I fully appreciate your point of view here in saying that we should pass that responsibility to others.  But I just disagree.  I think that passing the priv escalation buck off to someone else ([these folks in this case](https://github.com/shadow-maint/shadow)) has some serious disadvantages to consider as well.

**Comment by jeffcbecker** [comment]
when is 3.3.0 rc2 going to be available? Thanks.
