### ISSUE TITLE
Create GitHub issue template for feature requests

### ISSUE THREAD

**Issue by justwheel** [apptainer/singularity#3763]
The current GitHub issue template is specific for bug reports. This is great for bug reports, but it would be nice to have some guidance or structure to requesting new features too. For example, I don't know what common things a developer or manager may want to know when reviewing feature requests. It saves my time and the team's time to ask helpful questions up front to provide the most useful information and context for new feature requests.

For some inspiration, check out this [FOSSRIT/infrastructure](https://github.com/FOSSRIT/infrastructure/issues/new/choose) repo for helpful issue prompts.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jwflory Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Old Singularity repo issues are now closed and replaced with issues under the new Apptainer repo
https://github.com/apptainer/apptainer/issues/627
