### ISSUE TITLE
Update OCI related URIs in docs

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/singularity#3786]
Update singularity docs to use `repo:tag` when referencing OCI registries instead of `image:tag`. Originally discussed here: https://github.com/sylabs/singularity/pull/3749#discussion_r296746363

> The nomenclature I've seen more is to call that a repo and then the image is the repo plus tag.

> i.e. https://hub.docker.com/_/golang, the repo is golang and then you specify which image you want based on the tag

**Comment by jscook2345** [comment]
It's possible other registries uses other terms as well, so we we should gather those up and modify them as needed.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@ikaneshiro Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This might not be relevant anymore so closing this old Singularity repo issue. If this is still critical please open issue under new Apptainer repo.
