### ISSUE TITLE
Illegal option --

### ISSUE THREAD

**Issue by aleita** [apptainer/singularity#3810]
## Version of Singularity:

singularity-3.2.1-1.el7.x86_64

### Expected behavior

start the Jupiter notebook

### Actual behavior

-bash-4.2$ singularity -s run --nv -B /lustre/MedPhys/f_abide/:/data -B /lustrehome/diacono/lstm-for-aging/lstm-for-aging/:/opt/notebooks  docker://medphys/vae-gpu --port=8887 --ip=90.147.168.157
/.singularity.d/runscript: 1: set: Illegal option --
-bash-4.2$ 

### Steps to reproduce behavior

it seems "--port" is not correctly handled

**Comment by aleita** [comment]
singularity exec docker://medphys/vae-gpu cat /.singularity.d/runscript
....

```
#!/bin/sh
OCI_ENTRYPOINT=''
OCI_CMD='"/usr/local/bin/jupyter" "notebook" "--allow-root" "--notebook-dir" "/opt/notebooks" "--ip" "'*'" "--port" "8877" "--no-browser"'
CMDLINE_ARGS=""
# prepare command line arguments for evaluation
for arg in "$@"; do
    CMDLINE_ARGS="${CMDLINE_ARGS} \"$arg\""
done

# ENTRYPOINT only - run entrypoint plus args
if [ -z "$OCI_CMD" ] && [ -n "$OCI_ENTRYPOINT" ]; then
    if [ $# -gt 0 ]; then
        SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${CMDLINE_ARGS}"
    else
        SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT}"
    fi
fi

# CMD only - run CMD or override with args
if [ -n "$OCI_CMD" ] && [ -z "$OCI_ENTRYPOINT" ]; then
    if [ $# -gt 0 ]; then
        SINGULARITY_OCI_RUN="${CMDLINE_ARGS}"
    else
        SINGULARITY_OCI_RUN="${OCI_CMD}"
    fi
fi

# ENTRYPOINT and CMD - run ENTRYPOINT with CMD as default args
# override with user provided args
if [ $# -gt 0 ]; then
    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${CMDLINE_ARGS}"
else
    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${OCI_CMD}"
fi

# Evaluate shell expressions first and set arguments accordingly,
# then execute final command as first container process
eval "set ${SINGULARITY_OCI_RUN}"
exec "$@"

```

**Comment by aleita** [comment]
it seems to me there is TYPO here

```
if [ $# -gt 0 ]; then
SINGULARITY_OCI_RUN="${CMDLINE_ARGS}"
else
SINGULARITY_OCI_RUN="${OCI_CMD}"
fi
```


it should be 

```
if [ $# -gt 0 ]; then
SINGULARITY_OCI_RUN="${OCI_CMD}" "${CMDLINE_ARGS}"
else
SINGULARITY_OCI_RUN="${OCI_CMD}"
fi
```

**Comment by aleita** [comment]
https://github.com/sylabs/singularity/pull/3814

**Comment by cclerget** [comment]
Hi @aleita , this is the expected behavior and you should get the same error with `docker run`, based on Dockerfile documentation here https://docs.docker.com/engine/reference/builder/ in the section `Understand how CMD and ENTRYPOINT interact`, the point 4 mentioned this behavior : `CMD will be overridden when running the container with alternative arguments.`.

This is exactly what's done in runscript with :

`SINGULARITY_OCI_RUN="${CMDLINE_ARGS}"`
and comment confirm that
`# CMD only - run CMD or override with args`

This image doesn't have an `ENTRYPOINT`, so you couldn't run it like you did unless to specify :
`singularity run docker://medphys/vae-gpu jupyter notebook --allow-root your_options`
It requires to fix that in Dockerfile to use `ENTRYPOINT` with something like :

```
ENTRYPOINT ["/usr/local/bin/jupyter", "notebook", "--allow-root", "--notebook-dir", "/opt/notebooks"]
CMD ["--ip", "'*'", "--port", "8877", "--no-browser"]
```

**Comment by aleita** [comment]
ok,

it sounds good.
Thanks for pointing it out

Ale

**Comment by cclerget** [comment]
Cool, closing, feel free to re-open if needed
