### ISSUE TITLE
Detached header for encrypted FS

### ISSUE THREAD

**Issue by schebro** [apptainer/singularity#3817]
## Version of Singularity:

BA

### Expected behavior

With the current design encrypted containers use dm-crypt linux libraries through cryptsetup utility to encrypt and decrypt file system. Currently we are not detaching the header and the body from the encrypted container but it's possible to detach the two for extra security where body of the container can be publicly shared and header can be shared privately.

### Actual behavior

NA
### Steps to reproduce behavior

NA

**Comment by schebro** [comment]
There's no real necessity for this feature right now. Will keep the issue open and revisit in later releases if necessary.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@schebro Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Migrated to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1158
