### ISSUE TITLE
Detaching container's /dev directory

### ISSUE THREAD

**Issue by schebro** [apptainer/singularity#3820]
## Version of Singularity:

With encrypted containers, during encryption/decryption dm-mapper library creates a temporary device in /dev/mapper, which is then mounted to access the file system. Other users have access to this directory and hence can see the mapper devices. This issue is to investigate about detaching /dev/ directory and move it inside container so that other users can't see the mapper devices.

### Expected behavior

NA

### Actual behavior

NA

### Steps to reproduce behavior

Write here.

**Comment by schebro** [comment]
Not necessary to do in any immediate release. Will leave the issue open and address it if necessary in future.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@schebro Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Migrated to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1158
