### ISSUE TITLE
Cache clean command not making any effect

### ISSUE THREAD

**Issue by sushma-4** [apptainer/singularity#3823]
## Version of Singularity:

3.3.0-rc1

### Expected behavior

> ``singularity cache clean`` will now delete only sub-directories of SINGULARITY_CACHEDIR instead of the directory itself

### Actual behavior

No deletions occurred
```
sushma@Sushma-Ubuntu:~$ singularity cache clean
sushma@Sushma-Ubuntu:~$ cd .singularity/cache
sushma@Sushma-Ubuntu:~/.singularity/cache$ ls
library  net  oci-tmp  oras  shub
sushma@Sushma-Ubuntu:~/.singularity/cache$ cd library
sushma@Sushma-Ubuntu:~/.singularity/cache/library$ ls
sha256.b80bddda1d84d827ea135eb890f969a83ccba2a7a2152e15567d114857280120
sushma@Sushma-Ubuntu:~/.singularity/cache/library/sha256.b80bddda1d84d827ea135eb890f969a83ccba2a7a2152e15567d114857280120$ ls
busybox_latest.sif

sushma@Sushma-Ubuntu:~/.singularity/cache$ cd oras
sushma@Sushma-Ubuntu:~/.singularity/cache/oras$ ls
sha256:5e15d96e9a185c66e4e7c0f3ba4b96c383cba8e8769ed2c704906abecd6ef812
sha256:d48dba1449488d24d270a20a9b9c6144b79ded5e4971195bfd0e36f507a9436d
sha256:d7d0e0f5eeb6f14143a174b01c6c719d826cc7323ccff7a7f4d5c162e719aba7

```

**Comment by phpHavok** [comment]
The reason files are still in library is because `singularity cache clean` only cleans blob files by default (files under `oci-tmp`). You need to use `singularity cache clean --all` to clean everything. However, I also noticed that `net` and `oras` were missing from the cache deletion code altogether, so I added a PR to fix that.
