### ISSUE TITLE
Roll Back PR #3865 once SingularityHub is up

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#3866]
Pr : 
> Disable tests or test cases that access singularity hub #3865

We should roll back that or setup a private SingularityHub instance for test purposes only

**Comment by dtrudg** [comment]
@ikaneshiro - I don't know whether it'd be possible for HPCng as an org to get a credential that allows enough API access to shub for this... and do something similar to the Docker handling?

**Comment by vsoch** [comment]
Back in the day after the rate limits were added I had proposed creating user-specific tokens to more finely control access with @ArangoGutierrez, but I don't think there was a solid response from Sylabs so it was dropped. At this point I couldn't make the justification for the time, but my suggestion would be to make a repository on there just for Sylabs, make a bunch of busybox images, and then spread them over your testing so that it doesn't go over the weekly pull limit. You might consider just running the test on a merge to master so it's not frequent, and disabling in the PR tests.

**Comment by dtrudg** [comment]
Thanks for the info @vsoch and apologies the discussion around tokens did not progress properly.

I think we'll postpone this for now, as even if we split the images so that we were pulling a different thing for each subtest we could still feasibly hit the "Every single download of a container is counted toward the weekly limit for that container, and the collection, which is set at 50 for each". 

I think this limit may be possible to reach in periods before a release even if the test is restricted to master & release branches - given that tests are sometimes re-run due to other failures. Maybe we wouldn't hit it, but it's close enough to make me uncomfortable that we could in odd circumstances end up with failing tests on master that might be disruptive.

**Comment by vsoch** [comment]
> I think we'll postpone this for now, as even if we split the images so that we were pulling a different thing for each subtest we could still feasibly hit the "Every single download of a container is counted toward the weekly limit for that container, and the collection, which is set at 50 for each".

Correct.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
