### ISSUE TITLE
Detach squashfs creation from encryption

### ISSUE THREAD

**Issue by schebro** [apptainer/singularity#3876]
## Version of Singularity:

3.4

### Expected behavior

@mem 's feedback from PR #3729
Create the unencrypted SIF file and later creating a second SIF that's encrypted. That would allow us to introduce an "encrypt" operation for existing SIF files. The more important consequence of that is that you can split the encryption code from the squashfs creation code.

### Actual behavior

Currently the encryption part is integrated with squashfs creation part

### Steps to reproduce behavior

NA

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@schebro Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Migrated to the new Apptainer repo https://github.com/apptainer/apptainer/issues/1158
