### ISSUE TITLE
Show error when using --bind with --writable

### ISSUE THREAD

**Issue by Flamefire** [apptainer/singularity#3894]
## Version of Singularity:
3.2.1

### Expected behavior

Not being able to mount a requested path should throw an error and exit.

### Actual behavior

`--bind` argument is silently ignored. Even `--verbose` does not show anything.

### Steps to reproduce behavior

run `singularity shell --bind /mypath:/foo --writable /tmp/ubuntu` on an image/sandbox with non-existing /foo folder

Note: https://sylabs.io/guides/3.2/user-guide/bind_paths_and_mounts.html#a-note-on-using-bind-with-the-writable-flag does describe the issue but current behaviour is inconsistent and user-unfriendly. If a user request a binding and it cannot be served then this is an error, not a "well, let's just ignore this silently" which the user may find out much later after trying to write expensive to create results to the folder.

**Comment by cclerget** [comment]
Hi @Flamefire , I will flag this issue as part of an epic issue, because the fix won't fit in a single line, actually triggering an error/exit could have side effect when running a container from a current working directory which doesn't exists in container image like :

```
cd /myshare
singularity shell --writable docker://alpine
```

So it need to be handled by "bind type" (`bind path`/`mount hostfs` in `singularity.conf`, home directory, cwd), I think more about a warning/info message for most cases instead otherwise Singularity would be almost unusable with an error/exit

**Comment by Flamefire** [comment]
> I think more about a warning/info message for most cases instead otherwise Singularity would be almost unusable with an error/exit

There already is a warning when the host directory does not exist, so similar warning can be issued. BUT read below

> So it need to be handled by "bind type" 

Agreed there need to be different types and actions taken according to them. Binding the CWD is non-critical as is HOME. But failure to bind an explicitly requested directory should be error&exit. This way a successful launch of the singularity command can be considered as "checked bind dirs" and users may even do that for CWD/HOME by adding `--bind $HOME;$PWD` to their command to "upgrade" the warning to an error. Remember that this bind applies to more than just interactive runs. So a warning for script-invoked containers would be next to useless.
