### ISSUE TITLE
connectivity issues with singularity on MacOS?

### ISSUE THREAD

**Issue by kkmann** [apptainer/singularity#3901]
## Version of Singularity:

singularity version 3.2.0-rc2 on MacOS

### Expected behavior

```singularity exec container.sif ping www.facebook.com``` should ping facebook

### Actual behavior

```
ping: socket: Operation not permitted
[    1.149837] reboot: Power down
```

### Steps to reproduce behavior

na

**Comment by jscook2345** [comment]
I believe the network stack is not quite there on the macos client yet. @jmstover @rherban ?

**Comment by rherban** [comment]
Correct, using the network stack on Mac requires some extra work and isn't fully fleshed out yet.

**Comment by kkmann** [comment]
thx, currently switched back to vagrant. ultimately, the native macOS implementation is intended to support building and network too though, right? is there a rough timeline already?

**Comment by rherban** [comment]
@kkmann The just-released beta version of Singularity Desktop now supports network access.  A small caveat to that is ping requires root access since it opens a raw socket.  You can add the `CAP_NET_ADMIN` capability to your user to enable it if you so desire.  Other network access will work as expected.

You can build containers in the context of converting from Docker images, but to build from a definition file requires the Remote Builder through cloud.sylabs.io .

There are plans on supporting native definition builds within the Desktop, but there are a number of hurdles to be dealt with first.  

More information about the beta release can be found here: https://medium.com/sylabs/announcing-the-first-beta-release-of-singularity-desktop-for-macos-f427c006aae6

**Comment by kkmann** [comment]
thx for the update! I am closing this now, will follow the further progress closely
