### ISSUE TITLE
Add subcommand to verify to spit out system image hash

### ISSUE THREAD

**Issue by rherban** [apptainer/singularity#3918]
After a conversation with @ikaneshiro, we agreed there should be a `verify` sub-command to spit out the system image hash so users can verify the core system partition hasn't changed over time (users would be expected to save the hash somewhere to confirm), even if the container itself has changed (signed by additional keys, etc).  

Expected:
```
singularity verify --system container.sif
EwV9VJoF6jXdd3qeO8iYbXB5txcWggimhhX1e
```
sign with new key, but leave system partition the same, and the system hash should remain the same.  

This is somewhat analogous to doing a shasum on the container itself, but that wouldn't give you any flexibility and wouldn't be future-proof if/when we have writable partitions in the SIF.

Slightly related to #408, but lots of things have changed since then.

**Comment by dtrudg** [comment]
@ikaneshiro - do you still see any value this given the changes to signing / verification?  It feels a bit like checking a signature over the specific SIF ID for the rootfs (which we can do) is probably enough for the goal here?

**Comment by ikaneshiro** [comment]
@dctrud The changes to the signing and verification work don't really cover this use case because they only check that the image is signed by a particular entity. That same entity could change the system partition and re-sign the container without the user being able to tell that the system partition changed. 

In general, I don't think this is really necessary to add to the CLI because a user can simply dump the system partition and calculate a shasum without much trouble like so:

```
$ singularity sif list alpine.sif 
Container id: 64dcfb73-8b98-44db-9d15-a6d2671e3569
Created on:   2020-08-04 20:50:40 +0000 UTC
Modified on:  2020-08-04 20:52:36 +0000 UTC
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-32807               |Def.FILE
2    |1       |NONE    |36864-36959               |JSON.Generic
3    |1       |NONE    |40960-2760704             |FS (Squashfs/*System/amd64)
4    |NONE    |1   (G) |2760704-2762270           |Signature (SHA256)
$ singularity sif dump 3 alpine.sif | shasum -a 256
ecc97d3663e9b0c6eb641ff7c3209af39b79d3700910d7ca009e3c8071ff0b1b
```

If we see users wanting this behavior more, let's reopen the issue, but for now I think it is fine to close.
