### ISSUE TITLE
Adding a bind path when using docker2singularity

### ISSUE THREAD

**Issue by chrisreidy** [apptainer/singularity#396]
HI
I am probably missing something straightforward.
I am replicating the Tacc/Stampede tutorial for the scenario where a user has a Docker image they want to run on our HPC and do not have Singularity installed. I create the image from Docker hub; then run docker2singularity against it; then SCP the image to a path in /extra on HPC which is included in singularity.conf but not in the image.  "singularity exec" then fails with:
WARNING: Non existant(sic) bind point (directory) in container: '/extra'
I tried adding -B to the exec command and tried changing ENABLE OVERLAY in the conf file. No luck.

**Comment by vsoch** [comment]
Hey @chrisreidy ! The best way to convert from docker to singularity actually isn't using the original docker2singularity that was made, it's by way of using the Singularity command line util directly, and there are three ways to do that:

- bootstrap (if the user wants to modify the image, or the run script)
- import
- shell

### Bootstrap
This means creating a Singularity image and then boostrapping with a docker spec file. Here is what that might look like. First we need a build file, with any changes the user might want, but this is the minimal required:

      BootStrap: docker
      From: ubuntu:latest

If you want to change the running command `%runscript`, or stuff that is done after bootstrap (`%post`) the user can add those sections:


      BootStrap: docker
      From: ubuntu:latest

      %runscript

      exec echo "Hello World!" "$@"


Then to do the bootstrap:

      sudo singularity create -s 4000 ubuntu.img
      sudo singularity bootstrap ubuntu.img Singularity
  
By default, the image's `ENTRYPOINT` is used as the runscript (if one is not defined as above). If the user wants a `CMD` to be used instead, the following should be added to the header:

     IncludeCmd: yes

### Import
You can also import directly from a docker container, akin to how you would import from another source:

      sudo singularity create ubuntu.img
      sudo singularity import ubuntu.img  docker://ubuntu:latest

(This method is probably easiest, but will use `ENTRYPOINT` by default and no modifications to container.)

### Shell
The final method is running a shell, which is like a throwaway, temporary, do-not-want-to-save-be-careful kind of deal:

     singularity shell docker://ubuntu:latest

For your users, since reproducibility is important, I would encourage them to create `Singularity` spec (build files) and then bootstrap them. That way, any and all changes to the container are recorded, and +1 points if they use Github and keep them version controlled!

@chrisreidy I didn't know you were at TACC/Stampede! My graduate school lab has strong connections :) This makes you very awesome!

**Comment by vsoch** [comment]
and actually, [here are some good docs](http://singularity.lbl.gov/docs-docker) that explain a little more detailed version of the above!

**Comment by vsoch** [comment]
If you are making user docs, I would add that a common error they will see is that the container is out of space when the bootstrap is running, and in this case they need to go back and make it bigger with `--size` or `-s`:

     sudo singularity create --size 4000 image.img

**Comment by chrisreidy** [comment]
Hey @vsoch . So perhaps I can only replicate the scenario from TACC's tutorial if I run the image from home or one of the other predefined paths and not from our shared storage /extra.  Hmmmm.  I have successfully tried the import and bootstrap methods so now I wanted to try the next step of not requiring the user to install singularity.  Not that it is so hard but you know how lazy .. ahem .. efficient users like to be.
Actually I am at Arizona - I was just studying the TACC docs

**Comment by chrisreidy** [comment]
Re running out of space I saw somewhere that you can resize an existing container.  That will be useful.

**Comment by vsoch** [comment]
@chrisreidy for your first point, if you want a way for the user to build / work with images that doesn't require sudo, that wouldn't generally work. The general workflow looks kind of like this:

![image](https://cloud.githubusercontent.com/assets/814322/20990688/eb307e1e-bc8e-11e6-9748-eebea4d92991.png)

So to be clear - any kind of writing action must be done in an environment where the user would have sudo permissions. The examples above that I provided are all generating (writing) new images, so that would require sudo! However once the images are done, you can basically `scp` or `sftp` them onto your cluster, wherever, and then run them as executables (no sudo required), for example:

      .ubuntu.img
      singularity run ubuntu.img
      singularity shell ubuntu.img

To your second question/point - I totally agree that a user shouldn't have to install Singularity, in which case we could use Vagrant or Docker (locally) that would have it pre-installed. Of course then they would have to install vagrant or docker... we do have simple Vagrantfiles that have singularity, or singularity and Docker:

      https://github.com/singularityware/singularity-vagrant

Does that answer your question?

**Comment by chrisreidy** [comment]
Hi @vsoch . Yes it does.  The "mkdir -p /extra" function that I have included in the .def files require root.  ENABLE OVERLAY doesn't work in my case.  So I will either have them run docker2singularity in their Docker environment and run the .img in their home on HPC; or use bootstrap / import with singularity and then they can run in any of their spaces on our HPC.  Choices are good!

**Comment by chrisgorgo** [comment]
I've added the "/extra" bind point to docker2singularity script. Give it a few minutes to rebuild on Docker Hub and update the container `docker pull singularityware/docker2singularity`. You can then rebuild the container image and the appropriate mount points should be automatically created.

**Comment by chrisreidy** [comment]
@chrisfilo .  Awesome!  Thanks!

**Comment by vsoch** [comment]
I think the correct way to go about this would be to add these custom mounts [here](https://github.com/singularityware/singularity/blob/master/etc/singularity.conf#L127), we couldn't just add every possible directory that a user would possibly want, that's why this is available in the config...

I'm thinking this over now. We needed docker2singularity when we didn't have it natively built into Singularity. Now Singularity does this using the Docker registry API (without needing the Docker engine). Wouldn't it be preferable to provide the user with a dockerized Singularity install and then generate the image using the Singularity version (which is rapidly changing). This script, if it isn't already broken, is going to break soon.

**Comment by vsoch** [comment]
@chrisreidy any kind of bootstrapping (the mkdir -p command in the def file) is always going to require root. The two options you noted are good! I think what we need to provide is an updated docker2singularity, one that installs current Singularity and provides instant access to those commands. My worry is that the [current script](https://github.com/singularityware/docker2singularity/blob/master/docker2singularity.sh) that uses the docker engine to run and obtain the image, dumps them in, and then does (possibly different) things with permissions and environment is going to produce something different than what Singularity command line would. @gmkurtzer  what are your thoughts? I think we should finish up the current PR to support `.env` and then I can update this docker container to mirror that.

**Comment by vsoch** [comment]
and @chrisfilo thanks for the speedy fix! You're still diabolical :)

**Comment by chrisreidy** [comment]
I tried the procedure again after the mod from @chrisfilo and it works great.  Of course!
I get your point @vsoch that you can't edit docker2singularity for every use case. But thanks to you both for helping me with this.  Unfortunately I can't let you see the Docs I am creating because I use Confluence and we are not allowed to expose it to the outside world (some license thing).  Next project is the NIH Cuda configuration.
