### ISSUE TITLE
scripts/go-test is not regenerated when Go build tags change

### ISSUE THREAD

**Issue by mem** [apptainer/singularity#3981]
## Version of Singularity:

edfc9d7e0d864871357523547eb0e85919d2bab5

### Expected behavior

scripts/go-test is regenerated if Go build tags change

### Actual behavior

scripts/go-test is not regenerated if Go build tags change

### Steps to reproduce behavior

mconfig
check scripts/go-test
remove seccomp development libraries
run mconfig again
check scripts/go-test, it didn't change.

related to #3980

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@mem Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. Please open new issue at https://github.com/apptainer/apptainer.
