### ISSUE TITLE
Exported function in pkg/util/crypt/key.go are not documented

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#3986]
## Version of Singularity:

All.

### Expected behavior

All exported functions must be documented.

### Actual behavior

Exported functions in `pkg/util/crypt/key.go` are not documented at all.
We need documentation for the following functions: `NewPlaintextKey()`, `EncryptKey()`, and `PlaintextKey()`.

### Steps to reproduce behavior

N/A.

**Comment by jscook2345** [comment]
@gvallee @mem 

Is there a way to catch this with our linter?

**Comment by GodloveD** [comment]
I actually thought we _were_ catching things like this with the linter.  Guess this is not the case?

**Comment by gvallee** [comment]
I also thought we were catching these problems and to be honest also expecting that all developers are actually using a configuration with a strict linter. But I clearly had a few of such problems lately and the only thing I can think about is that the configuration of the linter changed.
I did not have the time to look at the problem and CI configuration yet.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@gvallee Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
This repository is no longer active. If singularity --version says singularity-ce, then please open a new issue at https://github.com/sylabs/singularity, otherwise please open a new issue at https://github.com/apptainer/apptainer.
