### ISSUE TITLE
Singularity pull doesn't respect cache

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4015]
## Version of Singularity:

3.3.0-rc.1.438.gc5e243fc4

### Expected behavior

Image is not pulled when image with same sha256 is already present in cache.

### Actual behavior

Image is pulled.

### Steps to reproduce behavior

```
rm -rf $HOME/.singularity/cache/library
singularity pull -U library://sashayakovtseva/test/image-server:sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0
ls -la  $HOME/.singularity/cache/library/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0
singularity pull -U library://sashayakovtseva/test/image-server:test
ls -la  $HOME/.singularity/cache/library/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0
```

**Comment by sashayakovtseva** [comment]
After offline discussion with @cali4888 it looks like this might be the intended behavior.
@ikaneshiro @GodloveD can you confirm it is not a bug?

**Comment by ikaneshiro** [comment]
I don't think this behavior is correct. Using a different uri for an identical image shouldn't result in a new pull. This most likely an oversight when the library cache was first implemented. I saw you had #4111 fixing this but then changed it to just update the client. What was your plan for fixing this? 

My first thought would be to change `LibraryImageExists()` to only look for the directory with the correct sha and then ensure that the a file in that directory exists with the correct sha to be used for that image.

**Comment by gvallee** [comment]
You are suggesting to drastically change how the cache is working. Right now, the cache is strictly based on the hash, meaning that if the hash is the same, what is in the cache will be used. So, to me, the behavior described in this issue is the intended one. Here, if I understand correctly, the idea would be to have the cache to be based on the hash+source URI, correct?

I am not personally opposed in changing the cache semantics but that should be discussed since it is a way more intrusive effort.

**Comment by ikaneshiro** [comment]
@gvallee the hash+source is actually the problem currently. Those two pulls results in two identical files in the cache:

```
ian@T440s:library$ pwd
/home/ian/.singularity/cache/library
ian@T440s:library$ tree
.
└── sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0
    ├── image-server_sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0.sif
    └── image-server_test.sif

1 directory, 2 files
```

Right now `LibraryImageExists()` checks the full path, which includes uri dependent stuff at the very end of the path. So, it thinks the image with the hash doesnt exists when it really does

**Comment by mem** [comment]
Ah, I see what you mean.

The first command produces the file:

```
~/.singularity/cache/library/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0/image-server_sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0.sif
```

and the second command produces the file:

```
~/.singularity/cache/library/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0/image-server_test.sif
```

the difference being only the file _name_ stored in the cache. Given that they are the same file:

```
$ sha256sum .singularity/cache/library/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0/image-server_test.sif .singularity/cache/library/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0/image-server_sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0.sif
d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0  .singularity/cache/library/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0/image-server_test.sif
d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0  .singularity/cache/library/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0/image-server_sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0.sif
```

you are saying they should be stored under the same name.

My _opinion_ is that the cache code is doing something weird: it's keeping the remote name even if it doesn't need it for anything. Since the library returns a hash when verifying if the image does exist, and that's enough to locate the image in the cache, we should not use the name in the URL to generate names in the cache. I _suspect_ that we are using the filename to deal with hash collisions... but that means we are creating a problem with a high likelihood of happening to deal with a situation with a low likelihood of happening :cry: 

If you make that change, this issue is solved.

**Comment by sashayakovtseva** [comment]
@gvallee as @ikaneshiro said, it is hash+source now, while it should (should it?) be hash only.
@mem yep, dealing with hash collisions is what @cali4888 thought too, that is why I changed #4111 from fixing it to simply update scs-library-client, thought we need to discuss this first.

As for me, if we are not going to keep it as it is to prevent possible collisions, there is no need fo a directory for each image, we can name SIFs by hash and that is it. Actually, that is how it is done in Singularity-CRI now.
But getting rid of directory per image looks like a really big change, we should decide, what we what to fix and how. Changing cache storing is the ideal solution IMO.

**Comment by pisarukv** [comment]
Just not to forget. Need to think how we will be migrating from the old cache to a new one.

**Comment by dtrudg** [comment]
> As for me, if we are not going to keep it as it is to prevent possible collisions, there is no need fo a directory for each image, we can name SIFs by hash and that is it. Actually, that is how it is done in Singularity-CRI now.

If there is any thought here around directory structure I would request it's considered to adopt some kind of tree structure. Having either directory or just straight file per image in the cache dir is problematic if you are working with 1000s of images on a filesystem that's slow with metadata ops. This has come up for me with automated building from the 1000s of biocontainers docker images (which I realize is not the library path, but cache structures are similar).

e.g. 

`.singularity/cache/library/d5/sha256.d50278eebfe4ca5655cc28503983f7c947914a34fbbb805481657d39e98f33f0.sif`
