### ISSUE TITLE
Add --remote (or similar) option/arg to commands like push

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#4021]
## Version of Singularity:

3.3.0-rc.1.436.gfdf86b487

### Problem

Right now, the `push` command (and others) can only interact with the default library as determined by the `remote.yaml` configuration files.  Consider a situation in which you want to automate the process of updating two different containers to two different remotes using two different batch scripts.  You will need to be very careful in coordinating the timing of these updates so that they do not interfere with one another when setting different default remotes in the `remote.yaml` file.  (Or you will need to use 2 different users or something.)

### Solution

There should be a runtime option for specifying a different remote that overwrites the default in the `remote.yaml`.   Something like this:

```
$ singularity push --remote SylabsCloud public.sif library://user/blah/public

$ singularity push --remote OnPrem proprietary.sif library://user/blah/proprietary

```

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@GodloveD Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Transferred this issue into the new Apptainer repo https://github.com/apptainer/apptainer/issues/1161
