### ISSUE TITLE
must an instance be started with `--fakeroot` to use `--fakeroot` with `exec`

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#4025]
See the following workflow:

```
$ singularity instance start busybox_latest.sif busybox_latest
INFO:    instance started successfully

$ singularity exec instance://busybox_latest id
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant)

$ singularity exec --fakeroot instance://busybox_latest id
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant)

$ singularity instance stop busybox_latest
Stopping busybox_latest instance of /home/vagrant/examples/exec/instance/busybox_latest.sif (PID=12777)
```

Note that the `exec --fakeroot` does not have an `id` of `0`, but rather `1000`. Is this because I did not run `instance start` with `--fakeroot`? I think the answer is `yes`, but I want to verify. :)

Thanks!

**Comment by Zohman** [comment]
> Note that the `exec --fakeroot` does not have an `id` of `0`, but rather `1000`. Is this because I did not run `instance start` with `--fakeroot`? I think the answer is `yes`, but I want to verify. :)

i think yes, and this is quite interesting,
i can say that in the docker world making a container instance ( docker run -d .. )
which run as real root by design allow to add the user string to the /etc/passwd during build
and then you can switch to it with 'docker exec --user <username>' during the container run-time.

here we have the --fakeroot concept as it works under user namespace.
if not executed with sudo; root id 0 is actually your uid in namespace.

what if you su to a 'real' user when using --fakeroot? it will just get one of the uid of the
allowed namespace from what you've been allocated in /etc/subuid, username:start_uid:total_uids.
which will make things much safer in terms of security.
the fakeroot have the ability to delete all files created on the namespace range inside the container.

so for example (at least for what i expect)
/etc/subuid: 1000:100000:65536
1000 is the user real UID, 100000 represents the first UID in the namespace range of available UIDs that processes within the container can run. 65536 represents the maximum number of UIDs that allowed to use by a container. Based on this example entry, a process running as the root user within the container is launched so that on the host system it runs with the UID 100000. 
If a process within the container run as a user with UID 500, on the host system it would run
with the UID 100500.

i'm assuming that for the most use-cases instances would run as real-root to maintain
services and bind to ports/network and mainly serve IT/HPC system admins mostly, 
but i might be wrong. :-)

**Comment by cclerget** [comment]
@jscook2345 Yes, you must run first `instance` with `--fakeroot`, also when joining instance with `shell/exec` most options have no effect

**Comment by jscook2345** [comment]
@cclerget 

Thanks for the info! <insert cat picture here> 😸
