### ISSUE TITLE
actions download images before checking for fakeroot support

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#4033]
Actions download images before checking for `--fakeroot` support. They should probably check for support than download if OK.

Related to #3927 

```
$ singularity run --fakeroot docker://centos id
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:8ba884070f611d31cb2c42eddb691319dc9facf5e0ec67672fcfa135181ab3df
 71.91 MiB / 71.91 MiB [===================================================] 16s
Copying config sha256:b9a1b1f0b2baaec83946a26d7045e4028f11eccc8b0e5b3514568e56a391beb2
 1.05 KiB / 1.05 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /home/vagrant/.singularity/cache/oci-tmp/a799dd8a2ded4a83484bbae769d97655392b3f86533ceb7dd96bbac929809f3c/centos_latest.sif
INFO:    Convert SIF file to sandbox...
FATAL:   newuidmap was not found in PATH (/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/usr/local/sbin), required with fakeroot and unprivileged installation
```

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@jscook2345 Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Pending issues from the old repo are copied to the new repo (https://github.com/apptainer/apptainer/issues/1392) and cleaned from the old, retired repo.
