### ISSUE TITLE
Add e2e tests for various corrupted filesystems/images

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#4034]
e2e tests mostly run with valid images, add some tests with corrupted filesystems/images to ensure Singularity correctly handle those cases

**Comment by jscook2345** [comment]
Some things that come to mind:
* Missing or bad config files
* Sections of sif missing using `sif del`
* Missing files in `/.singularity`

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@cclerget Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
https://www.google.com/url?q=https://drive.google.com/drive/u/1/folders/1npfBhIDxqeJIUHZ0tMeuHPvc_iB4T2B6&sa=D&source=calendar&usd=2&usg=AOvVaw1WshbuXjeUkCxuyMz8JW-N

**Comment by kmuriki** [comment]
This repository is no longer active. Please open a new issue at https://github.com/apptainer/apptainer.
