### ISSUE TITLE
Revisit signing package

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4043]
I am using signing package in Singularity-CRI and I believe there are some issues now we should address in order to make it a nifty library package. 

1. `IsSigned` function should not call `Verify` on the container. Instead, as naming implies, it should check for signatures, especially taking into account that all parameters needed are there.
2. `Verify` should not return formatted output. This is a library call and we should omit any formatting related things there IMO.

**Comment by WestleyK** [comment]
Semi-related to: https://github.com/sylabs/singularity/pull/3966.

#3966 is supposed to improve the flexibility and usability for the signing package.

**Comment by sashayakovtseva** [comment]
Not really related, this issue is more about package API enhancements and cleanup, rather that errors improvements.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@sashayakovtseva Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.
