### ISSUE TITLE
singularity_user_ns_enabled() call breaks functionality 

### ISSUE THREAD

**Issue by bauerm97** [apptainer/singularity#409]
Commit ed07e7ced8a1b5e25180715388e702e2586c1beb breaks functionality, reverting it to the previously used `singularity_ns_user_configured()` fixes this, however I'm not sure about the logic behind what we're doing here so I can't comment on if that is an acceptable fix. I'm looking into the best way to fix it, but for now it might be best to revert back to the original form, so that PR tests will pass again.

**Comment by bbockelm** [comment]
The original PR was correct; the commit you point out is incorrect.

We can't use _enabled there because we haven't entered the user namespace code, meaning it will always return false (-1).

**Comment by bauerm97** [comment]
Makes sense to me. I've reverted this in a local testing branch, applied #407 and applied #404 on top if it, and it is now building and passing tests.

**Comment by gmkurtzer** [comment]
The logic in ns/user.c is not very clear. As I can see in `singularity_ns_user_unshare()`:

1. We start off checking if it should run via `singularity_ns_user_configured()`
2. Then we try to `unshare(CLONE_NEWUSER)`
3. If `unshare()` fails, we then abort only if it is not running SUID, but if it is, we return success and we never set `enabled = 0`

While the above is what is currently coded, it is an impossible situation because the SUID test is duplicated within `check_for_suid()` and `singularity_ns_user_configured()`. The only want to get to the second possibility above is if it is not running SUID which would have already been handled by the previous function.

So I agree that we can "trust" that `singularity_ns_user_configured()`, but only because the current return true within the code is impossible to reach. Please fix this and add it to #410, and then I'll merge it together.

Thanks!
