### ISSUE TITLE
$LD_LIBRARY_PATH is unset within the container (with setuid)

### ISSUE THREAD

**Issue by alvarosimon** [apptainer/singularity#411]
This is quite simple to reproduce, singularity should be able to inherit the OS envs but `$LD_LIBRARY_PATH` is always unset within the container. 

As example  from the host:
> $ echo $LD_LIBRARY_PATH
> /apps/....

but from the container the variable is always unset (probably because singularity is executed with setuid flag and is unset for security reasons by the OS)
>$ singularity shell $VSC_DATA_VO_USER/debian_ib_drivers.img
> $ echo $LD_LIBRARY_PATH
>

This is documented in `ld.so`

The image was generated from scratch using a debian bootstrap definition file, and `/etc/singularity/init` host file looks like this:
  
> unset module
> unset BASH_ENV
> PATH="$PATH:/bin:/sbin:/usr/bin:/usr/sbin"
> HISTFILE="/dev/null"
> if [ -z "${TZ:-}" ]; then
>     TZ=`date +%Z`
> fi
> export PATH HISTFILE TZ

Any workaround to change this behaviour in singularity 2.2 to keep ` $LD_LIBRARY_PATH`? maybe we should create another variable as backup and recover the original variable within the container?

**Comment by alvarosimon** [comment]
I have tried to do something like this:

```
$ diff -Naur /etc/singularity/init.orig /etc/singularity/init
--- /etc/singularity/init.orig	2016-12-12 16:21:34.667802836 +0100
+++ /etc/singularity/init	2016-12-12 16:24:42.285398331 +0100
@@ -17,5 +17,12 @@
     TZ=`date +%Z`
 fi
 
-export PATH HISTFILE TZ
+# Set LD_LIBRARY_PATH
+if [ -n "$LD_LIBRARY_PATH" ]; then
+
+    LD_LIBRARY_PATH_COPY="$LD_LIBRARY_PATH"
+
+fi
+
+export PATH HISTFILE TZ LD_LIBRARY_PATH_COPY
```
to keep a copy, but then you have to generate again LD_LIBRARY_PATH in your container, I don't know if there is a better workaround to bypass this...

**Comment by gmkurtzer** [comment]
Hi @alvarosimon, you are right in pointing at SUID but something else to consider is that there is no guarantee that the LD_LIBRARY_PATH which works on the host will also be applicable via the container... As a matter of fact, it seems to me that this by definition may end up with ABI incompatibilities and severely stunt container portability.

Are you sharing libraries from the host operating system and binding them into the container?

**Comment by alvarosimon** [comment]
Hi @gmkurtzer 
Yes we are binding the required libraries between the hosts and the containers, we are also using modules and `/etc/modulefiles`   is included in our bind list as well. 
The only "issue" that we found for the moment is related with  `LD_LIBRARY_PATH`   variable that is unset due to the SUID, also other `LD_*`  will be affected by this security measure, so I don't know if you know a workaround to handle this in singularity...

**Comment by alvarosimon** [comment]
I was wondering if it would be possible to include an option in Singularity to include these variables even with the SUID set.. of course not a default option, just if you know (more or less :smile:) what are you doing

**Comment by gmkurtzer** [comment]
While technically it can be accomplished via a envar name rewrite, I am still concerned about the portability of a feature like this. That is because the libraries that are referenced via the host's LD_LIBRARY_PATH are not likely to be functional in non host equivalent containers.

**Comment by alvarosimon** [comment]
I see your concerns, that may break your container configuration if the libraries are not there for some reason.. but it also very handy for some hpc use cases, for example, if you are using modules and you want to import your configuration also in your container. We are generating our modules and installing our software through EasyBuild, that will be very helpful for us. EB takes care to put everything in their place.. just something to think about. 
Of course this should be an option, never used by default by Singularity.

**Comment by bbockelm** [comment]
@gmkurtzer - food for thought: `$PATH` (among other environment variables) is also passed from host through to the payload process, but it also is likely to not be relevant inside the container.  It would be beneficial to be consistent.

**Comment by boegel** [comment]
I fully agree with @bbockelm. Passing environment variables like `$PATH` into the container environment but not `$LD_LIBRARY_PATH` is just wrong/broken imho.

Ignoring `$LD_*` is done for security reasons on `setuid` programs (see section 3.3.3 in http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html), and it makes sense, but `Singularity` is a special case imho, since once you're in the container environment the security issue is no longer there imho.

The argument that passing `$LD_LIBRARY_PATH` may result in breaking things is fair, but there's multiple other ways of shooting yourself in the foot here.

So, how about an option for `singularity exec` & `singularity shell` to specify that the full environment (incl. `$LD_*`) of the host should be passed down in the container? If not enabled, the environment should be 'clean', just like you'd start an entirely new terminal session.

This also relates to #276

**Comment by vsoch** [comment]
@bauerm97 this should probably relate to the work to have the different steps we talked about in https://github.com/singularityware/singularity/pull/376#issuecomment-264425242

**Comment by bauerm97** [comment]
@vsoch Yup, was just thinking the same thing! 

The question that I'm having, is if we want to use the environment variables from whatever host the container is running on, or if we would rather have a consistent and never changing set of environment variables inside the container (no matter what host it's on). Simply grabbing all environment variables from whatever host the container is running on has the potential to break portability. If our goal is to guarantee portability to *any* host, then we should always have the same environment inside the container.

It makes sense in my mind that containers will *always* start with a clean environment, and we build up from there. For instance: 

1. Container environment is wiped totally clean
2. `/.env/00-baseenv` is sourced. This file contains all the environment variables that were present on the host during bootstrapping. 
3. `/.env/01-docker` is sourced. This file contains the environment variables that were defined inside the docker image that the container was built from (if `bootstrap: docker`)
4. `/.env/02-bootdef` is sourced. This file contains the environment variables defined by the user in the %environment section of their bootstrap definition file.

Doing this will ensure that the container will run the same way on any host that it's running on, no matter what the hosts environment looks like. Perhaps we also give the user a runtime option that allows them to override `/.env/00-baseenv` with the current hosts environment if they desire. When selected, that option will generate `00-hostenv` from the current environment inside of `sessiondir`, then bind mount the new `00-hostenv` as `/.env/00-baseenv`.

**Comment by vsoch** [comment]
+1. I was thinking that if we keep the different potential "input" sources for the environment modular (whether from the docker container that the image was created from or a custom set defined in `%environment`) then the user might have full control to specify a subset (or none) of the set at runtime. It's a hard issue because there are use cases for different possible scenarios, and as others have pointed out, setting a hard standard might break things. Something along those lines, giving the user control to make this decision (and decide to break or not) seems like a good solution, and especially if down the line we have layers of environments being included (with the potential for one layer to overwrite another).

**Comment by boegel** [comment]
Taking full control of the environment in the container makes sense to me, as long as there's an easy way to override some environment variables.

You'd need to be careful with collecting `/.env/00-baseenv` as the *full* environment of the host when bootstrapping the container though, since some things in the environment are specific to the system you are on (`$USER`, `$HOME`, etc.). How would you ensure that those are set correctly @bauerm97, and how do you tell which variables *should* be different in the container?

Also, some (sub)values are going to be irrelevant (or even harmful) in the container environment, like entries in `$PATH` that point to locations that are not accessible in the container.

**Comment by bauerm97** [comment]
@boegel This is a good question, and one I hadn't considered. If we can come up with an exhaustive list of things that we want to not be set in the container, but rather always come from the host, then those variables can always be defined in a `hostenv` file, which is then bind mounted onto an empty place-holder file inside of `/.env/01-hostenv` (or similar)

**Comment by bbockelm** [comment]
:/

Unfortunately, we pass a *ton* of environment variables (about 50 or so, some with dynamically-generated names) when we want to use Singularity to implement OS portability - as opposed to using it for portable applications.

I think the discussion is going in a good direction.  A few asks:
1.  Don't break backward compatibility with existing setups that upgrade.  The default (pass-through environment variables from environment) should remain if one uses containers constructed with the current version.
2. Allow a simple CLI way (`--clear-environ`?) to invert the defaults.  Maybe even a config file?
3. I like the general direction of having this augmented / replaced by the container configuration.

**Comment by jtriley** [comment]
Just dropping a note that I'm working on a simple clone of the nvidia-docker project for singularity that works by assembling a driver directory (using hardlinks) and then binding it into the container (so that container doesn't have to contain the host's exact version of the drivers). For this to work I need to update `LD_LIBRARY_PATH` in the container's environment, however, currently I have to modify the user's image OR prefix their `exec` commands with `env LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/nvidia/lib` to do this because of this issue. For example:
```
$ export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/nvidia/lib
$ singularity-gpu exec ./docker/cuda75.img nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
```
with the `env` hack:
```
$ singularity-gpu exec ./docker/cuda75.img env LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/nvidia/lib nvidia-smi
Fri Dec 16 10:36:52 2016
+------------------------------------------------------+
| NVIDIA-SMI 352.93     Driver Version: 352.93         |
```

I agree that this should be possible to do and isn't a security concern in this case given that `LD_LIBRARY_PATH` would be passed down into the container's environment rather than active in the SUID script's environment which is entirely the security risk. We just need a different way to get this inside the container's environment other than exporting `LD_LIBRARY_PATH` in the singularity process' environment. As you can see above we can kind of already do this using `env` it's just incredibly hard/impossible to work with.

**Comment by gmkurtzer** [comment]
I want to clarify a few things. The risk of `LD_LIBRARY_PATH` is two fold. The first is because the program path of Singularity itself relies on a SUID program, and we thus the linker itself will drop the `LD_LIBRARY_PATH` such that `sexec` itself can't be used for a library preload attack. The second risk or rather issue is what I articulated above, that any libraries that are shared from the host are not guaranteed to be compatible with the applications inside the container, and that could lead to difficult to diagnose problems.

I agree with @boegel's comment above about allowing `PATH` but not `LD_LIBRARY_PATH`. That was not directly a conscious decision. Singularity itself isn't specifically changing anything within the user's environment outside of `SINGULARITY_` specific environment variables. While this point makes sense, and we probably should do a deliberate sanitization of certain envars like `PATH` and `LD_LIBRARY_PATH`.

Lastly, I have been speaking with some of the Nvidia team and I think the best route will be to have a module within Singularity that specifically finds the CUDA libraries and passes them into the container at an appropriate place. From this module, we can easily add this path to the `LD_LIBRARY_PATH`.

Generally I do not like the idea of making `LD_LIBRARY_PATH` translate inside the container. There are ways to do it safely without exposing the sexec binary to a preload hack but I'm not sure it gains us much within the container. Can someone give me an example use case that would articulate this?

**Comment by gmkurtzer** [comment]
I spoke with @jtriley in Slack and he convinced me to create a workaround using `SINGULARITY_LD_LIBRARY_PATH`. If that is set, sexec will automatically use that defined string for `LD_LIBRARY_PATH`. This gets done after sexec has been executed (and thus linked) and right before we execute the command within the container.

**Comment by gmkurtzer** [comment]
And here is the example usage:

```bash
$ SINGULARITY_LD_LIBRARY_PATH=/test_path singularity shell /tmp/Centos7-ompi.img 
Singularity: Invoking an interactive shell within container...

Singularity.Centos7.img> echo $LD_LIBRARY_PATH
/test_path
Singularity.Centos7.img> 
```

**Comment by alvarosimon** [comment]
there are several options, I was thinking about:

a) binary option just pass  every env variable or just a clean container env.

b) only a group of them, similar to directories and files binding, instead of `-B /apps`   or `bind path = /apps`    something like `-E LD_LIBRARY_PATH`   and `bind env = LD_LIBRARY_PATH`   or even...
`-E  host_env:container_env`  

both options have pros and cons...

**Comment by gmkurtzer** [comment]
With the latest update to "development" branch, you can now set any variable you want inside the container by prefixing it with "SINGULARITYENV_". It will be transposed automatically and the prefix will be stripped.

I think that satisfies this PR so I am closing it. If not, comment and let me know so I can reopen.
