### ISSUE TITLE
Add whitelist/blacklist option for environment variables when running containers

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4127]
## Version of Singularity:

n/a.

### Expected behavior

- Be able to specify whitelists of environment variables, preferably with wildcard support (e.g., SLURM_*), that are allowed (always?) to pass from host/calling environment to the containers.
- Be able to specify blacklists of environment variables, preferably with wildcard support, that are blocked from being passed from host/calling environment to the containers.
- Be able to specify both on the command line or in a configuration file.

### Actual behavior

Currently not supported.

### Steps to reproduce behavior

n/a.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@gvallee Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Pending issues from the old repo are copied to the new repo (https://github.com/apptainer/apptainer/issues/1388) and cleaned from the old retired repo.
