### ISSUE TITLE
Cleanup CLI package

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4128]
1. Introduce common errors for each CLI call

**Comment by pisarukv** [comment]
2. Move init to the top of the file :)
3. Overall, return nil errors only in case of successful execution.
4. Call os.Exit, log.Fatal only in main or somewhere near it.

**Comment by cali4888** [comment]
3. Overall, return nil errors only in case of successful execution.

**Comment by jscook2345** [comment]
@sashayakovtseva @cali4888 

I think these are good things to do in general, not just in the `cli` package.

Something to consider while you do this work: Is it possible to introduce `lint` rules or create `lint` rules with our linter to make sure we avoid some of these issues in the future?

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@sashayakovtseva Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Moved to the new Apptainer repo issue https://github.com/apptainer/apptainer/issues/1157
