### ISSUE TITLE
Bootstrap History Removed

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#4134]
I might be looking in the wrong spot, but I can no longer find any bootstrap-history folder, where in the case of an image being a base (localimage) or built over by a second, we would maintain all of the recipes for reproducibility. To trigger your memory, here is the simple way it used to work:

https://github.com/sylabs/singularity/blob/vault/release-2.6/libexec/bootstrap-scripts/deffile-sections.sh#L453

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by vsoch** [comment]
If this is still an issue please fix, thanks!

**Comment by vsoch** [comment]
Don't close stalebot, the contributors to this issue have responded and it's the maintainers that have not.

**Comment by pedroalvesbatista** [comment]
@vsoch We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Pending issues from the old repo is now copied to the new repo (https://github.com/apptainer/apptainer/issues/1394) and cleaned from the old, retired repo.
