### ISSUE TITLE
Singularity images should be reversible back to Docker

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#414]
If we can import Singularity from Docker, we should also be able to export Singularity back to Docker. We will need to think about what this means in terms of metadata, etc. Minimally, we could have a Singularity build files commands translated into the matching Dockerfile commands.

**Comment by ArangoGutierrez** [comment]
With the OCI compliance efforts on going, this issue can become a PR in the near future.
Considerations:
 - As you said, `reversible`, the first requirement must be that the image came from a docker registry. Otherwise it will be really difficult to revert.
 - SIF don't handle the rootFS with layers as [Docker AUFS](https://docs.docker.com/storage/storagedriver/aufs-driver/) does.

I think the workflow on this will be to export the rootFS to a tar file an them run `docker import`, taking into account the the tar file will also have the [config.json](https://github.com/opencontainers/image-spec/blob/master/schema/config-schema.json) OCI compatible.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by vsoch** [comment]
I would up implementing a Singularity Python recipe converter, but it doesn’t do any image conversion. If a singularity image can be dumped into one layer it seems reasonable that a Docker conversion would be easy to do. See https://github.com/singularityhub/singularity2docker for logistics.

**Comment by vsoch** [comment]
Don't close stalebot, the contributors to this issue have responded and it's the maintainers that have not.

**Comment by pedroalvesbatista** [comment]
@vsoch We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by kmuriki** [comment]
Old singularity repo issues are being ported to the new Apptainer issues
https://github.com/apptainer/apptainer/issues/624

**Comment by wilke** [comment]
I think this is a great feature. Being able to push singularity images to any container registry, e.g. docker hub.

**Comment by vsoch** [comment]
@wilke this is already possible with ORAS. See https://github.com/singularityhub/github-ci.

However this is fundamentally different from a conversion back to Docker, which the PR is asking for. It is technically possible: https://github.com/singularityhub/singularity2docker but could be better supported.
