### ISSUE TITLE
Cache management code should not directly handle the environment variables

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4192]
## Version of Singularity:

master.

### Expected behavior

Checking the environment variables should be done as close as possible to the CLI code. As a result, the code for the management of image caches should not include any call to `os.Getenv()` or `os.Setenv()`.

The CLI code should therefore look like:
```
var cacheEnv cache.Env
cacheEnv.CacheDir = os.Getenv(cache.DirEnv)
cacheEnv.DisableCache = os.Getenv(cache.DisableEnv

c := cache.NewHandle(cacheEnv)
```

Then, the code that implements the image cache only need to rely on the environment that is specified in the `Env` argument.

### Actual behavior

The current implementation checks both `SINGULARITY_DISABLE_CACHE` and `SINGULARITY_CACHEDIR`.

### Steps to reproduce behavior

Write here.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@gvallee Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping interest over the subject.

**Comment by kmuriki** [comment]
Moved to the new Apptainer repo issue. https://github.com/apptainer/apptainer/issues/1157
