### ISSUE TITLE
[E2E] 'key newpair' add tests for not using a password

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#4223]
## Version of Singularity:

```
3.3
```

### Expected behavior

We should be testing `key newpair` (and all the key commands) that does not have a password.

The e2e testing _should_ have caught this issue https://github.com/sylabs/singularity/pull/4221#pullrequestreview-276030131, https://github.com/sylabs/singularity/pull/4221.

Related to: https://github.com/sylabs/singularity/pull/3968

### Actual behavior

Not tested yet.

### Steps to reproduce behavior

Write here.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@WestleyK Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping interest over the subject.

**Comment by kmuriki** [comment]
Copied to the new Apptainer issue list. https://github.com/apptainer/apptainer/issues/1155
