### ISSUE TITLE
'cache clean --dry-run' is ignored

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#4225]
## Version of Singularity:

```
3.3.0-736.g2e524b566
```

### Expected behavior

`--dry-run` should not be interactive and should print what will be removed, imo.

```
$ singularity cache clean --dry-run
Would remove ...
```

### Actual behavior

```
$ singularity cache clean --dry-run
This will delete everything in your cache (containers from all sources and OCI blobs). 
Hint: You can see exactly what would be deleted by canceling and using the --dry-run option.
Do you want to continue? [N/y] 
```

WHAT?! I already specified the `--dry-run` flag! _seems to be ignored._

### Steps to reproduce behavior

```
$ singularity cache clean --dry-run
```

**Comment by sashayakovtseva** [comment]
As I remember, we discussed this and everyone agreed this is the behavior we want.
@GodloveD correct me if I am wrong, I was following [your suggestion](https://github.com/sylabs/singularity/pull/4105#issuecomment-517788320).

**Comment by GodloveD** [comment]
Actually this is not really the behavior that I had envisioned, but I think that I should have been more specific.  I agree with @WestleyK that the `--dry-run` option should be non-interactive.  afaik, traditionally, a `--dry-run` option will print everything to the screen that would have happened when the command was executed, but will not actually perform any actions.  

But this is a little funny because nothing is actually printed to the screen when we do a `cache clean`.  So let me suggest some more changes.  

First, let's change the `cache clean` command so that it prints some std out by default.  If the user wants to suppress output they can use the `singularity --quiet` or `singularity --silent` options.  Here are the specific things I think that a normal cache clean should print out.  Given the following cache:
```
$ singularity cache list --verbose 
NAME                     DATE CREATED           SIZE             TYPE
lolcow_latest.sif        2019-08-21 11:45:49    93.57 MB         library
lolcow_latest.sif        2019-08-21 11:45:10    92.23 MB         oci
lolcow_latest.sif        2019-08-21 11:46:12    91.83 MB         shub
3b61febd4aefe982e0cb9c   2019-08-21 11:44:52    0.85 kB          blob
73d5b1025fbfa138f2cacf   2019-08-21 11:44:57    3.41 kB          blob
7fac07fb303e0589b9c23e   2019-08-21 11:44:54    0.17 kB          blob
8e860504ff1ee5dc795367   2019-08-21 11:44:57    56.36 MB         blob
9d99b9777eb02b8943c0e7   2019-08-21 11:44:53    0.62 kB          blob
9fb6c798fa41e509b58bcc   2019-08-21 11:44:52    47.54 MB         blob
d010c8cf75d7eb5d2504d5   2019-08-21 11:44:53    0.85 kB          blob
f2a852991b0a36a9f3d6b2   2019-08-21 11:44:57    1.12 kB          blob

There are 3 container file(s) using 277.63 MB and 8 oci blob file(s) using 103.90 MB of space
Total space used: 381.53 MB
```
We should expect the following output with a `cache clean`:
```
$ singularity cache clean --force 
Singularity will remove the following container data:
lolcow_latest.sif        
lolcow_latest.sif        
lolcow_latest.sif       
3b61febd4aefe982e0cb9c  
73d5b1025fbfa138f2cacf  
7fac07fb303e0589b9c23e  
8e860504ff1ee5dc795367  
9d99b9777eb02b8943c0e7  
9fb6c798fa41e509b58bcc  
d010c8cf75d7eb5d2504d5  
f2a852991b0a36a9f3d6b2
```
Or if we had specified a type:
```
$ singularity cache clean --type library --force 
Singularity will remove the following container data:
lolcow_latest.sif  

$ singularity cache clean --type blob --force 
Singularity will remove the following container data:      
3b61febd4aefe982e0cb9c  
73d5b1025fbfa138f2cacf  
7fac07fb303e0589b9c23e  
8e860504ff1ee5dc795367  
9d99b9777eb02b8943c0e7  
9fb6c798fa41e509b58bcc  
d010c8cf75d7eb5d2504d5  
f2a852991b0a36a9f3d6b2  
```
Obviously this info would also be presented to the user if they selected `y` at the `[N/y]` prompt without the `--force` flag, and it could be suppressed with the `--quiet` or `--silent` flag.  

After making that change, it is easy to see how the `--dry-run` option would work.  
```
$ singularity cache clean --dry-run
User requested a dry run.  Not actually deleting any data!
Singularity will remove the following container data:
lolcow_latest.sif        
lolcow_latest.sif        
lolcow_latest.sif       
3b61febd4aefe982e0cb9c  
73d5b1025fbfa138f2cacf  
7fac07fb303e0589b9c23e  
8e860504ff1ee5dc795367  
9d99b9777eb02b8943c0e7  
9fb6c798fa41e509b58bcc  
d010c8cf75d7eb5d2504d5  
f2a852991b0a36a9f3d6b2
```
Or if we had specified a type:
```
$ singularity cache clean --type library --dry-run
User requested a dry run.  Not actually deleting any data!
Singularity will remove the following container data:
lolcow_latest.sif  

$ singularity cache clean --type blob --dry-run
User requested a dry run.  Not actually deleting any data!
Singularity will remove the following container data:      
3b61febd4aefe982e0cb9c  
73d5b1025fbfa138f2cacf  
7fac07fb303e0589b9c23e  
8e860504ff1ee5dc795367  
9d99b9777eb02b8943c0e7  
9fb6c798fa41e509b58bcc  
d010c8cf75d7eb5d2504d5  
f2a852991b0a36a9f3d6b2  
```
Sorry that I was not very specific before and I basically expected people to read my mind.  How does this look to everyone?

**Comment by sashayakovtseva** [comment]
@GodloveD okay, will work on the fix. Thanks.
