### ISSUE TITLE
[e2e] Verify test: extend the current test to verify that the image is correctly signed after signing

### ISSUE THREAD

**Issue by gvallee** [apptainer/singularity#4229]
## Version of Singularity:

master.

### Expected behavior

This is in the context of the e2e tests only.
After signing an image, we should verify that it is correctly signed by verifying the image.

### Actual behavior

At the moment, we only check the exit code and the output; we do not verify the image. 

### Steps to reproduce behavior

n/a.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@gvallee Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping interest over the subject.

**Comment by kmuriki** [comment]
Copied to the new Apptainer issue list. https://github.com/apptainer/apptainer/issues/1155
