### ISSUE TITLE
build fails on rhel7

### ISSUE THREAD

**Issue by ashwinidr3** [apptainer/singularity#4246]
## Version of Singularity:

version 3.1.1
### Expected behavior

build the image
### Actual behavior

build fails with following error

WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: error making request to server:
        Get https://library.sylabs.io/v1/images///ubuntu:latest: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

all the commands work fine with normal user, but fails with sudo. since i am trying to convert the image to sandbox i need to do it as sudo and it is failing

### Steps to reproduce behavior

sudo singularity build --sandbox ubuntu/ library://ubuntu

**Comment by dtrudg** [comment]
Hello @ashwinidr3  - does your site use a web proxy? Generally if things network operations work well as a user, but fail with `sudo` this is a suspect - as sudo won't generally preserve the proxy variables by default.

**Comment by ashwinidr3** [comment]
Thank you for your response,proxy settings are indeed there in our cluster.
But I did add those before running the command.


One more thing I noticed - on one of the clusters the build works with
docker library images( was trying to convert docker images to sandbox ) and
not singularity.

On the other cluster neither docker nor singularity images are working. Any
suggestions?

Thanks and regards,
Ashwini

**Comment by dtrudg** [comment]
@ashwinidr3 this is still likely due to proxy settings. The libraries we use to access docker hub etc. may be picking up proxy settings slightly differently resulting in the mixed behavior you are seeing.

You say you set the proxy settings before running the command. Do you mean you set them _inside_ your `sudo` environment, as root - or before you ran `sudo`? If you set them before you run `sudo` they will not be available inside the `sudo` environment by default. You can try...

`sudo -E singularity build --sandbox ubuntu/ library://ubuntu`

.. in this case.

If you believe you should have the environment set inside of `sudo` try to run `sudo env | grep -i proxy` to verify that they are indeed going to be visible to singularity.

**Comment by GodloveD** [comment]
Heya @ashwinidr3 can you verify whether using the `-E` option or otherwise making sure that proxy env vars are present in sudo environment fixes this issue?  For now, I'll assume that it does and close, but please holler if the issue should be re-opened.

**Comment by ashwinidr3** [comment]
The  -e option did not work, but it's was proxy issue indeed. I got it
around by including proxy with the command itself.
Thanks for your help.

**Comment by GodloveD** [comment]
Thanks for the update @ashwinidr3.  Hopefully this issue helps somebody else with a similar problem in the future.
