### ISSUE TITLE
Add e2e tests for ext3 concurrent writes

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#4273]
To keep PR #4069 smaller, this will be done in a separate PR. The idea is to run multiple instances with both ext3 overlay image and ext3/SIF container images to all possible scenario where locking is done.

Also related to issue #4048

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@cclerget Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping interest over the subject.

**Comment by kmuriki** [comment]
Copied to the new Apptainer issue list. https://github.com/apptainer/apptainer/issues/1155
