### ISSUE TITLE
Add e2e test for when a user does not have a home directory

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#4276]
There is an e2e test for the situation in which a user's home directory is not writable, but there does not seem to be a test for the situation in which no home directory exists.  This is a slightly different situation and can result in errors that the non-writable scenario will not.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@GodloveD Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping interest over the subject.

**Comment by kmuriki** [comment]
Copied to the new Apptainer issue list. https://github.com/apptainer/apptainer/issues/1155
