### ISSUE TITLE
OpenMPI inside/outside Singularity

### ISSUE THREAD

**Issue by saidamirouche** [apptainer/singularity#4288]
Hello every body,

I have a question that i cant get a logical answer to it, i wish that you can make my mind more clear about it : 

The main goal of singularity containers is to be able to run programs independantly on clusters, no matter what version or set up configuration is on the cluster.

So Why there is the condition that OpenMPI of the system must be the same as the one installed on Singularity Container? and if we're going to use OpenMPI of the system, what's the use of the OpenMPI inside the image ?

Thank you for your clarifications. 

Said

**Comment by gvallee** [comment]
@saidamirouche to execute any MPI application with containers, you have two options:
- **The hybrid model** - You rely on the `mpirun` command on the host to start the containers and therefore the MPI ranks in the containers. This is fairly portable since it relies on the `mpirun` command of MPI implementation installed on the host system and not on specificities of the implementation itself (which I will explain a little bit in the next point). However, this requires that the MPI implementation on the host (which is used to run the `mpirun` command) to be compatible with the MPI implementation used in the containers: the MPI library invoked by `mpirun` on the host needs to *talk* to the MPI library used in the containers, therefore they need to be compatible. A classic example is the wire-up of the MPI libraries on the different nodes, which is basically an exchange of information so that the MPI rank can be correctly initialized.
- **The native model** - You do *not* rely on the MPI implementation of the host system but rely only on the MPI implementation in the container. This approach is specific to the MPI implementation that is used. For example, with Open MPI, this requires to change how the daemons running on the nodes are starting the MPI ranks. This does not involve the MPI implementation installed on the host but is usually considered as being a little more complicated to setup.

Also, we have a slack workspace that can be used for questions that may be more efficient than GitHub issues: singularity-container.slack.com

**Comment by GodloveD** [comment]
@saidamirouche I'm closing this since it seems that @gvallee did a great job answering.  If you want me to re-open just say so plz.
