### ISSUE TITLE
why is a valid Docker image not good for Singularity?

### ISSUE THREAD

**Issue by czka** [apptainer/singularity#429]
I built a valid Docker image `archlinux-bootstrap-x86_64` with [this Dockerfile](https://github.com/czka/archlinux-docker/blob/master/Dockerfile).

Trying to import it to Singularity now:

```
$ docker save archlinux-bootstrap-x86_64 | sudo singularity import archlinux-bootstrap-x86_64.img
Assuming import from incoming pipe
Bootstrap initialization
No bootstrap definition passed, updating container
Executing Prebootstrap module
Executing Postbootstrap module
ERROR: Container does not contain the valid minimum requirement of /bin/sh
```

What does the `Container does not contain the valid minimum requirement of /bin/sh` error mean? How do I fix my Docker image so that Singularity accepted it?

It's Singularity 2.2.

**Comment by vsoch** [comment]
Hey @czka !

I haven't done much with docker save, so I decided to give it a try. One quick note about your instructions - you don't just need python 3, you need at least 3.5. Here is running with python 3.4.x:

       python3 tar_fix.py --input=archlinux-bootstrap-2016.12.01-x86_64.tar.gz --output=bootstrap.tar.gz
       Traceback (most recent call last):
       File "tar_fix.py", line 67, in <module>
       tarball.drop_lead_comp()
       File "tar_fix.py", line 22, in drop_lead_comp
       lead_comp_name = os.path.commonpath(tarin.getnames())
       AttributeError: 'module' object has no attribute 'commonpath'

I then reproduced your error, and then tried looking at what docker save is exporting:

![image](https://cloud.githubusercontent.com/assets/814322/21467344/f04fba3c-c99e-11e6-8030-e41a9b91b10d.png)

It looks likei it's a tar of layers, where each is additionally tarred. So the reason it's not working is likely because you are extracting the above into the image, which is correct, is not a valid image. You could go this path if you additionally extracted those layer.tar in the image. I'll show you how to do it differently, using the method supported by the Singulraity software.

Try this - run a local registry, push your image to it, then Bootstrap.

## Step 1: Run local registry
Deploy the local registry, which is a docker image itself

      docker run -d -p 5000:5000 --restart=always --name registry registry:2


## Step 2: Add your image
Tag your image to give it the uri for the registry
  
      docker tag archlinux-x86_64-base localhost:5000/archlinux-x86_64-base

Here I am pushing the image I built (seen via docker images) to the locally running registry on port 5000

      docker push localhost:5000/archlinux-x86_64-base
      The push refers to a repository [localhost:5000/archlinux-x86_64-base]
      5a1a6d049e84: Pushed 
      cfddd09dab9c: Pushed 
      latest: digest: sha256:7e7dba1b859aafe51ead66352734c390f08d8e46307cf94b0f187846e96df585 size: 742


## Step 3: Bootstrap from build file
Then in a bootstrap spec file, Singularity, do:

      BootStrap: docker
      From: /archlinux-x86_64-base:latest
      IncludeCmd: no
      Registry: http://localhost:5000

Note the / in front of the image name - this is important so we set the namespace to be empty
you could equally try adding some different namespace (in the tag above) but this seemed cleanest to me. You also don't need the IncludeCmd, that would substitute `ENTRYPOINT` for `CMD` so choose based on your preference.

and then the bootstrap should work:
  
      sudo singularity create test.img
      sudo singularity bootstrap test.img Singularity


## Step 4: Run/test it
Did it work?

       ./test.img 
      No Singularity runscript found, executing /bin/sh
      Singularity.test.img> 

Note that I'm using a newer version (likely close to current master) of the software, although you could definitely give it a try with the one you have before upgrading (in case it's an older one).

Hope that helps! I'll write up some better docs for doing this for the site, going back to sleep for a bit though :) Happy Holidays!

**Comment by czka** [comment]
I see. So, in short, even though `singularity import` can't digest a Docker image, which consists of many layers, it will import a single image layer just fine. And since Docker container is just a yet another layer on top of the image layer stack, the following works:

`docker run --name for_export archlinux-bootstrap-x86_64 /bin/true`
`sudo singularity create imported.img`
`docker export for_export | sudo singularity import imported.img`
`docker rm for_export`

Thanks for the Python 3.5 hint - README.md updated. Sleep well :).

**Comment by hartzell** [comment]
@cska @vsoch 

If [the trick in the final comment](https://github.com/singularityware/singularity/issues/429#issuecomment-269089311) is "legal" it would be a great addition to the FAQ's.  It's easier than running a registry and pushing back and forth.

I'll PR it to the docs-docker page if there's not something fundamentally wrong about it.

**Comment by vsoch** [comment]
I think the easiest thing is still to do:

    sudo singularity import image.img docker://analysis/image

but by all means if you want to summarize a problem with a different solution, that will likely be useful to someone!

**Comment by hartzell** [comment]
👍

**Comment by gmkurtzer** [comment]
You  might also have been hitting a bug in archlinux where /bin/sh was a link that did not resolve from a mountpoint. Please confirm if this is the case. Additionally, I believe this is fixed in the "development" branch. Can you test?
