### ISSUE TITLE
Can't set a passphrase on an RSA key for encrypted containers

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#4294]
## Version of Singularity:

```
$ singularity --version
singularity version 1b4fe41b8
```
### Expected behavior

I expect to be able to create an RSA key with a passphrase, encrypt a container with the PEM file and then use the private key with the passphrase to run the container.  
### Actual behavior
When I try to run the container with the private key to which the passphrase was attached I get an unhandled stack trace.
```
$ singularity shell --pem-path=rsa encrypted.sif
FATAL:   Cannot retrieve key from image /home/dave/containers/encrypted.sif: asn1: syntax error: non-minimal tag
loading private key for key decryption
github.com/sylabs/singularity/pkg/util/crypt.PlaintextKey
	pkg/util/crypt/key.go:104
github.com/sylabs/singularity/cmd/internal/cli.execStarter
	cmd/internal/cli/actions_linux.go:284
github.com/sylabs/singularity/cmd/internal/cli.glob..func2
	cmd/internal/cli/actions.go:428
github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:914
github.com/sylabs/singularity/cmd/internal/cli.ExecuteSingularity
	cmd/internal/cli/singularity.go:246
main.main
	cmd/singularity/cli.go:17
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337

```
### Steps to reproduce behavior

Use `ssh-keygen` to create an RSA key and attach a passphrase.  Create the PEM file and use it to encrypt the container.  Then try running with the private RSA key.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@GodloveD Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping interest over the subject.
