### ISSUE TITLE
Encrypting a container should also encrypt the deffile partition

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity#4316]
## Version of Singularity:

```
v3.4
```

### Expected behavior

When encrypting a container, it should also encrypt the deffile partition. Imo should not remove that partition, (that would be inconsistent, and will break `inspect` (pending https://github.com/sylabs/singularity/pull/4306)).

### Actual behavior

Dose not encrypt the deffile partition yet...

### Steps to reproduce behavior

Write here.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment]
@WestleyK Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping interest over the subject.
