### ISSUE TITLE
Unclear error when decryption fails due to RAM limitation

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4336]
## Version of Singularity:

3.4.0-rc.1

### Expected behavior

If there is a decryption failure due to #4162 (RAM on decrypting host < 2GB and << encrypting host) the error message reports a specific error, e.g.:

`FATAL: Could not decrypt, insufficient memory available`

### Actual behavior

A confusing error message is reported, which does not indicate the cause of the failure:

```
singularity run --pem-path ~/pair1_rsa.key testing_0.2.sif
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: unable to decrypt the file system: cryptsetup open failed: : <nil>
```

### Steps to reproduce behavior

1. Encrypt a container on a machine/VM with >2GB of RAM
2. Try to run the container on a machine/VM with 1GB or less RAM and no swap, or RAM+Swap <1GB

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
