### ISSUE TITLE
Key newpair command should fail if an argument is missing in non-interactive mode

### ISSUE THREAD

**Issue by pisarukv** [apptainer/singularity#4347]
Discussion under pr https://github.com/sylabs/singularity/pull/4240

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
