### ISSUE TITLE
Label Schema Deprecation

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#4362]
This is more of a discussion item than an action, as I'm not sure how to address! The entire label schema specification, which is used by Docker, GitHub actions, and Singularity here is being deprecated http://label-schema.org/rc1/.

It's disappointing, and I'm not sure what action to take because it's so widely used, across containers. For now I'll open it as an FYI so if (in the future) some action is taken, we have an issue for it.

**Comment by dtrudg** [comment]
Thanks for noting this here Vanessa. This is a shame, since the label-schema isn't tied to a specific image format specification.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by vsoch** [comment]
This should be discussed by your developers, because it would be ok to leave but long term is probably not ideal using a deprecated standard.

**Comment by vsoch** [comment]
Don't close stalebot, the contributors to this issue have responded and it's the maintainers that have not.

**Comment by kmuriki** [comment]
Pending issues from the old repo is now copied to the new repo (https://github.com/apptainer/apptainer/issues/1393) and cleaned from the old, retired repo.
