### ISSUE TITLE
`hostname` output differs on linux vs macOS desktop

### ISSUE THREAD

**Issue by bjarthur** [apptainer/singularity#4364]
running `hostname` on lolcow results in entirely different answers on linux vs. macOS desktop, even with `-i` or `-I`.  should be the same, no?

relatedly, the progress bar shown when downloading an image on linux is really nice.  can we get that on mac too please?

```
$ cat /etc/*-release
NAME="Scientific Linux"
VERSION="7.4 (Nitrogen)"
ID="rhel"
ID_LIKE="scientific centos fedora"
VERSION_ID="7.4"
PRETTY_NAME="Scientific Linux 7.4 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.4:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
Scientific Linux release 7.4 (Nitrogen)
Scientific Linux release 7.4 (Nitrogen)
Scientific Linux release 7.4 (Nitrogen)

$ singularity --version
singularity version 3.2.1-1.1.el7

$ singularity exec library://sylabsed/examples/lolcow hostname
INFO:    Downloading library image
 79.91 MiB / 79.91 MiB [==========================================] 100.00% 6.54 MiB/s 12s
arthurb-ws2

$ singularity exec library://sylabsed/examples/lolcow hostname -i
10.150.100.16

[$ singularity exec library://sylabsed/examples/lolcow hostname -I
10.150.100.16 192.168.122.1 172.17.0.1 
```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

$ singularity --version
singularity version 3.3.0-rc.1.658.g7427b73f1.dirty

$ singularity exec library://sylabsed/examples/lolcow hostname
INFO:    Downloading library image
(none)
[    4.343497] reboot: Power down

$ singularity exec library://sylabsed/examples/lolcow hostname -i
hostname: Temporary failure in name resolution
[   14.779143] reboot: Power down

$ singularity exec library://sylabsed/examples/lolcow hostname -I
192.168.64.32 
[    4.784623] reboot: Power down
```

**Comment by bjarthur** [comment]
https://groups.google.com/a/lbl.gov/forum/#!msg/singularity/Subsp7IMzPE/R6AmmIRcBgAJ

**Comment by jmstover** [comment]
@bjarthur ... Have a PR to pass the name. Missed the `hostname -I` info... That will *not* be the same because of how the networking works.

The container network is attached to a bridge under the control of vmnet.Framework. Apple passes traffic in special cases (uhh... it *must* assign an address over dhcp :( ), but it's a separate network from the host (defaults to `192.168.64.0/24`). So, if you run a container that has a web server running on port 8080, then do:

`telnet [IP] 8080`

You'll connect to that webserver on the container IP. Use the `-v` flag to get the IP if you need to.

Some of these are controlled by the files:
`/Library/Preferences/SystemConfiguration/com.apple.vmnet.plist`  --- At the end it will give you the network block
`/var/db/dhcpd_leases` --- We don't keep the same Mac on every execution, so the IP changes. You can clean that up here. If we hardcoded a Mac ... then you'd only ever be able to run one with networking, or you'd get a Mac collision.

You need to reboot if you modify either of those files. They're loaded by `vmnet.Framework` early on and hold that configuration from what I've seen.
