### ISSUE TITLE
Cloning git and access to scripts

### ISSUE THREAD

**Issue by Lcornet** [apptainer/singularity#4371]
## Version of Singularity:

2.5.2-dist

### Expected behavior

singularity exec cider.simg eccDNA.py 
Usage: cs-eccDNA.py [OPTIONS] LIST_FILE GENOME_FILE
Try "cs-eccDNA.py --help" for help.

Error: Missing argument "LIST_FILE"

### Actual behavior

singularity exec cider.simg cs-eccDNA.py
/.singularity.d/actions/exec: 9: exec: cs-eccDNA.py: not found

### Steps to reproduce behavior

I have a git repository and i want to put all dependencies ect in a container.
This the log :
 sudo singularity build --force cider.simg Singularity.log

BootStrap: debootstrap
OSVersion: xenial
MirrorURL: http://us.archive.ubuntu.com/ubuntu/

%files
    /home/ulg/Documents/program/CIDER-singularity/prog/ncbi-blast-2.9.0+-x64-linux.tar.gz /mnt
    /home/ulg/Documents/program/CIDER-singularity/prog/muscle3.8.31_i86linux64.tar /mnt

%environment
    export LISTEN_PORT=12345
    export LC_ALL=C
    export PATH=/root/ncbi-blast-2.9.0+/bin:$PATH
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    export PATH=/root/ciderseq2/eccDNA:$PATH
    export PATH=/root/ciderseq2:$PATH

%post
    echo "Hello from inside the container"
    sed -i 's/$/ universe/' /etc/apt/sources.list
    apt-get update
    apt-get -y install vim
    apt-get clean
    #CIDER seq modules part
    apt-get -y install software-properties-common
    add-apt-repository ppa:deadsnakes/ppa
    apt-get update
    apt-get -y install python3.6
    apt-get -y install python3-pip
    pip3 install --upgrade pip
    python3.6 -m pip install Biopython
    python3.6 -m pip install matplotlib
    python3.6 -m pip install Numpy
    python3.6 -m pip install Click
    #Cider git
    apt-get -y install git
    git clone https://github.com/devang-mehta/ciderseq2
    chmod 755 /root
    #Blast NCBI part
    tar -xzvf /mnt/ncbi-blast-2.9.0+-x64-linux.tar.gz -C /root/
    #Muscle part
    tar -xvf /mnt/muscle3.8.31_i86linux64.tar -C /root
    mv /root/muscle3.8.31_i86linux64 /root/ciderseq2
    #define python3.6 (needed for matplotlib) as global python
    ln -s /usr/bin/python3.6 /usr/bin/python

%runscript
    echo "This is what happens when you run the container..."

When I Shel into the container, the script is available :  
--
sudo singularity shell cider.simg
Singularity cider.simg:~> cs-eccDNA.py 
Usage: cs-eccDNA.py [OPTIONS] LIST_FILE GENOME_FILE
Try "cs-eccDNA.py --help" for help.

Error: Missing argument "LIST_FILE"
--

With exec, i have the following error : 
singularity exec cider.simg cs-eccDNA.py
/.singularity.d/actions/exec: 9: exec: cs-eccDNA.py: not found

Can you help me to solve this issue?

**Comment by dtrudg** [comment]
Hello @Lcornet 

A couple of best-practice pointers before we dig into this for you further:

1. Singularity 2.5.2 is not supported / patched for known, or any future security issues. If you are unable to use the 3.x series, please try to move to at least 2.6.1 if possible: https://github.com/sylabs/singularity/releases/tag/2.6.1 - but note that 3.x is where all development is occurring.

2. In general, you should try to avoid installing software into `/root`. It's better to put software in e.g. `/opt` `/usr/local` if you can. Also, setting `python-3.6` to be `/usr/bin/python` may cause unexpected behavior beyond the issues you are experiencing - since the system python is expected to be a certain version, and may be used by other system-packaged tools that your workflow might invoke.

If you can use Singularity 2.6.1 or a 3.x and experience the same behavior I'd be happy to look into it further.

**Comment by dtrudg** [comment]
I'm going to close this issue as there was no follow-up from the suggested best practices. If you have the issue on a current version of Singularity please feel free to re-open.
