### ISSUE TITLE
Indicate which container formats are supported by which version of singularity

### ISSUE THREAD

**Issue by chrisgorgo** [apptainer/singularity#444]
There are multiple versions of singularity installed on different systems at the moment. It would be beneficial for users to indicate which version of Singularity is required to run different types of images http://singularity.lbl.gov/user-guide#other-container-formats-supported.

**Comment by vsoch** [comment]
+1 on this. @gmkurtzer do the earliest versions support these types? I think what we need is better documentation on how to generate those image types, for example to compress the image properly (from python) I had to do:

         # Compress image
        compressed_image = "%s.img.gz" %image
        os.system('gzip -c -9 %s > %s' %(image,compressed_image))

and then standard creation and bootstrap, which is different from the entire line up of things that I was attempting before that one. :)

**Comment by gmkurtzer** [comment]
I would have to look at the Release notes on GitHub to see when each format was introduced. I think they were introduced in 2.2 and before that Singularity just supported the image format.

**Comment by chrisgorgo** [comment]
Is squashfs support only in current master or also in 2.2?

**Comment by vsoch** [comment]
I'll let others comment, but I'm pretty sure that most of the features added after the 2.2 initial release were not back-propagated into the previous release. There might have been one or two essential bug fixes, but likely not the squashfs. We are going to be restructuring the repo workflow for the next release so the `master` branch contains the current version, and additions/features added since (eg, our current master) will be in a `devel` branch.

**Comment by gmkurtzer** [comment]
Help output will now show the supported container formats.
