### ISSUE TITLE
Shelling into an encrypted container should prompt for password

### ISSUE THREAD

**Issue by rherban** [apptainer/singularity#4448]
## Version of Singularity:

3.4+

### Expected behavior

If we are `shell`ing into an encrypted container, would be nice to prompt for password if neither of the ENV vars are set.  Shell already implies an interactive workload.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
