### ISSUE TITLE
Remote builds: Allow external files to be copied to remote

### ISSUE THREAD

**Issue by dmey** [apptainer/singularity#4455]
When using the `--remote` option for building images, any additional file required during the build (e.g. `environment.yml` files used to install package in Anaconda) are not uploaded to the remote, thus leading to the build to fail. This results in a different behaviour between local (where this is allowed) and remote.

**Comment by dtrudg** [comment]
Currently this is a limitation of remote builds. If you are able to host the files on an internet accessible server / git repo then you would be able to fetch them via a `curl` or `wget`, or `git` operation in the definition file when building remotely.

**Comment by letmaik** [comment]
@dctrud This should be documented somewhere. Is there a plan to lift this limitation in the future?

**Comment by dtrudg** [comment]
> This should be documented somewhere. 

Agreed - work to improve some of our docs is planned. They are also hosted in a GitHub repo here: https://github.com/sylabs/singularity-userdocs/ and issue reports, contributions are very welcome

> Is there a plan to lift this limitation in the future?

Will defer to @EmmEff on this question.

**Comment by agilly** [comment]
Agree, would be useful.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by nathanweeks** [comment]
There's still interest in this feature.

**Comment by kmuriki** [comment]
Pending issues from the old repo copied to the new repo (https://github.com/apptainer/apptainer/issues/1390) and cleaned from the old, retired repo.
