### ISSUE TITLE
environment variables not transferred in macOS

### ISSUE THREAD

**Issue by bjarthur** [apptainer/singularity#4476]
another difference with linux.  i search the issues this time; sorry if it's a dup:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

$ export LOL=cow

$ echo $LOL
cow

Singularity lolcow_latest.sif:~> echo $LOL

Singularity lolcow_latest.sif:~> 
```

```
$ cat /etc/*-release
NAME="Scientific Linux"
VERSION="7.4 (Nitrogen)"
ID="rhel"
ID_LIKE="scientific centos fedora"
VERSION_ID="7.4"
PRETTY_NAME="Scientific Linux 7.4 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.4:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
Scientific Linux release 7.4 (Nitrogen)
Scientific Linux release 7.4 (Nitrogen)
Scientific Linux release 7.4 (Nitrogen)

$ export LOL=cow

$ echo $LOL
cow

$ singularity shell library://sylabsed/examples/lolcow
Singularity lolcow_latest.sif:~> echo $LOL
cow
Singularity lolcow_latest.sif:~> 
```

**Comment by bjarthur** [comment]
maybe related to https://github.com/sylabs/singularity/issues/4368 ?

**Comment by jmstover** [comment]
Hi @bjarthur ... Design wise, this isn't something that can be fixed with how the Mac version operates (Mac shell -> Hypervisor -> Linux Kernel -> Singularity).

And yes, #4368 is a similar issue. #4368 can probably be fixed for most cases, but a random environment variable in the Mac environment cannot be.

Long term design, we have an idea on how this could work in this way. But the current design makes it extremely difficult to pass the environment from the Mac shell to the running Singularity inside the VM.
