### ISSUE TITLE
Functionality of Singularity without sudo

### ISSUE THREAD

**Issue by dmey** [apptainer/singularity#4507]
For running Singularity on local/remote machines without the need for admin privileges. The installation of Singularity without sudo is already possible but only a few utilities (e.g. `build --remote`) are available.

**Comment by dtrudg** [comment]
Hi @dmey - there are limitations around what can be supported without a sudo, as you mentioned:

> The installation of Singularity without sudo is already possible but only a few utilities (e.g. build --remote) are available.

The breadth of what is available depends on e.g. whether user namespaces are available on your system, which permits `singularity build --fakeroot` instead of `sudo singularity build` etc.

What version of Singularity are you using, and what is the environment you are using it on? What is missing that you would hope to achieve without sudo? With a bit more detail we can tell you how to approach it, or discuss what is/isn't possible.

**Comment by dtrudg** [comment]
NB - I'm going to edit the title of this issue, since it doesn't really match up with the statement that:

> The installation of Singularity without sudo is already possible

**Comment by dmey** [comment]
The reason I mentioned it was mainly to use Singularity in the event of 'unreceptive' sysadmins. I also thought that perhaps a linuxbrew recipe, where sudo is not allowed, would make the installation of Singularity even easier. In any case I started writing a linuxbrew formula (see https://github.com/dmey/homebrew-singularity-container). Not sure if anyone would find this useful give the limitations and the fact that macOS would not be supported. Furthermore, I did try passing `--fakeroot` but got `FATAL:   container creation failed: failed to resolved session directory` (see https://travis-ci.com/dmey/homebrew-singularity-container/builds/129935954#L2195-L2196).

**Comment by dmey** [comment]
@dctrud any updates re this?

**Comment by dtrudg** [comment]
Hi @dmey - I'm afraid we can't really offer specific support for the linuxbrew packaging effort, but with regard to what you are doing there - without privilege (setuid that comes from a sudo make install), Singularity cannot run SIF containers. Only  sandbox directories are usable since mounting the filesystem inside the SIF image requires privilege. `--fakeroot` is about providing a fake root inside the container, but the mounting needs privilege outside of the container during runtime setup.

You should be able to do a...

```
singularity build -s mysandbox docker://ubuntu
singularity run mysandbox
```

... without priv.

**Comment by gvallee** [comment]
I am afraid that it is not quite enough when dealing with more complex workflows. 

In order to facilitate the discussion, here is an example: it is not possible to use the `singularity inspect` command, which returns in that context an error message that can appear quite cryptic to some:

```
demo@linux$ ./mconfig --prefix=$HOME/install/singularity_master && make -j4 -C builddir && make install -C builddir
[... cut output, installation successful ...]
demo@linux$ singularity version
3.5.0-rc.2+12-g4eacdbeee
demo@linux$ singularity run -u library://sylabsed/examples/lolcow
INFO:    Convert SIF file to sandbox...
WARNING: underlay of /etc/localtime required more than 50 (76) bind mounts
 ____________________________
< Save energy: be apathetic. >
 ----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
INFO:    Cleaning up image...
demo@linux$ singularity pull library://sylabsed/examples/lolcow
WARNING: unable to verify container: lolcow_latest.sif
WARNING: Skipping container verification
demo@linux$ singularity inspect ./lolcow_latest.sif 
WARNING: No metadata partition, searching in container...
FATAL:   Unable to process command: while running /home/gvallee/install/singularity_master/libexec/singularity/bin/starter-suid: exit status 1: ERROR  : Failed to set effective UID to 0
```
And as far as I recall, it gives an error even if a metadata partition is there. Also, if the idea is to support only a metadata partition with that workflow, it is not clearly explained in the documentation.

**Comment by dtrudg** [comment]
If we want to support `inspect` here we'd need to go through the SIF -> sandbox conversion and then have `inspect` look in the sandbox, not try to mount from the SIF.

> And as far as I recall, it gives an error even if a metadata partition is there. Also, if the idea is to support only a metadata partition with that workflow, it is not clearly explained in the documentation.

We don't capture all the metadata, e.g. labels, the various things related to the driver scripts in a separate portion of the SIF yet, that doesn't require a `mount` to access, though that is a long term aim. There are definitely documentation issues, and things we could implement here - but for now `inspect` on a SIF will not work without the setuid workflow, and we should at least fail with something obvious and understandable.

**Comment by gvallee** [comment]
FYI, I will find a solution about the `inspect` command because I need the metadata in a workflow without setuid, even if it means that I will have my own metadata mechanism on top of SIF. I opened issue #4724 to track the discussion specific to the `inspect` command.

**Comment by dtrudg** [comment]
Inspect issue #4724 was fixed and closed.

@dmey - is there anything further I can answer?

**Comment by dtrudg** [comment]
Closing as there has been no further follow-up. We've added more about non-privileged no setuid installs to our userdocs and admindocs.

Please feel free to re-open or open new issues for any further specific questions.
