### ISSUE TITLE
Ability to bind as READ-ONLY

### ISSUE THREAD

**Issue by PauloSouza7** [apptainer/singularity#451]
Ability to bind as READ-ONLY, example:

--robind /path/to/host/dir:/path/to/container/READ-ONLY/dir/
--robind /path/to/host/dir

robind == read only bind

**Comment by jobh** [comment]
One possible implementation is [here](https://github.com/singularityware/singularity/compare/master...jobh:read-only-userbinds
). It is sufficient for my needs, but probably too simplistic to consider for merging.

I added an extra field to the mount spec - hostdir:[containerdir[:options]] - rather than a separate flag. This makes it possible to pass it in SINGULARITY_BINDPATH along with the other binds. Example:
--bind /scratch:/scratch:ro

Beware: There may be issues with recursive mounts. It is possible that only the top level will end up read-only, while submounts are unchanged.

**Comment by gmkurtzer** [comment]
Nothing wrong with simple, send in a PR to the lib-refactor branch please. :)

Thanks!

**Comment by gmkurtzer** [comment]
This has been merged. Closing.
