### ISSUE TITLE
Support build engine plugins

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity#4568]
Engine config mutators should be called in `internal/pkg/build/build.go:362`.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
