### ISSUE TITLE
vendor: missing "rootlesscontainers.proto"

### ISSUE THREAD

**Issue by onlyjob** [apptainer/singularity#4647]
Vendoring of [github.com/rootless-containers/proto](https://github.com/rootless-containers/proto) is incomplete as `rootlesscontainers.proto` files are missing: https://github.com/sylabs/singularity/tree/v3.4.2/vendor/github.com/rootless-containers/proto

To ensure integrity of build (and for open source compliance) please make sure that all sources are included into source release so that all generated files could be re-built.

It is best to make source tarball releases comprehensive (i.e. include all sources).

Thanks.

**Comment by dtrudg** [comment]
The content of vendor on the 3.4 branch is complete from a `go mod vendor` under go `1.12.x`.

Not sure if we have any issue there? @mem are you able to give any input? 

Note that the vendor directory is removed on the `master` branch which will become the next release.

**Comment by onlyjob** [comment]
It is a small file and it would be desirable to include it. If `go mod vendor` does not pick it up then how can it be included along with any other potentially missing `.proto` files?

**Comment by mem** [comment]
Which version of Go are you using?

**Comment by mem** [comment]
I'm going to guess you are building from master, is that right?

**Comment by dtrudg** [comment]
@onlyjob - actually, it looks like you are looking on the `v3.4.2` tag not master. Since we aren't anticipating making any further 3.4 releases unless any major bugs come up, and on `master` for an upcoming `3.5` we are no longer committing a vendor directory, I'm going to mark this with a `wontfix` - but I'll leave open for now in case there is further comment relative to the situation on `master` without a vendor directory?

For reference, it seems we *did* lose this file in https://github.com/sylabs/singularity/commit/4044a9f00f6bc8378ffd827e3692a69e27b24890

**Comment by onlyjob** [comment]
> Which version of Go are you using?

Why do you think this is relevant?? 1.13.

Please don't mark it "wontfix". It is a legitimate issue _demonstrated_ in v3.4.2 but possibly affecting future releases unless you make any changes.

I am building current release from source for Debian. Good practice is to recompile all files from source therefore _all_ sources must be shipped if not for integrity of build then for open source compliance.
Shipping only source-less pre-built (pre-compiled) files is the same as to ship a binary without sources -- this is the actual problem here and not the version of Golang that I'm using or vendorless master.

**Comment by onlyjob** [comment]
This issue affects release process, i.e. how releases are tagged.

**Comment by dtrudg** [comment]
>> Which version of Go are you using?

> Why do you think this is relevant?? 1.13.

I believe @mem was asking this as it's relevant if you are working from the `master` branch source (where there is no `vendor` committed) and running `go mod vendor` because vendor will be slightly different (excludes some files) with go `1.13` vs `1.12`

> Please don't mark it "wontfix". It is a legitimate issue demonstrated in v3.4.2 but possibly affecting future releases unless you make any changes.

This would only affect any future `3.4.x` release at present, and we don't have one planned. `vendor` is no longer in master and that will be the source of our next `3.5.x` release. I'm happy to keep this open and will label it `release-3.4` and we can revisit the `wontfix` if there are other reasons that end up leading to a `3.4.3` release, but this is not anticipated at this point.

**Comment by onlyjob** [comment]
If vendored libraries will not be included to future releases then dynamics of packaging Singularity releases for Debian will be impaired because we will have to ensure that Singularity builds perfectly with available components.  
For instance if there were no vendored "containers/image" library in the 3.4.2 release then we could not have build it for Debian due to #4648.

Is there going to be no comprehensive source releases?

**Comment by dtrudg** [comment]
The intention at this point is, as far as I am aware, for the use of the global `GOPROXY` to provide a reliable way to fetch the dependencies that are required.

As an aside - @0xaf1f here used to maintain a Debian package for Singularity, but we were advised it was excluded (see https://groups.google.com/a/lbl.gov/forum/#!searchin/singularity/debian%7Csort:date/singularity/kbtX1UekVrg/FBi7895TFgAJ)

Is the situation now changed in this regard?

**Comment by onlyjob** [comment]
At the moment I'm co-maintaining Singularity package in Debian together with Afif and other members of the HPC team. Singularity is not in the current Debian "stable" but it is in "testing/unstable/experimental" and (if everything goes well) it might be included in the upcoming "stable".

Debian packages are built offline and no build-time download is permitted...

**Comment by mem** [comment]
> > Which version of Go are you using?
> 
> Why do you think this is relevant?? 1.13.

Because the way the vendor/ directory is populated changed between 1.13 and prior releases. Since you didn't provide more background, I thought this was related to something else.

> I am building current release from source for Debian. Good practice is to recompile all files from source therefore all sources must be shipped if not for integrity of build then for open source compliance.
> Shipping only source-less pre-built (pre-compiled) files is the same as to ship a binary without sources -- this is the actual problem here and not the version of Golang that I'm using or vendorless master.

I do understand that (I was a member of the project for many years). But if this is what you are after, I think you need to take a step back. The way Go vendors dependencies _is not_ a faithful representation of the dependency. The code is pruned to contain only what's strictly necessary to build (and one or two more files). If you compare the contents of one of the modules in the vendor directory against their respective state in version control (using the corresponding tag or hash as specified in the go.mod file), you'll find that vendor does not contain _pristine_ source code. (This is why I asked for the Go version, because as I said 1.13 removes _more_ files)

And this bumps into the other issue with your request: while the vendor directory does not contain _all_ the files found in the original source code repository, the files that _are_ found there are copies of their counterparts in the repo. These files are not patched or modified in any way. Entirely hypothetical situation: if you were to fix a problem in a file in the vendor directory (because, let's say, its license makes it non-distributable), you couldn't do that, as the next time "go mod vendor" runs, it will restore that file. You would have to use a non-pristine tarball in that case. Adding a file falls into the same category: rerun "go mod vendor" and the file is gone again.

My guess as to what happened here is that the commit 4044a9f removed the file, but I'm not sure why. At the time I probably thought it was because the clean up that that commit was doing, but looking again at it, I'm not sure what that would have been the case.

I'm trying to understand here: did something failed to build, or how did you notice the file was gone?

**Comment by onlyjob** [comment]
Thanks for the explanation and context, @mem.  I'm building from the source tarball release.

I've noticed that the file is missing during attempt to run `go generate` to re-build all pre-built files.
Good build systems removes all precompiled files in "clean" stage then builds everything from source...

**Comment by dtrudg** [comment]
> I've noticed that the file is missing during attempt to run go generate to re-build all pre-built files.
Good build systems removes all precompiled files in "clean" stage then builds everything from source...

At least from my experience (@mem is much more knowledgeable here), this is not what is expected in the Go ecosystem. `go mod` is built to deliver you what you need to run `go build`. As mem mentioned, go 1.13 will deliver fewer files while satisfying that than go 1.12 did from a `go mod vendor` run. Also....

> Go generate is never run automatically by go build, go get, go test,
and so on. It must be run explicitly.

... so as far as I understand it, the libraries like `rootlesscontainers/proto` are expected to be retrieved with `go mod` and used in a `go build` without having to run `go generate`. A build system requiring a `go generate` on vendored deps would be unusual.

Assuming I'm correct on this I'm not sure we'd want to modify our build process or what we distribute to accommodate the extra files. In our `3.4.x` CI we are checking that no change to the committed `vendor` or `go.mod` would be required by a `go mod vendor`. Adding additional files over what `go mod vendor` is going to provide may break that check. I'd need to look further at the 4044a9f to be certain it's expected with go 1.12 which is our 3.4.x target - but even if this is a fixable issue here for 3.4.x, I'm still concerned about how we could generally move forward if we are using `go mod vendor` at build time or to commit/distribute vendored deps - but you need to run a `go generate`.

Does Debian have any guidelines specifically for packaging Go programs that are being referred to here? Any further information in that regard to give us more context on what you absolutely need to achieve would be welcome.

**Comment by dtrudg** [comment]
Another quick q.... how are you running `go generate` over the vendored deps? With 1.13 `go generate ./...` ignores vendor. And if I try to do it explicitly inside vendor then...

```
dtrudg@dt-sylabs~/G/s/vendor> go generate ./...
go: not generating in packages in dependency modules
```
... your `go version` is important for us to know and consider here. I'm running here in GO module mode. The code is not in `$GOPATH`

**Comment by onlyjob** [comment]
Irrelevant, all irrelevant. If you do source release then include _all_ sources. This is basic common sense and open source compliance. Doesn't matter how I build, which compiler version etc.

Downstream challenges are different. We need to build offline in the coherent repository where all libraries should already run `go generate` on build. This is DFSG compliance and pragmatic approach to build. Some day grpc or protobuf compiler updates and cause build failures because pre-built files are not re-build somewhere while various components may be shipping pre-built files produced by different compiler versions.  Building everything from source is required for integrity of build and to prevent future FTBFS.
I am trying to invoke `go generate` in `vendor` specifically. Ideally we should have nothing in "vendor", relying on packaged libraries exclusively but when vendoring is unavoidable then at least it is worth building it properly.
Golang does not do many things by default - for instance it does not run any tests for vendored components. This is why Debian build is superior because we build from _tested_ libraries and we notice when things break or FTBFS.
My `go version` is whatever is in Debian "unstable" at the moment.

**Comment by dtrudg** [comment]
Hi @onlyjob 

> Irrelevant, all irrelevant. If you do source release then include all sources. This is basic common sense and open source compliance. Doesn't matter how I build, which compiler version etc.

I'm afraid that it's not all irrelevant in this case. We are using the standard `go mod` tool to obtain the sources in `vendor` and, as explained before, with that there are certainly slight differences in behavior and what is included from a `go mod vendor` between go versions. We have had to consider this in e.g. the transition from e.g. Go 1.12 to Go 1.13 in our CI as there are conflicts between developers committing `go.mod` and `vendor/` from different versions.

>  I am trying to invoke go generate in vendor specifically. Ideally we should have nothing in "vendor", relying on packaged libraries exclusively but when vendoring is unavoidable then at least it is worth building it properly.

As I showed above, this will not work outside of `$GOPATH` with Go 1.13. We really do need specifics to understand what you need, and how you are trying to accomplish it.

> My go version is whatever is in Debian "unstable" at the moment.

Please be specific with the information requested when possible. It's unlikely that many developers here are running debian unstable and are extremely familiar with / tracking the go version there.

At this point I'd like to leave this with the offer that we are very happy to consider PRs and will try wherever possible to accommodate specific, justified needs of distributions that are distributing Singularity. It is also, of course, always possible that another member of the Sylabs team or community may wish to take on the changes that facilitate the Debian packaging.

Cheers.

**Comment by onlyjob** [comment]
> Please be specific with the information requested when possible. 

This is subject to change, at any time. Yet requirement to have all the sources exist regardless of the compiler version. To comply with this requirement you do not need to know my Golang version.

Similarly, specifics of how we invoke compiler to re-build pre-generated files are irrelevant.
First of all you need sources to build those files from and they are missing.
Please stay focused.

I've merely described the problem leaving the solution up to you as I presume you are much more qualified to understand how to invoke `go mod` in any Golang version of your choice to produce comprehensive source release with all source files included.

**Comment by mem** [comment]
> Thanks for the explanation and context, @mem. I'm building from the source tarball release.
> 
> I've noticed that the file is missing during attempt to run `go generate` to re-build all pre-built files.
> Good build systems removes all precompiled files in "clean" stage then builds everything from source...

Ok, thanks for the info. I'll try to reproduce that. That would be an easy argument to fix this.

**Comment by onlyjob** [comment]
Thanks.
