### ISSUE TITLE
push latest tag handling

### ISSUE THREAD

**Issue by h3kker** [apptainer/singularity#4688]
I'm working on a minimalistic implementation of a server for the library:// protocol and I've noticed something that confuses me a little:

A push with an explicit tag would check the current tag list for the image and update it accordingly. If there is no explicit tag (e.g. `singularity push -U test.sif library://entity/collection/container`) it will get the tag list, but then don't do any updates (since it has an empty tag list). It would leave the uploaded image "dangling".

Wouldn't it make more sense to default empty tags to `latest` in that case, as is done when pulling?

The reason I'm raising this is that I don't want to automatically advance the `latest` tag on every push. Someone doing some work on an older version of a container and pushing that with the old version tag should not reset the latest tag that was pointing to a newer version before. 

So far so good, but people seem to expect that a push without a tag would go to latest, as does with pulling, and I've got quite a few dangling images as a result. 

Is the desired/expected behaviour to always set the latest tag on push?

Tested on v3.4.1 as well as a current build (singularity version 3.4.2+543-g3fdd19f3e)

Thanks,
Heinz

**Comment by mem** [comment]
Hi @h3kker,

this topic has come up a couple of times in the past.

For the simple case, it would make sense to automatically advance the latest tag.

Let's say the user has these images:

- 1.0
- 1.1
- 1.2

upon creation of 1.0, that's the only image and it makes sense for that to be "latest". When pushing 1.1, it makes sense for that to be latest, and the same goes for 1.2, so at this point latest points to the same image as 1.2.

Now they push:

- 2.0

it could be argued that this is latest.

And now the figure there's an issue that needs to be addressed in the 1.x series, and they push:

- 1.3

is this latest? Or does the latest tag stick to 2.0?

The problem with "latest" is that it could be interpreted in two ways, and depending on your interpretation that's the answer you get above.

The first interpretation is that latest is the most recent image, so 1.3 would be latest. This is easy to implement.

The second interpretation is that latest is the most recent version, so 2.0 would be latest. This assumes that the tags represent versions and that those versions have a well-defined ordering.

To your specific case, I'm not sure if you are asking about the case where there are no tags at all, or the case where the user didn't specify a tag for that particular image. I think you are talking about the former. In that specific case I think it makes sense to tag _something_ with latest, and it makes sense for that something to be "the most recently pushed". The problem that I would have with that approach is that behavior would suddenly change if the user decides to use a tag. For example, the user is pushing some test images, without tags, so they each get the "latest" tag, and at some point they are happy with some image, and they do tag that (say 1.0). And then they go back to pushing more test images. In this case "latest" would stick to 1.0 (there were no tags before that, so latest is applied to that one). We would have created the expectation that latest follows the most recent commit, and suddenly we stop doing that.

To me it feels like we need a "tag" command on the client side, so that we can manage tags without going thru the web interface. I also think that on the library side, we need a couple of attributes:

- latest follows most recent image
- latest follows newest image (using semantic versioning)

the client could check that attribute and decide what to do with the tag based on that. Or the library could apply the tag based on that.

@EmmEff?

**Comment by EmmEff** [comment]
Contrary to the current behaviour, IMO, the most recently image pushed to the library _without a tag_ should be automatically tagged as "latest". It is, after all, the "latest" image pushed to the library, which is not necessarily the newest by semantic versioning.

IMO, it is bad practice for an image to exist in the library without a tag. Pulling an image without specifying the tag should automatically return the `latest` tag as is the default pull behaviour.

**Comment by mem** [comment]
> Contrary to the current behaviour, IMO, the most recently image pushed to the library _without a tag_ should be automatically tagged as "latest". It is, after all, the "latest" image pushed to the library, which is not necessarily the newest by semantic versioning.
> 
> IMO, it is bad practice for an image to exist in the library without a tag. Pulling an image without specifying the tag should automatically return the `latest` tag as is the default pull behaviour.

Right.

But note that if we automatically tag images with "latest", we end up in a situation were we have many images without tags:

```
$ singularity push ~/my.sif library://user/collection/my.sif
...
$ singularity push ~/my.sif library://user/collection/my.sif
...
$ singularity push ~/my.sif library://user/collection/my.sif
```

at the end of that process, the last image would be tagged as "latest" and the other two would not have any tags. Under current behavior we "encourage" bad practice by not applying tags to anything, and under the new behavior we would do the same by having a single moving tag.

From my point of view, the problem with having latest follow the most recently uploaded image is that in the example I described, a user would pull the image and get 2.0, and then they would pull the same URL at a later time and get 1.3. You could argue that this is on them because they should not be using latest, instead they should be using the image's hash, so that they always get the same thing. On the client side we don't offer a good UI for that kind of workflow (for discovering and listing images, I mean).

(and for the record, with my UI hat on, I'm of the opinion that the problem is not push, but pull defaulting to latest, as it opens the door for surprising behavior, and good UIs don't surprise users)

**Comment by dtrudg** [comment]
> (and for the record, with my UI hat on, I'm of the opinion that the problem is not push, but pull defaulting to latest, as it opens the door for surprising behavior, and good UIs don't surprise users)

We had much discussion about that in the past. It settled on the side that pulling `:latest` by default was less surprising to most users - as they are familiar with docker doing that, or singularity when pulling/building from docker images. It's not an uncontroversial thing there either though.

**Comment by h3kker** [comment]
Regarding advancing the latest tag on every push: another use case that it interferes with would be a CI/CD systems set up to push to latest only on the master branch, but not on development branches. Like: I would like to have the containers under development pushed with a special tag (e.g. branch name) so that I can test them in the cluster environment, but anybody just using `latest` should not see them (yet).

My point being that a push without tags tagging latest IMHO would have fewer unexpected side effects than always advancing latest on every push; people used to docker would be even less surprised; and it would be sort of symmetric to the behaviour of push.

**Comment by dtrudg** [comment]
This is an issue which has pros and cons on each side, but at this point we are now far enough in with the library protocol that it would be disruptive to change.
