### ISSUE TITLE
feature request: minimizing singularity image footprint

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#470]
using reprozip/strace one can determine which files in a given container are necessary for a particular application at hand.

for docker, we have then used that information to create a minimal footprint only containing the necessary files.

it would be nice if we could do the following:

1. add a `-t/--trace` flag to `exec` that generates and possibly extends an existing trace
2. add a `pack` command that uses the trace to minimize the footprint of the container

```
s exec -t tracefile some_img some parameters
s exec -t tracefile some_img some other parameters # increments tracefile
s pack some_img -t tracefile new_img # creates minimal image using info in tracefile
```

the last bit could possibly write out the files that have been removed into a `%post script` to recreate this minimal footprint from bootstrap.

**Comment by gmkurtzer** [comment]
In Singularity v1.0 we had a mechanism to do something very similar to this. We had to use ptrace, and we could in theory reuse that code and integrate it into `bootstrap` such that you can build a container based on a local application.

But, this method is not foolproof which is why version 2.0 went a completely different path. Lots of programs conditionally require other bits that might not be triggered on the host, but would on different hosts. Python was notoriously bad for this reason.

With that said, with appropriate user "demand", I could probably be persuaded to bring this feature back (pending I don't get the support questions when things fail in weird ways - lol)!

**Comment by bbockelm** [comment]
@satra - Would this make more sense if it was a part of ReproZip instead?

**Comment by satra** [comment]
@bbockelm - possibly. since @gmkurtzer reply, i have been chewing on this. i'd like to keep singularity minimal - so if this can be taken care of with a build script or such that includes reprozip trace into the container that would be great. i'm going to try a few things and see if using ptrace directly or using reprozip, which requires python is the better route.

**Comment by gmkurtzer** [comment]
I'd like to find out if we can import a Reprozip .rpz file directly to a container.... Anybody know?

If not, we can always go back to using Ptrace, but I'd prefer to use an existing project if one exists.

**Comment by vsoch** [comment]
I think reprozip itself is just a compressed archive, although I haven't looked in some time. The [tracer](https://github.com/ViDA-NYU/reprozip/blob/1.0.x/reprozip/reprozip/tracer/trace.py) seems to just walk directories and add ones that include files relevant to what the user selected. The problems I see with this approach is that many core OS files would be essential to the container, but possibly not included in the trace (at least based on what I think the python bits are doing, the system version might be different). @gmkurtzer and @satra  - we could either take a similar (python based) approach like reprozip, or go with the core linux command (probably doing the same thing) as @satra has mentioned. @satra - is the command that you showed sufficient for the functionality? Do you have preference for python vs. bash? I'd be happy to implement something like this, because it makes a lot of sense for many use cases, like starting with a bloaty container and then reducing it to a minimum version given some executable. It would also be interesting to just learn what kinds of unnecessary junk gets carried around :)

**Comment by satra** [comment]
@vsoch - i will be finishing a tutorial on this today (not in the context of singularity directly, but more generally how one can capture provenance of execution). fingers crossed, the tutorial should highlight the different options available for singularity. what reprozip provides is more than just what files need to be kept, but all that information may not be essential for minification.

**Comment by gmkurtzer** [comment]
If Reprozip doesn't seem to do an actual trace, then we might need to do it ourselves. Perhaps, if I write the necessary functions in C and properly `ptrace()` even the Reprozip team could utilize that for making archives. Maybe they would be interested in joining forces and helping to make Singularity create images based on this model as it seems in synergistic alignment. :)

**Comment by satra** [comment]
@gmkurtzer - i believe reprozip uses ptrace (may be the python interface to ptrace) and does an actual trace. what reprozip adds is which package that particular file was installed from if that information is exists. it also creates a dependency structures across programs to determine an execution graph. they already unpack to vagrant, chroot, and docker, so adding singularity to their unpackers would not be hard.

**Comment by gmkurtzer** [comment]
Oh, fantastic. I think that would be ideal. If we can take the output of reprozip, and create an image based on that directly. That means, I won't have to do any ptracing! YAY!

**Comment by VickyRampin** [comment]
Hi all! I work on ReproZip -- we actually have an issue open to write an "unpacker" for Singularity (with the tag, "help wanted" :wink:): https://github.com/ViDA-NYU/reprozip/issues/267

We would love to integrate these two tools!

**Comment by vsoch** [comment]
@gmkurtzer would squashfs create images with a minimal footprint not? @VickySteeves what did you have in mind for an unpacker? (eg, when would I want to unpack a Singularity image and what does it mean?) Apologies I don't know as much about Reprozip as I should!

**Comment by remram44** [comment]
"unpackers" are the pluggable ways of reproducing environments in ReproZip. From the .RPZ file that the ReproZip packer creates, you can create chroots, VMs with Vagrant, or containers with Docker.

Because none of those options are available on HPC, we are planning to write an "unpacker" from Singularity, e.g. a way to run .RPZ files using Singularity as the isolation mechanism ([reprozip#267](https://github.com/ViDA-NYU/reprozip/issues/267)). This is the reason for #879.

This shouldn't need changes on Singularity's part, we can just have a ReproZip plugin output a Singularity image file from a .RPZ.

**Comment by vsoch** [comment]
oh cool! So dumping a repozip into singularity so it can be run anywhere! I definitely like this idea. Do you need any help?

**Comment by GodloveD** [comment]
If you can already dump the reprozip out into a directory you should be most of the way there.  The new `build` command in singularity 2.4 (currently development branch) can create a singularity image (squashfs) from a directory.  The only thing you would need to figure out is the meta data (I think).

**Comment by vsoch** [comment]
+1! You would want the metadata to closely match what is in `/.singularity.d/` which broadly includes:

 - labels.json: you should add labels for the repozip
 - env/91-environment.sh: this is sourced at run/shell,etc, add environment things here
 
The one thing to think about is the definition file - this normally is a Singularity recipe, but I think we should (in this case) use it as a record that the container came from reprozip. Does reprozip have a recipe /generation history equivalent?. I would suggest the following to start:

 - reprozip function to export into directory, then import into singularity (development branch) from folder
 - look inside the final image at the metadata folder, see what you have to work with
 - step back, make those changes at the first step (so the import includes the files)

You could also write a build recipe on the fly, with import from the directory, this way you can write things into easy sections and singularity will take care of putting it in the right places!

**Comment by remram44** [comment]
> If you can already dump the reprozip out into a directory you should be most of the way there.

The problem with a filesystem roundtrip is that you'd lose file ownership. You can only put in the image files with metadata you are allowed to create on disk (so owned by you).

**Comment by vsoch** [comment]
I don't completely understand this - if you are able to extract a reprozip object, how would you extract at all?

During a singularity import, with a "proper" that includes metadata it **must** be done with sudo. If an import is done without it, we still extract .tar.gz and extract the labels / other metadata into an in memory tar to export.

I don't totally understand what you mean by a "filesystem" roundtrip. Maybe a bit of explanation would help, and writing out the steps you have in mind for this.

**Comment by remram44** [comment]
Having to use sudo is exactly what I want to avoid, as it is not available on HPC nodes. Sudo is not required to create a Singularity image, so long as you don't create the directory structure on disk.

**Comment by vsoch** [comment]
how about try doing an export (without sudo) and then an import (without sudo) and post the issues you run  into as you go, and we can help. Talking about it abstractly isn't going much anywhere!

**Comment by remram44** [comment]
Nothing abstract here, "exporting" a tarball to disk without root privilege will create the files with the current user as owner, and once re-imported the original ownership will have been lost. This is the reason why things like [fakeroot](https://wiki.debian.org/FakeRoot) exist.

Whether the ownership information of files is important is up for debate, but if they can be preserved by writing the image file directly I say why not 🤔

**Comment by vsoch** [comment]
import comes down to this:

https://github.com/singularityware/singularity/blob/development/libexec/helpers/image.sh#L40

**Comment by dtrudg** [comment]
Hi @VickySteeves @remram44 - this issue has been untouched for a long time, but am wondering whether the ability to use reprozip for Singularity images is still something that's being looked at? I think stuff at the bottom of #879 (though imperfectly documented) may make it workable if I understand correctly?

**Comment by dtrudg** [comment]
This issue looks stale, so I'm going to close it. Note that over the next couple of releases of Singularity there is a plan to expose hooks in the build system that tracing / minimization may be able pursued as a plugin by anyone interested.
