### ISSUE TITLE
missing bind mounts result in a fatal error

### ISSUE THREAD

**Issue by LaHaine** [apptainer/singularity#4700]
### Version of Singularity: 3.5.0-rc1

What version of Singularity are you using? Run:

```
$ singularity version

```
`3.5.0~rc.1-1.el7`

### Expected behavior
It should run the image and ignore the missing bind.

### Actual behavior

FATAL:   container creation failed: mount /net->/net error: while mounting /net: mount source /net doesn't exist

### Steps to reproduce this behavior
Have this in singularity.conf:
`bind path = /net`
/net doesn't exist on the system.

Then run any image.

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
But the same happens on RHEL7

### How did you install Singularity
alien converted to .deb from the RHEL7 rpm package.

**Comment by LaHaine** [comment]
This is a regression from 3.4.2, there you had only a warning about a missing bind.

**Comment by dtrudg** [comment]
Hi @LaHaine - this is not a regression, in the sense that it is behavior that has been implemented due to specific requests.

E.g. in issue #3894 #3797 #3530 #2700  it has been requested that Singularity doesn't simply ignore and proceed if there are missing explicit bind mounts.

A error was the behavior in 2.x and it seems we've been inconsistent in 3.x around silently proceeding or issuing warnings.

What we do need to do here, definitely though, is call this out in the changelog / release notes.
