### ISSUE TITLE
Singularity exec hangs on v3.2+ but not 2.5.2, with wildcarded paths

### ISSUE THREAD

**Issue by kpepper** [apptainer/singularity#4723]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
2.5.2-dist
$ /software/singularity-v3.2.0/bin/singularity --version
singularity version 3.2.0

```

### Expected and actual behavior

What did you expect to see when you do...?

Using version 2.5.2...

singularity -d exec -B /myhostdir:/temp  any-image.simg ls /temp/*

I expect to see 2000 files listed out and this works as expected. However when I do the same with Singularity 3.2.0 or 3.3.0 it hangs and I don't see anything listed:

/software/singularity-v3.2.0/bin/singularity -d exec -B /myhostdir:/temp  any-image.simg ls /temp/*

This is not dependent on the image - I can use any one and get the same result. It seems to be Singularity version related. Versions 3.2+ will list out ~1200 files but hang on anything much above that.

I use "ls" above just to illustrate the issue but it seems that any wildcarded path passed into Singularity 3.2+ has the same issue if enough files are involved.

### Steps to reproduce this behavior

see above

### What OS/distro are you running

```
$ cat /etc/os-release

Red Hat Enterprise Linux Server 7.6

and also

Ubuntu 18.04.3 LTS (Bionic Beaver)

```

### How did you install Singularity

For 2.5.2 - rpm packages, and for 3.2+ into a directory.

**Comment by jmstover** [comment]
What's the behavior if you do:
```
/software/singularity-v3.2.0/bin/singularity -d exec -B /myhostdir:/temp any-image.simg ls /temp/\*
```

I'm wondering if it's doing the wildcard globing first, then passing the entire bunch to the Go binary to work through as options and that's causing it to hang?

It _shouldn't_ be unless you have a `/temp` link on the host as well ... but

@mem @jscook2345

**Comment by kpepper** [comment]
Hi **@jmstover**. Thanks for the quick reply.

Result (for all versions):
ls:   /temp/*: No such file or directory

In simplifying the file paths, the command line I pasted was slightly misleading, specifically I'm using:
/software/singularity-v3.2.0/bin/singularity -d exec -B /temp any-image.simg ls /temp/subdir/*

**Comment by dtrudg** [comment]
I can get this to hang also - but not at ~1200 - instead between 4703 and 9824 files.

```
dave@piran:~
08:32 AM $ singularity exec -B /data docker://alpine ls /data/Archive/*/*/*/*/* | wc -l
4703
dave@piran:~
08:32 AM $ singularity exec -B /data docker://alpine ls /data/Archive/*/*/*/*/*/* | wc -l
^C
```

The latter `ls /data/Archive/*/*/*/*/*/* | wc -l` will list `9824` run on the host.

**Comment by cclerget** [comment]
@kpepper As shell expand the wildcard instead of passing `ls -la /tmp/*` as a command to execute it will pass `ls -la /tmp/file1 /tmp/file2 ...` as command to execute, so the number of command arguments can increase drastically depending of the content of `/tmp` in this example. What happens here is that `singularity` CLI will pass the expanded arguments in the resulting configuration which is then passed to the runtime : `starter` command.
There is a size limit due to architecture of v3, the limit is fixed by the value in `/proc/sys/net/core/wmem_default` as in v3 the CLI command communicate via a socket with the `starter` command.

More generally running the command like you did could give you unexpected result, if I take the following example :
`singularity exec docker://alpine ls -la /etc/*`

it will give you the `/etc` files of the host filesystem not those in container image and that's not what we want.

The way to execute command when using wildcard is to run singularity like:

`singularity exec docker://alpine /bin/sh -c "ls -la /tmp/*"`

**Comment by kpepper** [comment]
**@cclerget** Thanks - that's very useful. So, essentially I have two options:
1. Increase /proc/sys/net/core/wmem_default in the image when building
2. Use the /bin/sh -c option, which is the recommended way.

**Comment by kpepper** [comment]
**@cclerget** Presumably, the /proc/sys/net/core/wmem_default value is the host value as Singularity is mounting /proc by default anyway?

**Comment by cclerget** [comment]
@kpepper Yes changing the value also affect host and services which depends of this value unless you run singularity from a dedicated network namespace in which case the value will affect services running in this network namespace.
