### ISSUE TITLE
support for tags on github repos

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#483]
@vsoch showed that you can have different branches corresponding to different singularity files. for example: `satra/myproject:branch_ubuntu` `satra/myproject:branch_tensorflow`

however, i may want to tag these branches with specific versions. it would be nice if i could simply do:

`satra/myproject:ubuntu1604` `satra/myproject:tensorflow0.12`

where `ubuntu1604` and `tensorflow0.12` are github tags associated with specific branch commits.

**Comment by gmkurtzer** [comment]
I believe this is already fixed in the "development" branch. Can you confirm?

**Comment by vsoch** [comment]
This would still need to be implemented - @satra just to confirm you would want this for a Singularity Hub file associated with the tag? (eg, shub bootstrap). This change would need to be a dual change to shub and singularity command line software.

**Comment by satra** [comment]
@vsoch - correct. 

right now singularity hub creates images for each branch in my github repo. if i tag something in github, that commit will lie in some branch. i would like to be able to pull it as:

```
singularity pull shub://satra/om-images:tensorflow-gpu:tagname (if available)
```
or 

```
singularity pull shub://satra/om-images:tagname (if available)
```

since a tag on github is really on the set of commits in the repo rather than a branch and those commits could have been merged into several branches.

however, we could simplify this only to the second form and expect that someone who downloads it or creates it puts enough information about the container in metadata.

**Comment by dtrudg** [comment]
@vsoch - I'm wondering if this was implemented on the Singularity Hub side - or if this issue should be closed? Thanks.

**Comment by vsoch** [comment]
This should be closed - if a user wanted to deploy a tag based on a release they would use the deployment option, but it would still be based on a Singularity file suffix associated with their tag of interest. Singularity Hub uses repository Singularity files to determine tags (e.g., Singularity.<tag>) and it would become messy if we had added support for the GitHub idea of a tag as well (because you could have overlap and it wouldn't be clear which was being used).
