### ISSUE TITLE
Request: system-wide cache for docker layers

### ISSUE THREAD

**Issue by biocyberman** [apptainer/singularity#4844]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.0

```

We are maintaining a multi-user environment where each user builds their own customized Singularity images. We mainly use `Bootstrap: docker`. I find it is time consuming and storage-wise inefficient that each user have to re-download docker base images that are already downloaded by other users. I can do a symbolink link trick to centralize the cache directory. But it is hacky that way, and may have bad security implication. So, can this be handled by Singularity, to have a centralized based images if registry and based image names satisfy certain conditions set in `singularity.conf`?

**Comment by dtrudg** [comment]
Hello - this is definitely a nice idea but needs very careful thought with regard to implementation on large clusters with many users, where safe locking is difficult - especially on filesystems such as lustre where an `flock` may not be available, or may be node local.

If bandwidth / space constraints are sever, sites may currently wish to `singularity build` common `docker://` sources into SIF files on a shared filesystems, and ask users to build from these SIF files rather than the docker sources directly.

**Comment by gmkurtzer** [comment]
In theory this should be possible by caching into a common directory for OCI layers, but I would HIGHLY recommend against doing this.

Given the fact that it's been a good 6 months with no movement or discussion, I'm going to close. If this comes up again, please either reopen or create a new issue referencing this one.

Thanks,
Greg
