### ISSUE TITLE
singularity should detect registry if provided with uri

### ISSUE THREAD

**Issue by gregcouch** [apptainer/singularity#491]
I an "error obtaining tags" trying to import the official Python docker image for building linux binaries:
```
% sudo singularity --verbose import python-build.img docker://quay.io/pypa/manylinux1_x86_64
increasing verbosity level (2)
Exec'ing: /usr/local/libexec/singularity/cli/import.exec python-build.imgVERBOSE: Set messagelevel to: 2
VERBOSE: Initialize configuration file: /usr/local/etc/singularity/singularity.conf
VERBOSE: Obtaining container name from environment variable
VERBOSE: Calculating image offset
VERBOSE: Found available loop device: /dev/loop0
VERBOSE: Using loop device: /dev/loop0
VERBOSE: Mounting image in read/write
VERBOSE: Setting SINGULARITY_ROOTFS to '/var/lib/singularity/mnt/final'
INFO:python:
*** STARTING PYTHON CLIENT PORTION ****
INFO:python:Root file system defined as /var/lib/singularity/mnt/final
INFO:python:Including Docker command as Runscript? False
INFO:python:Docker image: quay.io/pypa/manylinux1_x86_64
INFO:python:Repo Name: pypa
INFO:python:Repo Tag: latest
INFO:python:Namespace: quay.io
INFO:python:Docker image path: quay.io/pypa:latest
INFO:python:Obtaining manifest: https://index.docker.io/v2/quay.io/pypa/manifests/latest
INFO:python:Obtaining tags: https://index.docker.io/v2/quay.io/pypa/tags/list
ERROR:python:Error obtaining tags: https://index.docker.io/v2/quay.io/pypa/tags/list
ERROR: Aborting with RETVAL=1
VERBOSE: Cleaning sessiondir: /tmp/.singularity-session-0.2069.6029624
```
This was on Ubuntu 16.10 with singularity 6007d3a1a46790bf1342eb99e2ac0aedd2e9cdb1 (Feb 15, 2017) from https://github.com/singularityware/singularity.git.

**Comment by vsoch** [comment]
Hey @gregcouch - going to any of those urls:

    https://index.docker.io/v2/quay.io/pypa/manifests/latest
    https://index.docker.io/v2/quay.io/pypa/tags/list

I get an unauthorized permissions error. Do you have a username and password that you could use to authenticate?

**Comment by bbockelm** [comment]
If you go directly to those URLs, you indeed should get a permission denied - you need to include your OAuth token in the request.

Try dumping the OAuth token request URL ... that might illuminate what is going on.

**Comment by vsoch** [comment]
@gregcouch try these environmental variables: http://singularity.lbl.gov/docs-docker#authentication-in-the-environment

**Comment by gregcouch** [comment]
I don't have a username nor a password.  When I use docker with a Dockerfile that has:
```
FROM quay.io/pypa/manylinux1_x86_64
```
or run:
```
docker run -it quay.io/pypa/manylinux1_x86_64 bash
```
it just works.

**Comment by vsoch** [comment]
sorry, to be more clear, when there is a different registry you have to specify it in an environmental variable, as @flx42 made more clear. I linked the page because it shows you how to do that, the first line:

     export SINGULARITY_DOCKER_REGISTRY='--registry myrepo'

I'll just be more clear next time, sorry about that!

**Comment by gregcouch** [comment]
Thank you.
```
sudo env SINGULARITY_DOCKER_REGISTRY='--registry quay.io' singularity import $IMAGE_NAME docker://pypa/manylinux1_x86_64
```
worked.

I still consider it a bug that singularity does not parse the docker argument the same way docker does.

**Comment by vsoch** [comment]
Could you be more clear in how the argument should be parsed? For example, with the current python function, I extract the namespace, repo name, and tag name:

      image = parse_image_uri('quay.io/pypa/manylinux1_x86_64')
      INFO:python:Repo Name: pypa
      INFO:python:Repo Tag: latest
      INFO:python:Namespace: quay.io

Could you expand more on "singularity does not parse the docker argument the same way docker does."

**Comment by flx42** [comment]
The registry should be parsed too:
nvidia/cuda:8.0-devel: namespace=nvidia repo=cuda tag=8.0-devel
quay.io/nvidia/cuda:8.0-devel: registry=quay.io namespace=nvidia repo=cuda tag=8.0-devel
Currently, the registry is parsed differently.

**Comment by vsoch** [comment]
ahh gotcha! So in the example from @gregcouch it would have been:

   quay.io/pypa/manylinux1_x86_6:latest

- registry: quay.io
- namespace: pypa
- repo: manylinux1_x86_6
- tag: latest

Yes I definitely can fix this up for the next version. Let me give that a go.

**Comment by vsoch** [comment]
ok here is a preview! This will definitely be fixed with the next version.

	parse_image_uri('ubuntu')
	{'namespace': 'library',
	 'registry': 'index.docker.io',
	 'repo_name': 'ubuntu',
	 'repo_tag': 'latest'}

	parse_image_uri('ubuntu/14.04')
	{'namespace': 'ubuntu',
	 'registry': 'index.docker.io',
	 'repo_name': '14.04',
	 'repo_tag': 'latest'}

	parse_image_uri('ubuntu/14.04:tag')
	{'namespace': 'ubuntu',
	 'registry': 'index.docker.io',
	 'repo_name': '14.04',
	 'repo_tag': 'tag'}

	parse_image_uri('quay.io/ubuntu/14.04:tag')
	{'namespace': 'ubuntu',
	 'registry': 'quay.io',
	 'repo_name': '14.04',
	 'repo_tag': 'tag'}

**Comment by flx42** [comment]
@vsoch great! How will that interact with the `--registry` option of `cli.py`?

**Comment by vsoch** [comment]
I'm getting rid of cli.py entirely, and replacing with a format that is akin to the core base - each module (shub and docker are the two we have now) has a `main.py` with various (non exposed) functions that use api.py, defaults.py, etc. Then, each module also has named scripts like "import.py" and "add.py" that get called with no arguments, and the arguments are all moved around as environment variables. So, for example, to import we would call:

      eval $SINGULARITY_libexecdir/singularity/python/docker/import.py

and the relevant variables, which were being passed from environment --> optparse commands (like `--registry`) will just be obtained from the environment. 

But actually, for `--registry`, and the rest of the details about the docker image, the user won't need to specify anything beyond the image name. We use the function above to get registry, repo, namespace, and tag. So @gregcouch original command should work without needing any environment stuff.

For variables that don't get parsed from image (eg, username and password for auth) instead of needing to export some weird thing for the client like `--username fee --password fofum` the user can just export:

    SINGULARITY_DOCKER_USERNAME
    SINGULARITY_DOCKER_PASSWORD

and they will be found! I just finished restructuring the code (and am going to get rid of cli.py soon) and still have a bit of work to do for labels/environment, but I should be done in the next few days! I really like this new format, because it mimics the core code base, and it also makes it easier because the different commands are more modular. I'll ping with a detailed PR when all is ready and tested... need to make sure we have new tests too :)

**Comment by gmkurtzer** [comment]
@vsoch, is this fixed in the 'development' branch? If so, let's close the issue.

Thanks!

**Comment by vsoch** [comment]
yep, this is addressed and fixed.
