### ISSUE TITLE
https://github.com/fatih/color no longer maintained

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4925]
https://github.com/fatih/color is no longer maintained. The 1.8.0 release added a note to this effect.

Watch the status of this repo to see if we need to switch to a maintained fork etc.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
