### ISSUE TITLE
Singularity built with --without-suid fails without --user option when root in unprivileged docker

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4971]
### Version of Singularity:

What version of Singularity are you using? 

3.5.2

### Expected behavior

Expect to be able to run singularity as the fake root inside of unprivileged docker

### Actual behavior

`singularity exec -ci` fails with `ERROR  : Failed to create ipc namespace: Operation not permitted` unless the `exec --user` option is given.  The same behavior happened in 3.4.0 & 3.4.1 but was fixed in 3.4.2.

### Steps to reproduce this behavior

```
$ docker run --security-opt seccomp=unconfined --rm -it -v /usr/local:/usr/local centos bash
# /usr/local/bin/singularity exec -ci docker://centos id
....
ERROR  : Failed to create ipc namespace: Operation not permitted
```
but it succeeds and shows the id if the exec -u option is included.

### What OS/distro are you running

CentOS 7.7

### How did you install Singularity

From source, using `./mconfig --without-suid`.

Attention: @dtrud @cclerget

**Comment by DrDaveD** [comment]
Also the problem does not go away with 'allow setuid = no' in singularity.conf.

**Comment by dtrudg** [comment]
Hi @DrDaveD - I appreciate this did work in `3.4.2` but I still don't really understand the reason to run a singularity unpriv install as root inside an unpriv docker fake root. What is the use case here?

If you have an unpriv Singularity run using a real host root account, then `-ci` will work AFAIK. In that situation the fact that we are running as `root` indicates that we don't want to/need to invoke the user namespace. I don't think we want to blindly use user-namespace in that situation. With that, then how do we go about making sure we do use user-namespace only if we are inside an unpriv fakeroot under docker, and not a real root?

**Comment by cclerget** [comment]
@DrDaveD It worked in 3.4.2 because of badly assuming to switch to user namespace when installed with `--without-suid` and was a mistake because it didn't cover the case where root want/need to run containers with the full set of features of Singularity since he has the privileges and Singularity doesn't provide a way to revert this behavior to tell to not use user namespace in this case.

After looking a bit it could be possible to add a check for root by looking at effective capability `CAP_SYS_ADMIN` presence and fallback to user namespace if missing meaning root won't be able to create namespaces without creating a user namespace first.

**Comment by DrDaveD** [comment]
@dctrud The use case was in a monitoring test, and I just learned that as it turns out it was not closely matched to the real use case which is to run as ordinary users.  However since a good solution was found in #4974, it's good to have it in case people want to use it.
