### ISSUE TITLE
Singulartity Installation (x509: certificate signed by unknown authority)

### ISSUE THREAD

**Issue by manoj1511** [apptainer/singularity#4975]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
singularity 3.5.2

### Expected behavior

when i run `make` expected behavior is for singularity to compile the source code.

### Actual behavior

```
go: github.com/Netflix/go-expect@v0.0.0-20190729225929-0e00d9168667: Get https://proxy.golang.org/github.com/%21netflix/go-expect/@v/v0.0.0-20190729225929-0e00d9168667.mod: x509: certificate signed by unknown authority
go: github.com/Netflix/go-expect@v0.0.0-20190729225929-0e00d9168667: Get https://proxy.golang.org/github.com/%21netflix/go-expect/@v/v0.0.0-20190729225929-0e00d9168667.mod: x509: certificate signed by unknown authority
/bin/sh: 1: /home/manoj/go/src/github.com/sylabs/singularity/scripts/go-generate: Permission denied
make: *** [Makefile:152: /home/manoj/go/src/github.com/sylabs/singularity/internal/pkg/buildcfg/config.go] Error 126
```

I am behind a company firewall where something is messed up behind. Is there a solution to install with out checking for certificates?

eg. 
`conda config --set ssl_verify false `
or 
`git config http.sslVerify false`

### What OS/distro are you running

ubuntu 19.04

### How are you trying to install Singularity

Source code

**Comment by dtrudg** [comment]
@manoj1511 - Are  you downloading the release tarball? This bundles vendored libraries so I would expect it to work.

Generally discussion on the `go` repo has been against allowing an insecure mode for `go mod` that ignores certificate issues: https://github.com/golang/go/issues/27332 - the issue was closed despite many people suggesting this. Unfortunately this means we don't have an easy workaround to support the `go mod` fetching of dependencies through a proxy that presents an invalid certificate. You would need to obtain the CA cert relevant for the proxy, and add it to the bundle on your machine so that it is trusted.

**Comment by dtrudg** [comment]
Hello. You should be able to work around this by using the fresh Go 1.14 which has a new env var:

>Environment variables

> GOINSECURE is a new environment variable that instructs the go command to not require an HTTPS connection, and to skip certificate validation, when fetching certain modules directly from their origins. Like the existing GOPRIVATE variable, the value of GOINSECURE is a comma-separated list of glob patterns.
