### ISSUE TITLE
Large numbers of simultaneous containers

### ISSUE THREAD

**Issue by anderspitman** [apptainer/singularity#4987]
This is a somewhat general question, though we are currently seeing issues on singularity 3.5.2, which I'll open a separate issue for once I have more information.

I'm wondering if there are any known limitations that might prevent singularity from scaling with large numbers of containers (200+) running simultaneously on the same machine? There have been several issues raised along these lines, ie #3929, #4767, and #4652 (which I opened myself several months ago).

It seems like there are a certain number of ways that the singularity runtime can turn into a sort of bottleneck. Sometimes these are just bugs, which get fixed over time. But is there any reason this shouldn't work in general?

Also, can you recommend techniques for debugging containers failing when lots of them are run at once? So far I've been monitoring number of open files and processes, but those both look ok.

Thanks!
//anders

**Comment by cclerget** [comment]
Hi @anderspitman , it's possible if you use single file container image like SIF that you reach the loop devices limit which is 256 loop devices maximum by default, Singularity can't go over due to this kernel limitation, you can check the following:

```
cat /sys/module/loop/parameters/max_loop
```

if it's > 0 so there is a non default limit between 1-256

You can also check that `max loop devices` is 256 in Singularity :

```
sudo singularity config global --get "max loop devices"
```

I was able to execute 200 instances without any issue with :

```
singularity build /tmp/test.sif docker://alpine
for i in $(seq 1 200); do singularity instance start /tmp/test.sif testing$i; done
```

The above used 200 loop devices.

Now if you need to go over this limitation you have two options depending of your requirements :

- you can use sandbox image instead, and run by example 2000 instances without any issues (depending of max user process limit) :
  ```
  singularity build -s /tmp/sandbox docker://alpine
  for i in $(seq 1 2000); do singularity instance start /tmp/sandbox testing$i; done
  ```
- you can use `shared loop devices` features if the containers (or most) are using same container image :
  ```
  sudo singularity config global --set "shared loop devices" yes
  singularity build /tmp/test.sif docker://alpine
  for i in $(seq 1 2000); do singularity instance start /tmp/test.sif testing$i; done
  ```

**Comment by cclerget** [comment]
I spoke too quickly about running 2000 instances, there is another thing to take into account: the maximum number of process that a user can have.

It worked but around 670 instances execution started to return error :

`runtime/cgo: pthread_create failed: Resource temporarily unavailable`

Singularity when running instance let two processes (master and sinit processes), both are running in Go context meaning they uses each between 7-8 processes so I have around 16 processes by instances, it began to fail around 670 instances giving 670*16 = 10720 processes, but this is normal with the systemd limit :

```
cat /sys/fs/cgroup/pids/user.slice/user-1000.slice/pids.max 
10813
```

To resume the number of processes used by Singularity (excluding container process of course) :
- around 16 processes by instances
- around 16 processes by execution with `--pid` option
- around 8 processes by execution with `shell`,`exec` and `run`

**Comment by anderspitman** [comment]
@cclerget this is exactly the type of information I'm looking for, thank you. I'll look into this more. Do you mind if I keep this issue open for a while in case I have more questions?

**Comment by cclerget** [comment]
> Do you mind if I keep this issue open for a while in case I have more questions?

No worries

**Comment by anderspitman** [comment]
@cclerget after further testing, I believe we're running into both of the issues above. One question about the "shared loop devices" setting. We have ~20 different containers, but all of them are likely to have multiple instances running at any given time. I don't expect the number to ever grow beyond maybe 40. Is this still a good use case for sharing loop devices? Are there any drawbacks?

As for user process limits. I'm still skeptical about that. The behavior matches what I would expect, but when running `watch -n .1 'ps ax | wc -l'`, I never see the actual number go above ~2000, and it should be able to handle 4096. Maybe it's just spiking too fast for me to see.

**Comment by anderspitman** [comment]
Also using sandboxes would not be ideal. The single-file deployment for containers is one of the big wins of singularity for us.

**Comment by cclerget** [comment]
@anderspitman `shared loop devices` is useful when using same container image as read-only, of course it doesn't work with writable container image but Singularity doesn't allow that as `shared loop devices` check only read-only loop devices. It will also reduces kernel cache usage. So it could definitively help in your case.

**Comment by mcuma** [comment]
Hi Cedric,

I am wondering why is "shared loop devices" not set to yes as default? Anders just asked us to do that on our Singularity installation and I'd prefer to have it on by default so that I don't forget to turn it on during future upgrades. Based on what you just said I don't see a reason for it to be set to no.

**Comment by cclerget** [comment]
Hi @mcuma , well it was set to no by default because it wasn't really battle tested but that could change in the next releases. In the meanwhile you could automate that with a singularity update script and set this feature on from command line with :

```
sudo singularity config global --set "shared loop devices" yes
```

**Comment by anderspitman** [comment]
@cclerget we enabled "shared loop devices" and increased the process limit for the user to 16384 (from 4096). My preliminary testing indicates that we're able to run a lot more concurrent containers now, so I feel fairly confident that you correctly diagnosed the problem.

I'm still not quite seeing what I'd expect in terms of the current number of processes run by the user. Can you recommend any good Linux tools for monitoring that? Ideally something that logs the maximum number of processes open during a given period of time, or at least something with very fine measurement resolution.

Anyway, thanks for your help!

**Comment by anderspitman** [comment]
I have an additional clue. According to [this](https://unix.stackexchange.com/a/307522/183448), threads count toward `ulimit` processes. I'm not sure if that's actually true, but running ps with -AL does indeed show upwards of 16k processes. Strangely it doesn't fail at 17k (and the hard limit is 16384). I had to push it beyond that in order to force it to fail forking.

**Comment by mcuma** [comment]
Thanks for the config command info - that's better than hand editing the config file.

**Comment by cclerget** [comment]
> I'm still not quite seeing what I'd expect in terms of the current number of processes run by the user. Can you recommend any good Linux tools for monitoring that? Ideally something that logs the maximum number of processes open during a given period of time, or at least something with very fine measurement resolution.

There is probably solutions but I'm not aware of outside of classic tools. More generally cgroups are very good at tracking the user resources consumed like cpu/mem/processes.

> I have an additional clue. According to this, threads count toward ulimit processes. I'm not sure if that's actually true, but running ps with -AL does indeed show upwards of 16k processes. Strangely it doesn't fail at 17k (and the hard limit is 16384). I had to push it beyond that in order to force it to fail forking.

For this observation, that's weird, rlimit should take precedence over cgroups pid max limit (if your system is driven by systemd), threads here are terminology because there are considered as process by kernel internal structure, they are lighter as they share memory/files with others but it remains a separate process within the same thread group. Linux shouldn't go over the max user process rlimit or cgroups pid limit.

**Comment by anderspitman** [comment]
@cclerget sorry I never closed the loop on this. I think we're good to go for now. Thanks again for the help.
