### ISSUE TITLE
Creating writable images for quick debugging as was possible in singularity 2.6

### ISSUE THREAD

**Issue by VedatDurmaz** [apptainer/singularity#4997]
Hi there,

last year, using singularity 2.6, I was able to create images that were both:
- writable AND
- executable

With those writable images, it took me only few seconds to see the effect of files inside the image (shell into writable img, modify stuff, STRG-D, execute).

With singularity 3.5, I have no more `--writable` option upon building, only `--sandbox`. If I build with the latter, I can modify files (scripts) in that "image", but then need to build a proper image from that sandbox image in order to be able to run it and check the results.  As a consequence, every modification of the image content takes about 15 minutes now until I see an effect! 

Is there some way to have the same fast options/cycles of testing images after internal modifications with version 3.5? I couldn't find any solution to that "issue". 

Many thanks in advance!
Vedat

**Comment by dtrudg** [comment]
@VedatDurmaz - I'm a little confused here. You can `singularity run mysandboxdir/` to run a sandbox. You shouldn't need to build it into an image to check each change that you make.

Is there a specific reason you need to run the image each time, and cannot run the sandbox - then just build the image when complete?

**Comment by VedatDurmaz** [comment]
@dctrud  I usually execute using 

```
singularity exec --bind ... image.sif /usr/bin/python script.py + many arguments
``` 
But applying this to the sandbox gives the error `container creation failed: mount /etc/localtime->/etc/localtime error: while mounting /etc/localtime: could not mount /etc/localtime: operation not supported`.

And if I execute using sudo (which I would like to avoid), I get another error: `SIF writable overlay partition found in image.sif`.

Do you think `singularity run` would solve the problem? And can I use it with an internal script? 

Sorry for the stupid questions!

**Comment by dtrudg** [comment]
`singularity run` won't change the issue you are seeing here. Which *exact* version of Singularity 3.5 are you using and what filesystem is your sandbox on? The localtime bind issue may be addressed already, or be possible to address.

If you can send `singularity -d ....` debug info and output of `mount` then that would be useful with regard to the mount issue.

Also note that you can use a writable overlay following the documentation here... https://sylabs.io/guides/3.5/user-guide/persistent_overlays.html ... to be able to make modifications over what is in a SIF file. These modifications will only be present when the overlay option is used though. The container root filesystem in a SIF file is read-only by design - to support the signing/verification etc.

**Comment by VedatDurmaz** [comment]
The sandbox runs without errors if I add the "--writable" flag. 

I'm very sorry & many thanks for your help anyway!
