### ISSUE TITLE
Better usage printout for Global options

### ISSUE THREAD

**Issue by robertlugg** [apptainer/singularity#5004]
### Version of Singularity:
```
$ singularity version
3.3.0-1
```

### Similar issues
https://github.com/sylabs/singularity/issues/3095
### Expected behavior

I want to see all available options when running `singularity build` and the `Usage:` string is displayed.  I don't know what the implementation should be.  Perhaps show two sections one for global and one for command specific options.

### Actual behavior

Only build related options are shown in the `Usage:` message:
```
sudo /usr/local/bin/singularity build --sandbox -V p5lab_v01 p5lab_v01.def
Error for command "build": unknown shorthand flag: 'V' in -V

Options for build command:

      --builder string    remote Build Service URL, setting this implies --remote (default "https://build.sylabs.io")
  -d, --detached          submit build job and print build ID (no real-time logs and requires --remote)
      --docker-login      login to a Docker Repository interactively
  -f, --fakeroot          build using user namespace to fake root user (requires a privileged installation)
  -F, --force             delete and overwrite an image if it currently exists
  -h, --help              help for build
      --json              interpret build definition as JSON
      --library string    container Library URL (default "https://library.sylabs.io")
      --no-cleanup        do NOT clean up bundle after failed build, can be helpul for debugging
      --nohttps           do NOT use HTTPS, for communicating with local docker registry
  -T, --notest            build without running tests in %test section
  -r, --remote            build image remotely (does not require root)
  -s, --sandbox           build image as sandbox format (chroot directory structure)
      --section strings   only run specific section(s) of deffile (setup, post, files, environment, test, labels, none) (default [all])
      --tmpdir string     specify a temporary directory to use for build
  -u, --update            run definition over existing container (skips header)

Run 'singularity build --help' for more detailed usage information.
```

The central problem is that when my command is incorrect for `singularity build`, it only shows the singularity build options.  It doesn't show the Global options

### What OS/distro are you running

```
cat /etc/redhat-release 
CentOS release 6.10 (Final)

```

### How did you install Singularity

From source, I believe.

**Comment by cclerget** [comment]
Hi @robertlugg , this is the expected output as `-V` is an unknown flag for the build command and you can't specify a global option in a command, Singularity always worked this way and the syntax is :

`singularity [global options...] command [command options...] [subcommand [subcommand options...]]`

The processing of CLI arguments is correct and display the usage of command usage where the option parsing failed, Singularity can't know that you want to use a global option inside a command because it's unlikely to work this way.

Additionally that will bring more confusion by generating big usage output.

**Comment by robertlugg** [comment]
My example was misleading.  The "-V" is just an artifact of what I was doing at the moment.  What I was trying to do is get verbose output.  After looking in the manual, I saw that I should have used `--debug` in that command line (but before `build`).  I'm asking to instead list --debug in the Usage message.

My request is for the Usage string to include **both** what I think are called Global Options (like --debug) and command options (like --sandbox).

I agree with you that a change might result in more confusion than its worth.  I was hoping someone was more clever than I am and could come up with a Usage string that was more informative while not being more confusing.

**Comment by cclerget** [comment]
Sorry for the late response but that's not something which will be fixed because of the amount of code to add and maintain to handle this as the CLI package used doesn't really give the possibility to do that in simply. I'm going to close the issue as the CLI provides this information with `singularity help` to show global options which can be passed.
