### ISSUE TITLE
Compile Go

### ISSUE THREAD

**Issue by shersoni610** [apptainer/singularity#5007]
Hello,

I downloaded the singularity and installed Go. However, following page-9 
of the documentation:
$ ./mconfig && \
make -C builddir && \
sudo make -C builddir install

I get the following message:

E: Not inside a git repository and no VERSION file found. Abort.

How should I compile the software?

**Comment by cclerget** [comment]
Hi @shersoni610 , if you are using a master archive then you need to version it yourself with :

```
cd singularity-master && echo "3.5.2" > VERSION
./mconfig && make -C builddir && sudo make -C builddir install
```

Between this is not covered by documentation because it's not the usual way to get and compile singularity unless you are a developer and don't have git installed.

It's better to use a release archive in this case :
https://github.com/sylabs/singularity/releases/download/v3.5.2/singularity-3.5.2.tar.gz

**Comment by tinchogb** [comment]
Hi,

I read [Downloading and Compiling](https://sylabs.io/guides/3.5/user-guide/quick_start.html#compile) and I did the same as @shersoni610 and didn't work either, even following the @cclerget recommendations (downloading [https://github.com/sylabs/singularity/releases/download/v3.5.3/singularity-3.5.3.tar.gz](https://github.com/sylabs/singularity/releases/download/v3.5.3/singularity-3.5.3.tar.gz))

Steps:
export VERSION=3.5.3
wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
tar -xzf "${VERSION}".tar.gz
cd singularity-3.5.3/
./mconfig && make -C builddir && sudo make -C builddir install

Error:
E: Not inside a git repository and no VERSION file found. Abort.

I checked the directory **singularity-3.5.3/**  and I think that is not a git tree repository and that's why the compilation fails when calls **scripts/get-version**.

Maybe the compilation checking files need to be re-written again.

**Comment by adszm** [comment]
I downloaded [Singularity 3.6.1](https://github.com/hpcng/singularity/releases/download/v3.6.1/singularity-3.6.1.tar.gz) and ./mconfig && make -C builddir && make -C builddir install. Performed manually works perfectly, but when I try to reproduce it with Ansible I get error:

/tmp/singularity-3.6.1/singularity/mconfig: 1: /tmp/singularity-3.6.1/singularity/mconfig: scripts/get-version: not found", "stderr_lines": ["/tmp/singularity-3.6.1/singularity/mconfig: 1: /tmp/singularity-3.6.1/singularity/mconfig: scripts/get-version: not found"

I can provide playbook if necessary.
