### ISSUE TITLE
File not found, but files exist inside the container

### ISSUE THREAD

**Issue by pguillem** [apptainer/singularity#5019]
### Version of Singularity: 

`2.4.2-dist`

I use a definition file to build an Ubuntu 14 container, where I instruct the a whole directory to be copied to the container. This directory has a program, which should be executed as %runscript.

When I run the container... it outputs this:

```
command not found
```
If I go inside the container's shell and navigate to the directory, I try executing the binary file and it gives this:

```
Singularity grid.sif:/group/bioinfp_apps/grid> ./greater.bin
bash: ./greater.bin: No such file or directory

```
However the file exists and all files are in the directory where they are expected to be. Permissions of all files are a+x.

### Expected behavior
What did you expect to see?

program 'greater.bin' should open its GUI interface.

### Actual behavior
The container says the file is not found. I go into the shell of the container and I can see the files in the directory. 

### What OS/distro are you running
Ubuntu 18

### How did you install Singularity
Dist package

**Comment by dtrudg** [comment]
Hi @pguillem - I'm afraid that the open-source Singularity 2.4 is very old now, and is no longer supported.

However as a general point, the error "No such file or directory" can happen because a library that the program is linked against doesn't exist in the container. Try to run `ldd` against your program, e.g. `ldd greater.bin` and look for any listed libraries that are not found.

If you compiled the program for Ubuntu 18.04 (your host system), and you are trying to use it in an older Ubuntu 14 container then it is quite likely that a library that is needed will not be found.

**Comment by dtrudg** [comment]
I'm going to close this now as the report was against an unsupported version of Singularity. Please feel free to open a new issue if you experience the problem on a current version. Thanks.
