### ISSUE TITLE
limit memory, cpu, etc without sudo/root?

### ISSUE THREAD

**Issue by BlakeGFitch** [apptainer/singularity#5024]
This is a question and maybe feature request.

I would like to set limits on a singularity container instances running on an HPC cluster where I do not have sudo privileges. I am starting multiple containers per node and hitting out-of-memory issues which bring down the slurm task and then the whole job. (This is with Nextflow and the ignite executor if interested.) It seems like such limits are either possible/done or there is a good reason why they can't be done which I'm not seeing.

Is it, or could it be possible to have command line arguments when starting a singularity container that limit the memory, cpu, etc without sudo?

Thanks!

**Comment by dtrudg** [comment]
In general when running under something like Nextflow you will be able to specify memory limits in your nextflow script for each process. If you are using the Ignite executor then Nextflow will need to support passing a limit defined on the process in your nextflow script to Ignite, and then Ignite will need to either enforce that limit directly, or would need to do something in the way it is calling out to singularity to enforce a limit.

Really this isn't something we can address purely from a Singularity point of view, since memory limits are a property of processes in Nextflow. We need to understand if you are setting memory limits in your nextflow script, and how Nextflow then passes them to Ignite, and Ignite then tries to enforce them.

Have you brought this up in the Nextflow Gitter chat or similar? We can assist here if there is a question of how Nextflow can enforce the limits when calling Singularity under the Ignite executor (if it doesn't already), but it's likely that this is really more a question through the chain of execution controlled by Nextflow rather than at the Singularity level.

**Comment by BlakeGFitch** [comment]
Thanks for the response.

I thought about what you are suggesting. But I don't think nextflow/ignite could ask singularity to enforce limits even if they were willing because I don't see a way ask singularity enforce such limits even at a command line without sudo.

I think I'm convincing myself that singularity can't enforce such limits either since the container is run as the invoking user. firejail seems capable of such enforcement but is setuid where singularity isn't.

**Comment by dtrudg** [comment]
To confirm, are you specifying memory limits in your Nextflow script, that aren't being respected? E.g.

```
process big_job {

    memory '2 GB'

    """
    your task script here
    """
}
```

If you have these limits in place in your Nextflow scripts _for all processes_, and they are not being respected then it would need dialogue with the Nextflow developers to find out:

- Are they passing such information to Ignite, and does Ignite have an inbuilt mechanism to impose limits on sub-processes. (it doesn't necessarily need to ask Singularity to do it, as Ignite could e.g. just monitor memory usage and send a KILL/TERM to the singularity container process if it exceeds a threshold).
- If there is a limit that Ignite is trying to impose, why is it being circumvented if a Singularity container is being run.

Also - is your Singularity install using the setuid root mode, or is it non-setuid using user namespaces?

**Comment by dtrudg** [comment]
Am going to tag @pditommaso here in case he has any time to give some input... apologies Paolo if you are busy :-)

**Comment by pditommaso** [comment]
NF does not propagate the mem requirement to the container. Said that, is Singularity able to handle memory containment?

**Comment by dtrudg** [comment]
Singularity can limit using cgroups, but applying cgroups limits needs it to be run with sudo.

```
09:41 AM $ cat memlimit.toml 
[memory]
    limit = 524288000

09:40 AM $ singularity run --apply-cgroups memlimit.toml docker://alpine
FATAL:   --apply-cgroups requires root privileges
```

I was wondering if Ignite job spec handled the memory limit in some way.... e.g the ignite daemon monitoring memory usage and doing a kill on the process it launched? I guess that's not the case?

**Comment by pditommaso** [comment]
Then, I don't think makes sense to support it in NF.

**Comment by pditommaso** [comment]
> I was wondering if Ignite job spec handled the memory limit in some way

No, it's not possible the task is executed in the hosting env as a Bash process.

**Comment by dtrudg** [comment]
Fair enough. The Ignite thought is related to how SLURM works without cgroups. E.g. SLURM can kill jobs going over mem limit even without cgroup support if you use the `task` plugin or accounting. It will periodically look at memory usage and kill something if it goes over the requested limit. In my experience this works relatively well regardless of what the job is... if it is spawning shells or similar.

I guess I'd naively assumed that Ignite, as an Executor service might provide similar.

Given Singularity is daemon-less it's not something we would really want to enforce in the manner without, aboiding cgroups.

**Comment by pditommaso** [comment]
Make sense, but Ignite does not provide anything such that out of the box and with NF we have no plan to implement such a feature.

**Comment by dtrudg** [comment]
Thanks much for your input @pditommaso 

Sorry @BlakeGFitch - it looks like this is not something that will be solved outside of Ignite adding a feature out of the box.

Because Singularity is daemon-less and we generally want to avoid adding supervising processes etc. into our architecture (deferring this to an upstream supervisor/scheduler) then cgroups which need privilege to setup remain the only option, and that's not compatible with use via Nextflow.

**Comment by BlakeGFitch** [comment]
Thanks for considering this! I'll close the issue.
