### ISSUE TITLE
Failed to resolve path to /usr/local/var/singularity/mnt/container

### ISSUE THREAD

**Issue by sgiavasis** [apptainer/singularity#5042]
### Version of Singularity:
`2.5.2-dist`

### Expected behavior
Expecting basic `singularity run` and `singularity shell` execution. 

Hello- hopefully this might be simple. This is for a collaborator who wants to run our container, who has Singularity client 2.5.2-dist on a shared computing resource with many users. I suspect this is some interaction arising from an older Singularity version with the way the client/install is set up on this particular system and may not be a Singularity error. We are not against suggesting they upgrade their Singularity version.

### Actual behavior
Regardless of container (for example below, using the simple singularity-cli container), and with correct mappings and all, users always see this error:

```
singularity shell singularityhub-singularity-cli-master-latest.simg
ERROR: Failed to resolve path to /usr/local/var/singularity/mnt/container: No such file or directory
ABORT : Retval = 255
```

I saw in previous issues that this similar error has arisen, but was potentially resolved in version 2.5.1, so I'm not sure if this is something different.

### Steps to reproduce this behavior

```
singularity pull shub://singularityhub/singularity-cli
singularity shell singularityhub-singularity-cli-master-latest.simg
```

(but on our client's system, :) )

### What OS/distro are you running
Ubuntu 18.04.4 LTS

### How did you install Singularity
From source. Commands taken:

```
tar xvf singularity-$VERSION.tar.gz
cd singularity-$VERSION
./configure --prefix=/usr/local
make
sudo make install
```

Singularity is installed in /usr/local/singularity.
(Not /usr/local/var as seen in error message).

Thank you!
Steve

**Comment by jmstover** [comment]
>  who has Singularity client 2.5.2-dist on a shared computing resource with many users

Okay .... When Singularity is built, paths are hardcoded into the binary based on `./configure` values. What you're looking at this the "localstatedir" value ( /usr/local/var ).

If singularity was build with `--prefix=/usr/local`  ... then it's going to require that this structure exists:
```
mkdir -p /usr/local/var/singularity/mnt/{container,final,overlay,session}
```
It's *highly* recommended that this location is local to the node it's running on. So, you could compile something like:

```
./configure --prefix=/usr/local/singularity --localstatedir=/var
```
Then you would need the following ran on each node:
```
mkdir -p /var/singularity/mnt/{container,final,overlay,session}
```

**Comment by tfrancois** [comment]
> > who has Singularity client 2.5.2-dist on a shared computing resource with many users
> 
> Okay .... When Singularity is built, paths are hardcoded into the binary based on `./configure` values. What you're looking at this the "localstatedir" value ( /usr/local/var ).
> 
> If singularity was build with `--prefix=/usr/local` ... then it's going to require that this structure exists:
> 
> ```
> mkdir -p /usr/local/var/singularity/mnt/{container,final,overlay,session}
> ```
> 
> It's _highly_ recommended that this location is local to the node it's running on. So, you could compile something like:
> 
> ```
> ./configure --prefix=/usr/local/singularity --localstatedir=/var
> ```
> 
> Then you would need the following ran on each node:
> 
> ```
> mkdir -p /var/singularity/mnt/{container,final,overlay,session}
> ```

@jmstover:  Thank you for your reply to this sir!  Question for you, the /usr/local/var folder structure is not standard fare in Ubuntu or Debian Linux distributions and not sure why singularity has to be installed in /usr/local/var/singularity rather than /usr/local/singularity.  

Rather than re-compiling or re-installing with the suggested /usr/local/var, is there something we can do to update our config to use the current installed location of /usr/local/singularity please?

It's not clear to me in your response if the fix you provided resolves this.  We'd rather do that than having to re-install Singularity to this /usr/local/var location.  Respectfully, can you please advise on this for us?   And again thank you kindly for your quick and timely response!

Alternatively, not sure if using a symlink folder in the expected location would resolve the issue.  I can try that but I'll first wait to see what you advise as a symlink might work but might be a little kludgey.

**Comment by dtrudg** [comment]
@tfrancois - if you want to install to `/usr/local/singularity` then you must configure with `--prefix=/usr/local/singularity` - then at make install the structure should be created for you.

I'm afraid there is no way to update the configuration of the installed singularity due to paths being compiled in, which is important for security reasons so Singularity looks at the correct root controlled configuration, for security critical operations.

**Comment by tfrancois** [comment]
Again thank you for the unbelievably quick responses!  Would a symlink suffice if I place in the in the /usr/local/var expecting location?  Or would that create security issues or be an unsupported fix?

**Comment by dtrudg** [comment]
It will probably work, but it'd definitely not be a supported / advised solution.

**Comment by jmstover** [comment]
> not sure why singularity has to be installed in /usr/local/var/singularity rather than /usr/local/singularity.

It comes down to the `localstatedir` value. By setting `--prefix`, this value defaults to `$prefix/var` ... We use a `singularity` directory within the `localstatedir` location. So it becomes: `$localstatedir/singularity`.

The other issues you're going to be running into is the `libexecdir` value, etc... If you used `--prefix=/usr/local` then it's going to be looking for `/usr/local/libexec/singularity`.  If you look at the singularity script, you can see where were expecting locations to be, and these locations are hard coded in the C code.

As @dctrud mentioned, the only true fix is a recompile as these values are taken at configure/build time.  As I mentioned, we highly recommend the `--localstatedir` value being local to the individual node and not part of a global filesystem.

You can get some path info by running:
```
strings start-suid | egrep 'libexec|singularity/'
```

Also the `singularity selftest` command will give you some info.
