### ISSUE TITLE
Detection of setns fails in very minimal chroot environment

### ISSUE THREAD

**Issue by benmenadue** [apptainer/singularity#5047]
The current `setns` detection during build fails on our new CentOS 8 cluster:
https://github.com/sylabs/singularity/blob/dbe15bdc62d81cbf6a45504aefefb3beddd25da0/mlocal/checks/project-post.chk#L293-L306

- The first check relies on the static `libc.a` being installed, even though it's not needed to use the program (we don't have it installed on our cluster because we don't use or support static linking for anything).
- The second check relies on `/proc` being mounted, which if you're building in a `chroot` (which we need to because it hard-codes the install paths) will fail unless you've explicitly bind-mounted `/proc` into place.
- Just because `/proc/self/ns` exists, doesn't mean that `SYS_setns` is defined.

Moreover, if neither `setns` nor `SYS_setns` are available, it produces an unusable build (even without using instances):
```
$ singularity -v exec alpine_latest.sif cat /etc/alpine-release
VERBOSE: HOME=/home/900/aww900
VERBOSE: Set messagelevel to: 4
VERBOSE: Starter initialization
VERBOSE: Check if we are running as setuid
VERBOSE: Drop root privileges
VERBOSE: Drop root privileges permanently
VERBOSE: Spawn stage 1
VERBOSE: Execute stage 1
VERBOSE: stage 1 exited with status 0
VERBOSE: Get root privileges
VERBOSE: Change filesystem uid to 8181
VERBOSE: Spawn master process
VERBOSE: Create mount namespace
VERBOSE: Entering in mount namespace
VERBOSE: setns() not supported at compile time by kernel at time of building
ERROR  : Failed to enter in shared mount namespace: Function not implemented
```
(I'm not sure why it needs `setns` for a simple `exec`...)

**Comment by benmenadue** [comment]
Perhaps a better method of trying to detect the libc wrapper would be to just try and link a binary that calls it; if it links, then the wrapper must exist. Similarly, if the wrapper is not available, then try and build something that uses `SYS_setns` to see if you can use `syscall(2)` to invoke it directly.

**Comment by cclerget** [comment]
Hi @benmenadue ,

> The first check relies on the static libc.a being installed, even though it's not needed to use the program (we don't have it installed on our cluster because we don't use or support static linking for anything).

I agree that a better check could be done there, it's an old one and could be reworked a bit without relying on static library.

> The second check relies on /proc being mounted, which if you're building in a chroot (which we need to because it hard-codes the install paths) will fail unless you've explicitly bind-mounted /proc into place.

It's generally recommended to at least bind mount `/proc` and `/dev` when you setup a chroot environment no matter what you do in it otherwise don't expect that everything works in it.

> Just because /proc/self/ns exists, doesn't mean that SYS_setns is defined.

The presence of `/proc/self/ns` is enough to assume that setns is available (not forcibly provided the C library wrapper) that's why it's provided by both https://github.com/sylabs/singularity/blob/master/cmd/starter/c/setns.c and https://github.com/sylabs/singularity/blob/master/cmd/starter/c/include/setns.h if the `libc.a` check fail and the presence check on `/proc/self/ns` pass.

Anyway you can fix your issue by just bind mount `/proc` in the chroot environment.
