### ISSUE TITLE
Issue with github.com/sylabs/singularity/log-plugin while compiling Singularity from scratch

### ISSUE THREAD

**Issue by bne86** [apptainer/singularity#5048]
### Version of Singularity:
3.5.3

### Expected behavior
compile without error

### Actual behavior
error is thrown for log plugin

### Steps to reproduce this behavior
```
$ wget https://github.com/sylabs/singularity/releases/download/v3.5.3/singularity-3.5.3.tar.gz
$ tar -xvf singularity-3.5.3.tar.gz
$ cd singularity/
$ ./mconfig
$ cd builddir/
$ make
 GEN /p/project/chpsadm/vonstvieth1/singularity/singularity/scripts/go-generate
 GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog imgbuild_engine oci_engine singularity_engine fakeroot_engine apparmor selinux"
 GEN etc/bash_completion.d/singularity
ERROR:   Unable to initialize plugins: while initializin plugin "github.com/sylabs/singularity/log-plugin": plugin.Open("object.so"): realpath failed
```

### What OS/distro are you running
CentOS 7.7

### How did you install Singularity
Source

**Comment by cclerget** [comment]
Hi @bne86 , 3.5.3 doesn't include fix for this issue because it's part of the plugin rework coming in 3.6.0, you need to remove it manually from the plugin installation directory, the message is confusing because it doesn't exit and just throw this error.

Additionally plugins compiled from master branch are not compatible with <= 3.5.3 and globally plugins would require to be recompiled for each version depending of changes in the code base.

**Comment by bne86** [comment]
Thanks for the swift response, do you already have a timeframe for the 3.6.0? Feel free to close this ticket as somewhat invalid.

**Comment by cclerget** [comment]
> do you already have a timeframe for the 3.6.0?

Should be around may
