### ISSUE TITLE
unsquashfs not found, even though it is available

### ISSUE THREAD

**Issue by casv2** [apptainer/singularity#5116]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
singularity version d5eaf8a+dirty
```

I built a .simg on my laptop and sent it to my HPC. Here I tried to shell into it using singularity installed through conda on the HPC.

```
(base) casv2@womble:~$ singularity shell ubuntu.simg 
INFO:    Convert SIF file to sandbox...
FATAL:   while extracting ubuntu.simg: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found
```

Unsquashfs is available though 

```
(base) casv2@womble:~$ unsquashfs -v
unsquashfs version 4.3 (2014/05/12)
```

This is within a conda environment on a HPC.

```
/home/casv2/miniconda2/bin/unsquashfs
```

### What OS/distro are you running

```
$ cat /etc/os-release

(base) casv2@womble:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"

```

### How did you install Singularity

Through conda

**Comment by moritzschaefer** [comment]
I encountered the same issue (and also installed singularity through conda). I assume that for some reason, singularity does not use the PATH variable of the calling environment/shell. 
When I symlink my conda-installed unsquashfs into /usr/local/bin, then everything works fine.

**Comment by jmstover** [comment]
In 3.x, there's a `singularity.conf` setting `mksquashfs path` ... In your case you'll want to set it to be something like:

```
mksquashfs path = /home/casv2/miniconda2/bin
```

The search PATH is restricted otherwise to system locations... i.e. `/bin, /usr/bin, /sbin, /usr/sbin, /usr/local/bin, /usr/local/sbin`

**Comment by moritzschaefer** [comment]
Is there a reason why singularity doesn't respect the PATH variable from the environment?

I'm asking because it's unsatisfying for conda users installing singularity to need to take a second step before being able to run it.

Would you suggest to file a bug report with conda for this package such that it provides a modified version of singularity.conf (containing the user's conda-bin path)?

**Comment by jmstover** [comment]
> why singularity doesn't respect the PATH variable from the environment

We're dependent on some specific programs to do things which should be host dependent. It's more of a philosophy thing that we have a SUID component, so we don't want an easy vector for a user to just change their PATH and hey... now we have a security issue because we aren't running the binary we think we should be. So the PATH is restricted.

If squashfs tools aren't the system package, then the admin needs to specify the location where you can find them. It comes down to security over ease of use.

It looks like above they're running a non-suid version since "shell" is extracting the SIF file. What that does is use unsquashfs to extract the image to a temp location, then run from that sandbox copy.

**Comment by casv2** [comment]
`mksquashfs path = /home/casv2/miniconda2/bin` solved the problem. 

Thank you very much for the help, much appreciated!
