### ISSUE TITLE
Can't use --nv with --writable

### ISSUE THREAD

**Issue by cceyda** [apptainer/singularity#5169]
Is `--nv` flag still incompatible with `--writable`? 
This is a big problem for a large portion of my use cases where I use singularity containers as development environments.
There are some closed issues and related PRs which suggests this issue is solved in version 3

- https://github.com/sylabs/singularity/pull/2156

- https://github.com/sylabs/singularity/pull/4946

**But**: I still get errors

```
singularity build --sandbox --fakeroot containers/ubuntu docker://ubuntu:18.04
singularity shell -w --nv containers/ubuntu/
```
![image](https://user-images.githubusercontent.com/15624271/78351205-6624ca80-75e1-11ea-884c-a69a936ab3c8.png)

I have overlay and underlays enabled (default) 
```
sudo singularity config global --get "enable overlay"
try
sudo singularity config global --get "enable underlay"
yes
```

### Version of Singularity:
singularity version 3.5.2 (Installed from source)
Running on Ubuntu:18.04

**Comment by cclerget** [comment]
@snu-ceyda Fix #4946 is not available in 3.5.2, please try with 3.5.3.

**Comment by cceyda** [comment]
I have updated to 3.5.3 there is no error now (just warnings saying gpu related directories couldn't be mounted)
So does this mean it isn't/won't be supported/possible to use GPU with --nv and the --writable flag?
(I guess I will have to install gpu stuff to every container :/ )

**Comment by cclerget** [comment]
@snu-ceyda It's supported at some point, CUDA libraries are always bound into container with or without writable option, the warnings are telling that some CUDA binaries like `nvidia-smi`, `nvidia-debugdump` ... won't be available with `--writable` but libraries are available and bound in `/.singularity.d/libs`, in writable mode both overlay/underlay are disabled and Singularity doesn't alter image if writable is selected, that's why Singularity can't create path `/usr/bin/nvidia-smi` and can't mount it in container image, so if you really need CUDA binaries with writable, you can just do:

```
singularity build --sandbox --fakeroot containers/ubuntu docker://ubuntu:18.04
touch containers/ubuntu/usr/bin/nvidia-smi
touch containers/ubuntu/usr/bin/nvidia-debugdump
...
singularity shell -w --nv containers/ubuntu/
```

**Comment by cceyda** [comment]
@cclerget I get it now that seems like a reasonable solution for the time being. Thank you!
