### ISSUE TITLE
Singularity / OpenMPI: PMIX Temporarily Unavailable

### ISSUE THREAD

**Issue by b3m2a1** [apptainer/singularity#5203]
### Version of Singularity:

What version of Singularity are you using? Run:

```
[host]$ singularity version
3.4.2-1
```

When I start up MPI using `mpirun` inside a SLURM, sometimes `MPI_Init` fails with

```
[host] PMIX ERROR: PMIX TEMPORARILY UNAVAILABLE in file ptl_tcp.c at line 688
[host] OPAL ERROR: Unreachable in file pmix2x_client.c at line 112
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

and the entire `mpirun` job just hangs, which means I can't even programmatically detect that this happened. 

The exact command is

```
module load gcc_8.2.1-ompi_3.1.4
mpirun -n 56 ./rynlib sim run CH5_5000
```

and in my container I built relative to OpenMPI v3.1.4 as well.

### Expected behavior

No crash

### Actual behavior

The `mpirun` call hangs

### Steps to reproduce this behavior

Install MPI according to what is here: https://sylabs.io/guides/3.3/user-guide/mpi.html

I used OpenMPI v3.1.4 because it was in the initial example I saw

I didn't have access to a `/opt` directory  inside my container, so I installed `mpi` in a directory relative to the image location.

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

I'm just using the HPC version of Singularity, so I don't know

**Comment by dtrudg** [comment]
@b3m2a1 - we need a bit more information here.

- How are you running the slurm job? If you are launching an `sbatch` script can you provide it?
- Related to this - how is Singularity being invoked? Are you running singularity and then mpirun inside it manually? I don't see any explicit call to `singularity` in the information you have provided.

**Comment by b3m2a1** [comment]
@dctrud this is the `sbatch` script

```
#!/bin/bash
#SBATCH --job-name=CH5_5000
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=28
#SBATCH --time=0-08:00:00
#SBATCH --mem=118G
#SBATCH --chdir=.
#SBATCH --partition=<p>
#SBATCH --account=<a>
#SBATCH --mail-type=ALL


echo "***** STARTING SIMULATION w/ OpenMPI v3.1.4  ******"

# load environment
module load gcc_8.2.1-ompi_3.1.4 # or whatever MPI module is available--must be 3.1.4 or in line with what is inside the container
mpirun -n 56 ./rynlib sim run CH5_5000

exit 0
```

In that, `rynlib` is a built Singularity image with a run script that will call into MPI if asking for the right kind of job.

I'm using python as an orchestrator, so the MPI hooks are in a library that python dynamically loads, hence not calling an MPI binary directly. This works in other environments and also works ~50% of the time with Singularity, so it seems to be fundamentally a Singularity issue.

**Comment by dtrudg** [comment]
> also works ~50% of the time with Singularity,

Does this mean it works 50% of the time with this container, or that it works with some containers but not others?

As a start, I'd advise using `srun` instead of `mpirun` if your install of SLURM is configured to support PMIx.

Then - how do you install OpenMPI into your container?

> I'm using python as an orchestrator, so the MPI hooks are in a library that python dynamically loads, hence not calling an MPI binary directly. 

Most things are related to a big MPI version mismatch, or environment variables host vs container. One thing to consider here is that with Singularity mounting `$HOME` by default then Python will pick up packages install in `$HOME` on the host which may not work in the container. The `--contain` option is worth a try there too to avoid this.

Generally to troubleshoot MPI issues we need a lot more information about the content of the container, and the environment on the host and in the container. The following are helpful...

- The container definition that shows how MPI was installed / configured in the container.
- The output of `env` run under mpirun  / srun in the batch job. e.g. `mpirun -n 1 /usr/bin/env`

**Comment by dtrudg** [comment]
Also, note that the documentation for 3.5 (your link refers to 3.3) now has more information about using MPI with Singularity, including the `bind` approach where you do not need MPI in the container, but bind it from the host. I'm not clear if that's what you intend?

https://sylabs.io/guides/3.5/user-guide/mpi.html

**Comment by b3m2a1** [comment]
It works 50% of the time with this container and this sbatch script.

I initially started by trying to use srun, but I get this issue

```

[n2109.hyak.local:21202] OPAL ERROR: Not initialized in file pmix2x_client.c at line 112
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
  PMI-2 support. SLURM builds PMI-1 by default, or you can manually
  install PMI-2. You must then build Open MPI using --with-pmi pointing
  to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
```

which I took to mean that SLURM hasn't been configured for that.

MPI was installed on the container by downloading from

https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.4.tar.bz2

unpacking this, calling ./configure with the flags

```
['--disable-oshmem', '--enable-branch-probabilities', '--disable-mpi-fortran', '--with-slurm']
```
(the --with-slurm one was a test and I hit the exact same issues/successes with or without it)

and then building with make -j4

The env is huge. Are there any specific bits you'd like to see before I just paste the entire dump here?

**Comment by dtrudg** [comment]
Hi @b3m2a1 - I'm not sure what I did here.... I thought I was editing my own response, quoting your last one - but apparently I edited your response. Apologies - trying to fix this.

**Comment by dtrudg** [comment]
okay - sorry about that - reverted to your original comment above. Here is my reply....

> It works 50% of the time with this container and this sbatch script.

This is the key piece of information. Because Singularity doesn't directly participate in any of the MPI communication / flow, rather it sets up namespaces and the container environment for a job and then gets out of the way, there isn't really a reason why anything specifically in Singularity should cause this unpredictable behaviour.

If things work 50% of the time then the environment setup by Singularity, and the container itself, are likely fine.

If the job is going out to different nodes between runs that pass / fail there is quite likely something different on those nodes to cause the varying behaviour. If repeated runs pass / fail when they are scheduled to the same nodes then there could be some difference in the node environment.

If you can, check the dmesg output on the nodes for any obvious errors.

We've seen in the past that code that deals with MPI dynamically from interpreted languages often ends up spawning a lot of processes. Are there process limits on the system? Execution with Singularity will involve some starter processes that are not there when you run outside of the container, and this could hit a limit.

Ultimately diagnosing these issues will come down to identifying some kind of difference between the successful and failing runs. From experience it's really quite unlikely that this is an issue directly caused by Singularity - it's more likely to be something related to system limits, or a bug elsewhere that is hit due to the slightly different environment, number of processes etc. when you run with a Singularity container.

**Comment by b3m2a1** [comment]
@dctrud Thanks for the info. If it's undiagnosable as a singularity issue at this point I'll close this. One final question: you note that

> We've seen in the past that code that deals with MPI dynamically from interpreted languages often ends up spawning a lot of processes.

Is this because of the way the code is written or because of some odd interaction between MPI and the interpreted language? I am not actively spawning any processes that SLURM did not generate and am just passing data from python to C to MPI using python's C-extension mechanism (and in this case since the error happens on `MPI_Init` there's not even any data being passed)

**Comment by dtrudg** [comment]
> @dctrud Thanks for the info. If it's undiagnosable as a singularity issue at this point I'll close this. 

If you do find anything that does point to Singularity, or have more information showing any difference between failing and successful runs, logs/errors from nodes don't hesitate to re-open. The Singularity group / mailing list is also often a good place for these types of issues, as the get seen by the eyes of many users who may have solved similar issues:

https://groups.google.com/a/lbl.gov/forum/#!forum/singularity

> One final question: you note that
> 
> > We've seen in the past that code that deals with MPI dynamically from interpreted languages often ends up spawning a lot of processes.
> 
> Is this because of the way the code is written or because of some odd interaction between MPI and the interpreted language? I am not actively spawning any processes that SLURM did not generate and am just passing data from python to C to MPI using python's C-extension mechanism (and in this case since the error happens on `MPI_Init` there's not even any data being passed)

It's generally how the code is written. I don't want to speculate too much without knowing how your code is working exactly, but it sounds like you aren't using an approach that would lead to many many processes existing. Other things I've personally seen in Python have used python's multiprocess package, and mpi4py in hybrid multiprocess + MPI models - which are more complex. The hybrid approach with 1 MPI rank per node, spawning various processes, can be somewhat beneficial to avoid a lot of overhead where code goes from MPI wire format -> python representations of data etc.

**Comment by b3m2a1** [comment]
@dctrud When Singularity says it "swaps out container MPI for host MPI", what exactly does this mean? Does this mean that if the container `libmpi.so` object disappeared there shouldn't be an issue? I'm still trying to debug this issue, since even on the same nodelist sometimes I get a crash and sometimes I don't

**Comment by dtrudg** [comment]
> @dctrud When Singularity says it "swaps out container MPI for host MPI", what exactly does this mean? 

Can you point me to the doc where you read that? It's not something that universally makes sense, so I'm wondering if it's specifically refering to the 'bind' workflow, where the user will choose to use `--bind` or `-B` to bind the host MPI libraries into the container.

> Does this mean that if the container `libmpi.so` object disappeared there shouldn't be an issue? I'm still trying to debug this issue, since even on the same nodelist sometimes I get a crash and sometimes I don't

There are different ways to run MPI programs with singularity. The most common approaches you'll see are:

1. The 'hybrid' model, where MPI is installed in the container, and MPI and/or a scheduler that can perform MPI process management are separately installed on the host. The version and configuration of MPI/scheduler on the host needs to be compatible with the MPI in the container - but they can be installed in different paths, the container can have very different versions of libraries than the host etc. The MPI application is typically compiled with the container MPI.

2. The 'bind' model, where MPI is *not* installed in the container. The host MPI installation is bound into the container, and any required PATH environment etc. is set in the container. This guarantees host and container MPI are compatible because they are the same. It can be difficult to bind in everything needed where an MPI stack on the host has dependencies, e.g. ofed, pmix etc. Also the basic libraries such as glibc etc. most be ABI compatible between host and container. The MPI application should be compiled with the host MPI.
