### ISSUE TITLE
conda install fails with --sandbox and --writable

### ISSUE THREAD

**Issue by pushkalkatara** [apptainer/singularity#5205]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.0.3
```

### Expected behavior

What did you expect to see when you do...?
I built the image using bootstrap with base ubuntu 16.04 docker with --sandbox option. Further started a shell with --writable option. Activated the conda environment and tried to add new package using `conda install package`.   

### Actual behavior

```bash
Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /opt/conda/envs/py36
  uid: 1000
  gid: 1000

```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```bash
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

### How did you install Singularity

source installation

**Comment by dtrudg** [comment]
Hello - please note that `3.0.3` is an old version of Singularity that is not supported. When reporting issues please make sure that they are not seen in the latest version, which is currently `3.5.3`.

How did you build the initial sandbox? If you did a `sudo singularity build ... ` then the content would not be accessible by a non-root user running `singularity shell`, since the files in the sandbox would be created with root ownership of `/opt` etc.

**Comment by pushkalkatara** [comment]
Thanks for pointing out the version issue @dctrud . I updated singularity and its working. Closing the issue.
