### ISSUE TITLE
How to get a root shell in an existing non-root instance?

### ISSUE THREAD

**Issue by sloretz** [apptainer/singularity#5209]
### Version of Singularity:
```
$ singularity version
3.5.2
```

### Expected behavior
This is more of a question. I'm curious if I can use Singularity just like I use Docker for my development workflow. In short, I was hoping to use `sudo singularity shell instance://foobar` to become root in an instance started by a non-root user for the purpose of temporarily installing software.

The reason I do this is I often work on open source software on different linux platforms. I usually start a docker container with: a user matching my user id, password-less sudo inside the container, and a volume mounted to the cloned repo. Then I install dependencies needed by the repo, make the patch, test it, submit the pr, and finally stop/rm the container.

This workflow might seem strange, but it is attractive to me because it allows me to test on other linux platforms or the same platform without having to clean up installed packages or worry about clobbering my filesystem. I'm wondering if there is a similar workflow using Singularity with the same benefits.

### Actual behavior

```
sudo singularity shell instance://rosfocalinstance
FATAL:   no instance found with name rosfocalinstance
```

### Steps to reproduce this behavior

<details><summary>Singularity definition file</summary>

```
Bootstrap:docker
From:ubuntu:20.04

%post
  apt-get update
  apt-get install -y \
    locales \
    curl \
    gnupg2 \
    lsb-release \
    vim

  # ... Lots of other stuff set up

  rm -rf /var/lib/apt/lists/*

%startscript
  sleep infinity
```
</details>

```singularity build --fakeroot rosfocal.sif definition_files/ros.focal```

```singularity instance start --containall --writable-tmpfs rosfocal.sif rosfocalinstance```

```sudo singularity shell instance://rosfocalinstance```

I can see the instance as root with the `--user` option, but I can't create a root shell.

```
$ sudo singularity instance list --user sloretz
INSTANCE NAME    PID      IP              IMAGE
rosfocalinstance 32353                    /home/sloretz/projects/singularity-ros/rosfocal.sif
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity
source

**Comment by dtrudg** [comment]
Hi @sloretz. I'm afraid you can't `sudo singularity shell` to a non-root instance in this way. Singularity instances are generally used for running detached services, rather than following the docker flow of starting a container than obtaining shells. Because Singularity is daemon-less and has a different security model that preserves the host -> container user relationship, a different work flow is likely to be most convenient.

With regard to your work flow:

> I usually start a docker container with: a user matching my user id, password-less sudo inside the container, and a volume mounted to the cloned repo. Then I install dependencies needed by the repo, make the patch, test it, submit the pr, and finally stop/rm the container.

With Singularity, the most common way to work like this would be with a sandbox container, which exists in a directory. Avoid `sudo` as Singularity's security model is designed specifically to prevent privilege escalation.

You can...

```
singularity build --fakeroot -s rosfocal_sandbox definition_files/ros.focal
```

Then you can `singularity shell` / `singularity shell --fakeroot` / `sudo singularity shell` into that sandbox as needed.

Generally this is going to be simpler than using SIF files when you want to run interactively and do not need to keep the result. The `--writable-tmpfs` area is limited, and does not persist across runs. It is possible to create and use overlay files to capture and persist changes between `shell` or other invocations, but this is more complex than using a sandbox.

**Comment by sloretz** [comment]
`--sandbox` works for my use case; thanks for taking the time to explain! For completeness, here's what I'm doing.

First I'm building an image file from the definition file to get a snapshot of a working system without having to re-download stuff for each sandbox.

```
singularity build --fakeroot ros.bionic.sif definition_files/ros.bionic.def
```

Then I build a sandbox from that image file.
```
singularity build --fakeroot --sandbox ros.bionic.sandbox ros.bionic.sif
```

This lets me install software into the sandbox using a root shell (I haven't successfully used `--fakeroot` or `--contain` at this step; it seems some files in `/tmp` aren't writable using `apt-get update` or `apt-get install`. I'm not sure why, and I didn't take good enough notes to get steps to reproduce)

```
sudo singularity shell --no-home --writable ros.bionic.sandbox/
```

Afterwards I can use that software in a non-root shell.

```
singularity shell --nv --contain ros.bionic.sandbox/
```

Finally, the whole thing can be cleaned up by deleting the sandbox


```
sudo rm -r ros.bionic.sandbox/
```
