### ISSUE TITLE
Communications between 2 machines

### ISSUE THREAD

**Issue by kimchitsigai** [apptainer/singularity#5210]
Hello,

Can 2 Singularity (3.5 compiled as root on Centos 7.6) containers be started **without using sudo** on 2 different machines and communicate using a CNI plugin ?

Thanks a lot.

**Comment by dtrudg** [comment]
@kimchitsigai - no, I'm afraid not. Using the CNI networking features requires privilege. Allowing CNI operations via setuid without `sudo` / `root` is something that could allow a normal user to cause disruption to a system / network, so is not permitted.

Without using sudo the containers will have the same networking environment as any other process on the host system, and can communicate on unprivileged ports (>1024).

If you have a particular use-case we might be able to suggest something.

**Comment by kimchitsigai** [comment]
Thanks a lot for the answer.
My use case is running AI containers, for a TensorFlow or PyTorch distributed training (16 machines * 16 GPU). My cluster (mixed HPC & AI workloads) is managed by Slurm, and users cannot be root.
Could mpirun be a solution to run my AI training without using sudo ? 
I'm not a mpirun expert, but it seems to me that mpirun can be configured to not use TCP/IP, but to use its own InfiniBand (which is my network) protocol.

Regards.

**Comment by dtrudg** [comment]
You can run MPI applications with Singularity, and it is certainly possible to use Infiniband for MPI communications.

The biggest concern here, however, is that your workload must be an MPI application. Tensorflow and PyTorch distributed training is not directly an MPI application. I would suggest looking into Horovod - https://github.com/horovod/horovod

Because this is a topic for discussion focused on using applications rather than a specific issue with Singularity, we would ask that you continue discussion in the Google Group / Mailing List or Slack Channel. These venues have more people looking at them, so there is a higher chance of you getting an answer or being pointed to an example someone has already used.

Group: https://groups.google.com/a/lbl.gov/forum/??sdf%7Csort:date#!forum/singularity

Slack Signup: https://bit.ly/2m0g3lX
