### ISSUE TITLE
How can a container reach the internet via an external proxy?

### ISSUE THREAD

**Issue by halloleo** [apptainer/singularity#5212]
### The Problem

My host machine RHEL Linux connects to the internet via a proxy at http://192.168.80.67:3128.

However in my Ubuntu container the `apt-get` command seem to reach the internet through this proxy

Here my def file `mini.def`:

```
Bootstrap: localimage
From: /home/me/singularity/ubuntu_18.10.sif

%post
    echo 'Acquire::http::Proxy "http://192.168.80.67:3128";' >/etc/apt/apt.conf
    echo 'Acquire::https::Proxy "http://192.168.80.67:3128";' >>/etc/apt/apt.conf
    apt-get -y update
    apt-get -y install fortune cowsay lolcat

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%runscript
    fortune | cowsay | lolcat
```

When I run 

    sudo singularity build -F mini.sif mini.def

I get 

```
INFO:    Starting build...
INFO:    Running post scriptlet
+ echo Acquire::http::Proxy "http://192.168.80.67:3128";
+ echo Acquire::https::Proxy "http://192.168.80.67:3128";
+ apt-get -y update
Ign:1 http://archive.ubuntu.com/ubuntu cosmic InRelease
Ign:2 http://archive.ubuntu.com/ubuntu cosmic-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu cosmic-backports InRelease
Err:4 http://archive.ubuntu.com/ubuntu cosmic Release
  404  Not Found [IP: 192.168.80.67 3128]
Err:5 http://archive.ubuntu.com/ubuntu cosmic-updates Release
  404  Not Found [IP: 192.168.80.67 3128]
.
.
.
FATAL:   failed to execute %post proc: exit status 100
FATAL:   While performing build: while running engine: while running /usr/libexec/singularity/bin/starter: exit status 255
```

This indicates that the Ubuntu system somehow cannot "reach out" of the container, because the proxy is definitely up: The host system can reach through it internet resources.

So there might something between the container and the host system in the way. Are there any tunnels or routes to set?

### The Environment

Singularity version: 3.5.3-1.1.el7 (installed via yum)
Host system: RHEL 7.6
Guest system: Ubuntu 18.10

**Comment by dtrudg** [comment]
By default, a container will have the same network access as a process on the host. There are no routes etc. to set.

There isn't any proxy issue here. The 404 errors reported are because the `archive.ubuntu.com` server does not have a `cosmic` entry in the `dists` that it is hosting.

http://archive.ubuntu.com/ubuntu/ubuntu/dists/

Cosmic /18.10 reached end of life on July 18th 2019

If you want to continue to use it (it is no longer secure) you have to use the `old-releases` apt mirror which still has cosmic files...

http://old-releases.ubuntu.com/ubuntu/dists/

**Comment by halloleo** [comment]
Thanks @dctrud! The outdated URL was the problem indeed. sed editing `/etc/apt/sources.list` fixed this.
