### ISSUE TITLE
Bash special parameters are ignored? 

### ISSUE THREAD

**Issue by wood-chris** [apptainer/singularity#5220]
### Version of Singularity:

```
$ singularity version
3.5.2
```

### Expected behavior

Given this simple def file:

```
$ more simple.def 
Bootstrap: library
From: ubuntu:18.04

%post

    mkdir -p /opt/openmpi-4.0.1 && cd $_
    pwd 
```

The `pwd` should print `/opt/openmpi-4.0.1`

### Actual behavior

Special bash parameters in def files are ignored - this isn't documented to my knowledge

When running the def file, the following output is generated

```
$ sudo singularity build simple simple.def 
INFO:    Starting build...
INFO:    Running post scriptlet
+ mkdir -p /opt/openmpi-4.0.1
+ cd
+ pwd
/root
INFO:    Creating SIF file...
INFO:    Build complete: simple
```

i.e. the `pwd` command still shows `/root`, not `/opt/openmpi-4.0.1` as we would expect

(Admittedly, I've not tried the other [special parameters](https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html))

### Steps to reproduce this behavior

Save def file as simple.def, and run `sudo singularity build simple simple.def`

If this is expected behaviour, can it be documented? :)

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
```

### How did you install Singularity

From source, following https://sylabs.io/guides/3.5/user-guide/quick_start.html#install-system-dependencies

**Comment by dtrudg** [comment]
Because it is guaranteed under POSIX, singularity calls `/bin/sh` and this may or may not be `bash` depending on what container is used. In general it's best to write in POSIX sh syntax within definition files to ensure compatibility. We can't assume `/bin/bash` is available. It is not in distros such as busybox, alpine, so Singularity calls `/bin/sh`.

The recipe with `$_` doesn't work on Ubuntu as `/bin/sh` is `dash`. If you set `From` to a `centos:7` base image it will work as `/bin/sh` is `bash` on CentOS.

```
dave@piran~> cat test
Bootstrap: library
From: centos:7

%post

    mkdir -p /opt/openmpi-4.0.1 && cd $_
    pwd

dave@piran~> sudo singularity build test.sif test
Build target 'test.sif' already exists and will be deleted during the build process. Do you want to continue? [N/y]y
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
INFO:    Using cached image
INFO:    Running post scriptlet
+ mkdir -p /opt/openmpi-4.0.1
+ cd /opt/openmpi-4.0.1
+ pwd
/opt/openmpi-4.0.1
INFO:    Creating SIF file...
INFO:    Build complete: test.sif
```

I'll try and find a better place in the docs to call this out.

**Comment by wood-chris** [comment]
Great! Yeh, I guess I made a massive assumption that bash was used in Ubuntu. What is slightly confusing is that when you shell into `simple`, the shell _is_ bash

```
$ singularity shell simple 
Singularity simple:~> echo $0
/bin/bash
```

**Comment by jmstover** [comment]
IIRC when you run `shell` the shell order looked for is:  `SINGULARITY_SHELL`, `/bin/bash`, `/bin/sh`

So, if bash exists, it'll be used before the `/bin/sh` fall back which must exist due to the POSIX standard.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by wood-chris** [comment]
This is milestoned for 3.6 - so maybe we can leave it open until it's actually in the docs?
