### ISSUE TITLE
how to forbid interactive mode such as shell

### ISSUE THREAD

**Issue by pheman** [apptainer/singularity#5223]
### Version of Singularity:

Singularity 3.5

```
$ singularity version

```

I understand it's not encouraged to ask a question here. But I cannot find any help from the document. I want to forbid the interactive shell mode considering security. 
However, one can easily enter interactive mode without singularity shell command, for example :

>singularity run ubuntu.sif bash

Is there any idea to prevent run or exec bash/sh command without a parameter or scripts?

Thanks!

**Comment by dtrudg** [comment]
It would potentially be possible to block use of `singularity shell` through a plugin. A plugin could probably also be written to look for certain parameters to runscripts that might give a shell. However, there are many, many ways in which to get a shell in a container - such as building it into a sandbox and editing the runscript to evade any restrictions.

What are you trying to accomplish by limiting shell access? It might be better if we can consider your goal rather than propose imperfect ways of limiting shell access.

**Comment by dtrudg** [comment]
Closing as no follow-up information was provided. Please don't hesitate to re-open if you can provide requested information.
