### ISSUE TITLE
Support for shared instance logs, info

### ISSUE THREAD

**Issue by tsnowlan** [apptainer/singularity#5229]
I would like an option when starting an instance to use a group owned/shared `.singularity/instances` directory for storage of instance info and logs.

Currently, instances started by a user have their data stored in `$HOME/.singularity/instances/{sing,logs}/$HOSTNAME/$USER`. The value of `HOME` is also pulled from the system (`/etc/passwd`, on linux) rather than actually using the `HOME` environment variable. This effectively separates instance data between users and cannot be changed without modifying source (or possibly compiling with a plugin?). 

Our use case:
Persistent web servers are being run as singularity instances inside an HPC cluster. The cluster does not support `su/sudo` to a shared service account between users, so the instances are stopped and then started by another user based on who has support duties. Sometimes an instance isn't stopped and a new instance has problems starting because expected ports are unavailable. Being able to easily see what instances are running by other users would help quickly troubleshoot these problems, especially if the controlling user is unavailable.

Similarly, a using a shared, group owned `.singularity` directory would simplify users checking the logs of running/past instances even if they weren't the starting user.

**Comment by dtrudg** [comment]
I think that this is something we might consider a PR for, but it isn't a high priority for our roadmap at present and it is more complex than it first seems, to do securely. The strict use of `$HOME/.singularity/instances` reflects Singularity's focus on being 'safe by default' on shared systems.

Note that actually being able to manage instances that were started by other users is more complex than just opening up access to the `instances` directory.  A malicious user might change the entries in their `instances` directory to trick singularity into joining an instance that is not theirs, even a root owned instance. We perform extra checks to make sure an instance really belongs to a user attempting to join/manage it. e.g.:

https://github.com/sylabs/singularity/blob/525dc53d3d3f6453c083aebf84c115583b8dfb40/internal/pkg/runtime/engine/singularity/prepare_linux.go#L732

Because a user can modify instance files themselves maliciously, for multi-user instance management Singularity would have to have a way of keeping track of which users (other than the person who started the instance) are allowed to manage it. We can't just blindly trust that access rights on the `instances` directory really control that.

> Persistent web servers are being run as singularity instances inside an HPC cluster. The cluster does not support su/sudo to a shared service account between users, so the instances are stopped and then started by another user based on who has support duties. 

I'd guess that this is quite an unusual situation, as running services from different user accounts has various implications around permissions for data etc., beyond the impact on managing instances. If others have a similar flow that would be good to know. I'd very strongly suggest some kind of shared service accounts if at all possible.

**Comment by tsnowlan** [comment]
I agree users should not be able to join other users' instances, that's a significant risk factor. I was hoping just for read access to metadata and a centralized log location (maybe an option to stop an instance if feasible). Would restricting instance management based on combined files/process user ownership, regardless of group access, be an acceptable control? I didn't dig too deep in the source for managing instances, just looked at listing and how the path for the instances was determined.

Juggling file permissions is one of our major pain points, though we've mostly managed setting guid bits on parent folders. Shared service accounts are the ideal solution, but unfortunately the cluster admins remain unconvinced.

**Comment by dtrudg** [comment]
> I agree users should not be able to join other users' instances, that's a significant risk factor. I was hoping just for read access to metadata and a centralized log location (maybe an option to stop an instance if feasible). 

Having the log storage / pid info location customizable without allowing control of instances is definitely more straightforward, but I'm not really clear how useful this will be for your particular siituation? I'm hesitant that we add complexity for something that doesn't really solve the problem:

>> The cluster does not support su/sudo to a shared service account between users, so the instances are stopped and then started by another user based on who has support duties.

> Would restricting instance management based on combined files/process user ownership, regardless of group access, be an acceptable control? I didn't dig too deep in the source for managing instances, just looked at listing and how the path for the instances was determined.

I'm not sure that relying on file <-> process ownership is sufficient, so that anyone who can access the file owned by the instance starting user can control it. It's quite common for permission mistakes to happen on shared systems, and we generally favour a defensive posture. I'm not the true expert on this stuff though, so I'll ask @cclerget if he is available to comment.

> Juggling file permissions is one of our major pain points, though we've mostly managed setting guid bits on parent folders. Shared service accounts are the ideal solution, but unfortunately the cluster admins remain unconvinced.

Understood - I've been an HPC user and and administrator. We'll try to have some internal discussion on this. The daemonless design of Singularity, which is what enables use on shared systems, does make this type of problem less straightforward to solve in a secure way.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
