### ISSUE TITLE
RFE: A %setup variable that fills in the right yum command to install packages

### ISSUE THREAD

**Issue by akkornel** [apptainer/singularity#524]
Hello!

I'm writing a CentOS 7 bootstrap file that involves installation of an RPM package.  The RPM is already built, so I just plan on downloading it and then using yum to install it.  However, I want to be sure that I use the correct yum command (else I might install the package on the host, which would be bad).  Would it be possible to have a variable, like `$yum_install_command`, that I could use in my `%setup` script?  `$yum_install_command` would then be replaced at runtime with the proper `yum` command (`yum --tolerant --installroot=…`) to install a package into the container.

P.S. I did think about using the `%setup` script to download the package, and then installing the package inside the `%post` script, but then I saw the warning at http://singularity.lbl.gov/bootstrap-image, explaining how that might not work in some situations.

**Comment by vsoch** [comment]
The easiest and quickest solution is to dump the OS and yum into the image from a repository that has had many eyes looking at this, Docker of course! I've helped users with this issue before and they find this to be an easy approach, and the very specific feature that you are requesting is likely overkill for a problem with already existing solutions. I can't comment because I'm not a heavy user of CentOS and configuring out, but here are the approaches you could take:

 - Bootstrap Centos from Docker. Here is an [example](https://singularity-hub.org/containers/91/).
 - look for other examples from Singularity Hub, [the repo](https://github.com/singularityware/singularity/blob/master/examples/centos.def), or user group / list.
 - You can easily test what you are concerned about by using a Docker container, Singularity will install fine and run with `--privileged` mode.

I would recommend setting up environments and taking approaches that empower you to play, try and learn! Gotta run, happy testing!

**Comment by vsoch** [comment]
@gmkurtzer thoughts on this?

**Comment by akkornel** [comment]
Hi @vsoch!  I've been working off of the examples from https://github.com/singularityware/singularity/blob/master/examples/centos.def, and I think part of the problem is my host OS (Ubuntu).

At the end of today I'd gotten far enough to confirm the issue and come up with a possible fix; tomorrow I'll do a write up with more info!

**Comment by akkornel** [comment]
I've re-run my stuff on the latest development Singularity (from the `development` branch), and I see that this would probably be harder to implement than expected: I originally thought that the BootStrap module kicked off the `%setup` and `%post` scripts, but looking at the code I see that's not the case!

Looking at the `yum` commands being run in the yum bootstrap process, I think a better solution might be to update the yum bootstrap documentation to say something like this:

> …This issue can be easily demonstrated by bootstrapping an older RHEL compatible image by a newer one (e.g. bootstrap a Centos 5 or 6 container from a Centos 7 host).
> If you plan to use `yum` in the `%setup` section to install an RPM package file, you must point yum to the container's temporary root path, and you should also disable plugin execution, like so:
> `yum --noplugins --installroot=%{SINGULARITY_ROOTFS} install /path/to/mypackage.rpm`

**Comment by vsoch** [comment]
If you are set on doing it this specific way, then perhaps you can discuss with [this thread](https://github.com/singularityware/singularity/issues/241#issuecomment-251431195)? I hope that you figure it out! 

If you want a simple, quick, and clean approach, I would still suggest to just bootstrap a docker image, it comes down to:

    Bootstrap: docker 
    From: centos:7
   
I would use development branch, and add your packages in files:

    %files

    /path/to/mypackage.rpm /path/in/container/package.rpm
   
and then you can issue whatever yum commands you want, to your heart's content, in `%post` as we can see in the [Dockerfile base](https://github.com/CentOS/sig-cloud-instance-build/blob/master/docker/centos-7.ks), all your yums and whatnots are present.

Perhaps you might try that?

**Comment by akkornel** [comment]
Thanks for pointing out `%files`!  That's going to be extremely helpful.

I'll take a look at the thread you linked now.

**Comment by vsoch** [comment]
Please see https://github.com/singularityware/singularity/issues/241#issuecomment-251431195
