### ISSUE TITLE
cuBLAS (cuda 10.1) runtime failure in ppc64le, but not in x86-64

### ISSUE THREAD

**Issue by qhaas** [apptainer/singularity#5245]
### overview
I'm attempting to run software leveraging [cuBLAS](https://developer.nvidia.com/cublas) inside a container derived from nvidia's [cuda 10.1 centos7 container](https://gitlab.com/nvidia/container-images/cuda).  I have completely succeeded in Singularity 3.5.3 on an x86-64 Ubuntu 18.04 host, but only partially on a ppc64le RHEL7.6 host.  [cublasCreate](https://docs.nvidia.com/cuda/cublas/index.html#cublas-context) is returning `CUBLAS_STATUS_NOT_INITIALIZED` when executed in a Singularity container on a ppc64le RHEL7.6 host.  Said code compiles/runs fine outside said Singularity container on the ppc64le RHEL7 host (with cuda 10.1), and compiles fine inside the container, but fails to run inside the container.  When I use a CUDA 10.0 container instead, cublas runs inside the container fine, even on ppc64le.

I'm using the nvidia supplied [cuda-samples v10.1.2](https://github.com/NVIDIA/cuda-samples/tree/10.1.2) simpleCUBLAS as a basic example of this with deviceQuery and matrixMul samples as sanity checks.  deviceQuery and matrixMul compile/run perfectly inside/outside the ppc64le cuda 10.1 container, so GPU acceleration is working.  

### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.5.3-1.1.el7

```

### Expected behavior
```
$ singularity exec --nv -e docker://nvidia/cuda-ppc64le:10.1-runtime-centos7 cuda-samples/bin/ppc64le/linux/release/simpleCUBLAS
GPU Device 0: "Tesla V100-PCIE-16GB" with compute capability 7.0

simpleCUBLAS test running..
simpleCUBLAS test passed.
```

### Actual behavior
```
$ singularity exec --nv -e docker://nvidia/cuda-ppc64le:10.1-runtime-centos7 cuda-samples/bin/ppc64le/linux/release/simpleCUBLAS
GPU Device 0: "Tesla V100-PCIE-16GB" with compute capability 7.0

simpleCUBLAS test running..
!!!! CUBLAS initialization error
```
That error is displayed because the return code of `cublasCreate` is `CUBLAS_STATUS_NOT_INITIALIZED` in the ppc64le cuda 10.1 centos7 container.

### Steps to reproduce this behavior

This simple definition file can create a Singularity container capable of compiling deviceQuery, matrixMul, and simpleCUBLAS samples from nvidia's cuda-samples project linked above, from there, one just needs to run `make` inside the samples' folders and execute the resulting binaries as depicted above.
```
$ cat centos7_101.def 
Bootstrap: docker
From: nvidia/cuda-ppc64le:10.1-devel-centos7

%post
 yum install -y make && yum clean all
```

### What OS/distro are you running

```
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```

### How did you install Singularity

For x86-64 Ubuntu 18.04, built from source.  For ppc64le RHEL7, used yum to install the RPM from [epel](https://fedoraproject.org/wiki/EPEL)

**Comment by dtrudg** [comment]
This is unlikely to be due to Singularity itself. Looking at some tensorflow issues the same error is being reported by people with various host installs / docker containers with CUDA 10.1 - and the culprit is a cublas library version bump.

The most recent change on NVIDIA's recipes for the containers was pinning a specific cublas, presumably to avoid the reported issues. They pinned `libcublas-devel-10.2.1.243-1` here:

https://gitlab.com/nvidia/container-images/cuda/-/commit/d442ff6975fb8310da90e6c3f35a988b6920b01

However,... if I pull `nvidia/cuda-ppc64le:10.1-devel-centos7` and look inside it's not that version which is present. Instead we have:

```
dave@piran~/p/lib64> find . | grep blas
...
./libcublas.so.10.2.2.89
```
This 10.2.2.89 version has been widely reported to cause the cublas initialization error in a tensorflow github issue, and downgrading to `10.2.1.243-1` fixes the problem:

https://github.com/tensorflow/tensorflow/issues/9489#issuecomment-616949644

You may wish to report this to NVIDIA, in case it is something that has been fixed for x86 in their docker images - and just remains on POWER.

**Comment by qhaas** [comment]
Thanks, this makes sense, opened an issue with nvidia on their cuda-ppc64le project:   https://gitlab.com/nvidia/container-images/cuda-ppc64le/-/issues/8

**Comment by qhaas** [comment]
Confirmed, [not a Singularity issue](https://gitlab.com/nvidia/container-images/cuda-ppc64le/-/issues/8#note_347647682), repeatable on podman + nvidia's runtime.
