### ISSUE TITLE
dask in container segfaults when run on HPC system

### ISSUE THREAD

**Issue by rmg55** [apptainer/singularity#5259]
### Overview

I am attempting to run code (in a jupyter notebook) that results in segmentation faults when run inside a singularity container on a HPC system.  The minimal example code is posted to this issue: [https://github.com/dask/dask-ml/issues/629](https://github.com/dask/dask-ml/issues/629) with a more detailed description of the errors. The container I am using is here: [https://hub.docker.com/r/rowangaffney/data_science_im_rs](https://hub.docker.com/r/rowangaffney/data_science_im_rs)

Tagging @ynanyam as he has been helping me troubleshoot.

Below I have posted a table of the different iterations I have attempted. From these iterations, I *think* the issue is with the combination of Singularity on an HPC... Any ideas as to the cause?

### Version of Singularity::

```
$ singularity version
singularity version 3.5.2-1.1.el7
```

### Expected behavior

| System | Host | Singularity Version | Success? |
|---------|-------|---------------------|------------|
|Desktop|Ubuntu 16.04|None| Pass|
|Desktop|Ubuntu 16.04|2.6.1| Pass|
|Desktop|CentOS 8|3.5.3| Pass|
|HPC|CentOS 7 (SLRUM)|3.5.2|Pass|
|HPC|RHEL (SLURM)|3.5.3|Pass|

### Actual behavior

| System | Host | Singularity Version | Success? |
|---------|-------|---------------------|------------|
|Desktop|Ubuntu 16.04|None| Pass|
|Desktop|Ubuntu 16.04|2.6.1| Pass|
|Desktop|CentOS 8|3.5.3| Pass|
|HPC|CentOS 7 (SLURM) |3.5.2|**Fail**|
|HPC|RHEL (SLURM) |3.5.3|**Fail**|

### Steps to reproduce this behavior

See code here:
[https://github.com/dask/dask-ml/issues/629](https://github.com/dask/dask-ml/issues/629)

### What OS/distro are you running
See above

### How did you install Singularity
See above

**Comment by dtrudg** [comment]
From the other thread, it looks like you are binding the entire `/usr/lib64` host library directory into the container.

```
 --bind /usr/lib64 
```

This will almost certainly cause issues including segfaults, unless the container OS exactly matches the host - because the executables in the container expect to use libraries from the container... not the ones from the host which will be a different version / built differently.

Also - when you run Singularity containers with python apps, python packages installed in your `$HOME` with `pip install --user` can interfere. Try  `--contain` to avoid that.

Please provided the `Dockerfile` for the container, and the exact `singularity` commands you are using to run things here, so it's easy for people to follow up without referencing the dask issue.

Note also that this is very unlikely a bug with Singularity, but related to usage, and incompatibility between libraries that are getting into the container, and the executables in the container. We encourage you to use Slack and the Google Group / mailing list for theses types of issues as they have more visibility from the community of users, and people there may already be using dask under Singularity:

https://sylabs.io/resources/community

**Comment by rmg55** [comment]
I get the same results when I run the code with ```--contain```, and not binding any directories. Thanks for the suggestion though - any other ideas?

**Comment by dtrudg** [comment]
Closing this issue as it is a usage question that has been posted for 90 days and is not active.

For usage questions you are encouraged to use the Slack channel and/or mailing list which have a community of users present who will see and often kindly answer queries.

We close stale usage questions in order that the issues tracker can focus on problems that are bugs in Singularity, and feature requests.
