### ISSUE TITLE
Build fails with "conveyor failed to get: Unexpected tar manifest.json"

### ISSUE THREAD

**Issue by mkgvt** [apptainer/singularity#5287]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.1
```

### Expected behavior

What did you expect to see when you do...?

I expected this to succeed as it has done in the past:
```
$ singularity build myimage.sif docker-archive://$HOME/myimage.tar
```
where `myimage.tar` was created by `docker save myimage > myimage.tar`.

### Actual behavior

What actually happened? Why was it incorrect?

```
$ singularity build myimage.sif docker-archive://$HOME/myimage.tar
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: Unexpected tar manifest.json: expected 1 item, got 2
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

All I can say is that previous versions of `myimage.tar` loaded without a problem. The only difference is the newer `myimage` contains a modification of my c++ program being built into the Docker image. As far as I know nothing else changed between a run yesterday and today.

### What OS/distro are you running

Singularity is being run on an HPC system with:
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

The image I am loading into singularity was built with Docker version:
```
$ docker --version
Docker version 19.03.5, build 633a0ea838f10e000b7c6d6eed1623e6e988b5bc
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

It was installed via:
```
$ module load singularity/3.5.1
```
As for where the module came from... No idea.

**Comment by dtrudg** [comment]
If you are able to provide the tar file we may be able to look into this further.. or a docker recipe and the full list of steps needed to produce a tar that fails to import.

**Comment by dtrudg** [comment]
Closing this as there is no follow-up. Please feel free to reopen if you can provide a reproducer.

**Comment by bnprks** [comment]
@dtrudg I think I have independently reproduced this -- I believe the issue has something to do with docker layer caching, since I get this issue when using an image where I have changed only a later layer, but not when I have rebuilt the image fresh

The singularity version I'm running is `singularity version 3.8.5-2.el7`

I've uploaded a copy of an offending tar file here (about 1GB): https://drive.google.com/file/d/1yEg9yS-r6nASgUbnurKNGukIqilkQizq/view?usp=sharing

And this is the Dockerfile that produced it (unfortunately takes about 1 hour to do a fresh build on my machine). After adding the last RUN call & rebuilding the new exported image produced the error while an exported image from before adding that run call made no issues. 

Given that my hypothesis is that this is due to the layer caching, I suspect that this could be reproduced even with the slow steps removed (`install.r Seurat tidyverse` and `installGithub.r ...` and `install.r Signac`), but I'm not sure if the reduced image size would mess with whether the issue occurs.

```
FROM rocker/r-base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        time \
        libxml2-dev \
        libssl-dev \
        libcurl4-openssl-dev \
        libgsl-dev \
        libhdf5-dev && \
    install.r Seurat tidyverse

RUN install.r BiocManager remotes && \
    installGithub.r \
        -r https://bioconductor.org/packages/3.14/bioc \
        -r "https://bioconductor.org/packages/3.14/data/annotation" \
        -r "https://bioconductor.org/packages/3.14/data/experiment" \
        -r "https://bioconductor.org/packages/3.14/workflows" \
        -r "https://cloud.r-project.org" \
        GreenleafLab/ArchR

RUN install.r Signac
```

**Comment by DrDaveD** [comment]
Continued in apptainer/apptainer#277
