### ISSUE TITLE
Dose Singularity support CNI env?

### ISSUE THREAD

**Issue by ruijf** [apptainer/singularity#5288]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.2
```

### Actual behavior
```
## ib0 is my custom define host-device network
# CI_IFNAME=ib singularity -v  shell -B /etc/ -B /lib64 -B /lib -B /usr/bin  -B /usr/sbin/ -B /sys -B /opt -B /usr  --net --network ib0  centos_latest.si
```
I want to set ifname to **ib0** ， but still is **eth0**
```
Singularity> ifconfig 
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 2044
        inet 10.0.0.240  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::1e34:da03:4a:4008  prefixlen 64  scopeid 0x20<link>
Infiniband hardware address can be incorrect! Please read BUGS section in ifconfig(8).
        infiniband 20:00:03:C9:FE:80:00:00:00:00:00:00:00:00:00:00:00:00:00:00  txqueuelen 256  (InfiniBand)
        RX packets 58  bytes 6416 (6.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 236  bytes 17260 (16.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity
Follow the official documentation

**Comment by cclerget** [comment]
@ruijf No Singularity doesn't support CNI environment variables simply because in this example setting CNI_IFNAME would set interface name for all networks brings in the container by example while specifying :

`--net --network=bridge,ptp`

it would setup two interfaces with the same name in the container.

To avoid this problem singularity use `--network-args` instead to specify arguments for each network, unfortunately setting ifname from there is not yet supported.

In your case the host-device CNI plugin even ignores CNI_IFNAME as mentioned in the README (https://github.com/containernetworking/plugins/tree/master/plugins/main/host-device) of this plugin 

> For this plugin, CNI_IFNAME will be ignored. Upon DEL, the device will be moved back.

**Comment by ruijf** [comment]
@cclerget Thanks for explain. I got it.
