### ISSUE TITLE
Prevent /etc/localtime from mounting via conf file

### ISSUE THREAD

**Issue by marshall-adrian** [apptainer/singularity#5301]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.0-RC2
```

### Expected behavior

What did you expect to see when you do...?
In previous version I could use --contain to prevent `/etc/localtime` from being mounted, now I have to add `--net` and that requires root or --fakeroot and I don't want a new network space. So removing `/etc/localtime` from singularity config should not mount it at all. 

### Actual behavior

What actually happened? Why was it incorrect?
In the singularity.conf if I remove the `bind path = /etc/localtime` it is still binding `/etc/localtime`.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
Removing bind path from config, then start up container and set $TZ to something different than what is current TZ, run $ date, and you will see that changing $TZ has no effect inside the container.

### What OS/distro are you running

```
$ cat /etc/os-release
Ubuntu 16.04

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Source

**Comment by dtrudg** [comment]
The change to include `/etc/localtime` with `--contain` was intentional in: https://github.com/hpcng/singularity/pull/4926 This change had previously been requested, and having a timezone matching the host seems fair, even if filesystems are `--contain`ed.

Looking back there, the explanation in the `singularity.conf` is misleading - it should note that `/etc/localtime` is always mounted with `--contain` even if it is removed from the bind list.

> then start up container and set $TZ to something different than what is current TZ, run $ date, and you will see that changing $TZ has no effect inside the container.

I don't observe this behavior - it is possible to override `$TZ` as expected:

```
dave@piran~/S/G/singularity> singularity run --contain docker://ubuntu
INFO:    Using cached SIF image
Singularity> date
Mon May 18 15:20:47 CDT 2020
Singularity> export TZ="UTC"
Singularity> date
Mon May 18 20:21:15 UTC 2020
```

Please could you show a full example where you are not able to override?

**Comment by marshall-adrian** [comment]
Thanks for the quick response.. So it seems like it has to with the .SIF I am using and the newer version of singularity..

```
[0] gamma10:/scratch/marshalla $ /singularity/3.6.0-RC2/bin/singularity shell --contain docker://ubuntu
INFO:    Using cached SIF image
Singularity>
Singularity>
Singularity>
Singularity> date
Mon May 18 16:33:31 PDT 2020
Singularity> export TZ=UTC
Singularity> date
Mon May 18 23:33:37 UTC 2020
Singularity>
Singularity>
Singularity> exit
exit
[0] gamma10:/scratch/marshalla $ /singularity/3.6.0-RC2/bin/singularity shell --contain 0.0.2.sif
Singularity>
Singularity>
Singularity> date
Mon May 18 16:34:04 PDT 2020
Singularity> export TZ=UTC
Singularity> date
Mon May 18 16:34:14 PDT 2020
Singularity> exit
exit
[0] gamma10:/scratch/marshalla $ /singularity/3.5.3/bin/singularity shell --contain 0.0.2.sif
Singularity> date
Mon May 18 23:35:47 UTC 2020
Singularity> export TZ=PDT
Singularity> date
Mon May 18 23:36:01 PDT 2020
Singularity> exit
exit
```

**Comment by dtrudg** [comment]
What's the SIF in this case? Can you extract the definition / recipe with `singularity inspect -d`

**Comment by marshall-adrian** [comment]
It is built from a Dockerfile that looks like this:

```
## Tools to Add to Image
FROM xilinx/vivado:2019.1 as a99ea912e5b3b4453e75b64431d835c75

FROM ubuntu:16.04
# Update and Install Ubuntu Software Repository
RUN apt update && apt install -y \ 
gdb \ 
python3-pip \ 
python3-yaml \ 
python3-dev \ 
python3-sympy \ 
python3-dateutil \ 
ruby-full \ 
vim \ 
fish \ 
tcsh \ 
ksh \ 
tree \ 
lsb-core \ 
gcc-multilib \ 
g++-multilib \ 
build-essential \ 
autoconf \ 
automake \ 
bison \ 
flex \ 
libmpc-dev \ 
libmpfr-dev \ 
libgmp-dev \ 
dejagnu \ 
dc \ 
libncurses5 \ 
libelf1 \ 
libc6-dev \ 
jq \ 
libncurses5-dev \ 
libglib2.0-dev \ 
libgtk2.0-dev \ 
libpango1.0-dev \ 
libssl-dev \ 
cmake \ 
git \ 
device-tree-compiler \ 
subversion \ 
libboost-all-dev \ 
linux-tools-virtual \ 
libftdi1-dev \ 
openjdk-8-jdk && \ 
## Needed for SNPS 
rm -rf /bin/sh && \ 
ln -s /bin/bash /bin/sh
 
COPY --from=a99ea912e5b3b4453e75b64431d835c75 /sifive/tools/xilinx /sifive/tools/xilinx/

ENV PATH=/sifive/tools/xilinx/Vivado/bin:$PATH
ENV XILINX_VIVADO=/sifive/tools/xilinx/Vivado/2019.1
ENV XILINXD_LICENSE_FILE=/sifive/tools/xilinx/Vivado/license
```
and the `FROM xilinx/vivado:2019.1` looks like this, just a copy of a directory into it...

```
FROM scratch
WORKDIR /sifive/tools/xilinx
COPY Vivado Vivado
```

**Comment by marshall-adrian** [comment]
If you send your DockerHub ID I can share this image with you and you can download it and test it out.

**Comment by marshall-adrian** [comment]
I will see if I can create a smaller test case to see if this can be narrowed down so it can be resolved quicker..

**Comment by dtrudg** [comment]
Hi @marshalla-sifive - we've been in some discussion around means for preventing things being bound in.. see https://github.com/hpcng/singularity/pull/5086 - that discussion is about reversing the hostfs bind config option - but there is a general theme around how to provide a consistent way to 'undo' bind mounts, whether they be default or configured. This wasn't resolved yet, and I'm afraid it is not a priority for the `3.6.0` release at this point.

Regarding `/etc/localtime` - it's my belief that most of the users we have would actually *expect* the timezone to still match the host even when using `--contain`. Many people are using `--contain` to run e.g. python notebook environments without the impact of `$HOME` mounts bringing in python modules. Needing to set the timezone manually in these environments is not something they'd generally expect - in this way the change in behavior here is likely beneficial to most people, so it won't be backed out in the RC period for 3.6.0 unless we have others hitting the issue.

I definitely do agree, however, that we should have more control to be able to disable things that are bound in automatically.

I haven't replicated anything where setting `$TZ` doesn't work at this point - a minimal test case would be great if you can get one.

**Comment by marshall-adrian** [comment]
HI @dctrud, Thanks for the response and info. So I have been playing around and finally got a dockerfile that produces this strange behavior... 

If you use this docker file below and then build a .sif, I see that TZ does not take affect. There are some other installed tools that causes the issue as well.

```
FROM ubuntu:16.04
# Update and Install Ubuntu Software Repository
RUN apt update && apt install -y \
ruby-full
```

**Comment by dtrudg** [comment]
@marshalla-sifive - the Dockerfile excerpt there looks incomplete. What's the `FROM` line you are using here?

**Comment by marshall-adrian** [comment]
That wasn't very helpful, sorry about that... I had a formatting issue, and did not put a newline/space after the ticks so it did not show the entire line, it has been fixed
![image](https://user-images.githubusercontent.com/51137825/83539671-29276800-a4ac-11ea-8dde-755f119cfb8c.png)

**Comment by dtrudg** [comment]
Have found out that on Ubuntu 16.04 `export TZ` *does* work... but not for the same values that work elsewhere. I.E. `UTC` does not work.

```
# My native timezone
Singularity> date
Tue Jun  2 11:20:01 CDT 2020

# Setting to 'UTC' doesn't work
Singularity> export TZ=UTC
Singularity> date
Tue Jun  2 11:20:14 CDT 2020

# Setting to the example from `date --help` works
Singularity> export TZ='America/Los_Angeles'
Singularity> date
Tue Jun  2 09:20:48 PDT 2020
```

To get UTC you can use the `<name><offset from UTC>` format, so...

```
Singularity> export TZ='UTC+0'
Singularity> date
Tue Jun  2 16:21:37 UTC 2020
```

**Comment by marshall-adrian** [comment]
hmm so do we know why this works in 3.5.3 normally but then in 3.6.0 when installing certain tools it forcing the formatting to change?

**Comment by dtrudg** [comment]
I don't see a difference for `3.5.2`  here *except* the for the bind-in of localtime. Using `TZ` works / fails in the same manner.

If I run without `--contain` then `TZ=UTC` does not work, but other TZ settings do.

```
01:08 PM $ singularity version
3.5.2

01:08 PM $ singularity run test.sif 
Singularity> clear

Singularity> date
Tue Jun  2 13:08:29 CDT 2020
Singularity> export TZ="UTC"
Singularity> date
Tue Jun  2 13:08:35 CDT 2020
Singularity> export TZ="UTC+0"
Singularity> date
Tue Jun  2 18:08:40 UTC 2020
```

If I add `--contain` then  the default localtime in the container (which is a working UTC file) is not overwritten, so I get native UTC, or it will appear that `TZ=UTC` will work if I set it manually. It's actually not working... but I am getting the default UTC from the container localtime.

The behavior of `TZ` here is nothing to do with Singularity - it relates to Ubuntu 16.04 in the container, which doesn't accept e.g. `TZ=UTC`. 

Are you seeing this for any timezone other than UTC? Otherwise this appears to be a limitation with Ubuntu 16.04s handling of `TZ=UTC` only.

**Comment by marshall-adrian** [comment]
So to summarize, my issue is caused by the following: Singularity version 3.6.0 FORCE binds `/etc/localtime`, with no way to prevent it currently,  and depending on what Ubuntu pkgs are installed removes the ability to make use of `TZ=UTC`, since we can see that a vanilla Ubuntu 16.04 using 3.6.0 singularity still works and installing something like ruby then stops it from working.

So our issue is that we have a very large tool from a very large vendor that requires doing something like `TZ=UTC` (is all the details they have given me) in order for it work correctly, something that odds are we will never be able to get them to change, so as singularity version 3.6.0 currently stands we will not be able to use it for our flows and fixing this is not a priority..

**Comment by dtrudg** [comment]
> So to summarize, my issue is caused by the following: Singularity version 3.6.0 FORCE binds `/etc/localtime`, with no way to prevent it currently, 

Agree on this. As mentioned, the binding in of localtime was a request implemented in 3.6 that will give behavior that is expected by other users (timezone matches host, when contain needs to be used).

> and depending on what Ubuntu pkgs are installed removes the ability to make use of `TZ=UTC`, since we can see that a vanilla Ubuntu 16.04 using 3.6.0 singularity still works and installing something like ruby then stops it from working.

Singularity itself is not doing this directly. It's an effect of how timezone configuration is happening in Ubuntu 16.04 specifically, such that it then doesn't act on explicit setting of `TZ=UTC`. It does not occur on other container distributions I've tried. It works correctly with e.g. Ubuntu 18.04.

> So our issue is that we have a very large tool from a very large vendor that requires doing something like `TZ=UTC` (is all the details they have given me) in order for it work correctly, something that odds are we will never be able to get them to change, so as singularity version 3.6.0 currently stands we will not be able to use it for our flows and fixing this is not a priority..

Have you tested whether setting `TZ="UTC+0"` works with the vendor software, as this will give the same time, and offset?

Another workaround appears to be to set a non-UTC timezone in the container and then install `tzdata`.

```
bootstrap: docker
from: ubuntu:16.04

%post
    apt update && apt install -y ruby-full

    export DEBIAN_FRONTEND=noninteractive
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
    apt install -y tzdata
```
With the resulting container then `TZ=UTC` works:

```
03:11 PM $ singularity version
3.6.0-rc.2+46-g971f9116b
dave@piran:~/issue5301
03:11 PM $ singularity run test.sif 
Singularity> date
Tue Jun  2 15:11:32 CDT 2020
Singularity> export TZ=UTC
Singularity> date
Tue Jun  2 20:11:37 UTC 2020
```

As an open-source project we always welcome pull requests for issues, and would gladly consider one to allow disabling the `localtime` mount.

At this point I'm afraid we are in an release candidate stage for 3.6, and this is not an issue that has affected others. We've indicated that we want to take a look at the general mechanism for preventing binds (ref https://github.com/hpcng/singularity/pull/5086) and this would be included in that work.

_Edit: changed def file to 16.04 (pasted incorrect version)_

**Comment by marshall-adrian** [comment]
> Have you tested whether setting TZ="UTC+0" works with the vendor software, as this will give the same time, and offset?

I am not the one that is setting TZ, they are doing it internally, so unfortunately I have no control on how it is done or how it is called... 

> Another workaround appears to be to set a non-UTC timezone in the container and then install tzdata.

I will try this workaround and see if that works for us, thanks!

> As an open-source project we always welcome pull requests for issues, and would gladly consider one to allow disabling the localtime mount.

Yes if I find some time I would love to help the community out!

Thanks for the help and information!

**Comment by Qwarctick** [comment]
> Regarding /etc/localtime - it's my belief that most of the users we have would actually expect the timezone to still match the host even when using --contain

The problem seems the same with `--containall`:
```sh
$ sudo singularity build --sandbox lolcow/ library://sylabs-jms/testing/lolcow
INFO:    Build complete: lolcow/
$ sudo singularity shell --writable lolcow
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
```
I can understand why mounting /etc/localtime is necessary for a simple container. But I'm agree with @marshalla-sifive, I don't understand why /etc/localtime is mounted by default with the `--contain` option and even less with the `--containall` option. This has an unexpected side effect and not indicated in the documentation

**Comment by dtrudg** [comment]
@PhilippeNoel1 - There's probably a good argument here for not binding with `--containall` (since all implies we don't bring in anything) and we'd happily consider a patch for that or an explicit disabling of the mount (and/or the documentation at hpcng/singularity-userdocs)

With regard to `--contain` - this option is commonly used to run containers that are adversely impacted by Singularity's default binds of `$HOME` etc. Generally Singularity prioritizes working with a host for fairly transparent execution of containerized applications, rather than full isolation. It is commonly used on HPC systems to run specific application as part of workflows that may include non-containerized applications, so it's reasonable for users to expect timezone parity even when they have to use `--contain`. The mounting of `/etc/localtime` with `--contain` was due to a request for this behaviour, and we are unlikely to revert it.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
