### ISSUE TITLE
Adjust capabilities in runtime engines

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#5314]
Capabilities should be adjusted by runtime engines instead of relying on C starter code like it's done actually. There is use case to support and fix like running singularity as root with a reduced set of capabilities. By default root has full capabilities and this is configurable via `singularity.conf`, instead the default should be `current` to match current capabilities and avoid runtime error.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
