### ISSUE TITLE
Using '--' to separate Singularity Cmd from Exec Cmd

### ISSUE THREAD

**Issue by marshall-adrian** [apptainer/singularity#5341]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3 and 3.6.0-RC2
```

### Expected behavior

What did you expect to see when you do...?
I would expect to see consistent behavior across versions/SIFs when using the `--` to separate cmds.

### Actual behavior

What actually happened? Why was it incorrect?
When I try to separate my Singularity CMD from my actual exec command using `--` I see varying behavior based on .SIF and Singularity version...

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

**Running Exec Command**
Vanilla 3.5.3:
```
$ /singularity/3.5.3/bin/singularity exec --contain docker://ubuntu -- hostname
/.singularity.d/actions/exec: 21: exec: --: not found
```
Custom SIF 3.5.3:
```
$ /singularity/3.5.3/bin/singularity exec --contain my_custom_image.sif -- hostname
gamma14.internal.sifive.com
```
Vanilla 3.6.0-RC2
```
$ /singularity/3.6.0-RC2/bin/singularity exec --contain docker://ubuntu -- hostname
INFO:    Using cached SIF image
FATAL:   "--": executable file not found in $PATH
```
Custom SIF 3.6.0-RC2
```
$ /singularity/3.6.0-RC2/bin/singularity exec --contain my_custom_image.sif -- hostname
FATAL:   "--": executable file not found in $PATH
```
**Can I run `-- hostname` in Shell?**
Custom SIF 3.5.3:
```
$ /singularity/3.5.3/bin/singularity shell --contain my_custom_image.sif
Singularity> -- hostname
bash: --: command not found
```
Custom SIF 3.6.0-RC2
```
$ /singularity/3.6.0-RC2/bin/singularity shell --contain my_custom_image.sif
Singularity> -- hostname
bash: --: command not found
```

### What OS/distro are you running

```
$ cat /etc/os-release
ubuntu 16.04
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
Source

**Comment by dtrudg** [comment]
Hi @marshalla-sifive 

 1) Could you clarify what you expect as the correct behavior here. The custom SIF in 3.5.3 seems to be the outlier to consistent behavior here. 

2) In 3.6.0 Singularity is using an embedded shell interpreter for some things, rather than the shell in the container. In your custom SIF what is the shell / how was the container built?

3.6.0 seems to be a fix here to me - as it brings consistency across containers, regardless of how they are setup internally, and `hostname` without a prefixed `--` would work in all cases across versions. So, I'm not sure there is anything to do here, as 3.6.0 will be the fix for consistency.

The Singularity CLI is written such that `--` isn't required. Everything past the name of the container that you `exec` is passed into the container execution flow directly, so you get the same  `exec: --: not found` as if you try to `-- hostname` in a shell. `--`

**Comment by marshall-adrian** [comment]
HI @dctrud,

> Could you clarify what you expect as the correct behavior here. The custom SIF in 3.5.3 seems to be the outlier to consistent behavior here.

Yes agreed, I wanted to confirm that the expectation is that `--` formatting is not supported since we have been using it with our custom .SIFs to make the command lines more readable.

> In 3.6.0 Singularity is using an embedded shell interpreter for some things, rather than the shell in the container. In your custom SIF what is the shell / how was the container built?

It is a bash shell and the image was built from a docker image 

 I missed posting this command but there is still variance with the `run` command because that still allows `--` to be used, which I guess relates to your comment about embedded shell interpreter being used for some things, so there will be some variance due to that.

```
$ /singularity/3.6.0-RC2/bin/singularity run --contain docker://ubuntu -- hostname
INFO:    Using cached SIF image
gamma14.internal.sifive.com  
```

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
