### ISSUE TITLE
Problem mount slurm in container singularity

### ISSUE THREAD

**Issue by miirkoo** [apptainer/singularity#5345]
### Version of Singularity:

What version of Singularity are you using? Run:

singularity version d5eaf8a+dirty

```
$ singularity version

3.5.3

```

Singularity> srun
srun: error: Invalid user for SlurmUser slurm, ignored
srun: fatal: Unable to process configuration file

### Expected behavior

What did you expect to see when you do...?

Run srun

### Actual behavior

What actually happend? Why was it incorrect?

I am trying to mount slurm in a container, but I have an error:

srun: error: Invalid user for SlurmUser slurm, ignored
srun: fatal: Unable to process configuration file

This is true, since our users work by ldap, the problem is that I don't know how to do it, for  what Singularity not sees user of ldap  which is currently as "slurm" and it's already created in our system.

Could you help me?, How could I mount ldap in singularity? or see a ldap user in singularity?

Thank you!!!.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

With Anaconda

**Comment by miirkoo** [comment]
Hello

Please help.

Thank you!.

**Comment by miirkoo** [comment]
Hello,

Someone could help me, thank you very much!

**Comment by dtrudg** [comment]
When you run a container with Singularity only the user executing the container is available inside the container. Note also that you cannot change to a different user by default - this is blocked due to the security model.

To have a container use LDAP etc would require configuring that inside the container, or setting up an auth proxy service such as `sssd` so that it can use the service running outside of the container via a bind mounted socket.

Guidance on this is really outside of the scope of an issue on the code repository - which is intended to track bugs or feature requests rather than usage queries. I'd suggest using the mailing lists or slack channel to ask for help from the user community.

https://sylabs.io/resources/community

**Comment by AndrewTsao** [comment]
I user a local `slurm` user in host, mount /etc/passwd file to solve the problem. but get another small problem, passwd config not effect.
