### ISSUE TITLE
More efficient builds: ccache, APT cache, git repo cache...?

### ISSUE THREAD

**Issue by peci1** [apptainer/singularity#5352]
### Version of Singularity:

```
$ singularity --version
2.5.2-dist
```

### Expected behavior

Extending (or working around) #3561, I'd like to speed up my builds utilizing host caches, like ccache, APT cache, git repo cache/proxy etc.

I [asked on SO](https://stackoverflow.com/questions/62027391/how-to-utilize-host-caches-in-a-singularity-build/62284370), but nobody came with a good solution.

Is it possible that singularity will be able to utilize these at some point?

### Actual behavior

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### How did you install Singularity

Site administrator did.

**Comment by dtrudg** [comment]
I don't think that using host caches is something that Singularity would do itself - it would be more of a question of can the locations / things you need from the host be exposed in the container during the build.

As it stands, the host `/tmp` is available in the `%post` block, and you can access sockets, or files, that are there. Also any caches exposed over network ports are available - so a cache service running on localhost can be used in the container build.

There is an argument for making `--bind` available during builds, but this does make them less reproducible, and adds additional ways in which build services such as SingularityHub and the Sylabs remote builder, would not be able to replicate local builds.

My personal view is this is something that is unlikely to be picked up unless:

- There is a very large call from the community for `--bind` in builds.
- Someone works up the change as a PR, and the consensus in the community is that it is an acceptable change.

If you are interested in pursuing this, I'd suggest that the mailing list or slack channel are likely good places to engage in a discussion:

https://sylabs.io/resources/community

Messages in these venues are seen by more people than would click on any one GitHub issue. A GitHub issue is likely more appropriate for a bug / suspected bug in Singularity, or a specific feature request to be implemented rather than exploratory discussion.

As an aside, please also note that Singularity 2.5.2 is very old, and not supported.

**Comment by peci1** [comment]
Thanks for the reply. I haven't known /tmp is bound during build. Is that documented somewhere? 

Also, if local networking works, that might be pretty usable for the git proxy cache.

I'm sorry for not helping with this, but my expertise is too far from developing singularity. But you can count me as one voice for `--bind` in builds.

And the version - that's what I have to work with, no way to change that... But if it's unsupported, the main argument of our admin for singularity over docker - security - is a bit dangling...

**Comment by dtrudg** [comment]
> Thanks for the reply. I haven't known /tmp is bound during build. Is that documented somewhere?

I'll double check and open an issue on our docs repo if not.

> And the version - that's what I have to work with, no way to change that... But if it's unsupported, the main argument of our admin for singularity over docker - security - is a bit dangling...

For the 2.x series... also note that there are versions later than 2.5.2 with important fixes, and those are detailed in release notes: https://github.com/hpcng/singularity/releases

**Comment by peci1** [comment]
Thanks, using `mount --bind` to mount the needed directories to `/tmp` works, I can now share the host caches with the build phase of the container.

I just wanted to make this setup part of the `%setup` phase of the recipe, but calling `mkdir /tmp/apt && mount --bind /var/cache/apt /tmp/apt` does not actually result in mounting the directory. If I issue the same commands with sudo from bash, they work. Do you have any idea what could be the reason?
