### ISSUE TITLE
Update INSTALL.md - installation from EPEL

### ISSUE THREAD

**Issue by durai23** [apptainer/singularity#5356]
Hello,

Can you please update INSTALL.md to let people know that singularity is available from EPEL and no longer needs to be compiled (for applicable OS). This will save people a lot of trouble (like installing compilers like go etc.).

Also please indicate if there are any differences between the installations - i.e. from EPEL and compiling from source. 

Thanks,
Durai

### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.3
```

### Expected behavior

What did you expect to see when you do...?

### Actual behavior

What actually happend? Why was it incorrect?

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

from epel

**Comment by dtrudg** [comment]
Hello,

This is actually a little awkward to do in the repository MD files, as we want to avoid misleading people about what version is available etc.

Most people would come across the `INSTALL.md` on the `master` branch here in GitHub, because this is our default branch. However, this is the *next* version of Singularity under development, not generally available in EPEL (or other repositories). Therefore the INSTALL.md is really correct in that you need to install Go and build from source to get the code that you are looking at in the `master` branch.

If we mention EPEL packages, which are kept very up-to-date, we should likely mention packages in other distros. We don't generally get informed of the status of these, and they are often older versions. It is difficult to mention them in the INSTALL.md for a _current_ or _development_ version of Singularity without inferring they should be up-to-date. As we do not produce the packages we can't make this happen, nor demand that package maintainers downstream do so.

We actually do mention the EPEL packages in our admin-guide documentation, which is provided for the stable released version:

https://sylabs.io/guides/3.5/admin-guide/installation.html#install-the-centos-rhel-package-using-yum

This is explicitly called out in the README as well...

> To install Singularity from source, see the installation instructions. For other installation options, see our guide.

...

> Also please indicate if there are any differences between the installations - i.e. from EPEL and compiling from source.

As we are an upstream project, and the EPEL packages are a downstream thing that we don't have control over, this is not something I believe we should do. The release notes provided by distro packages generally indicate differences. In the EPEL case @DrDaveD is diligent about posting any differences on the Singularity mailing list.

I think we could provide a generic reference in the INSTALL.md along the lines of 'packages are available for various distros x, y, z - but may not be available for the current version of Singularity'. I don't think we should track and provide specifics, as this needs quite a lot of work to ensure accuracy.

**Comment by DrDaveD** [comment]
I agree that the files in the singularity github repo shouldn't list specific differences.   I do think it is a good idea for INSTALL.md to refer to the guide for other installation methods, just like README does, for people who miss it there.
