### ISSUE TITLE
Cache not resistant to thundering herd problem

### ISSUE THREAD

**Issue by frankier** [apptainer/singularity#5363]
Running `singularity exec shub://... ...` on many nodes with access to the same cache simultaneously, e.g. using SLURM will download the image on each node. This is quite a problem in practice with Singularity Hub since you can easily hit the limits this way. This problem is sometimes referred to as the [thundering herd problem](https://en.wikipedia.org/wiki/Thundering_herd_problem) or a [cache stampede](https://en.wikipedia.org/wiki/Cache_stampede). It is avoidable if all nodes can request mutually exclusive access to the cache. This way, only one node will end up doing the download. The rest of the nodes can be unblocked when the cache item is available.

**Comment by dtrudg** [comment]
This is a well known issue, and a complete solution is difficult to implement due to:

- Singularity is daemon-less by design, so there is no daemon to co-ordinate between nodes
- Singularity is deployed on HPC systems that use a wide range of network/parallel filesystems on which the cache could reside. These filesystems do not always provide consistent `flock` between nodes, or atomic renames. In some cases (such as NFS with attribute caching effects) the view of the files in a directory may not always be consistent.

Our advice is that parallel jobs should `singularity pull` an image to disk from a single location before executing in parallel, much as fetching other resources (such as datasets from http URLs) would be approached in parallel jobs.

More explicit mention of this has been added to the user docs for the upcoming 3.6.0 release: https://github.com/hpcng/singularity-userdocs/blob/0057f9ec80cd5e981788716a6de74604682c4e57/build_env.rst
