### ISSUE TITLE
Cgroups v2 hieararchy support

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5379]
Some distributions, such as Fedora 31 / 32, have switched to presenting the cgroups v2 hierarchy which differes from cgroups v1.

This causes issues for various container platforms and other tools that do not support the cgroups v2 hierarchy, including Singularity. There is some nice background here:

https://www.redhat.com/sysadmin/fedora-31-control-group-v2

A workaround for using cgroups the old way is to set the kernel command line option `systemd.unified_cgroup_hierarchy=0`

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
