### ISSUE TITLE
./configure --prefix=/usr/local fails on python check

### ISSUE THREAD

**Issue by NikosDelijohn** [apptainer/singularity#5420]
### OS: Ubuntu (Focal Fossa 20.04 LTS) 

So due to the fact that there is no backwards compatibility between v3 and v2 .imgs of singularity I am forced to install a previous version. Thus I picked version 2.4.5 . When I tried to "./configure --prefix=/usr/local/" the script said that I have to install python. Well, python2/3 is present in my system. How can I resolve this issue?

**Comment by dtrudg** [comment]
Hello. I'm afraid the open-source release of singularity 2.x is no longer supported, and it was never tested with Ubuntu >18.04.

Singularity 3.x can run Singularity 2.x images. If you experience errors running 2.x images with 3.x please file an issue as this is something that should be addressed in Singularity 3.x

If you need to build images with Singularity 2.x to distribute to locations where only 2.x is available then please ensure you are using the latest 2.6.1 version of Singularity 2.x, and I'd suggest using Ubuntu 18.04 or earlier. The detection of python may be problematic on newer distributions due to the migration from Python 2.7 -> 3.x. This won't be fixed, as no further work is happening to 2.x.
