### ISSUE TITLE
3.6.0 error after entering shell

### ISSUE THREAD

**Issue by AlexKurek** [apptainer/singularity#5438]
### Version of Singularity:
3.6.0

### Expected behavior

It should enter shell flawlessly after `singularity shell [name].sif`. It was so at 3.5.3 version.

### Actual behavior

It enters shell, but there is an error:
`"ulimit": executable file not found in $PATH`

### Steps to reproduce this behavior

Compile the attached recipes:
`sudo singularity build --force pref3_ubuntu18_python2.sif SING_pref3_ubuntu18_python2.sh`

### What OS/distro are you running
Ubuntu 18.04.4

### How did you install Singularity

Manually, like below:
```
export GO_VERSION=1.14.6
export SINGULARITY_VERSION=3.6.0

# GO:
export OS=linux ARCH=amd64
cd /tmp/
wget https://dl.google.com/go/go$GO_VERSION.$OS-$ARCH.tar.gz
tar -C /usr/local -xzf go$GO_VERSION.$OS-$ARCH.tar.gz
echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
source ~/.bashrc


# Singularity:
apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev pkg-config
mkdir -p $GOPATH/src/github.com/sylabs/
cd $GOPATH/src/github.com/sylabs/
wget https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
rm singularity-${SINGULARITY_VERSION}.tar.gz
cd ./singularity/
#./mconfig --prefix=/opt/singularity
./mconfig --prefix=/usr/local/
make -C ./builddir
make -C ./builddir install
# https://ubuntuforums.org/showthread.php?t=1528009&p=9571256#post9571256 symlink
rm -rf /usr/local/go/
rm -rf ~/go
```
[SING_pref3_ubuntu18_python2.zip](https://github.com/hpcng/singularity/files/4941497/SING_pref3_ubuntu18_python2.zip)

**Comment by cclerget** [comment]
@AlexKurek Since 3.6.0 Singularity now embed a shell interpreter to address many issues encountered with environment variables handling seen in the past, this interpreter doesn't provide the full set of builtins that you can expect from a standard shell like bash, `ulimit` is not provided and I don't think it would be provided because setting ulimit in the environment section while it is convenient may not be the right solution because :

setting `ulimit -n 4096` in the environment section would probably run just fine on some nodes but may fail to run on nodes where the hard limit for "open files" is lower than 4096 making the image unusable on those nodes and forcing you to rebuild the image to change this limit, that's why it would be probably better to change this limit outside of the image either before running the image or by adjusting the limit in a script running the application.
