### ISSUE TITLE
3.6 drops users into CWD... except when it doesn't

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#5462]
Consider the following behavior of v3.5.3.

```
$ singularity --version
singularity version 3.5.3

$ pwd
/home/user

$ singularity exec some.sif pwd
/home/user

$ sudo singularity exec some.sif pwd
/home/user

$ cd /opt/

$ sudo singularity exec ~/some.sif pwd
/opt
```

Now consider the different behavior of 3.6.1

```
$ singularity --version
singularity version 3.6.1

$ pwd
/home/user

$ singularity exec some.sif pwd
/home/user

$ sudo singularity exec some.sif pwd #<--- This is the confusing one
/root

$ cd /opt

$ sudo singularity exec ~/some.sif pwd
/opt
```
So it seems like the user's current working directory will remain unchanged when executing a Singularity command unless the user enters the container as root **AND** they do so from the user's home directory?  Is this intended behavior?  

The release notes for 3.6.0 do state the following:

>Restored the CWD mount behaviour of v2, implying that CWD path is not recreated inside container and any symlinks in the CWD path are not resolved anymore to determine the destination path inside container.

Is that what is behind this different behavior?  Maybe.

```
$ sudo mkdir -p /foo/bar/this/and/that

$ cd !$
cd /foo/bar/this/and/that

$ singularity exec ~/some.sif pwd
/home/user

$ sudo singularity exec ~/some.sif pwd
/root
```

Based on this test, it seems like singularity will drop you into the current working directory within the container unless it is a subdirectory within a parent directory that doesn't exist within the container.  That seems really confusing and arbitrary imho.

Just for completeness, this is not the way things were in 3.5

```
$ singularity --version
singularity version 3.5.3

$ pwd
/foo/bar/this/and/that

$ singularity exec ~/some.sif pwd
/foo/bar/this/and/that

$ sudo !!
sudo singularity exec ~/some.sif pwd
/foo/bar/this/and/that
```

**Comment by dtrudg** [comment]
AFAIK this is intended, and @cclerget can probably confirm.

The reason to go back to this 2.x behavior is that throughout 3.x it has been a complete game of whack-a-mole with CWD mounts when CWD involves symlinks, is across filesystems, etc. Every change to fix an issue for someone with a complex symlinked setup, auto mount issues, etc. etc. has resulted in behaviour that is undesirable for another person.

The current setup does have this behavior with sudo, because when you `sudo` from a subdir within a user $HOME you are root so the user $HOME isn't mounted, and the CWD handling won't try to create that in the container. 

The call during the 3.6 development process with this and the environment handling was to favour some simplicity, and stick to it now, rather than keep playing whack-a-mole with no clear expectation that all the issues raised in the past about CWD could be addressed concurrently.

**Comment by cclerget** [comment]
@GodloveD Yes this is expected as @dctrud explained, there was a bunch of issues around CWD with symlinks, the creation of unexpected directories, it was really annoying and hacky to fix all of them without breaking other corner cases that it is really difficult to handle correctly in order to satisfy everyone expectations. The main rule to retain with this v2 behavior is: if the directory doesn't exist in container, don't rely on it

**Comment by GodloveD** [comment]
OK.  Sounds like this is expected behavior and there is good reason for it.  Fair enough.
