### ISSUE TITLE
Failure to run container as a different user

### ISSUE THREAD

**Issue by tashrifbillah** [apptainer/singularity#5477]
# Way to reproduce
```
singularity build --sandbox /tmp/centos7 docker://centos:7.5.1804
singularity shell -u trump centos7/
```

# Error
> FATAL:   failed to retrieved path for /tmp/trump: lstat /tmp/trump: no such file or directory

# Additional information
```vim
[tb571@pnl-z840-2 tmp]$ singularity --version
singularity version 3.2.1-1.1.el7
[tb571@pnl-z840-2 tmp]$ uname -a
Linux pnl-z840-2 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

# Goal
Run a singularity container as a different user than the user running the singularity process

**Comment by dtrudg** [comment]
The `-u` option enters a user namespace as your current user, creating the container without needing root privilege. It does not allow you run the container as a different user.

The default security model of Singularity is different than docker. You are the same user in the container as you are on the host when you started the container. This is by design to allow use on shared systems, respecting host file permissions etc.

If your system supports it you can use the `--fakeroot` option, and can then become another user inside the container as a workaround. See https://sylabs.io/guides/3.6/user-guide/fakeroot.html - there are caveats discussed there.

**Comment by tashrifbillah** [comment]
Okay. Yet, why am I not able to use the `-u` namespace then? I tried reading the doc but couldn't undestand.

**Comment by dtrudg** [comment]
If you run `singularity shell -u trump centos7/` then `trump` is going to be used as the name of the container you want to run, as `-u` does not take any arguments.

If you want the user namespace (which will not become a different user.. it will stay as you) then it's `singularity shell centos7/`
