### ISSUE TITLE
can I run a program which is outside the image?

### ISSUE THREAD

**Issue by JoKalliauer** [apptainer/singularity#5483]
Is it possible to run a (portable) program, which is stored outside the image, or copy a program into the image?

I try to reproduce the steps in
https://learningpatterns.me/posts-output/2018-01-30-abaqus-singularity/
https://github.com/jomority/abaqus-2018-centos-7-singularity
However I take firefox as example instead of abaqus to reproduce the behaviour

### Version of Singularity:
`3.6.0`

### Expected behavior

run firefox from /usr/lib/firefox/firefox.sh

### Actual behavior

```
FATAL:   stat /usr/lib/firefox/firefox.sh: no such file or directory
```

### Steps to reproduce this behavior

`sudo singularity build MWE.img `[`MWE.def.txt`](https://github.com/hpcng/singularity/files/5034476/MWE.def.txt)

`singularity exec MWE.img /usr/lib/firefox/firefox.sh`

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

### How did you install Singularity

```sh
export VERSION=3.6.0 && # adjust this as necessary \
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
    tar -xzf singularity-${VERSION}.tar.gz && \
    cd singularity

./mconfig && \
    make -C ./builddir && \
    sudo make -C ./builddir install
```

**Comment by dtrudg** [comment]
If the program is outside of the container image then the location will have to be made available in the container by `--bind` ing the location into the container. Also any libraries required by the program must be available in the container.

Firefox uses a large number of libraries that would have to match between host and container in order to be able to run the host firefox in the container. Unless you are using exactly the same Linux distribution on the host as in the container I would not recommend this. Bringing anything from `/usr/lib` on the host into the container is generally a bad idea, as any mismatch in library compatibility will result in things in the container not working.

Copying a program into the container can be accomplished using a `%files` section in your definition file. See https://sylabs.io/guides/3.6/user-guide/definition_files.html#files

This is likely a better topic for the mailing list or slack channel where what you are trying to accomplish can be discussed. Others on the slack chat and mailing list have tried this approach for certain things and are likely to be able to help - but are  unlikely to see a specific  issue here.

Slack and mailing list links at: https://sylabs.io/resources/community

**Comment by JoKalliauer** [comment]
@dctrud : Thanks `--bind` solved the problem.

I found the explantation at https://sylabs.io/guides/3.6/user-guide/bind_paths_and_mounts.html helpful

I used `singularity exec --bind /opt/abaqus /home/jkalliau/imgs/sing/abaqus-2017-centos-7JK.img vglrun /opt/abaqus/CAE/2019/linux_a64/code/bin/ABQLauncher cae -mesa`.

A minmial working example:
`singularity exec --bind /folder/to/mount MyImage.img /folder/to/mount/bin/run.sh`
