### ISSUE TITLE
Ability to edit the recipe when something goes wrong

### ISSUE THREAD

**Issue by NormanTUD** [apptainer/singularity#5485]
### Version of Singularity: 2.5.2-dist

I really like singularity and use it a lot. But sometimes, for very large projects, there's a problem for me. Imagine I compile a certain software that is required as dependency for another program being installed later on, which takes about 2 hours on the remote machine, and then the command after that fails because I, for example, forgot to add `-y` to `apt-get install` or something like that. 

Since singularity recognizes lines that failed, there should be an option to, when failing, edit the recipe file directly and then continuing creating the image. This could be as easy as simply opening

> vim +123 recipe_file

via a `system`-call and then re-reading it from that line onwards (or even better, creating a diff and running it from the state on where the last change was made).

I'm not sure how hard this would be to implement, but it would greatly simplify practical work with singularity.

It may be best to do this via a parameter though, so it has to be enabled manually, so it does not interfere with any automated build scripts.

**Comment by dtrudg** [comment]
I'm afraid this is not something that would be at all easy. 

First - Singularity has to read in the whole definition file to process it so it knows how to build the container. If the file was edited half way through a build then it would need to be re-read, and it's very possible changes could be made in an editor that might make the file invalid, or change behavior inconsistently with what has already been run. Recognizing this in a robust way, and dealing with it, would be extremely difficult.

> or even better, creating a diff and running it from the state on where the last change was made

... is not really possible as you cannot guarantee that it's safe to go backward in an arbitrary shell script and start again from a prior point. Not all operations are idempotent.

Second - The `%post` block (and other blocks) is essentially a shell script, and is passed to the shell used to build the container. The shell runs the whole script. Singularity does not send one command at a time, and doesn't know which command failed.

When you see the commands running, and it stops at the failure point this is because the build shell is showing commands /output as they run, and Singularity is passing this to the terminal directly.

**Comment by GH-maggio** [comment]
This might be alleviated by using a container orchestrator such as https://github.com/singularityhub/singularity-compose.

**Comment by Iain-S** [comment]
@dctrud I completely understand the objections on the grounds of program correctness and idempotency. However, writing a Singularity .def file is, inevitably, an iterative process. For small errors or errors of omission (e.g. forgetting an `apt-get install` as mentioned above) and large compile times, this iterative loop could be made several orders of magnitude quicker if there was the option to edit the .def file on the fly.

> changes could be made in an editor that might make the file invalid, or change behavior inconsistently with what has already been run. Recognizing this in a robust way, and dealing with it, would be extremely difficult.

To be honest, I don't think you _do_ need to recognise them.  If a user is editing the .def file mid-build then it us up to them to do it in such a way that is consistent and correct. 

At the very least, it should be possible to edit the %test part of the build when a build fails and quickly re-run only the test script.  Likewise, it should be possible to rebuild the container quickly if you alter non-build steps (%environment, %test, %runscript, etc.) after a successful build.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
