### ISSUE TITLE
Improve e2e coverage of `delete` command

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5496]
### Version of Singularity:

What version of Singularity are you using? Run:

```
master
```

### Expected behavior

e2e tests of the delete command should be able to test that it is connecting to the correct location (via remote config, or a `--library` override). Also that it handles responses other than unauthorized correctly.

This will require full refactor of the test code for delete. It should use a mock service instead of calling out to the real library, so that we can test deletion success etc. Hopefully `scs-library-client` can provide the mock service that can be used in the e2e tests?

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
