### ISSUE TITLE
release-3.6 e2e failure - json: Key path not found in LabelCheckSchemaVersion

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5533]
### Version of Singularity:

What version of Singularity are you using? Run:

```
release-3.6
```

### Actual behavior

Running e2e tests on RHEL 7.8

```
                    --- FAIL: TestE2E/PAR/BUILD/non-root_build/docker_busybox/LabelCheckSchemaVersion (1.20s)
                        imageverify.go:111: Running command "/usr/local/bin/singularity inspect --json --labels /tmp/stest.578319358/non-root-build.447148868/container"
                        imageverify.go:104: unable to get expected output from json: Key path not found
```

### What OS/distro are you running

```
RHEL 7.8
```

**Comment by dtrudg** [comment]
This did not reproduce in 5 consecutive runs after cleaning up `/tmp` on my host. It appears to have been due to an out of disk space issue in parallel tests resulting in an incomplete container. This isn't a release blocker, but it does need investigation, as the out of disk space issue should have been caught somewhere instead.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
