### ISSUE TITLE
Using singularity container on a slurm managed cluster

### ISSUE THREAD

**Issue by brettChapman** [apptainer/singularity#5536]
Hi, I'm using some Singularity containers on my cluster that I built, which run tools that directly interact with slurm. Specifically I'm using Get_homologies-est (https://github.com/eead-csic-compbio/get_homologues), which needs access to slurm commands like sacct, sinfo etc from the host, and REPET (https://hub.docker.com/r/urgi/docker_vre_aio), which has it's own installation of slurm and a slurm.conf file (which I could replace with my systems slurm.conf or simply modify it, as they're different versions of slurm). At the moment I'm running the tools on single nodes, which is just too slow for the large jobs I'm running.

I've read that Singulairty works with HPC systems. I usually run singularity exec from a *.sif container with --bind to mount files I need for the job.

For example I usually run my tools like so:
```
srun -n 1 singularity exec --bind ${PWD}:${PWD} ${GET_HOMOLOGUES_IMAGE} get_homologues-est.pl -d cds -D -n ${SLURM_NTASKS_PER_NODE} -o &> log.cds.pfam
```

If I needed to get the singularity containers to see the host slurm installation, what steps would I need to take? I've read a lot of FAQs, forums etc but nothing has jumped out as a solution. Would running my singularity container as a sandbox instead of a *.sif allow the container to see the host systems slurm install? or perhaps binding particular directories?

Thanks for your help.

### Version of Singularity:

3.6

### Expected behavior

Using Singularity with my cluster

### Actual behavior

Have my singularity container see and access slurm commands 

### What OS/distro are you running

Ubuntu 20.04

### How did you install Singularity

Git pull and install from source.

**Comment by sjpb** [comment]
Interesting. If the host is on the latest slurm (20.02) then there is a [REST api ](https://slurm.schedmd.com/rest.html) which you could use to get info from slurm, although I think that info is currently limited. Realise it's unlikely you're on that slurm though!

**Comment by brettChapman** [comment]
Thanks for the suggestion. The host system has slurm 19.05.5.

If there is no other workaround, I guess I'll have to install directly to the host system instead of within a container.

I would have thought this would be a common problem when deploying Singularity containers on HPCs. How is Singularity usually deployed for HPC systems? Are job schedulers like slurm usually involved?

**Comment by sjpb** [comment]
Containers or not, I think it's probably pretty unusual for commands launched by the scheduler to then need to query the scheduler. For "static" info the environment variables which slurm provides are generally enough so calling `sinfo`, `sacct` etc is definitely not common practice.

**Comment by dtrudg** [comment]
Various people have, and do, mount or install slurm binaries into containers so that the container can use SLURM. This is generally discouraged if avoidable because it makes the container somewhat dependent on the host environment, lessening one of the chief benefits of containerizing an application.

The exact binds needed will depend on how SLURM is installed on your system, i.e. distro packages, source install, under an environment such as Bright CM etc. You have to ensure all SLURM binaries and config are bound in, and that they are compatible with the container OS & libraries - or install SLURM in the container and bind in or provide the config file if that's not possible.

The mailing list may have useful information, as the question comes up there from time to time: https://groups.google.com/a/lbl.gov/g/singularity/search?q=slurm

**Comment by brettChapman** [comment]
Thanks for your help. I install slurm and all dependencies through the distro packages (sudo apt-get install). Most if not all relevant files are under /etc/slurm-llnl/, /var/run/ etc.

I'll try my luck with the mailing list. A quick look through seems there are an awful lot of similar questions to mine. Thanks.

**Comment by dtrudg** [comment]
Closing, as this issue is a usage question that has not had follow up for >90 days.

For issues that are questions r.e. using Singularity, rather than bugs or feature requests, the mailing-list and slack channel are often better venues. Questions to the slack channel and mailing list will be seen by a large number of subscribed users, rather than only those who look inside a particular GitHub issue. Therefore they are encouraged for this type of inquiry.

Slack: See https://hpcng.org/ for invite (bottom of page)
Mailing List / Google Group: https://groups.google.com/a/lbl.gov/forum/#!forum/singularity

**Comment by frankier** [comment]
Interesting to hear that it is possible to mount the SLURM binaries within the container. I have had problems doing this where I had to mount more and more shared libraries until stuff started breaking ;) . My solution was to do RPC through the filesystem so that the SLURM commands run outside the binary. See: https://github.com/frankier/singslurm2
