### ISSUE TITLE
Proposal: Remote service management

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#5540]
# Remote services management

This a follow up and proposal regarding discussions about changes introduced by #5445 and #5464 in order to allow users/admins to define additional services for managing them through `singularity remote`.

An idea brought up by Adam Hughes (https://github.com/hpcng/singularity/pull/5464#pullrequestreview-460923370) involves expanding the `singularity remote` command group to support keyserver overrides. We generally agree with this assessment for both the registry credential management as well as the key service, and potentially future remote service options. We think this idea is worth discussion beyond just the keyserver use case as it gives us the opportunity to standardize the way Singularity interacts with all external service configurations within a single command group.

## Singularity remote proposal

Here a proposal to manage detached services, a detached service wouldn't be tight to any particular endpoint and would be available as long it is not removed explicitly:

```
// Add an SCS endpoint
singularity remote add [-g] <endpoint_name> <hostname>
// Add a keyserver to override SCS endpoint keystore
singularity remote add [-g] keyserver://<service_name> <hostname>
// Add oci registry
singularity remote add oci://<service_name> <hostname>

// List configured SCS endpoints
singularity remote list
// List configured keyserver override
singularity remote list keyserver
// List configured oci registry hostnames
singularity remote list oci

// Ping SCS endpoint for service statuses
singularity remote status
// Ping keyserver for status
singularity remote status keyserver
// Ping oci registry for status
singularity remote status oci

// Remove an SCS endpoint
singularity remote remove [-g] <endpoint_name>
// Remove a keyserver override
singularity remote remove [-g] keyserver://<service_name>
// Remove oci registry
singularity remote remove oci://<service_name>

// Authenticate with SCS endpoint
singularity remote login [--username|--password|--password-stdin|--insecure] <endpoint_name>
// Authenticate with keyserver (if applicable)
singularity remote login [--username|--password|--password-stdin|--insecure] keyserver://<service_name>
// Authenticate with OCI registry
singularity remote login [--username|--password|--password-stdin|--insecure] oci://<service_name>

// Set remote used by default
singularity remote use [-g] <endpoint_name>
```

**Comment by dtrudg** [comment]
Hi @cclerget - thanks for this. Could you add some detail of the output the user would expect to see from these commands / subsequent interactions with the services?

I believe that one of @tri-adam 's main concerns was that it should be clear to the user when e.g. they are using a default library service, but the keyserver has been overridden etc.

Also we now have two image storage protocols.... OCI and library. How is push intended to work there? Presumably this will only set an endpoint for `singularity push oras://.....` or is there a different intention? For pull would you then assume that default pulls e.g. `singularity pull ubuntu` are going to go to oras, do an oci pull from the registry, or stay with the configured server for the library protocol?

**Comment by tri-adam** [comment]
I'll add that I think brief admin/user "stories" would really help clarify the use cases. For example, "Admin Amy wants to add an additional keyserver to a configured `remote`", or "User Uri is unable to `verify`, and wants to check which keyserver is in use." From there, as @dctrud suggests, going through the admin/user workflow with some mock output would be a good way to tease out the UX detail here.

In particular, it's not clear to me what is expected how `remote use`, `remote list` are to behave. The proposal seems to have the concept of `endpoint`s and `service`s, but it's unclear how they interact from an admin and user point of view. Is an `endpoint` a group of `service`s? How does one `list` an `endpoint` versus a `service`? Are `service`s scoped to an `endpoint`, or do they span all `endpoint`s?

**Comment by cclerget** [comment]
> For pull would you then assume that default pulls e.g. singularity pull ubuntu are going to go to oras, do an oci pull from the registry, or stay with the configured server for the library protocol?

No, nothing would change at this level, `singularity remote add oci://` would add an oci registry in order to manage the credentials via `singularity remote login ... oci://` which is responsible of checking credentials to store them with the host associated to the oci registry in `docker-config.json` like it was done in #5445.

Let's take the docker/gitlab example, a user want to manage both docker and gitlab credentials

To add oci registries (to not accidentally leak admin credentials, they couldn't be added as global):

```
singularity remote add oci://gitlab registry.gitlab.com
singularity remote add oci://dockerhub docker.io
```

To associate credentials:

```
singularity remote login --username foo --password bar oci://gitlab
Login succeed
singularity remote login --username bar --password foo oci://dockerhub
Login succeed
```

And pull from private repo:

```
singularity pull gitlab.sif docker://registry.gitlab.com/foo/private/image:latest
singularity pull docker.sif docker://bar/private/image:latest
```

List OCI registries:
```
singularity remote list oci
NAME       URI                  GLOBAL
gitlab     registry.gitlab.com  NO
dockerhub  docker.io            NO
```

Remove registries and credentials:
```
singularity remote remove oci://gitlab
singularity remote remove oci://dockerhub
```

> Are services scoped to an endpoint, or do they span all endpoints?

They span all endpoints. To give you an overview of internal structure, it would look like :

```
type Config struct {
	DefaultRemote    string                      `yaml:"Active"`
	Remotes          map[string]*endpoint.Config `yaml:"Remotes"`
	DetachedServices map[string][]service.Config `yaml:"DetachedServices"`
}
```

> In particular, it's not clear to me what is expected how remote use, remote list are to behave

The `remote use` is actually not used by services. For `remote list`, please refer to example above and below.

> Could you add some detail of the output the user would expect to see from these commands / subsequent interactions with the services?

Keyserver use case :

An administrator set a keyserver to override all the keyservers defined by users' remote endpoints :
```
singularity remote add -g keyserver://keys@domains.com https://keys.domain.com
```

A user set a keyserver to override all the keyservers defined by his remote endpoints :
```
singularity remote add keyserver://keys@domains.com https://keys.domain.com
```

Note that if an admin has already overridden the keyserver globally, the global keyserver take precedence over the one set by the user. The order is :
1. Use the global keyserver if any
2. Use the user keyserver if any
3. Use the keyserver from the remote endpoint

To check which keyserver is in use:

```
singularity remote list keyserver
NAME              URI              GLOBAL   ACTIVE
keys@domains.com  keys.domain.com  YES      YES
```

> I believe that one of @tri-adam 's main concerns was that it should be clear to the user when e.g. they are using a default library service, but the keyserver has been overridden etc.

In this case it would be easy to detect that and display info/warn users accordingly

**Comment by cclerget** [comment]
@dctrud @tri-adam I fixed the typo error `singularity login` which should be `singularity remote login`.

Otherwise what do you think about that ? Any thoughts/proposal would be greatly appreciated.

**Comment by dtrudg** [comment]
Hi Cedric - I'm a bit busy today, but will get back to you again no later than end of day tomorrow.

**Comment by dtrudg** [comment]
Hi @cclerget - some specific thoughts on the proposal here. I am still trying to articulate some general ideas around this whole concept and will aim to get them down ASAP.

> To add oci registries (to not accidentally leak admin credentials, they couldn't be added as global):
> ```
> singularity remote add oci://gitlab registry.gitlab.com
> singularity remote add oci://dockerhub docker.io
> ```

The URI style `oci://<name>` is a bit confusing to me here, given that later on we need to pull using `docker://` and the host name.. not the `oci://<name>` 

> And pull from private repo:
> 
> ```
> singularity pull gitlab.sif docker://registry.gitlab.com/foo/private/image:latest
> singularity pull docker.sif docker://bar/private/image:latest
> ```

I think this type of inconsistency would be best avoided if possible especially since an `oci:` prefix is in use elsewhere. Singularity will accept `oci://xxxxx` as a pull source meaning `an oci archive at /xxxxx`... 

```
[ec2-user@ip-172-31-78-196 ~]$ singularity pull oci://docker.io/ubuntu
FATAL:   While making image from oci registry: failed to get checksum for oci://docker.io/ubuntu: unable to parse image name oci://docker.io/ubuntu: lstat /docker.io: no such file or directory
```

Moving on from this It's not really clear why we have to `add` and `login` in separate steps. If after `add` I can't use (unauthenticated) the OCI remote by name..... I still need the full `docker://hostname/...` in my pull... what is the reasoning behind adding and login being separate? Is there an intention to be able to override a the default `docker.io` registry for `docker://ubuntu` or similar at some point?

Generally in the OCI space it's usual to have to supply the hostname as part of the repo you are pulling from / pushing to,  so could we stick to that pattern for the remote command also, and not introduce an alternate name at all?

> List OCI registries:
> 
> ```
> singularity remote list oci
> NAME       URI                  GLOBAL
> gitlab     registry.gitlab.com  NO
> dockerhub  docker.io            NO
> ```

Having `singularity remote list` and `singularity remote list oci` is going to be a bit confusing. If we have both library/builder/keyserver and OCI things under `remote` I think a default list should show it all, and filtering down to a subset would be the option.

> Remove registries and credentials:
> 
> ```
> singularity remote remove oci://gitlab
> singularity remote remove oci://dockerhub
> ```

To me there should be a natural pairing of `login` -> `logout`... Thinking about it, in the OCI case maybe `add` -> `remove` are just synonyms of `login` -> `logout` for our purposes?

> > In particular, it's not clear to me what is expected how remote use, remote list are to behave
> 
> The `remote use` is actually not used by services. For `remote list`, please refer to example above and below.

I think this is something that would have to be nice and clear in the default output of `remote list` - that there are different classes of remotes, and the user can see them and easily understand what is going to be used for what actions, from the default output of `list`.

> > Could you add some detail of the output the user would expect to see from these commands / subsequent interactions with the services?
> 
> Keyserver use case :
> 
> An administrator set a keyserver to override all the keyservers defined by users' remote endpoints :
> 
> ```
> singularity remote add -g keyserver://keys@domains.com https://keys.domain.com
> ```

Again here, using a `keyserver://xxxx` URI style name, but also having to supply an `https://hostname` is a bit confusing. `keyserver://keys@domains.com` looks like it should be some kind of natural URI a program can use to communicate, but it's an arbitrary name? We made a bit of a mistake with `library://` URIs that don't take a hostname component ( I believe @tri-adam has mentioned it in various discussions) that we should try not to repeat.

I think we can use more natural language? It's an override, so let's say that? Things like...

```
# global (admin)
singularity remote override-keyserver -g https://keys.domain.com

# user
singularity remote override-keyserver https://keys.domain.com
```

> Note that if an admin has already overridden the keyserver globally, the global keyserver take precedence over the one set by the user. The order is :
> 
>     1. Use the global keyserver if any
> 
>     2. Use the user keyserver if any
> 
>     3. Use the keyserver from the remote endpoint

Are there more subtle situations than this? Does an admin ever want to set a global keyserver that is a default, but *can* be overridden by a user? The precedence at the moment strikes me as catering to very prescriptive, strict environments. I'd guess that there are relatively few places who want to absolutely enforce a particular remote service is used. I think it more likely sites might want to set a default to any in-house / custom infra for a nice user experience, but allow users to override if they need to.

> To check which keyserver is in use:
> 
> ```
> singularity remote list keyserver
> NAME              URI              GLOBAL   ACTIVE
> keys@domains.com  keys.domain.com  YES      YES
> ```

We should definitely be able to see this in a straight `remote list` in my opinion. It's vital that a user can tell what endpoint a key / library / builder action is going to.

**Comment by tri-adam** [comment]
Apologies for the slow feedback @cclerget. I agree with the direction things are headed here, and really appreciate the openness. One idea I'll add into the mix:

> Again here, using a `keyserver://xxxx` URI style name, but also having to supply an `https://hostname` is a bit confusing. `keyserver://keys@domains.com` looks like it should be some kind of natural URI a program can use to communicate, but it's an arbitrary name? We made a bit of a mistake with `library://` URIs that don't take a hostname component ( I believe @tri-adam has mentioned it in various discussions) that we should try not to repeat.
> 
> I think we can use more natural language? It's an override, so let's say that? Things like...
> 
> ```
> # global (admin)
> singularity remote override-keyserver -g https://keys.domain.com
> 
> # user
> singularity remote override-keyserver https://keys.domain.com
> ```
> 
> > Note that if an admin has already overridden the keyserver globally, the global keyserver take precedence over the one set by the user. The order is :
> > ```
> > 1. Use the global keyserver if any
> > 
> > 2. Use the user keyserver if any
> > 
> > 3. Use the keyserver from the remote endpoint
> > ```
> 
> Are there more subtle situations than this? Does an admin ever want to set a global keyserver that is a default, but _can_ be overridden by a user? The precedence at the moment strikes me as catering to very prescriptive, strict environments. I'd guess that there are relatively few places who want to absolutely enforce a particular remote service is used. I think it more likely sites might want to set a default to any in-house / custom infra for a nice user experience, but allow users to override if they need to.

I totally agree that we shouldn't use URI-style names for things that aren't, particularly when there is also a URI in the same command. And although I can see the use case for setting a global override keyserver and preventing users from setting their own... it's important to note that users would still be able to add any key they like via `singularity key import`.

Given this, might it also be good to make the verb agnostic of priority? I would imagine the general case is as @dctrud describes, setting one or more additional key servers so that verification "just works". Perhaps this could be as simple as:

```sh
singularity remote add-keyserver -g hkps://keys.domain.com
```

Use of the agnostic verb would then open up the possibility of an admin defining a more restrictive "override", something like:

```sh
singularity remote add-keyserver -g --override hkps://keys.domain.com
```

And also, more complex setups in the future, such as having priorities associated with each, as suggested by @gmkurtzer in the last developer call.

**Comment by cclerget** [comment]
Thanks @dctrud and @tri-adam for the feedback's.

## OCI registry

> Moving on from this It's not really clear why we have to add and login in separate steps. If after add I can't use (unauthenticated) the OCI remote by name..... I still need the full docker://hostname/... in my pull... what is the reasoning behind adding and login being separate? Is there an intention to be able to override a the default docker.io registry for docker://ubuntu or similar at some point?

There is no intention to override the default `docker://` or `oras://` or any registry with this approach, no behavior change implied at this level.

> Generally in the OCI space it's usual to have to supply the hostname as part of the repo you are pulling from / pushing to, so could we stick to that pattern for the remote command also, and not introduce an alternate name at all?

We could remove the necessity for add and just stick with `singularity remote login` and add a `singularity remote logout` command:

```
singularity remote login --username foo --password bar docker://docker.io
singularity remote login --username bar --password foo --insecure oras://localhost:5000
```

```
singularity remote logout docker://docker.io
singularity remote logout oras://localhost:5000
```

Where we could manage login based on scheme which could be extended in the future. Those remote services could be just managed through `remote login/remote logout` without any further interaction with commands like `remote list` or `remote status` and without being impacted by `singularity remove/singularity use`. Does that make sense ?

## Keyserver 

> And although I can see the use case for setting a global override keyserver and preventing users from setting their own... it's important to note that users would still be able to add any key they like via singularity key import.
Given this, might it also be good to make the verb agnostic of priority? I would imagine the general case is as @dctrud describes, setting one or more additional key servers so that verification "just works". Perhaps this could be as simple as:

So having something like :

```
singularity remote add-keyserver [-g] [--order X] <hkp|http|https|hkps>://keys.domain.com
singularity remote remove-keyserver [-g] <hkp|http|https|hkps>://keys.domain.com
```
```
singularity remote list-keyserver
URI              ORDER
keys.sylabs.io   0
```
```
singularity remote add-keyserver -g --order 0 hkps://keys.domain.com
singularity remote list-keyserver
URI              ORDER
keys.domain.com  0
keys.sylabs.io   1
```
```
singularity remote remove-keyserver keys.domain.com
singularity remote list-keyserver
URI              ORDER
keys.sylabs.io   0
```

So a keyserver with the lowest order would be the primary one used for `key push/pull/newpair/search` and `verify` would just iterate over key servers in order, does that make sense ?

**Comment by dtrudg** [comment]
Hi @cclerget - sorry for the delay in further feedback due to release work.

> We could remove the necessity for add and just stick with `singularity remote login` and add a `singularity remote logout` command:
> 
> ```
> singularity remote login --username foo --password bar docker://docker.io
> singularity remote login --username bar --password foo --insecure oras://localhost:5000
> ```
> 
> ```
> singularity remote logout docker://docker.io
> singularity remote logout oras://localhost:5000
> ```

I definitely prefer this if we really want to keep OCI logins under the `remote` command rather than in the `oci` command. i think it's pretty clear, and it maps quite nicely to the `docker login` / `docker logout` pattern that people might be familiar with.

> Where we could manage login based on scheme which could be extended in the future. Those remote services could be just managed through `remote login/remote logout` without any further interaction with commands like `remote list` or `remote status` and without being impacted by `singularity remove/singularity use`. Does that make sense ?

I think I'd still quite like to see `remote list` show any `docker://` endpoints we have logged in to. I feel like if anything is managed under the `remote` command then it should be visible in `remote list`. It would be pretty reasonable for it to be a visually separate section below the 'cloud services' remotes.

> ## Keyserver
> 
> > And although I can see the use case for setting a global override keyserver and preventing users from setting their own... it's important to note that users would still be able to add any key they like via singularity key import.
> > Given this, might it also be good to make the verb agnostic of priority? I would imagine the general case is as @dctrud describes, setting one or more additional key servers so that verification "just works". Perhaps this could be as simple as:
> 
> So having something like :
> 
> ```
> singularity remote add-keyserver [-g] [--order X] <hkp|http|https|hkps>://keys.domain.com
> singularity remote remove-keyserver [-g] <hkp|http|https|hkps>://keys.domain.com
> ```
> 
> ```
> singularity remote list-keyserver
> URI              ORDER
> keys.sylabs.io   0
> ```
> 
> ```
> singularity remote add-keyserver -g --order 0 hkps://keys.domain.com
> singularity remote list-keyserver
> URI              ORDER
> keys.domain.com  0
> keys.sylabs.io   1
> ```
> 
> ```
> singularity remote remove-keyserver keys.domain.com
> singularity remote list-keyserver
> URI              ORDER
> keys.sylabs.io   0
> ```
> 
> So a keyserver with the lowest order would be the primary one used for `key push/pull/newpair/search` and `verify` would just iterate over key servers in order, does that make sense ?

This is definitely getting there. I still think we should have a mock-up for a `remote list` that shows *all* of the stuff configured under the `remote` command nicely - so it's clear to someone if there are global keyservers set, ordering etc. At the very least it should indicate something like `Additional keyservers are configured, see singularity remote list-keyserver`

The below as just a very quick and naive thought:


```
09:43 AM $ singularity remote list

Cloud Services Endpoints
========================

NAME           URI                      GLOBAL ACTIVE
SylabsCloud    cloud.sylabs.io          YES    NO
myco           cloud.example.com        NO     YES


Keyservers
==========

URI                   GLOBAL   ORDER
keys.domain.com       NO       1
keys.example.com      YES      2*

* Active cloud services keyserver


Docker / OCI Registry Credentials
=================================

URI                         INSECURE
docker.io			   NO
localhost:5000		 YES
```

I think this is what I'd most like to get settled now.... the big picture - what does the user see that allows them to understand what is going on across all remotes / keyservers / authorized OCI registries etc.

Going to ping @EmmEff and @tri-adam for their thoughts toward moving this on too.
