### ISSUE TITLE
Singularity container to container communication

### ISSUE THREAD

**Issue by atharvnagarikar** [apptainer/singularity#5542]
### Version of Singularity: 3.6

What version of Singularity are you using? Run:3.6

Actually,, I'm trying to integrate an AI Application i.e. deploying a small part of the application on multiple clusters and
they will communicate with each other to execute the operation. Is it possible to so?

**Comment by dtrudg** [comment]
Closing, as this issue is a usage question that has not had follow up for >90 days.

For issues that are questions r.e. using Singularity, rather than bugs or feature requests, the mailing-list and slack channel are often better venues. Questions to the slack channel and mailing list will be seen by a large number of subscribed users, rather than only those who look inside a particular GitHub issue. Therefore they are encouraged for this type of inquiry.

Slack: See https://hpcng.org/ for invite (bottom of page)
Mailing List / Google Group: https://groups.google.com/a/lbl.gov/forum/#!forum/singularity
