### ISSUE TITLE
FATAL:   while obtaining keyring for ECL: openpgp: invalid data: tag byte does not have MSB set

### ISSUE THREAD

**Issue by pouya-codes** [apptainer/singularity#5569]
### Expected behavior
```
Running my code using singularity image.
```
### Actual behavior
`FATAL:   while obtaining keyring for ECL: openpgp: invalid data: tag byte does not have MSB set`
### What OS/distro are you running
```
Ubuntu 18.04.1 LTS
```
### How did you install Singularity
I'm using a cluster and the admin has installed Singularity.

**Comment by dtrudg** [comment]
Hello poya1991 - have you ever manipulated your singularity pgp keyring manually? This error appears to occur when the PGP 2.1 version is used to create a keyring.

e.g. https://github.com/helm/helm/issues/2843

Otherwise, it's possible that your singularity keyring under `~/.singularity/sypgp/` have become corrupt somehow. If you have not manually modified them you may wish to `mv` the directory to `sypgp.old` so that they can be recreated.

**Comment by pouya-codes** [comment]
Hi David, thanks! I didn't modify the keyring and moving the directory solved my problem.
