### ISSUE TITLE
can't mount image

### ISSUE THREAD

**Issue by cccbauer** [apptainer/singularity#5582]
### Version of Singularity:

What version of Singularity are you using? Run: 3.0.3

```
$ singularity version

```

### Expected behavior
a graphical inter phase

### Actual behavior

singularity exec singularity-images/murfi2.sif murfi -f murfi_example_data/scripts/neurofeedback.xml
FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/10: failed to mount squashfs filesystem: invalid argument

### Steps to reproduce this behavior

the singularity image can be found here and the

https://github.com/kaczmarj/murfi2/tree/add/dockerfile/docker

### What OS/distro are you running

ubuntu 20.4
```
$ cat /etc/os-release


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by dtrudg** [comment]
Older versions of Singularity are not compatible with the new version of the Linux kernel in Ubuntu 20.04. Singularity will give this error due to a mount option Singularity is trying to pass to the kernel.

This issue has already been fixed. Please upgrade to the current version of Singularity. Note that bug fixes are only added on the current open source version. 3.0.x has not received any fixes for some time.
