### ISSUE TITLE
Plugin compile failed with error: singularity source directory not found

### ISSUE THREAD

**Issue by willfurnass** [apptainer/singularity#5583]
Singularity v3.6.2 and Go 1.15.2 on Arch Linux.  Singularity installed via AUR.

### Expected behavior

The following should build an example plugin: 

```
$ git clone https://github.com/singularityware/singularity.git 
$ cd singularity
$ git checkout v3.6.2
$ singularity plugin compile examples/plugins/log-plugin/
```

### Actual behavior

```
$ singularity plugin compile examples/plugins/log-plugin/
FATAL:   Plugin compile failed with error: singularity source directory not found
```

**Comment by willfurnass** [comment]
This may relate to my singularity binary having been built from a source tree in a different location to the one I'm wanting to use to build plugins: 

```
$ cd /home/will/dev/singularity
...
$ strace -f singularity plugin compile examples/plugins/log-plugin/
...
[pid 73293] newfstatat(AT_FDCWD, "/home/will/.singularity", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
[pid 73293] newfstatat(AT_FDCWD, "/home/will/.singularity/remote.yaml", 0xc000211488, 0) = -1 ENOENT (No such file or directory)
[pid 73293] newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[pid 73293] newfstatat(AT_FDCWD, "/home/will/dev/singularity", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[pid 73293] newfstatat(AT_FDCWD, "/home/will/dev/singularity/examples/plugins/log-plugin", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[pid 73293] newfstatat(AT_FDCWD, "/home/will/.cache/pacaur/singularity-container/src/singularity/src/github.com/sylabs/singularity/internal/app/singularity/plugin_compile_linux.go", 0xc000211898, 0) = -1 ENOENT (No such file or directory)
[pid 73293] write(2, "\33[31mFATAL:  \33[0m Plugin compile"..., 91FATAL:   Plugin compile failed with error: singularity source directory not found
```

**Comment by dtrudg** [comment]
The plugins mechanism for the go language that Singularity is written in is quite restrictive - it requires extremely close version matching of packages used in a plugin to the ones used in the program the plugin is built for. Additionally Singularity is using build time config to get the source tree location for `singularity plugin compile` so that you don't need to export vars etc, and there isn't mismatch between package path information that go uses.

This means that at present you must:

- Build plugins using the exact same version of the source code, in the same location, as was used to build the Singularity executable.
- Use the exact same version of Go that was used to build the executable when compiling a plugin for it.

**Comment by willfurnass** [comment]
@dctrud Thanks for the info; I've filed a PR against the user docs that includes this (https://github.com/hpcng/singularity-userdocs/pull/344).

So presumably building plugins will also be non-trivial if one has installed Singularity using a RPM from the EPEL repo?

**Comment by dtrudg** [comment]
> So presumably building plugins will also be non-trivial if one has installed Singularity using a RPM from the EPEL repo?

Correct - it's non-trivial for all installs that were built under a distro packaging system where a temporary build location is used etc.

There are possibly some very limited things we can do to improve the situation slightly, but with the hard version-match requirement for go modules imported by plugin vs app, and also the requirement of exactly the same go version it's not really going to help much.

Thanks for the docs PR.

**Comment by willfurnass** [comment]
I suppose the things you list are the disadvantages of Go shipping static binaries.  Know if there's been any discussion of using e.g. an embedded Lua interpreter for sysadmin/end user plugins?

**Comment by dtrudg** [comment]
No discussion of an embedded interpreter for plugins to date. I think that would be quite a large amount of work. Also, due to the way the Singularity code must use escalated privilege in key places, and could be modified to do nasty things, the security model would be complex and difficult to get right if we considered allowing end-user plugins.

My feeling is that it's something that is unlikely to be pursued by the core group of developers due to the complexity, and lack of general requests for it. With my release manager hat on, the maintenance / security burden probably makes it unlikely to be merged from a community contribution... but others may have a different perspective.
