### ISSUE TITLE
Request: integrated logging mechanism

### ISSUE THREAD

**Issue by willfurnass** [apptainer/singularity#5584]
Singularity no longer logs actions (#4992) but the source tree does include a `log-plugin` plugin.  However, it's difficult building plugins if you're installing/managing singularity using binary packages or a package manager that builds from source in an ephemeral location (#5583).

I'd therefore be very much interested in some mechanism for logging Singularity actions to be built into Singularity itself. Auditing/assessing usage is something administrators could do by enforcing the use of a local image registry but it would definitely be good to be able to audit usage in execution environments (via syslog) instead / as well.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by willfurnass** [comment]
1. No, I think this is should still be Open and isn't a duplicate.
2. Yes, I think this is still relevant
3. Yes
