### ISSUE TITLE
Undocumented %environment timeout sometimes prevents conda activate

### ISSUE THREAD

**Issue by Iain-S** [apptainer/singularity#5589]
### Version of Singularity:

What version of Singularity are you using?

```
$ singularity version
3.6.1
```
**Note:** The issue does not seem to occur on Singularity version 3.5.3.

### Expected behaviour

I expect that running `singularity shell minimal.simg` should start my container.

### Actual behaviour

I get an error message:

> FATAL: command "sleep 6" was killed after 5s timeout

Obviously this happens because I explicitly call `sleep` but it also happens for any initialisation code that takes >5s to run.  I have tracked the 5s timeout down to [interpreter.go](https://github.com/hpcng/singularity/blob/master/internal/pkg/util/shell/interpreter/interpreter.go).  A comment in that file says

> // defaultExecHandler is the default command execution handler if there is
> // no registered shell builtin.

However it is not clear to me what a "registered shell builtin" is.

### How it came to light

I had installed an R package into a conda environment.  The R package relied on r-base and r-base called `R CMD javareconfig`.  That command sometimes takes >5s.

It isn't clear how one is supposed to activate a conda env in %environment or %runscript etc.  Unfortunately, if you do manage to run conda activate in %environment, you don't get the env name in the prompt.  You would normally see (env-name) in your prompt e.g.:

```
(base) $
```

But you see

```
Singularity>
```

even though `conda list` shows that the env has been activated.  This is perhaps a separate issue but I thought I should mention it because it is not what I would intuitively expect.

### Other comments

In general, the [shell docs](https://sylabs.io/guides/3.1/user-guide/cli/singularity_shell.html) do not cover:

1) Which shell will be run
1) Whether the shell will source e.g. .bashrc in my ~
1) How I am supposed to activate a conda environment in %environment

Many .bashrc files have a conda-managed section such as:

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/me/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/me/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/me/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/me/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

If my ~/.bashrc is sourced when running `singularity shell` then surely I will get quite different results when running the container than someone who hasn't previously set up conda on their machine.  Isn't the point of containers to defend against such inconsistencies?

### Steps to reproduce this behaviour

1) Make a file called minimal.def with the following contents
   ```
   Bootstrap: docker                                 
   From: centos:7.7.1908
                                                  
   %environment                                                                                                
       sleep 6
   ```
1) Run
   ```
   sudo `which singularity` build minimal.simg minimal.def
   ```
1) Run
   ```
   singularity shell minimal.simg
   ```
### How did you install Singularity

Using [singularity-3.6.1.tar.gz](https://github.com/hpcng/singularity/releases/download/v3.6.1/singularity-3.6.1.tar.gz)

**Comment by dtrudg** [comment]
This has been changed to a fixed 1 minute by @cclerget in #5661. The thinking is that this should be sufficient for any reasonable environment initialization, and we'd like to avoid added more user-configurable options unless absolutely necessary.

For the documentation concerns, please open any issues in the userdocs repo at: https://github.com/hpcng/singularity-userdocs. Please ensure you review the latest version of the docs before filing an issue (shell docs link above is against docs for version 3.1)

R.E. conda...

> Isn't the point of containers to defend against such inconsistencies?

Singularity has adopted an approach that has less isolation by default, so that containerised programs can be used easily interactively in batch jobs etc. - with similar semantics as a program that is on the host. The `--contain` and `--containall` options allow greater levels of containment, similar to Docker etc., that will e.g. prevent `$HOME` dotfiles being sources in the container.
