### ISSUE TITLE
Singularity fails to run on HPC compute nodes with aprun 

### ISSUE THREAD

**Issue by akshaymanu007** [apptainer/singularity#5598]
### Version of Singularity:
singularity version 3.6.3

I am running simple singularity program on compute node with the help of aprun but it is showing following error 

FATAL:   Couldn't determine user account information: user: unknown userid 606

As we know only userid will be passed to the compute node while executing with aprun  and not all the user information

This error is coming from  following file 
singularity/cmd/internal/cli/singularity.go

It checks for user information but only user id is present on compute node.

How to solve this issue ?? 

```


<!-- please include command-line output in a code block -->

### Expected behavior

What did you expect to see when you do...?


### Actual behavior

What actually happend? Why was it incorrect?



<!-- if this is a feature request, you can ignore this next part -->

### Steps to reproduce this behavior

How can others reproduce this issue/problem?


### What OS/distro are you running

```
$ cat /etc/os-release

```


### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by akshaymanu007** [comment]
any updates on this ??

**Comment by dtrudg** [comment]
I'm not familiar with `aprun` - please provide more information about what it is, what you are running with it (i.e. commands), and generally how the problem can be replicated in order that people might be able to make suggestions. You may also want to try the slack channel and mailing list.

This doesn't really appear to be a bug in Singularity. Singularity needs to find the user $HOME directory, and other information about the user when it is run. If this is not present on a system then it is unlikely it will be possible to run Singularity.

**Comment by dtrudg** [comment]
Closing, as this issue is a usage question that has not had follow up for >90 days.

For issues that are questions r.e. using Singularity, rather than bugs or feature requests, the mailing-list and slack channel are often better venues. Questions to the slack channel and mailing list will be seen by a large number of subscribed users, rather than only those who look inside a particular GitHub issue. Therefore they are encouraged for this type of inquiry.

Slack: See https://hpcng.org/ for invite (bottom of page)
Mailing List / Google Group: https://groups.google.com/a/lbl.gov/forum/#!forum/singularity

**Comment by zhanwenchen** [comment]
Same thing happened when running a script with PyTorch's `torchrun`:

```
^[[33mWARNING:^[[0m Could not lookup the current user's information: user: lookup userid 2911849: no such file or directory
^[[31mFATAL:  ^[[0m Couldn't determine user account information: user: lookup userid 2911849: no such file or directory
```

**Comment by dlejeune** [comment]
I'm sorry to bump such an old thread, but this is happening to me too on an HPC. I'm not entirely sure how to start debugging this, but I can provide some logs and such if that's helpful

**Comment by DrDaveD** [comment]
This repository is no longer active.  If you want to follow up, please open a new issue.  If `singularity --version` says `singularity-ce`, open a new issue at https://github.com/sylabs/singularity, otherwise open one at https://github.com/apptainer/apptainer.  Link back to this issue for background.

**Comment by bozki** [comment]
I also face the similar problem. It happens when I enter compute node.

in login node: I run 
(base) XXXX@podhead1:apptainer$ singularity --version
apptainer version 1.4.1

but if I salloc one gpu

then I want to use singularity, the error happen 
FATAL:   Couldn't determine user account information: user: unknown userid XXXXXXX

And I am not sure how to fix it

**Comment by DrDaveD** [comment]
This repository is closed.  Please post an issue on https://github.com/apptainer/apptainer.  It can reference this one if you think it's related.
