### ISSUE TITLE
Need to switch CircleCI docker tests to be authenticated

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#5602]
On the first of November, Docker is going to start rate-limiting pulls.  There are now [CircleCI instructions](https://circleci.com/docs/2.0/private-images/) on how to deal with it.  The singularity project needs an authenticated account, which can be passed through environment variables set in a CircleCI context that is only visible to the CircleCI project admin.  If we do nothing, the docker pulls will be tracked by IP address and would surely get hit by all the other projects sharing the same CircleCI cloud addresses.

singularity should probably be able to get away with a free authenticated account, which allows up to 200 pulls per 6 hours.  I see 5 docker pulls in the singularity .circleci/config.yml.  That would mean there would need to be an average of less than 7 per hour for every 6 hours, of pull requests or commits added to open pull requests.  Worst case, a pro account with unlimited pulls is only $60 per year.

@dctrud @ikaneshiro @cclerget @gmkurtzer

**Comment by ikaneshiro** [comment]
Opened #5673 to address this. The requirement for credentials within CI jobs comes with implications around trusting jobs running on forks. I included some thoughts on the PR:

> It is important to note that the CircleCI environment variables leveraged for credentials will not be passed to builds on forks. Users with commit access to this repository are considered trusted by CircleCI's trust model and exposing these variables within forks would allow anyone to expose or abuse these credentials.

>With that being said, the situation with CircleCI rate limiting of DockerHub pulls appears to be changing to prevent extreme CI disruption come the start of November(https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567). So, I have decided to not include logic to fail/skip jobs that require credentials on forks until we know when rate limiting will become a blocker for fork based CI jobs.

>Once/if rate limiting does become a blocker, users without commit access submitting PRs from forks will only be able to run a subset of tests that do not rely on DockerHub, like the short unit tests, and someone with commit access will need to bring shepherd their work into a branch within the repo, after an initial review, in order to be able to test against DockerHub.

I anticipate this will require more discussion/community messaging as pull rate limiting starts to be enforced, so I want to leave this issue open or open another to continue any required discussion.

**Comment by dtrudg** [comment]
Going to remove this from the 3.7.0 milestone as #5673 implements a good first defensive step against the rate limits, and it seems they won't really now hit us in the 3.7.0 timescale (as above).

**Comment by DrDaveD** [comment]
Does CircleCI have an option to allow these credentials to be used by anyone who submits a PR?

If so, I would argue that if the docker account is only used for this purpose, and it is a free docker account, that not a lot of harm would be done if somebody did tinker with a test script in a PR in such a way as to expose the username and password.  The worst they could do is denial of service, and we could always replace it with another free account.

**Comment by ikaneshiro** [comment]
@DrDaveD Since the limit for free accounts is 200 pulls per 6 hours, and we have ~40 docker pulls within the e2e tests themselves, we would hit this limit really fast. So the HPCng account used in CI will be paid come the start of the month in order to have unlimited pulls. There are options within CirlceCI to pass credentials to PR jobs running on forks, but since DockerHub doesn't have a way to grant "read only" access tokens for an account, exposure of the current credentials could cause harm and should be avoided.

**Comment by dtrudg** [comment]
Needs documentation for how to setup and run tests / which ones not to run.... use of short-unit / short-integration etc.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by DrDaveD** [comment]
This issue is no longer relevant.
