### ISSUE TITLE
Singularity instance stop by `--timeout` not worked

### ISSUE THREAD

**Issue by DechinPhy** [apptainer/singularity#5610]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version 3.6.3
```

### Expected behavior

When I run:
```bash
singularity instance start centos.sif instance1 && singularity instance stop --timeout 10 -a
```
And in another shell I would run:
```bash
singularity instance list
```
The expected result is that there could be one instance in singularity instance list, and after 10 seconds this instance would disappear.

### Actual behavior

There are no instances in singularity instance list during the 10 seconds.

**Comment by dtrudg** [comment]
This is the expected behaviour.

`instance stop` will _immediately_ try to gracefully stop an instance. The `--timeout` value is the time after which it will forcefully kill instances still running.

The `--timeout` is a timeout for the graceful `stop` operation, and not a delay.

```
  -t, --timeout int     force kill non stopped instances after X seconds
                        (default 10)
```

The behavior you are looking for would be supplied by

```
singularity instance start centos.sif instance1 && sleep 10 && singularity instance stop
```
