### ISSUE TITLE
New way to find free loop device

### ISSUE THREAD

**Issue by locula** [apptainer/singularity#5615]
### Version of Singularity:

What version of Singularity are you using?

```
$ singularity version
3.5.2-1.1.el7.20.deshaw
```

### Expected behavior

I expect that when looking for a free loop device, we should always be able to find one if there are free loop devices available.

### Actual behavior

What actually happened? Why was it incorrect?

Currently, if we run two containers at the same time and both containers are looking for a free loop device, they may both pick the same loop device thinking that it is free. In this case, the second containers fails because when it tries to use the loop device, it is already taken by the first container. To resolve this, we want to use LOOP_CTL_GET_FREE to get a new loop device. We also want to increase the maximum number of loop devices from 256 to 10,000 to accommodate for greater loop device usage.

**Comment by dtrudg** [comment]
> To resolve this, we want to use LOOP_CTL_GET_FREE to get a new loop device.

Hi @locula - the issue here is understood. However, as mentioned in comments on the #5614 that you opened, we are still currently supporting running on distros with a kernel <3.1, which is where `LOOP_CTL_GET_FREE` was introduced.

Also, the shared loop device cannot leverage `LOOP_CTL_GET_FREE`, and is a feature that a number of deployments are making use of, to share loop devices where they run many instances of the same container on a single machine.

If you would like to propose a change, please could you ensure the above is either accommodated, or you explain why you believe changes are appropriate.

> We also want to increase the maximum number of loop devices from 256 to 10,000 to accommodate for greater loop device usage.

As a default this would be a very large number, that probably doesn't make sense to have as a default. Most sites will not accumulate more than 256 loop devices on a machine, and larger than that number would likely indicate a problem somewhere. Please could you give more information, as an issue report, of the circumstances that require this very large number for your install.

Finally...

> $ singularity version
3.5.2-1.1.el7.20.deshaw

It looks like this is a version that has likely been customized in house at deshaw. Please could you make sure the issue occurs with the latest open source code, in version 3.6.4 without any modifications, and report here if true. It would be useful to show a simple way to replicate the problem with debug output too, so it can inform review of any code changes.

Thank you.

**Comment by locula** [comment]
> Hi @locula - the issue here is understood. However, as mentioned in comments on the #5614 that you opened, we are still currently supporting running on distros with a kernel <3.1, which is where `LOOP_CTL_GET_FREE` was introduced.

@dctrud Since the kernel version is an issue, we could include an #ifdef in the code to check the kernel version. This way, we can limit the change to only be compiled for newer kernels.

> As a default this would be a very large number, that probably doesn't make sense to have as a default. Most sites will not accumulate more than 256 loop devices on a machine, and larger than that number would likely indicate a problem somewhere. Please could you give more information, as an issue report, of the circumstances that require this very large number for your install.

We make use of some proprietary tools unrelated to Singularity that create a large number of loop devices, which is why we want to allow for more than 256 devices. Instead of changing the default maximum to 10,000, we could include the maximum number of loop devices as a constant in the config file. This will allow users to change the maximum number of devices allowed and use an arbitrary number of devices without any problem. Would a patch that adds the max loop devices constant to the config file be acceptable?

**Comment by dtrudg** [comment]
> > Hi @locula - the issue here is understood. However, as mentioned in comments on the #5614 that you opened, we are still currently supporting running on distros with a kernel <3.1, which is where `LOOP_CTL_GET_FREE` was introduced.
> 
> @dctrud Since the kernel version is an issue, we could include an #ifdef in the code to check the kernel version. This way, we can limit the change to only be compiled for newer kernels.

Compile time #ifdef macros don't really apply here. We are in the Go code rather than C for these changes, and we do want avoid breaking builds on one machine - > execution on a different machine if possible.

> > As a default this would be a very large number, that probably doesn't make sense to have as a default. Most sites will not accumulate more than 256 loop devices on a machine, and larger than that number would likely indicate a problem somewhere. Please could you give more information, as an issue report, of the circumstances that require this very large number for your install.
> 
> We make use of some proprietary tools unrelated to Singularity that create a large number of loop devices, which is why we want to allow for more than 256 devices. Instead of changing the default maximum to 10,000, we could include the maximum number of loop devices as a constant in the config file. This will allow users to change the maximum number of devices allowed and use an arbitrary number of devices without any problem. Would a patch that adds the max loop devices constant to the config file be acceptable?

The max loop devices is already present in the config file at 256 - I don't think we want to change that value as a default. However. If the config value is ignored in some parts of the code, so that increasing it doesn't work, then a patch to address that would be appropriate.

**Comment by locula** [comment]
> Compile time #ifdef macros don't really apply here. We are in the Go code rather than C for these changes, and we do want avoid breaking builds on one machine - > execution on a different machine if possible.

I understand that #ifdef macros don't apply in Go, so instead of this, we could use the kernel environmental variable to control runtime behavior. If we see that the kernel version is above 3.1, then we can use LOOP_CTL_GET_FREE to find a free loop device and otherwise, we can find free loop devices the way it is done currently. This way, even if the code is compiled on one machine and later switched to another, the build will not break since the changes will only be reflected at runtime based on the kernel version. Would this be an acceptable fix?

**Comment by dtrudg** [comment]
> > Compile time #ifdef macros don't really apply here. We are in the Go code rather than C for these changes, and we do want avoid breaking builds on one machine - > execution on a different machine if possible.
> 
> I understand that #ifdef macros don't apply in Go, so instead of this, we could use the kernel environmental variable to control runtime behavior. If we see that the kernel version is above 3.1, then we can use LOOP_CTL_GET_FREE to find a free loop device and otherwise, we can find free loop devices the way it is done currently. This way, even if the code is compiled on one machine and later switched to another, the build will not break since the changes will only be reflected at runtime based on the kernel version. Would this be an acceptable fix?

I would suggest not relying on the kernel version, as things are often backported into enterprise distributions that have a lower version number. Can you instead attempt to make a call, and fall back to the old method if it fails?

**Comment by locula** [comment]
> I would suggest not relying on the kernel version, as things are often backported into enterprise distributions that have a lower version number. Can you instead attempt to make a call, and fall back to the old method if it fails?

I have made these changes in https://github.com/hpcng/singularity/pull/5614
Here, I check to make sure that calling LOOP_CTL_GET_FREE does not return an error before using this function to find a free loop device. If this does throw an error, the code defaults to the previous method of finding a free loop device.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
