### ISSUE TITLE
Make execTimeout configurable

### ISSUE THREAD

**Issue by kpedro88** [apptainer/singularity#5653]
### Version of Singularity:

```
singularity version 3.6.3-1.el7
```

### Expected behavior

I expect `singularity instance start` to finish successfully. Because some commands may take longer than 5 seconds, making this timeout configurable (e.g. with a command-line argument) would be much nicer.

### Actual behavior

Sometimes, it fails with messages like this:
```
command "sed s/^$/unknown/" was killed after 5s timeout
```
or
```
command "/opt/mellanox/change_mofed_version.sh " was killed after 5s timeout
```

This requires retrying multiple times to get a successful start, which is tedious, and confusing for new users.

### Steps to reproduce this behavior

These are the commands I run (requires cvmfs):
```bash
mkdir lib
ln -s /cvmfs/unpacked.cern.ch/registry.hub.docker.com/fastml/triton-torchgeo:20.09-py3-geometric/opt/tritonserver/lib/* lib/
mkdir -p models
singularity instance start -B /dev/shm:/run/shm -B models:/models -B lib:/opt/tritonserver/lib -B /cvmfs /cvmfs/unpacked.cern.ch/registry.hub.docker.com/fastml/triton-torchgeo:20.09-py3-geometric triton_server_instance
```

### What OS/distro are you running

```
NAME="Scientific Linux"
VERSION="7.9 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.9"
PRETTY_NAME="Scientific Linux 7.9 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.9:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

### How did you install Singularity

RPM

**Comment by dtrudg** [comment]
This has been changed to a fixed 1 minute. The thinking is that this should be sufficient for any reasonable environment initialization, and we'd like to avoid added more user-configurable options unless absolutely necessary.

**Comment by vinjana** [comment]
> This has been changed to a fixed 1 minute. The thinking is that this should be sufficient for any reasonable environment initialization, and we'd like to avoid added more user-configurable options unless absolutely necessary.

The time needed for such an initialization may depend on many factors, including (temporary or permanent) issues with file-access latency, due to network or I/O load, etc. In multi-user environments these factors are about as uncontrollable for the individual Apptainer users as is the weather. I totally agree that the default should be short, but keeping this non-configurable renders Apptainer unusable for such users. And what is the problem of even waiting for 10 minutes if the container runs for many hours or longer? It is frustrating if you see it working in 25% of the jobs, but in 75% of your jobs the delay is just a little bit longer than the completely arbitrarily chosen cutoff.

**Comment by DrDaveD** [comment]
If you want to request this, please make a new issue.
