### ISSUE TITLE
Pass keys or keyserver config to remote builds with `Fingerprints:` check

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5695]
In #5659 we introduce the `Fingerprints:` header for fingerprint checks at the start of a build from a SIF image source.

At: https://github.com/hpcng/singularity/pull/5659/files/3f65227fac01ea71c97d993cda39daa248a2be21#diff-33ab3644155c3e8b9eaf936e4f1a4147d56816494880cc0dd22dd8c7a1ec6eb7R122

... note there is a TODO to pass the local keyserver config to the remote builder so that fingerprint checks work as in a local build. At present a remote builder using `Fingerprints:` will check them using the default keyserver config, not the remote or independent keyservers etc. that are configured on the calling user's machine.

Local keyrings (public keys) can also impact the verification... so would have to be conveyed somehow too.

I will document this limitation for the 3.7.0 release.

**Comment by dtrudg** [comment]
It has been pointed out by @tri-adam that of course it might be simpler to just retrieve the specified public keys locally, and pass them up. This has the advantage of a quick local failure if we can't get the public keys, also.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
