### ISSUE TITLE
root filesystem extraction failed: command error: while getting library dependencies: exit status 127

### ISSUE THREAD

**Issue by lucky110125** [apptainer/singularity#5711]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
3.6.4

### Expected behavior

What did you expect to see when you do...?
Activating singularity image /tmp/pytest_workflow_1hc6bkzr/test-qc-trio/.snakemake/singularity/05b71b45568ce53c6c5821005933b1d7.simg

### Actual behavior

What actually happend? Why was it incorrect?
[Mon Nov 16 10:11:14 2020]
rule cutadapt:
    input: test/data/fastq/R1.fq.gz, test/data/fastq/R2.fq.gz
    output: TestSample2/qc-seq/rg_2/TestSample2-rg_2-R1.fq.gz, TestSample2/qc-seq/rg_2/TestSample2-rg_2-R2.fq.gz
    jobid: 14
    reason: Missing output files: TestSample2/qc-seq/rg_2/TestSample2-rg_2-R2.fq.gz, TestSample2/qc-seq/rg_2/TestSample2-rg_2-R1.fq.gz
    wildcards: sample=TestSample2, read_group=rg_2

cutadapt -a AGATCGGAAGAG -A AGATCGGAAGAG --minimum-length=20 --quality-cutoff=20,20 --output=TestSample2/qc-seq/rg_2/TestSample2-rg_2-R1.fq.gz --paired-output=TestSample2/qc-seq/rg_2/TestSample2-rg_2-R2.fq.gz test/data/fastq/R1.fq.gz test/data/fastq/R2.fq.gz
INFO:    Convert SIF file to sandbox...
INFO:    Convert SIF file to sandbox...
INFO:    Convert SIF file to sandbox...
INFO:    Convert SIF file to sandbox...
FATAL:   while extracting /tmp/pytest_workflow_1hc6bkzr/test-qc-trio/.snakemake/singularity/05b71b45568ce53c6c5821005933b1d7.simg: root filesystem extraction failed: command error: while getting library dependencies: exit status 127
/usr/local/bin/unsquashfs: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory
 singularity exec --home /tmp/pytest_workflow_1hc6bkzr/test-qc-trio  --bind /xtdisk/wangqf_group/yanln/ENTER/envs/HAMLET/lib/python3.9/site-packages:/mnt/snakemake /tmp/pytest_workflow_1hc6bkzr/test-qc-trio/.snakemake/singularity/59882057c92bfa30461c1d25bb7465aa.simg bash -c 'set -euo pipefail;  cutadapt -a AGATCGGAAGAG -A AGATCGGAAGAG --minimum-length=20 --quality-cutoff=20,20 --output=TestSample2/qc-seq/rg_2/TestSample2-rg_2-R1.fq.gz --paired-output=TestSample2/qc-seq/rg_2/TestSample2-rg_2-R2.fq.gz test/data/fastq/R1.fq.gz test/data/fastq/R2.fq.gz'

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
I'm using [HAMLET pipeline](https://github.com/LUMC/HAMLET),when I test it by `pytest --kwd --tag functional`, there are troubles with the singularity.

### What OS/distro are you running

```
$ cat /etc/os-release


```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

conda

**Comment by lucky110125** [comment]
The version of unsquashfs is 4.3. Later I downgrading to singularity 3.6.3, there is new trouble:
FATAL:   while extracting /tmp/pytest_workflow_xr6i2sd9/test-qc-duo/.snakemake/singularity/05b71b45568ce53c6c5821005933b1d7.simg: root filesystem extraction failed: extract command failed: : fork/exec /usr/local/bin/unsquashfs: resource temporarily unavailable

**Comment by dtrudg** [comment]
@yanlina0205 - this may be fixed by a change that is in the `3.7.0-rc.2` release candidate version of Singularity. The cause is likely that a conda environment is in use for HAMLET, and library search is affected by this. In 3.7.0 a bugfix will clean the environment before it tries to find the libraries needed - so conda etc. should not interfere.

If you could let us know if it works with `3.7.0-rc.2` that would be great.

**Comment by lucky110125** [comment]
Thanks for your reply. I installed the 3.7.0-rc.2 release,but there are still some problems, which are different from before. The details are shown below:
[log.err.txt](https://github.com/hpcng/singularity/files/5559877/log.err.txt)
I'm looking forward to your reply, thanks.

**Comment by cclerget** [comment]
@yanlina0205 Based on :

```
root filesystem extraction failed: extract command failed: : fork/exec /usr/local/bin/unsquashfs: resource temporarily unavailable
```

and from the last log :

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
``` 

It means that you run out of your concurrent process/thread limit, you can check the value with `ulimit -u`, but looks like you are restricted to a pretty low number of processes/threads that you can execute concurrently, not a singularity issue, this is dependent of your environment setup by the admins and limits they applied.

**Comment by lucky110125** [comment]
OK, thank you. My concurrent process/threadI is only 100. I asked the administrator and he said that I need to rent a node separately to run this software. I will try it.

**Comment by marshals1999** [comment]
I also have the similar problem. I use singularity 3.7.1, which was installed by conda. I use singularity build --sandbox blast ubuntu_20.04.sif  in the conda base  environment, the information shows:
INFO:    Starting build...
INFO:    Verifying bootstrap image ubuntu_20.04.sif
WARNING: integrity: signature not found for object group 1
WARNING: Bootstrap image could not be verified, but build will continue.
ERROR:   unpackSIF failed: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found

I check the unsquashfs using which unsquashfs,  it shows that /usr/bin/unsquashfs. 
I use unsquashfs -v, it show unsquashfs version 4.3 (2014/05/12), it means that unsquashfs can be use in the system. 
then, I use ls -al /usr/bin/*squashfs, it show that 
-rwxr-xr-x 1 root root 189432 Jul  5  2018 /usr/bin/mksquashfs
-rwxr-xr-x 1 root root  98008 Jul  5  2018 /usr/bin/unsquashfs

I am very puzzled. 
Anyone can help me? Thank you very much!

**Comment by ikaneshiro** [comment]
Hi @marshals1999, this looks like a separate issue. Could you open a new issue and include the output of your build with debug output enabled? `singularity -d build ...`

Thanks

**Comment by marshals1999** [comment]
@ikaneshiro Thank you for your response. 
I use the  "singularity -d build --sandbox blast ubuntu_20.04.sif" , the information show that:
DEBUG   [U=1001,P=33064]   persistentPreRun()            Singularity version: 3.7.1
DEBUG   [U=1001,P=33064]   persistentPreRun()            Parsing configuration file /pub/anaconda3/etc/singularity/singularity.conf
DEBUG   [U=1001,P=33064]   handleConfDir()               /home/author/.singularity already exists. Not creating.
DEBUG   [U=1001,P=33064]   setValue()                    Updated flag 'tmpdir' value to: /home/author/singularity-env
DEBUG   [U=1001,P=33064]   getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=1001,P=33064]   Init()                        Image format detection
DEBUG   [U=1001,P=33064]   Init()                        Check for sandbox image format
DEBUG   [U=1001,P=33064]   Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1001,P=33064]   Init()                        Check for sif image format
DEBUG   [U=1001,P=33064]   Init()                        sif image format detected
DEBUG   [U=1001,P=33064]   Init()                        Image format detection
DEBUG   [U=1001,P=33064]   Init()                        Check for sandbox image format
DEBUG   [U=1001,P=33064]   Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1001,P=33064]   Init()                        Check for sif image format
DEBUG   [U=1001,P=33064]   Init()                        sif image format detected
DEBUG   [U=1001,P=33064]   newBundle()                   Created temporary directory "/home/author/singularity-env/bundle-temp-325135578" for the bundle
DEBUG   [U=1001,P=33064]   newBundle()                   Created directory "/hone3/project/comparative_genome/workspace/test_singularity/build-temp-087770535/rootfs" for the bundle
INFO    [U=1001,P=33064]   Full()                        Starting build...
DEBUG   [U=1001,P=33064]   Init()                        Image format detection
DEBUG   [U=1001,P=33064]   Init()                        Check for sandbox image format
DEBUG   [U=1001,P=33064]   Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1001,P=33064]   Init()                        Check for sif image format
DEBUG   [U=1001,P=33064]   Init()                        sif image format detected
DEBUG   [U=1001,P=33064]   GetLocalPacker()              Packing from SIF
INFO    [U=1001,P=33064]   verifySIF()                   Verifying bootstrap image ubuntu_20.04.sif
WARNING [U=1001,P=33064]   GetLocalPacker()              integrity: signature not found for object group 1
WARNING [U=1001,P=33064]   GetLocalPacker()              Bootstrap image could not be verified, but build will continue.
ERROR   [U=1001,P=33064]   Pack()                        unpackSIF failed: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found
DEBUG   [U=1001,P=33064]   cleanUp()                     Cleaning up "/hone3/project/comparative_genome/workspace/test_singularity/build-temp-087770535/rootfs" and "/home/author/singularity-env/bundle-temp-325135578"
FATAL   [U=1001,P=33064]   runBuildLocal()               While performing build: packer failed to pack: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found

other information:
$ singularity --version
singularity version 3.7.1

$ mount | grep /dev/shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)

$ ldconfig -p | grep libgcc_s
	libgcc_s.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcc_s.so.1
	libgcc_s.so.1 (libc6) => /usr/lib32/libgcc_s.so.1

$mount | grep rootfs  , no information show.

$ uname -a
Linux root123 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ which singularity unsquashfs ldd 
/pub/anaconda3/bin/singularity
/pub/anaconda3/bin/unsquashfs
/usr/bin/ldd

$ ldd $(which unsquashfs)
linux-vdso.so.1 (0x00007ffe70584000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffbd8b19000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffbd877b000)
	libz.so.1 => /pub/anaconda3/bin/../lib/libz.so.1 (0x00007ffbd8d8f000)
	liblzma.so.5 => /pub/anaconda3/bin/../lib/liblzma.so.5 (0x00007ffbd8d66000)
	liblzo2.so.2 => /pub/anaconda3/bin/../lib/liblzo2.so.2 (0x00007ffbd8538000)
	liblz4.so.1 => /pub/anaconda3/bin/../lib/liblz4.so.1 (0x00007ffbd8504000)
	libzstd.so.1 => /pub/anaconda3/bin/../lib/libzstd.so.1 (0x00007ffbd8445000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffbd8054000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffbd8d38000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffbd7e4c000)

I also try to use "$unset LD_LIBRARY_PATH; singularity build --sandbox blast ubuntu_20.04.sif", the problem is still there.

then I make a folder in my home directory named singularity-env, and add 
export SINGULARITY_TMPDIR=/home/author/singularity-env
export SINGULARITY_CACHEDIR=/home/author/singularity-env

to my .bashrc, the problem is not resolved.

Thank you again for you help!

**Comment by marshals1999** [comment]
The problem is resolved, and it is very simple. You need download the squashfs-tools (version>4.4). The download address is https://sourceforge.net/projects/squashfs/files/squashfs/  and then use the commond tar -zxvf squashfs4.4.tar.gz, subsequently, go to the working direction (cd  squashfs4.4/squashfs-tools ), finally, use the command make && sudo make install. It will be OK. Have a try.

**Comment by kw-cn** [comment]
I ran into the same bug, my Singularity version was 3.8.6, but Singularity showed an error.

ERROR:   unpackSIF failed: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found。
Have you solved the problem？
