### ISSUE TITLE
mounting with --fakeroot

### ISSUE THREAD

**Issue by alhirzel** [apptainer/singularity#5713]
### Version of Singularity:

```
$ singularity version
singularity version 3.6.4
```

### Expected behavior

I expect that with the `--fakeroot` option, I can mount a `proc` filesystem inside a container. I can do this successfully as a non-root user inside the container by enabling the capability (e.g. `singularity capability add --user alhirzel CAP_SYS_ADMIN`).

### Actual behavior

It appears the mount fails when `--fakeroot` is used, which is surprising.

### Steps to reproduce this behavior

```
$ singularity exec --add-caps CAP_SYS_ADMIN docker://alpine mount proc /tmp/proc -t proc
INFO:    Using cached SIF image
$ singularity exec --fakeroot --add-caps CAP_SYS_ADMIN docker://alpine mount proc /tmp/proc -t proc
INFO:    Using cached SIF image
INFO:    Convert SIF file to sandbox...
mount: permission denied (are you root?)
INFO:    Cleaning up image...
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### How did you install Singularity

`yay singularity-container` (from the AUR, which is the user-contributed package repository for Arch Linux).

### How did you install Singularity

**Comment by cclerget** [comment]
@alhirzel Since fakeroot use a user namespace therefore you have no control over the host namespaces for security reasons, with fakeroot you also don't need to manage capabilities (`--add-caps CAP_SYS_ADMIN`) as they are all set in the user namespace of fakeroot, so in order to make it works as expected you would need to create a new PID namespace by specifying `--pid` option in order to have permission within this namespace, the following works :

```
singularity exec --fakeroot --pid docker://alpine mount proc /tmp/proc -t proc
```

**Comment by alhirzel** [comment]
Hey @cclerget, thank you for your informative response! I don't know that I quite understand why `--pid` has the effect it does. Does the new PID namespace give permissions which cannot come from a user namespace alone, making the "added layer" necessary?

Also, what about this case? I don't mean to be a pain :)  I am trying to wrap `mkarchiso` and `pacstrap` on Arch Linux.

```
$ singularity exec --fakeroot --pid docker://alpine mount sys /tmp/sys -t sysfs
INFO:    Using cached SIF image
INFO:    Convert SIF file to sandbox...
mount: permission denied (are you root?)
INFO:    Cleaning up image...
```

**Comment by cclerget** [comment]
> Does the new PID namespace give permissions which cannot come from a user namespace alone, making the "added layer" necessary?

Yes, the user namespace is created first and subsequent created namespaces are associated to and owned by the user namespace therefore you have full permissions (to some extent) in those namespaces.

Regarding `sysfs` mount, it requires to create a network namespace as `/sys/class/net` reflect available network interfaces for the current network namespace and in your case this is the host network namespace where fakeroot has no right so it end up with a permission denied.
But your best option is probably to just bind mount `/sys` instead of mounting an instance to avoid permission denied errors.

**Comment by alhirzel** [comment]
Edit: I see the `--net` option but do run into the permissions issue you're indicating. I am trying to wrap an upstream script without patching it, but I could be at a dead-end. Here is the offending `chroot` setup: https://github.com/archlinux/arch-install-scripts/blob/master/common#L80

**Comment by dtrudg** [comment]
Closing this issue as it is a usage question that has been posted for 90 days and is not active.

For usage questions you are encouraged to use the Slack channel and/or mailing list which have a community of users present who will see and often kindly answer queries.

We close stale usage questions in order that the issues tracker can focus on problems that are bugs in Singularity, and feature requests.
