### ISSUE TITLE
E2E Registry image can trigger docker rate limits

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5716]
Even when #5715 is addressed, the registry image created by `PrepRegistry` can trigger docker hub rate limits. Its instance start script uses `img` to pull busybox down from docker hub, and push it into the local test registry. This invocation of `img` inside the registry container does not use credentials provided to the e2e tests.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
