### ISSUE TITLE
Singularity instance start doesn't recognize the --pid flag?

### ISSUE THREAD

**Issue by mapsacosta** [apptainer/singularity#5732]
### Version of Singularity:

```
Linux <host> 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.2$ singularity version
3.6.4-1.el7
```

### Expected behavior
Expected a Singularity **instance** to start with the same options as it would with singularity run:

The following won't work:
`singularity instance start --pid --ipc --contain --bind /etc/hosts [...] docker://somedockerimg`

Whereas a normal run command would: 
`singularity run --pid --ipc --contain --bind /etc/hosts [...] docker://somedockerimg`

### Actual behavior
The instance will not start and will complain about the pid flag. I noticed some flags were removed after 3.6.5, is there a particular reason why?: 
```
-bash-4.2$ singularity instance start --pid --ipc --contain --bind /etc/hosts [...] docker://somedockerimg
Error for command "start": unknown flag: --pid
```

**Comment by dtrudg** [comment]
See - https://github.com/hpcng/singularity/pull/5037

The `--pid` and `--ipc` namespaces are always used for instances. These flags were previously allowed, but they had no effect since pid and ipc namespaces were already enabled. They were removed as options in singularity 3.6, as having the flags present suggested they were optional, when they were not.

**Comment by mapsacosta** [comment]
Got it, thanks @dctrud !
