### ISSUE TITLE
Using bind-mounts breaks cascaded singualrity container

### ISSUE THREAD

**Issue by rcaspart** [apptainer/singularity#5766]
The changes introduced with  #5670 and included in singularity 3.7.0 break running a singularity container within a singularity container in certain cases. This happens when a bind-mount with a different target than source path is specified for the outer container and the source path is not existing in the container. This breaks since the `SINGULARITY_BIND` variable available in the outer container includes the binds-mounts for the outer container and also gets evaluated for the inner container.

Our use case requiring cascaded singularity container is described in #5759 .

### Version of Singularity:

`3.7.0-el7`

### Expected behavior

Singularity container can be started within other singularity container. Bind-mounts specified for the outer container do not propagate to the inner one.

### Actual behavior

Starting the inner singularity container fails, since singularity tries to perform the bind-mounts of the outer-container, which are present in the `SINGULARITY_BIND` variable within the container, also for the inner container.

```
singularity shell --bind /home/ceph:/srv docker://matterminers/wlcg-wn
INFO:    Using cached SIF image
Singularity> echo $SINGULARITY_BIND 
/home/ceph:/srv
Singularity> singularity shell docker://matterminers/wlcg-wn
WARN[0000] "/run/user/0" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/0: no such file or directory: Trying to pull image in the event that it is a public image. 
INFO:    Using cached SIF image
FATAL:   container creation failed: mount /home/ceph->/srv error: while mounting /home/ceph: mount source /home/ceph doesn't exist
Singularity>
```

### Steps to reproduce this behavior

Bind-mount a directory, that is not existing in the container, into a singularity container at a different target.
Start a second singularity container within the first one.

### What OS/distro are you running

Scientific Linux 7.9 (Nitrogen)

### How did you install Singularity

From EPEL repository

**Comment by dtrudg** [comment]
One of the goals of #5670 was to re-introduce the behavior of prior versions of Singularity, where binds set on the host via `SINGULARITY_BIND` as an environment variable are passed into the container. Because this was addressing a regression I don't think it is likely we will revert it completely.

The inclusion of `-B/--bind` arguments in the inner `SINGULARITY_BIND` value is new, but even if that is removed you would still need to account for the pass through of an binds set in the env var on the host to be safe.

The suggested workaround here would be to unset SINGULARITY_BIND in the outer images used in nested environments. Unless this is a widespread issue occurring outside of the WCLG deployments I don't think this is something that would be considered urgent to roll back at this point.

_Edit_ - perhaps we could have some detection of the nest and reset it manually.

**Comment by dtrudg** [comment]
Please see also the comments at: https://github.com/hpcng/singularity/issues/5759#issuecomment-747493218

We'll keep an open mind and consider a (partial) roll back if it is indeed causing more harm than benefit, but the best way to ensure Singularity supports complex nested / middleware setups is to contribute test cases for the e2e testing suite, so that changes affecting such behavior are automatically identified.

**Comment by giffels** [comment]
Maybe a command line option to ignore settings in `SINGULARITY_BIND` would be a reasonable compromise? What do you think?

**Comment by dtrudg** [comment]
@giffels - that would be fine, yes. If you are able to provide a PR we could turn that around quickly. We might want to use the  `--no-mount ` flag added in 3.7.0 to avoid additional things.... maybe `--no-mount env` to ignore the binds via env var.

**Comment by giffels** [comment]
@dctrud sure. I took a look into the code and I doubt that `--no-mount env` will work without major code changes. The reason is that you already append the `SINGULARITY_BIND` environment variable to the bind path during parsing the command line arguments.

https://github.com/hpcng/singularity/blob/e66ae656a0603e7f9c5562ccb87d6df8aee0c720/cmd/internal/cli/action_flags.go#L83-L94

Therefore, I would propose to use a different command line option like `--no-env bind` or `--no-env-bind` and place a conditional in front of 

https://github.com/hpcng/singularity/blob/e66ae656a0603e7f9c5562ccb87d6df8aee0c720/cmd/internal/cli/actions_linux.go#L416

What do you think about that approach? I would volunteer to provide a PR for that.

**Comment by dtrudg** [comment]
@giffels - I'll look into it a bit. I would prefer to make the inner singularity ignore the env var rather than add a new flag so the outer singularity does not set it.

I don't know that the latter is needed as it's almost as easy to use `--env SINGULARITY_BIND=""` (which already exists) for the same practical outcome due to the env var precedence that we have:

```
dave@dev-fedora~> export SINGULARITY_BIND=/tmp,/lalala

dave@dev-fedora~> singularity run docker://alpine env | grep SINGULARITY_BIND
INFO:    Using cached SIF image
SINGULARITY_BIND=/tmp,/lalala

dave@dev-fedora~> singularity run --env SINGULARITY_BIND="" docker://alpine env | grep SINGULARITY_BIND
INFO:    Using cached SIF image
SINGULARITY_BIND=
```

Is this workaround actually suitable for your needs?

**Comment by giffels** [comment]
@dctrud : Oh great. Yes, that workaround is very suitable for our needs. Thanks!
