### ISSUE TITLE
hardcoded GOPROXY

### ISSUE THREAD

**Issue by smallzzy** [apptainer/singularity#5770]
### Version of Singularity:
master

### Expected behavior

GOPROXY should be set by user.

### Actual behavior

GOPROXY is set to https://proxy.golang.org in file "mlocal/frags/go_common_opts.mk"
Which cause the compilation to timeout if a proxy is needed.

### How did you install Singularity

source

**Comment by smallzzy** [comment]
In a similar way, I doubt if the goproxy needs to be exported in "makeit/gengodep"

**Comment by dtrudg** [comment]
#5775 (failure to install in china) is related to this and will be tackled generally here.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
