### ISSUE TITLE
Containerised defined LD_LIBRARY_PATH is lost when using SINGULARITYENV_LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by AlexisEspinosaGayosso** [apptainer/singularity#5781]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.4
```

### Expected behavior

In previous versions, the definition of `SINGULARITYENV_LD_LIBRARY_PATH` was appended to the containerised definition of `LD_LIBRARY_PATH`. That is how it's working for version 3.5.3. For 3.6 and 3.7 I was expecting the appending behaviour.

### Actual behavior

Now with 3.6.4 (and also tested with 3.7.0), the definition of `SINGULARITYENV_LD_LIBRARY_PATH` OVERRIDES the containerised definition instead of appending.
What is the Sylabs intended behaviour? Overriding or appending? In my opinion, it should continue to be appending.

### Steps to reproduce this behavior

Use this simple definition file:
```
Bootstrap: docker
From: centos:7

%environment
export FOO=foo
export PATH=/foo/bin:$PATH
export LD_LIBRARY_PATH=/foo/lib:$LD_LIBRARY_PATH
```

set the environment in the host:
```
host> export SINGULARITYENV_LD_LIBRARY_PATH=/usr/lib64
host> echo $SINGULARITYENV_LD_LIBRARY_PATH 
/usr/lib64
```

and check the environment inside the container:

```
host> singularity exec testLD_LIBRARY_PATH.sif printenv LD_LIBRARY_PATH
/usr/lib64:/.singularity.d/libs
```
As can be seen, the `/foo/lib` is lost.

(When using the older version 3.5.3, the result is: "/foo/lib:/usr/lib64:/.singularity.d/libs", i.e. appending)

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"
```

### How did you install Singularity

Installed from source. (https://github.com/PawseySC/maali-cygnet/blob/master/sles12sp3/singularity.cyg)

**Comment by dtrudg** [comment]
This is the expected behavior. Environment variable handling was re-written in 3.6 to be more internally consistent, and establish a fixed precedence. Previously there had been various small changes across many singularity versions, and inconsistency (e.g. append for some variables vs override for others etc.)

Hinted at in the changelog for 3.6.0:

> Environment variables prefixed with SINGULARITYENV_ always take precedence over variables without SINGULARITYENV_ prefix.

There is full documentation of the precedence etc. at:

https://sylabs.io/guides/3.7/user-guide/environment_and_metadata.html

Note that prior to the release of 3.6.0 proposals were set out and comments sought via slack, the mailing list, and community meetings. The history of that discussion can be found at: https://github.com/hpcng/singularity/issues/5040

**Comment by AlexisEspinosaGayosso** [comment]
Thanks for your prompt response and clarification.
Then, in order to keep appending, the preferred solution is to use `$LD_LIBRARY_PATH` within the definition of `SINGULARITYENV_LD_LIBRARY_PATH`, am I right? (escaping the `$` if needed):
```
host> export SINGULARITYENV_LD_LIBRARY_PATH="/usr/lib64:\$LD_LIBRARY_PATH"
host> echo $SINGULARITYENV_LD_LIBRARY_PATH 
/usr/lib64:$LD_LIBRARY_PATH
```

and check environment inside the container:
```
host> singularity exec testLD_LIBRARY_PATH.sif printenv LD_LIBRARY_PATH
/usr/lib64:/foo/lib::/.singularity.d/libs:/.singularity.d/libs
```
Now initial containerised definition is preserved by appending.
