### ISSUE TITLE
Refactor Remote Build Handling Code

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5786]
The code that handles the CLI / CLI adjacent parts of submission of remote builds is in need of a refactor.

1. We are constructing a struct of build args in upper-level CLI code, but then passing individual values into lower-level remote build functions with large signatures:

https://github.com/hpcng/singularity/blob/55a4fbff3ca3e0e0bef02f937d99adc2b193771c/cmd/internal/cli/build_linux.go#L213

2. We have some need in the lower level code to know whether service URIs were overridden with flags, to optimize messages to the user (see https://github.com/hpcng/singularity/pull/5785#pullrequestreview-563770820). On this line we don't need `--library` in the instructional message if the user is not overriding the library URL via flag:

https://github.com/hpcng/singularity/blob/55a4fbff3ca3e0e0bef02f937d99adc2b193771c/internal/pkg/build/remotebuilder/remotebuilder.go#L108

The code doesn't have access to this information. Likely this message logic should be higher in the CLI. Otherwise the required information about flags set/unset needs to be passed.

More generally, code to fetch configurations for service clients seems a little oddly placed, such as:

https://github.com/hpcng/singularity/blob/master/cmd/internal/cli/singularity.go#L589

This is all tied into how the current remote information is handled and kept in a private var `currentRemoteEndpoint`. 

It would probably be good to restructure the flow in which service URIs are discovered from remote configuration and optional flags, so that it is more clear.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
