### ISSUE TITLE
Cant find file when executing python script from a container

### ISSUE THREAD

**Issue by pavaninguva** [apptainer/singularity#5798]
### Version of Singularity: 

3.7.0 

### Expected behavior

Upon running the following command to execute a script: 
```
singularity exec ./ocellaris_2019.0.2.sif python foo.py
```

It should run foo.py

### Actual behavior

Upon running, i get the following error: 

```
/usr/bin/python: can't open file 'foo.py': [Errno 2] No such file or directory
```

### Steps to reproduce this behavior

I have tested the if singularity is functional by using the lolcow mwe and I am able to execute that just fine with ```singularity exec``` etc. I have also naively run the script by typing `python foo.py` and it executes normally. 

### What OS/distro are you running

Ubuntu-18.04 on WSL2

### How did you install Singularity

Downloaded and built from the github release page per https://sylabs.io/guides/3.7/user-guide/quick_start.html

**Comment by pavaninguva** [comment]
Hi, just saw the new `NeedsMoreInfo` tag. Ive also run the set of commands on a pure linux machine running singularity 3.6 and encountered the same issue. When I downgraded to Singularity 3.2.0-1 on the pure linux machine, I am able run my script normally using `singularity exec`. 

Please let me know what I should run to provide additional diagnostic info that would be useful. It seems that while Singularity 3.2.0-1 solves my problem on pure linux, it does not like WSL2 as I get the squashfs file system error: 
```
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument
```

**Comment by dtrudg** [comment]
The error with 3.2 in WSL2 is because 3.2 does not support newer kernels. There is a fix for the squashfs options passed to the kernel in later version of Singularity.

```
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error:
```

If there is an issue with 3.7 it is likely due to environment handling that has changed since version 3.2. You will need to look at the definition from which the container is built, with reference to the guide:

https://sylabs.io/guides/3.7/user-guide/environment_and_metadata.html

To give any further input we'd need to the definition / source of the container, and details of where this file is on the system, which filesystems are mounted to the container etc.

**Comment by dtrudg** [comment]
Actually... this may be the issue:

From the change log for 3.6:

> Restored the CWD mount behaviour of v2, implying that CWD path is not recreated inside container and any symlinks in the CWD path are not resolved anymore to determine the destination path inside container.

If your current working directory is not a directory that is present in the container through another mount, then it won't explicitly be created in the container for 3.6 and 3.7. You would need to ensure you bind mount the location into the container.

This change was made due to the extreme complexity of handling symlinks, overlapping mounts etc, which made automatic CWD creation in the container impossible to implement consistently.

**Comment by dtrudg** [comment]
The above comment is likely the issue. If it doesn't explain the problem and you believe there is a bug, please feel to reopen the issue.
