### ISSUE TITLE
Reading large h5 files in parallel under singularity under a cgroup with insufficient memory results in long delay/hang

### ISSUE THREAD

**Issue by gmgithub122** [apptainer/singularity#5800]
### Version of Singularity:

```
$ singularity --version
2.4.2-dist
```

### Expected behavior

Reading large h5 files in parallel under singularity under a cgroup with insufficient memory should be OOMed immediately.

### Actual behavior

Reading large h5 files in parallel under singularity under a cgroup with insufficient memory results in long delay/hang.

### Steps to reproduce this behavior

Clone: https://github.com/gmgithub122/sing_mem_hang
Copied from README:

Steps to reproduce:

1. Create cgroup with 1GB memory limit.
```
$ sudo ./create_cg <USER> <GROUP>
``` 
2. Write singularity container from `minimal.def` to `/tmp/minimal.sif`.
```
$ sudo ./create_sing.sh
```
3. Write large h5 file to `/tmp/8GB.h5`.
```
python write_h5.py
```
4. Write large binary file to `/tmp/8GB.bin`.
```
./write_bin.sh
```
5. Run 10 parallel `read_bin.py` under the cgroup.
```
$ time ./cg_bin_loop.sh
# intermediate output omitted
real    0m48.193s
user    0m0.127s
sys     1m10.643s
```
6. Run 10 parallel `read_h5.py` under the cgroup.
```
$ time ./cg_h5_loop.sh
# intermediate output omitted
real    0m58.077s
user    0m14.772s
sys     1m12.767s
```
7. Run 10 parallel `read_bin.py` under singularity under the cgroup.
```
$ time ./cg_sing_bin_loop.sh
# intermediate output omitted
real    0m48.932s
user    0m0.364s
sys     1m16.328s
```
8. Run 10 parallel `read_h5.py` under singularity under the cgroup.
```
$ time ./cg_sing_h5_loop.sh
# intermediate output omitted
real    4m37.325s
user    0m13.924s
sys     20m44.424s
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

```
sudo apt install singularity-container
```

**Comment by dtrudg** [comment]
Singularity 2.x is unsupported. Please replicate under the current 3.7 version.

The exact kernel version is also important to know, as we are aware of some cgroup memory handling issues on older kernel versions.

**Comment by gmgithub122** [comment]
Thanks for the quick response!

Kernel version:
```
$ uname -r
4.15.0-99-generic
```

I reproduced the problem with the latest version (after building and installing it):
```
$ singularity --version
singularity version 3.7.1
```

Please advise.

**Comment by dtrudg** [comment]
I believe this is the issue related to a bad interaction between cgroup memory limits and the kernel squashfs filesystem (which Singuarity uses). We have previously observed an issue that leads to freezes like you describe on RHEL 7 (3.10 series kernel), but not on RHEL 8 (4.18 series kernel), nor much newer kernels (under Fedora, Ubuntu 20.04 etc.).

Since you are on the original 4.15 series kernel in Ubuntu 18.04 I would suspect the same issue. To narrow it down, could you:

1. Run the same procedure, but use a sandbox (directory) container for Singularity, instead of the SIF file. If I'm correct, you will not see a hang when running the contained process with cgroups, but from a sandbox.
2. Try the same procedure on a machine that has been updated to the newer HWE kernel provided by 18.04.4 - I believe it's a 5.3 series kernel.

**Comment by gmgithub122** [comment]
1. Fixed it

Getting a new kernel up and going will require a bit more work, but I will be sure to comment here after we can test it. Thank you for diagnosing this so quickly!

**Comment by gmgithub122** [comment]
Unfortunately upgrading the kernel did not fix it.

```
$ uname -r
5.4.0-53-generic
```

```
$ time ./cg_sing_h5_loop.sh
# intermediate output omitted
real    3m5.286s
user    0m2.554s
sys     16m15.267s
```

**Comment by dtrudg** [comment]
Okay, thanks. That's somewhat unexpected given our previous reproducer was okay on RHEL8. Will add this to a list to examine further.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
