### ISSUE TITLE
Does --fakeroot require sandbox ?

### ISSUE THREAD

**Issue by kimchitsigai** [apptainer/singularity#5801]
### Version of Singularity:
```
$ singularity version
3.6.4
```

### Actual behavior

When I run 
```
singularity shell --fakeroot my.sif
```
the output is:
```
INFO:    Convert SIF file to sandbox...
ERROR  : Failed to create container process: No space left on device
```
First question: Is the sif to sandbox conversion done by design ? Or is it due to my configuration ?
Without  --fakeroot, singularity does not convert the sif to a sandbox.

Second question: Which space has no space left? I've configured SINGULARITY_CACHEDIR to point on a directory wth sufficient space, but there are still files created in ~/.singularity/cache 

### Steps to reproduce this behavior
```
$ singularity shell --fakeroot my.sif
```
my uid(gid) is in /etc/subuid(gid)

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"
```

### How did you install Singularity

Installed from source by root with setuid set

**Comment by dtrudg** [comment]
> First question: Is the sif to sandbox conversion done by design ? Or is it due to my configuration ?
Without --fakeroot, singularity does not convert the sif to a sandbox.

Conversion to a sandbox is required for running in a user namespace or with fakeroot. The conversion is by design as mounting from a SIF file requires privilege.

> Second question: Which space has no space left? I've configured SINGULARITY_CACHEDIR to point on a directory wth sufficient space, but there are still files created in ~/.singularity/cache

Check the debug output with `singularity -d ...` for more information. Also please  update to a current `3.7.1` version of Singularity to see if the issue is resolved. if `SINGULARITY_CACHEDIR` is still being ignored, please file a detailed bug report of exactly how you run singularity, and the debug output given.

**Comment by kimchitsigai** [comment]
Thank you for the answers.
I've  found the answer to my second question. The cause of the error message ('no space left on device') was that the node on which I was running the test hadn't  max_user_namespaces configured. I was fooled by the error message.
