### ISSUE TITLE
 How to add port in Singularity

### ISSUE THREAD

**Issue by Rexmiao** [apptainer/singularity#5814]
### Version of Singularity: 3.5

What version of Singularity are you using? Run:

```
Bootstrap: docker
From: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
IncludeCmd: yes

%setup

#%files
#	./cuda_10/requirements.txt
#    ./cuda_10/requirements.txt /opt/quick_annotator/requirements.txt
#	. 
#	. /opt/quick_annotator

%post
  	apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         ca-certificates \
         libglib2.0-0 \
         libjpeg-dev \
         libpng-dev \
         python3 \
         python3-pip \
         python3-wheel \
         python3-setuptools \
         sqlite3 \
         libsqlite3-dev\
		 gcc gfortran libopenblas-dev liblapack-dev cython\
		 git
    
	git clone https://github.com/choosehappy/QuickAnnotator.git
	
	cd QuickAnnotator
#	docker build -t quick_annotator -f cuda_10/Dockerfile .
	
	cd QuickAnnotator/cuda_10
	pip3 install -U pip
	pip3 install -r requirements.txt


%environment
	DEBIAN_FRONTEND=noninteractive

   PORT=5739


%runscript
   python3 QA.py
#   docker run --gpus all -p 5739:5739 quick_annotator


```

### Actual behavior

In the docker file, we have [-p] tag to set the port number of a Flask Application.
What should I do if I want to set a port number for a flask web application delivered by Singularity?

**Comment by dtrudg** [comment]
Singularity uses the host networking by default. You do not need to specify a port to map. If the flask application runs on port 5379 in the container, then it will be available as port 5379 on the host.

As this is an application usage question rather than a bug report or feature request I would suggest using the slack channel or mailing list if you require further assistance.

See: https://sylabs.io/resources/community
