### ISSUE TITLE
/dev/urandom (or equivalent) not found when compiling ROS

### ISSUE THREAD

**Issue by nordmoen** [apptainer/singularity#583]
Trying to compile a [ROS](http://ros.org/) project inside a Singularity images leads to the following error message:
```bash
+ catkin_make
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_make", line 14, in <module>
    from catkin.builder import cmake_input_changed
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/builder.py", line 36, in <module>
    import multiprocessing
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 64, in <module>
    from multiprocessing.process import Process, current_process, active_children
  File "/usr/lib/python2.7/multiprocessing/process.py", line 312, in <module>
    _current_process = _MainProcess()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 309, in __init__
    self._authkey = AuthenticationString(os.urandom(32))
NotImplementedError: /dev/urandom (or equivalent) not found
```

**Comment by vsoch** [comment]
Hey @nordmoen ! I was just playing around with this, and I think it has something to do with the software using chroot and then [not having those spaces mounted](https://superuser.com/questions/165116/mount-dev-proc-sys-in-a-chroot-environment). So fix 1, you could try mounting them. Another thing I noticed is that updating mkinitrd might fix the issue, but [this is different on ubuntu](https://www.cyberciti.biz/faq/read_urandom-devurandom-open-failed-no-such-file-or-directory/).

You probably want do compile from source, so you may not like this answer, but is there a reason to not bootstrap the ros docker image to start? Eg:

```bash
singularity create --size 4000 ros.img
singularity import ros.img docker://ros:latest
singularity shell ros.img
```

It looks like the ros entrypoint is successfully passed to the runscript:

```bash
Singularity ros.img:/> cat /.singularity.d/runscript
#!/bin/sh

exec /ros_entrypoint.sh "$@"
```
and ros is under opt:

```bash
ls /opt/ros/kinetic
bin	etc	 lib	     setup.sh	     setup.zsh
env.sh	include  setup.bash  _setup_util.py  share
```

Now if only I knew how to make a robot!

Granted that the Docker images are maintained, you would be able to (literally) bootstrap that work for your singularity image, and not have to maintain updates yourself. If there are bugs with configuration, you could start with this as a bootstrap base, and tweak as needed, eg here is the bootstrap file

```
Bootstrap:docker
From: ros:latest

%post

apt-get update && apt-get install.... [etc]
```

then

```
singularity create --size 4000 ros.img
sudo singularity bootstrap ros.img Singularity
```

I just tested this now, (note using the development branch) and it seems to start up ok, although I'm not exactly sure how to make my robot. Anyway, how about give that a start, and go from there?

**Comment by nordmoen** [comment]
Thanks for the quick reply yet again!

I am boostrapping the image from docker. The reason I am compiling is to build my own project into a Singularity image which I am then going to run to perform my experiments. I boostrap from `docker://ros:kinetic-perception` which work. Then copy my project into a [workspace](http://wiki.ros.org/catkin/Tutorials/create_a_workspace) and compile (which leads to the problem above).

I realise I have given you way to little to go on in the bug description so I will try to make a small build to reproduce the issue.

**Comment by vsoch** [comment]
yes that would be fantastic! I was trying to build my own bootstrap file and then realized I had no idea what I was doing, haha. Just FYI I will likely get a chance to look later today, so no rush.

**Comment by nordmoen** [comment]
Here is a minimal example with code from the official [ROS tutorial](https://github.com/ros/ros_tutorials)

```bash
Bootstrap: docker
From: ros:kinetic-perception

%setup
        # This is done before we are "inside" container

        # We first create our workspace folder
        mkdir -p $SINGULARITY_ROOTFS/workspace/src
        # Then copy our code into this workspace
        cd $SINGULARITY_ROOTFS/workspace/src
        git clone https://github.com/ros/ros_tutorials.git

%post
        # This is executed inside container
        . /opt/ros/kinetic/setup.sh
        cd /workspace/src
        catkin_init_workspace
        # Then it is time to build everything
        cd /workspace
        catkin_make
        catkin_make install

%runscript
        cd /workspace
        source /workspace/devel/setup.bash
```

This exhibit the same problem as mentioned in this issue. Note that the build could probably use any of the `ros:kinetic` images, I simply copied my build from before and stripped it out.

This is also the way to compile ROS projects. E.g. this [listener](https://github.com/ros/ros_tutorials/blob/lunar-devel/roscpp_tutorials/listener/listener.cpp) is a [node](http://wiki.ros.org/Nodes) which must be compiled to run. The listener mentioned comes from [this tutorial](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29) which explains how some of the core concepts in ROS functions.

**Comment by nordmoen** [comment]
To add some context.

This is what anyone doing ROS inside Singularity would have to do. Unless you are building a full docker image (which I didn't want to do because our cluster only supports Singularity) you have to perform the compile step inside Singularity.

The steps with ROS is, [create a workspace](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment), [create a package](http://wiki.ros.org/ROS/Tutorials/CreatingPackage), [build](http://wiki.ros.org/ROS/Tutorials/BuildingPackages) and run. By doing the compile step during build the image is much quicker to deploy and so I found it natural to place there.

**Comment by vsoch** [comment]
thanks for the details - I will take a look later today.

**Comment by vsoch** [comment]
Hey! Apologies for the delay - I had some unexpected badness happen yesterday that sent me through a spin, and I'm still catching up with stuffs.

I just tested your build spec, and interestingly the first thing I noticed is that the commands work when you run them via shell (after) initially creating the image. This means that the bug is that something that happens after the `%post` scriptlet needs to be done before it. So first, to test this, I made the following spec file:

```
Bootstrap: docker
From: ros:kinetic-perception

%setup
        # This is done before we are "inside" container

        # We first create our workspace folder
        mkdir -p $SINGULARITY_ROOTFS/workspace/src
        # Then copy our code into this workspace
        cd $SINGULARITY_ROOTFS/workspace/src
        git clone https://github.com/ros/ros_tutorials.git

%post
        # This is executed inside container
        apt-get update && apt-get install -y vim
        . /opt/ros/kinetic/setup.sh
        
%runscript
        . /opt/ros/kinetic/setup.sh
        cd /workspace/src
        catkin_init_workspace
        cd /workspace
        catkin_make
        catkin_make install
        /bin/bash /workspace/devel/setup.bash
```

meaning that the compilation stuffs would happen at runtime, and we would have to use sudo with writable. So first create and bootstrap:

```
singularity create --size 4096 ros.img
sudo singularity bootstrap ros.img ros.def
```
where

```
sudo singularity run --writable ros.img
```

and that actually works to at least get it compiled. But it's not ideal, because you have this extra step (that needs sudo) that really should be done with standard bootstrap.

The better approach would be to figure out what needs to be fixed to get it working in post. The first thing that happens is [here](https://github.com/singularityware/singularity/blob/development/libexec/bootstrap-scripts/deffile-sections.sh#L151) and the final chunk of stuff is [here](https://github.com/singularityware/singularity/blob/development/libexec/bootstrap-scripts/post.sh#L45). It it's not something there, then it's something that happens with regard to mounting at runtime, and we could likely mimic that as well during post.

I have to start making dinner, but I'll keep playing around with this later and likely tomorrow morning - just wanted to share with you some progress! I definitely think we will figure out this bug, or at least a workaround.

**Comment by vsoch** [comment]
ah I got it!  Will post in a sec.

**Comment by vsoch** [comment]
ok this should do the trick - here is the build spec, called `Singularity`:

```
Bootstrap: docker
From: ros:kinetic-perception

%setup
        # This is done before we are "inside" container
        # We first create our workspace folder
        mkdir -p $SINGULARITY_ROOTFS/workspace/src
        # Then copy our code into this workspace
        cd $SINGULARITY_ROOTFS/workspace/src
        git clone https://github.com/ros/ros_tutorials.git

%post
        apt-get update && apt-get install -y vim &&
        . /opt/ros/kinetic/setup.sh
        test -L "/etc/mtab"  && rm -f "/etc/mtab"
        cd /dev && /sbin/MAKEDEV std
        cd /workspace/src
        catkin_init_workspace
        cd /workspace
        catkin_make
        catkin_make install

%runscript
        cd /workspace
        /bin/bash /workspace/devel/setup.bash
```

and then:

```
singularity create --size 4096 ros.img
sudo singularity bootstrap ros.img Singularity
```

it was a very stupid debugging. I just did an ls for `/`, and then for `/dev` and then saw the only thing there was `null`. Then I searched for how to create the junk in `/dev` and found [this page](http://serverfault.com/questions/91675/dev-random-is-missing-after-an-upgrade) with the instruction to make those files. Then it just seemed to work? Reading that post, it sounds like `/udev` is used to dynamically populate that folder. I would look closely at [this post](http://serverfault.com/a/91739) and see if you can do the same, because according to it, not using udev has some kind of future consequences? Anyway this is an ok first fix, and I would give a shot at using udev. Give it a test and let me know!

**Comment by gmkurtzer** [comment]
A few days ago, I changed things such that the host's `/dev` file system is bound into the container during bootstrap. Can you check this and see if the latest 'development' branch just works now?

Thanks!

**Comment by nordmoen** [comment]
Sorry for the late reply, public holiday. Pulling in the latest development branch worked. Thanks for the help both of you!

**Comment by vsoch** [comment]
ok great! I'll close the issue. Please re-open if necessary... and share if /when you make a cool robot! :_)
