### ISSUE TITLE
Research: better support with IB

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5832]
CtrlIQ roadmap item: https://docs.google.com/document/d/1mEjRmwOfFXiz4U5uPQ6paa-h3jDgMeGoxM5PPs6r8SI

**Comment by ikaneshiro** [comment]
@dtrudg This will not be completed by the end of the 3.8 milestone and will need to slip into the future

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
