### ISSUE TITLE
Cannot login with tokenfile to oras registry

### ISSUE THREAD

**Issue by dcsouthwick** [apptainer/singularity#5838]
### Version of Singularity: 

`3.7.1-1.el7`

### Expected behavior

singularity 3.7+ should use tokenfiles, and accept "no input" for username, as is written in the help info:

```
$ singularity remote login --help
Options:
  -h, --help               help for login
  -i, --insecure           allow insecure login
  -p, --password string    password to authenticate with
      --password-stdin     take password from standard input
      --tokenfile string   path to the file holding token
  -u, --username string    username to authenticate with (leave it empty
                           for token authentication)

singularity remote login --tokenfile ./path/to/credentials.token oras://registry.domain.com
INFO:    Token stored in /home/dsouthwi/.singularity/remote.yaml
```

### Actual behavior

What actually happend? Why was it incorrect?
**You cannot specify an empty user with --tokenfile argument.**
```
$ singularity remote login --tokenfile ./harbor.token oras://registry.domain.com
FATAL:   while login to oras://registry.domain.com: Docker/OCI registry requires a username

$ singularity remote login -u --tokenfile ./harbor.token oras://registry.domain.com
Error for command "login": accepts between 0 and 1 arg(s), received 2

$ singularity remote login -u "" --tokenfile ./harbor.token oras://registry.domain.com
FATAL:   while login to oras://registry.domain.com: Docker/OCI registry requires a username
```

### What OS/distro are you running

```
CentOS Linux release 7.9.2009 (Core)
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
EPEL7

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
