### ISSUE TITLE
Nice feature: recursive build of congainer .def dependency chain

### ISSUE THREAD

**Issue by max-l** [apptainer/singularity#5842]
Suppose I have the following container definitions : 

```
container3.def (BootStrap: localimage, From: ./container2.def)
container2.def (BootStrap: localimage, From: ./container1.def)
container1.def (BootStrap: library, From: ./ubuntu:20.04)
```

Wouldn't it be nice if there was a build command that built the whole dependency chain (all the .sif) when all .def are local and no other dependency need to be fetched ?

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
