### ISSUE TITLE
Setup a default seccomp file

### ISSUE THREAD

**Issue by lud0viskm** [apptainer/singularity#5845]
Hello, this is my first time opening an issue on github :)

### Version of Singularity:

What version of Singularity are you using? Run:

```
3.7.0
```
### Expected behavior

To enhance security, we want to setup a specific (or default) seccomp file for all our HPC users (without invoking `--security seccomp:/foo/bar/joe.json`) . Actually only users can use seccomp file, but they "must" not.

### Actual behavior

Default seccomp file is not used by default even if `--security` param is used.

### Question / Evolution

Is this feature is already supported in singularity 3.7? If it is not, is it possible to add support of default seccomp file in `singularity.conf` and path to default seccomp file? This should disable the override of `--security seccomp:/foo/bar/joe.json` param at runtime.

Thank a lot.
Ludovic

**Comment by dtrudg** [comment]
This would be a nice feature to have. I'm sure we'd consider a PR contribution for it but it's not currently on our roadmap.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
