### ISSUE TITLE
Source conda.sh prior to `singularity shell` or `singularity exec`?

### ISSUE THREAD

**Issue by siddk** [apptainer/singularity#5847]
### Version of Singularity:

What version of Singularity are you using? 
```
$ singularity version
> 3.6.0-rc.2+26-g2c6cf59
```

### Problem

Currently, when I install Anaconda (MiniConda) in an environment, I have to run the following to source the `conda` commands:

```
.  <MINICONDA_PATH>/etc/profile.d/conda.sh
```

I have to do this on each call to `singularity shell` and `singularity exec`. For `singularity run` I can add the above command to `%runscript` but this doesn't translate to `shell` or `exec`.

Here is a sample `.def` file I've been using:

```
Bootstrap: library
From: ubuntu:20.04
Stage: build

%environment
    # Ensure MiniConda on Path
    PATH="/usr/local/miniconda/bin:$PATH"

%post
    # Generic Updates
    apt-get -y update
    apt-get -y install curl git gzip less python-is-python3 python3-distutils python3-apt tar unzip vim wget

    # Install MiniConda for Python Environment Management!
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    /bin/bash ~/miniconda.sh -bfp /usr/local/miniconda
    rm ~/miniconda.sh

    # Set Path
    export PATH="/usr/local/miniconda/bin:$PATH"

    # Set MiniConda Path for EVERYONE
    ln -s /usr/local/miniconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

    # Conda configuration of channels from .condarc file
    conda config --file /.condarc --add channels defaults
    conda config --file /.condarc --add channels conda-forge
    conda update conda

    # Install Bare Minimum
    conda install numpy scipy ipython

    # Versioning & Timestamping
    CONTAINER_NAME="ubuntu-dev"
    CONTAINER_VERSION="0.0.1"
    NOW=`date`
    echo "export CONTAINER_NAME=\"${CONTAINER_NAME}\"" >> $SINGULARITY_ENVIRONMENT
    echo "export CONTAINER_VERSION=\"${CONTAINER_VERSION}\"" >> $SINGULARITY_ENVIRONMENT
    echo "export NOW=\"${NOW}\"" >> $SINGULARITY_ENVIRONMENT

    # Set Conda Path
    echo ". /usr/local/miniconda/etc/profile.d/conda.sh" >> $SINGULARITY_ENVIRONMENT
    echo "conda activate" >> $SINGULARITY_ENVIRONMENT

%runscript
    echo "Running with Container '$CONTAINER_NAME' -- Version '$CONTAINER_VERSION' -- Created at $NOW"
    echo "Arguments received: $*"

    # Source `conda.sh`
    . /usr/loca/miniconda/etc/profile.d/conda.sh

    # Execute!
    exec "$@"
```

**Comment by tsnowlan** [comment]
Instead of putting the source command in the `%runscript`, echo it into `$SINGULARITY_ENVIRONMENT`. Then it will be available everywhere. ref: https://stackoverflow.com/a/56490063/5791702

**Comment by siddk** [comment]
That doesn't work - it's already in the $SINGULARITY_ENVIRONMENT --> the the line immediately after `# Set Conda Path` in the def file above...

**Comment by jmstover** [comment]
Is this because of functions defined in the `conda.sh` file? If so... it's not going to work. Exported functions are not passed to a new shell from a `exec` call. You need to have something in your `~/.bashrc` or similar file.

IIRC, you can look to see if `SINGULARITY_NAME` is set. And if so, source the file... So, something like:

```
if [ -n "$SINGULARITY_NAME" ]; then
    . /usr/loca/miniconda/etc/profile.d/conda.sh
fi
```

You can also look for a specific `SINGULARITY_NAME` value, etc... I'm pretty sure that's the variable that holds the name of the image you're running.

**Comment by siddk** [comment]
I guess this might be a fundamental misunderstanding on my part - but when I run `singularity shell` what shell does it actually use? Default shell on my HPC setup is bash - should I add that line to my .bashrc?

**Comment by jmstover** [comment]
I believe that it tries defaulting to `/bin/bash` ... and falls back to `/bin/sh` if it doesn't exist.  So, yeah, try putting the check in your `~/.bashrc` 

If you wanted to be more generic, I _think_ if you were to define `CONDA_PATH` or similar in the `%environment` section, then you could use a line like:

```
. ${CONDA_PATH}/etc/profile.d/conda.sh
```

The values in `%environment` should be set on the shell that's executed for the command, and in theory, would be visible when your `~/.bashrc` is parsed.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
