### ISSUE TITLE
Feature request: streaming conversion of Docker images to SIFs

### ISSUE THREAD

**Issue by frankier** [apptainer/singularity#5861]
It seems the current situation of converting Docker images to SIF files has some drawbacks. In summary as I understand the current process is like so:

  * Download Docker layers
  * Extract layers from oldest to newest to temporary directory - each time a newer layer has a newer version of a file overwrite, and delete if it is removed in the new layer 
  * Use `mksquashfs` to convert to squashfs image

The main drawbacks here are the temporary directory can cause performance problems. Each file has an entry in the filesystem and so on. The situation is obviously worse with a non-local filesystem, which hopefully we're not working on, but it's often done by accident in HPC environments.

It's possible that serializing is simply not necessary. https://github.com/AgentD/squashfs-tools-ng contains the tar2sqfs tool. With this tool we could have the following strategy:

 * Download Docker layers newest to oldest
 * As layers become available, extract them to a TAR stream
 * As we go, keep track of deleted and overwritten files, and do not put them into the TAR stream when we extract older layers
 * The whole thing gets piped to `tar2sqfs`

Clearly there's some amount of memory usage and overhead from keeping track of overwritten/deleted files, but I suspect the overall performance may benefit.

I wonder whether there would be the possibility of offering something like this, perhaps as an alternative strategy for this common case of direct conversion, and perhaps only available if the system to have tar2sqfs available already.

Does this seem like it could be possible/desirable?

**Comment by frankier** [comment]
Here is the corresponding feature request for old school squashfs-tools to implement something like tar2sqfs https://github.com/plougher/squashfs-tools/issues/25

**Comment by dtrudg** [comment]
There are definitely potential speed-ups here. However this work is not something that would be a high priority as it is complex, and the requirement of squashfs-tools-ng would limit deployment.

- This would only be relevant for a direct translation from docker -> SIF. Any definition file with any `%post` operations etc. has to work on an extracted temporary build directory.
- tar2sqfs is not available on many systems.
- Docker layers generally have to be extracted in order. There are AUFS 'whiteout' and 'opaque' markers that have to be dealt with between layers. These are quite a bit more complicated than just tracking deleted and overwritten files. I don't think it's possible to deal with them correctly in a newest->oldest extraction order.
- There are a lot of edge cases to deal with when extracting layer tars. Extended attribute handling, permission handling, etc. has to be attended to carefully in root and root-less extraction. You cannot simply extract the tar verbatim in various situations. When piping into squashfs these issues may be lessened, but flattening ownership is still the norm for Singularity.
- We purposefully use a package for layer extraction (opencontainers/umoci) that is associated with the Open Containers Initiative (OCI), so that we can have good confidence Singularity is extracting OCI images correctly. An alternative approach would mean we have to write and maintain our own implementation, which is likely to be buggier.

If you are considering looking into this further yourself I'd suggest exploring the unpack/extraction code of umoci for an indication of how various situations during extraction have to be handled: https://github.com/opencontainers/umoci/tree/master/oci/layer
