### ISSUE TITLE
Bash environment issues upgrading to 3.6+

### ISSUE THREAD

**Issue by ajw1980** [apptainer/singularity#5872]
I recently upgraded to singularity 3.7, so I've got the new environment loading features.

I'm possibly exploiting an unexpected behavior, but with the previous version (3.5 or before), it was possible to bind mount basically any bash environment script in /.singularity.d/env. Specifically, I had this bind mount to make Environment Modules (installed via spack) from a shared location available in the container:

    -B /opt/spack/opt/profile/spack.sh:/.singularity.d/env/91-environment.sh

This ultimately is a bash script with functions (using `declare -f`) so I had to switch to the workaround as described in #5541. I made a new spack-singularity.sh and bind mount that, which works but needs some additional quoting in some circumstances. Before something like this did not need double quotes:

    singularity exec <container> "/bin/bash -c '[ -f $linkdir/bin/python ] && rm $linkdir/bin/python'"

I think there are probably similar use cases (like activating conda environments) that this would be useful for. It would be nice if there was a way to continue to use bash to load the environment so a wrapper around bash scripts isn't required.

**Comment by dtrudg** [comment]
The environment handling was rewritten in 3.6 and uses an embedded shell so that minimal containers without a shell can be used with Singularity. At this time I don't believe that we will be modifying this to introduce workarounds to use a different shell. One of the additional intentions of the environment re-write was to ensure more consistent behavior through versions, and across containers and hosts.

I would strongly suggest avoiding any kind of bind into `.singularity.d`  - this directory is really meant for scripts that are part of the container's environment, or used internally by the singularity engine, not for runtime modification of the environment by the calling user. In future versions of Singularity it is likely to be removed altogether, as there is an intention to move container metadata and configuration out of the root filesystem and into config descriptors.

I'll ask @cclerget / @ikaneshiro to comment here, just in case they aren't in agreement with the above.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
