### ISSUE TITLE
Best practise to run external script from post 

### ISSUE THREAD

**Issue by liborw** [apptainer/singularity#5875]
Hi,

what is a best practice to run an external script in `%post` section, I have seen some different aproaches, cloning git repository with scripts from `%post` section, copiing files to `/root` and so on, but all seems  bit complicated...

Thanks

**Comment by dtrudg** [comment]
Hi @liborw - I would advise asking this on the mailing list or in the slack channel. Those are better places for open discussions, as questions will be seen by more people. GitHub issues are best for specific bugs/issues or feature requests.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
