### ISSUE TITLE
Host screwed up when cancelling build during `pacstrap` phase

### ISSUE THREAD

**Issue by LukeLR** [apptainer/singularity#5879]
### Expected behavior

The host shouldn't be affected when building a container.

### Actual behavior

When cancelling a `bootstrap: arch` build during the `pacstrap` (initialization) phase, while `SINGULARITY_TMPDIR` is set, Singularity will screw up the host by messing up the `systemd` bus, causing every `systemd`-operation to fail with:

```
$ systemctl status
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

This makes a `systemd`-based system basically unusable, as not even `reboot` will work anymore.

### Steps to reproduce this behavior

- Set `SINGULARITY_TMPDIR` using e.g. `export SINGULARITY_TMPDIR=/usr/share/.singularity/`
- Run `sudo --preserve-env=SINGULARITY_TMPDIR singularity build container.sif container.def` with `container.def` containing `bootstrap: arch`
- Press Ctrl+C during the first few seconds.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### How did you install Singularity
pacman

**Comment by dtrudg** [comment]
Please could you provide full output from running Singularity with the `-d` debug flag so that we are able to see where this is occurring, and exactly what binds are happening etc.

`singularity -d build ....`

Singularity shouldn't be doing anything that affects the host here. There is likely something that pacstrap is doing that it does not back out cleaning when killed in the first phase.

Archlinux is generally not a heavily tested host platform given the usual deployment targets of Singularity, so any PR contributions towards a fix would be extremely welcome.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
