### ISSUE TITLE
Singularity and MPI applications - SIGSEGV: Segmentation fault - invalid memory reference

### ISSUE THREAD

**Issue by j34ni** [apptainer/singularity#5885]
### Version of Singularity:

```
singularity version 3.5.3-1.1.el7

```

### Problem

We are trying to execute an MPI application with a Singularity container running the native mpirun command from the host.

The application is already built and started with the command:
```
mpirun -n <NUMBER_OF_RANKS> singularity exec <PATH/TO/MY/IMAGE> </PATH/TO/BINARY/WITHIN/CONTAINER>
```
### Actual behavior

Most of the time the application crashes:
```
SIGSEGV: Segmentation fault - invalid memory reference
```
We tried to change the number of ranks (which requires re-building the application) and the stack size (for execution), however there does not seem to be any systematic behavior.

Sometimes runs which have failed succeed when re-submitted without changing anything.

Even with a single node the application often fails, but it never crashes when started from inside singularity:

```
singularity>
mpirun -n <NUMBER_OF_RANKS> </PATH/TO/BINARY/WITHIN/CONTAINER>
```
Any idea how to sort this out?

**Comment by dtrudg** [comment]
There could be many causes for a SIGSEV of the application. They should not be due to Singularity itself, but can be due to library / MPI mismatches etc. between the host and the containerized application. A lot more information would be required to provide assistance,

For help with the issue the following is needed:

- Please verify the same behavior under the current version of Singularity 3.7
- Please provide information about what the application is, how the container was built (definition file), how you are running the application (full command line).
- Please provide debug output from singularity using the `-d` debug flag: `mpirun ... singularity -d ....`
- Please provide any stack trace / crash message from the terminal, or `dmesg`.

Also note that issues containerizing applications often receive more input on the slack channel and mailing list, where more community members read and can offer advice.

**Comment by j34ni** [comment]
Thank you for your answer but I believe that we can close this issue
Unfortunately I cannot easily test with Singularity 3.7 since I am not Singularity Administrator on the HPCs
The application in question is a climate model
The problem seems to occur only with this particular version of the code which is more demanding in terms of memory
It may be worth finding out why this makes it crash with Singularity, though
