### ISSUE TITLE
Yade container run error on CentOS Host

### ISSUE THREAD

**Issue by quanmqiu** [apptainer/singularity#5893]
Singularity 3.7 with go 1.16.2 from tar.gz.

I installed a host by using centos 7.9 ISO. Within the centos host, run 

`singularity exec registry.gitlab.com/yade-dev/docker-prod:ubuntu20.04 yade -n --test`

A error occured:

`Using python version: 3.8.5 (default, Jan 27 2021, 15:41:15)`
`[GCC 9.3.0]`
`Traceback (most recent call last):`
`  File "/usr/bin/yade", line 103, in <module>`
`    import yade.tests`
`  File "/usr/lib/x86_64-linux-gnu/yade/py/yade/__init__.py", line 75, in <module>`
`    from yade import boot`
`ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory`

But if I run the same command in a host installed by using ubuntu 20.04 ISO, all tests passed.

When I use docker directly:

`docker run -it registry.gitlab.com/yade-dev/docker-prod:ubuntu20.04`
`yade -n --test`

I got the same result. All tests passed in the ubuntu 20.04 host, but ImportError occured in the centos 7.9 host.

I know this may be not singularity's problem. 

Would you mind trying to check this problem?

By the way, if I use `registry.gitlab.com/yade-dev/docker-prod:ubuntu18.04`, no error occured in both hosts.

Thanks.

**Comment by dtrudg** [comment]
Please raise this issue with the yade community, or if you wish to discuss it with other Singularity users the Slack channel and mailing list are more appropriate.

We use GitHub issues to track Singularity bugs and feature requests. Because the issue occurs with both Singularity and Docker this does not appear to be a bug in Singularity, so is best handled elsewhere.
