### ISSUE TITLE
pushing a new key to a custom remote outputs no keystore url

### ISSUE THREAD

**Issue by wobito** [apptainer/singularity#5897]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.7.2
```

### Expected behavior

when creating and pushing a new key for a custom remote (keys.domain.tld), the output doesn't report an URL

```sh
singularity key newpair
```

After filling in all the prompts and pushing to the custom remote the last output line should read. 

```sh
Key successfully pushed to: keys.domain.tld
```

### Actual behavior

```sh
Key successfully pushed to: 
```

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by DrDaveD** [comment]
This is still relevant, and Sylabs fixed it in their [pr 24](https://github.com/sylabs/singularity/pull/24).

**Comment by pedroalvesbatista** [comment]
I could run and test it, keys pushed succesfully to Keystore.

**Comment by DrDaveD** [comment]
@pedroalvesbatista The issue is about the output message.  Are you saying you reproduced the problem with the output message?

**Comment by pedroalvesbatista** [comment]
> @pedroalvesbatista The issue is about the output message. Are you saying you reproduced the problem with the output message?

Well, I'll recheck this steps to see the proper output.

But, still is necessary to check the CLI output for the URI, and maybe some checking in code is necessary.
