### ISSUE TITLE
Bazel rules for singularity (feature request)

### ISSUE THREAD

**Issue by dmadisetti** [apptainer/singularity#5902]
I would love to more tightly couple singularity with my build and testing process using bazel.
Here's an example of docker rules: https://github.com/bazelbuild/rules_docker

I can see singularity doing something similar:

```starlark

sif_image(
  name = "my_container",
  docker_bootstrap = ":my_docker_container",
  setup = "touch file",
  ... // other sections here
  apps = [":my_app", ...],
)

singulairty_app(
  name = "my_app",
  run = ":my_bazel_compiled_python_binary",
  labels = [...],
  help = "whatever help"
)

```

`rules_singularity` should be able to take in a docker label (produced by docker_rules), and for each section take in a label or a string. In addition, the rule should be able to accept a list of apps.
Ultimately, I should be able to do: `bazel run :my_container --app my_app`
or `bazel build :my_container` to create a sif.

## Implementation

Very naively, the rules can template a definition file, and run singularity on top of it- but there might be deeper ways of doing this.

## Benefit to Singularity

I'm not the only person who uses Bazel. Many are forced to use Bazel to compile Tensorflow, taking on this feature means you can provide Tensorflow images, which will hopefully lead to larger adoption of singularity. a `tf-python` image could see pretty broad use across hpcs. Having this rule would make it relatively trivial to keep up to date with cutting edge tensorflow.

**Comment by dtrudg** [comment]
This would be quite a large effort to implement, and keep maintained. It'd also really be a separate project, rather than a core part of Singularity. I don't think that it is likely it would be something that the Singularity core developers have the resources to do. As a community driven project it would be something nice to have.

I'm not too sure there are many people building tf from source to use with Singularity, however. The dockerhub tf nightly images can be used with Singularity, and building from them is often a suitable way of tracking tensorflow between releases.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
