### ISSUE TITLE
How to create command alias?

### ISSUE THREAD

**Issue by radiantone** [apptainer/singularity#5930]
### Version of Singularity:
3.7

Is there any way to specify inside the build recipe an alias for a complex command such that a user only need to exec the container and use the alias as the command?

I tried adding an alias= command to %environment but that didn't work

thanks

**Comment by pedroalvesbatista** [comment]
You mean the alias being some sort of flag when calling the container, and this flag inflates into the recipe ?

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
