### ISSUE TITLE
Singularity sometimes fails to extract root filesystem

### ISSUE THREAD

**Issue by jje42** [apptainer/singularity#5944]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.7.3
```

### Expected behavior

What did you expect to see when you do...?
Singularity should execute a command without error for

```
$ singularity exec container.sif echo 'hello, world'
INFO:    Converting SIF file to temporary sandbox...
hello, world
INFO:    Cleaning up image...
```

### Actual behavior

What actually happend? Why was it incorrect?

During testing of a new HPC system, I see the following error output sometimes. The majority of submitted jobs run successfully without error. Failing jobs are using the same singularity binary and same container file as those that succeed.

```
$ singularity exec container.sif echo 'hello, world'
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting ~/container.sif: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /home/tjellis/.local/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /home/tjellis/.local/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /home/tjellis/.local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
FATAL ERROR:Failed to create thread
```

The same jobs (same container file) all run without errors on our legacy HPC system. So it's likely something in the setup of the new system; however, I've no idea what from the error message or why it only occurs sometimes.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

I'm unable to replicate the issue when submitting single jobs. The problem only happens a few times in every thousand jobs submitted.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

From source

**Comment by dtrudg** [comment]
The new system likely has a limit on the number of threads/process that can be created, or a similar limit enforced. It can be triggered sporadically because these limits generally apply across processes running on the same host, so often are only seen if other tasks are running at the same time.

You will need to check for limitations that show with `ulimit -a` or are configured with cgroups or similar.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
