### ISSUE TITLE
How to set a relative soft link using $SINGULARITY_ROOTFS in the setup part of the Singularity recipe file?

### ISSUE THREAD

**Issue by verilog15** [apptainer/singularity#5957]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.7.1-1
```
### Question

I'm trying to create soft link in the `%setup` section of the Singularity recipe file. If the link is relative, it does not work. For example:
```
ln -s ${SINGULARITY_ROOTFS}../python2/2.7.5a ${SINGULARITY_ROOTFS}/usr/pkgs/python/2.7.5
```
It creates:
```
lrwxrwxrwx 1 root root 49 Apr 24 06:33 /tmp/build-temp-976030219/rootfs/usr/pkgs/python/2.7.5 -> /tmp/build-temp-976030219/rootfs../python2/2.7.5a
```
The `/tmp/build-temp-976030219/rootfs../python2/2.7.5a` is of course invalid path. I don't want to start getting the realpath because I could get other links on the way. How to make it work with **relative paths**? Am I not using the `${SINGULARITY_ROOTFS}` properly?

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter
