### ISSUE TITLE
docker images convert  SFI image

### ISSUE THREAD

**Issue by xspython** [apptainer/singularity#5963]
$ singularity version
3.7.3

If you compile a docker local image into a SIF image, I see an image command, but it seems to be cancelled in 3.7.3

**Comment by gmkurtzer** [comment]
Can you elaborate on this please?

**Comment by xspython** [comment]
$ docker pull centos
$ docker save centos:latest -o centos.tar

How can this image be directly converted into SIF

**Comment by gmkurtzer** [comment]
Please check the following documentation page:

https://sylabs.io/guides/3.0/user-guide/singularity_and_docker.html#locally-available-images-cached-by-docker

You can also splat out that tarball into a local directory and build a SIF image from that.

I'm closing this issue because technical support should be directed to the email list or Slack.

Good luck!
