### ISSUE TITLE
repo home page link doesn't work

### ISSUE THREAD

**Issue by mr-c** [apptainer/singularity#5975]
https://singularity.hpcng.org/ link found at https://github.com/hpcng/singularity

> 404

> There isn't a GitHub Pages site here.

> If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by mr-c** [comment]
This issue has been fixed, thanks
