### ISSUE TITLE
FATAL:   Invalid encryption private key: asn1: structure error: tags don't match

### ISSUE THREAD

**Issue by paulo7777** [apptainer/singularity#6007]
This is about building and running encrypted containers.
Got the error below with keys generated by `ssh-keygen` from openSUSE 15.2.
If I create the keys on a CentOS server, then I'm able to build and execute images with both CentOS and openSUSE. 

### Version of Singularity:

```
singularity version 3.7.2-lp152.2.12.1
singularity version 3.7.3
```

### Expected behavior

Build and execute encrypted images with openSUSE 15.2.

### Actual behavior

What actually happened? Why was it incorrect?

```
singularity exec --pem-path=rsa_pri.pem encrypted.sif cat /etc/os-release 
FATAL:   Invalid encryption private key: asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2
```

### Steps to reproduce this behavior

With an openSUSE 15.2, run this:
```
# create a new key pair without password
ssh-keygen -t rsa -b 2048 -f rsa -q -P ""
ssh-keygen -f ./rsa.pub -e -m pem >rsa_pub.pem
mv rsa rsa_pri.pem
# build and execute an encrypted container
sudo singularity build --pem-path=rsa_pub.pem encrypted.sif docker://alpine
singularity exec --pem-path=rsa_pri.pem encrypted.sif cat /etc/os-release 
```

If you create the keys on a CentOS box with `ssh-keygen`, then you can successfully build and execute containers with openSUSE.

### What OS/distro are you running

```
NAME="openSUSE Leap"
VERSION="15.2"
```
and
```
CentOS Linux release 7.8.2003 (Core)
```

### How did you install Singularity

Got the error with singularity from openSUSE repo and build from source:
```
singularity version 3.7.2-lp152.2.12.1
singularity version 3.7.3
```

**Comment by kthun91** [comment]
I can confirm this issue with ubuntu 20.04.2.
Singularity version 3.7.4 and 3.6.4
Same error same use case

**Comment by kthun91** [comment]
Ok I solved the issue. 
The problem is the OpenSSH update 7.8. 
`ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format. The OpenSSH format,
   supported in OpenSSH releases since 2014 and described in the
   PROTOCOL.key file in the source distribution, offers substantially
   better protection against offline password guessing and supports
   key comments in private keys. If necessary, it is possible to write
   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
   when generating or updating a key.`
cited from the release notes of Open SSH

The solution is to simply add a `-m pem` to the command. It should look like this now:
`ssh-keygen -t rsa -b 4096 -m pem -N "" -f ./rsa`

The issue should be solved after an edit in the singularity documentation.

**Comment by DrDaveD** [comment]
Since singularity is maintained by volunteers, please submit a PR to https://github.com/hpcng/singularity-userdocs for this documentation change if it is a priority for you.

**Comment by kmuriki** [comment]
This repository is no longer active. If singularity --version says singularity-ce, then please open a new issue at https://github.com/sylabs/singularity, otherwise please open a new issue at https://github.com/apptainer/apptainer.

**Comment by GodloveD** [comment]
For future ref:
https://github.com/apptainer/apptainer-userdocs/pull/106
