### ISSUE TITLE
CentOS not building when using Bootstrap: library

### ISSUE THREAD

**Issue by jwschroeder3** [apptainer/singularity#6095]
### Version of Singularity:

```bash
3.7.2
```

### Expected behavior

If I try to build a container using a def file with the following contents:

```
Bootstrap: library
From: centos
Stage: build

%post -c /bin/bash
    yum -y install vim wget
```

### Actual behavior

As of 2021-08-02, I get the following output:

```
INFO:    Starting build...
INFO:    Using cached image
INFO:    Verifying bootstrap image /root/.singularity/cache/library/sha256.75151dfae5df6061d7e79899700bdd8cee08228cd69d54546c7c18f04fadbccd
INFO:    Running post scriptlet
+ /bin/bash /.post.script
/.post.script: line 1: yum: command not found
FATAL:   While performing build: while running engine: exit status 127
```

However, if I instead use docker, like so:

```
Bootstrap: docker
From: centos
Stage: build

%post -c /bin/bash
    yum -y install vim wget
```

This def file will produce a functional container.

### Steps to reproduce this behavior

You can reproduce my error by running

```
sudo singularity build test.sif vanilla.def
```

Where vanilla.def contains the example information above, using `Bootstrap: library`.

### What OS/distro are you running

```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

### How did you install Singularity

I installed Singularity from source.

**Comment by dtrudg** [comment]
Hi @jwschroeder3 - The default cloud library is run by Sylabs, and we do not continuously monitor the hpcng/singularity project, nor does hpcng have the ability to administer the library. In general the support link on the library site should be used for issues that are experienced related to the Sylabs library.

In this particular case, the short / immediate answer is to use `dnf` instead of `yum`. `library://centos` will bring down a CentOS 8 image. In CentOS 8, `dnf` has replaced `yum`. In most installs `yum` is present as a compatibility wrapper on top of `dnf` but it is not present in the minimal bootstrap the image is using. We'll fix this so that the `yum` wrapper for compatibility is present later today.

**Comment by dtrudg** [comment]
The `yum` wrapper is now present in the image for `amd64` and `arm64` / `ppc64le` will be updated shortly.

@DrDaveD - you can probably close this ticket.
