### ISSUE TITLE
ERROR: Unrecognized OSBuild type: docker

### ISSUE THREAD

**Issue by inJeans** [apptainer/singularity#617]
Why am I getting this error when I try to build from a Docker image?

 `ERROR: Unrecognized OSBuild type: docker`

If it makes any difference I am trying to do this inside a Docker container one a Windows 10 machine (running Docker for Windows). I get the same error when trying to use [this](https://hub.docker.com/r/singularityware/docker2singularity/) tool as well. 

Thanks for you help team.

**Comment by vsoch** [comment]
Ack, this is a hard one because I haven't used Docker on windows or have access to a windows machine. Afaik Docker on Windows is a different beast!

I can say that we are no longer supporting the original docker2singularity image (it was a hack to get functionality like environment from docker into singularity that now 2.3 supports natively).

It does make sense to first make sure the definition file you are using is not out of date - the Osbuild tag isn't relevant for docker, if you are bootstrapping it should look something like:

```
Bootstrap: docker
From:ubuntu:latest
```

So if you spec file is a bit off, try the above. If there are still issues, share it here so I can test it (on non windows) and then we will go from there!

**Comment by inJeans** [comment]
Oh. Thanks. I am just trying to build the example on the [NIH repo](https://github.com/NIH-HPC/gpu4singularity) at the moment. 

    BootStrap: docker
    From: nvidia/cuda:8.0-cudnn5-devel

    %post

        # add universe repo and install some packages
        sed -i '/xenial.*universe/s/^#//g' /etc/apt/sources.list
        locale-gen en_US.UTF-8
        apt-get -y update
        apt-get -y install vim wget perl python python-pip python-dev

        # download and run NIH HPC NVIDIA driver installer
        wget gpu4singularity 
        chmod u+rwx gpu4singularity
        ./gpu4singularity --verbose
        rm gpu4singularity

        # install tensorflow
        pip install --upgrade pip
        pip install tensorflow-gpu

I am still inside an Ubuntu container though, so it should look to Singularity like I am running Ubuntu right?

**Comment by inJeans** [comment]
I can `singularity create` no problem.

**Comment by vsoch** [comment]
ah that's @GodloveD! Hey @GodloveD any hints on this? Did you test with Windows? @inJeans I would give a test with the support that @gmkurtzer just added: https://github.com/singularityware/singularity/issues/611#issuecomment-295049418 on the development branch.

**Comment by inJeans** [comment]
Oh yeah. That was what I wanted to try out, but I couldn't even make it to that stage. It definitely isn't the NIH stuff. I get the same error even if I just try to build the simple example in the Singularity documentation

    Bootstrap: docker
    From: tensorflow/tensorflow:latest

    %runscript
 
        exec /usr/bin/python "$@"

    %post

        echo "Post install stuffs!"

**Comment by vsoch** [comment]
Are you able to use Virtual Box (or other VM) to run linux instead of Docker?

**Comment by inJeans** [comment]
I will try.

**Comment by GodloveD** [comment]
@vsoch I love how you can recognize me from a definition file :-P @injeans I've not tried running Singularity on Windows within Docker but it's a groovy idea.  What happens if you use another bootstrap agent (ie debootstrap?).  Can you try one of the definition files in the `/examples` subdir?

**Comment by gmkurtzer** [comment]
Hi @inJeans 

Can you confirm that your Windows computer did not add an extra character at the end of the line? We have seen something like this before and it is due to Windows thinking a new line should be two characters (`\r\n`) instead of Unix's single `\n`. Run the bootstrap definition file through `dos2unix` and see if that helps.

**Comment by inJeans** [comment]
Hey, guys. I won't be at my desk for a few days, but the line endings sound like a very likely candidate. I will let you know when I get the chance. Thanks for your help.

**Comment by inJeans** [comment]
Okay team. It was the line endings. Thanks @gmkurtzer for the suggestion. I have fallen victim to such rookie mistakes before. Thanks everyone for the help.

**Comment by vsoch** [comment]
glad to hear @inJeans ! I still fall for these kind of things, and it's nothing to be ashamed of, it just means you are a human :) I'm going to close the issue, please re-open if necessary.

**Comment by gmkurtzer** [comment]
Oh, and the only reason I picked up on it so fast is because there was just a similar ticket and so it was fresh in my mind.

Glad it's working now for you @inJeans and let us know how it works out for you.

Thanks!
