### ISSUE TITLE
binding directories in the same base directory as home 

### ISSUE THREAD

**Issue by bkemish** [apptainer/singularity#624]
I am trying to use singularity on a  Linux cluster where network users have their home directory mapped to /srv/home/username. I also wish to bind 2 other network directories called /srv/proj and /srv/share. I created /srv/home, /srv/proj and /srv/share in the image. When I try to run "singularity shell --bind /srv/proj --bind /srv/share my.img" I get the warnings
WARNING: Skipping user bind, non existant bind point (directory) in container: '/srv/proj'
WARNING: Skipping user bind, non existant bind point (directory) in container: '/srv/share'
and  the directories aren't bound.

If I try  "singularity shell --bind /srv my.img" I get the warning
WARNING: Not mounting requested bind point (already  mounted in container): /srv

If I use a local user whose home directory is in /home everything works perfectly. I have tried changing the home using the -H option and --contain but /srv/home is still bound and I can not bind anything else in /srv. I can bind those directories to other locations on the image, but my use case is to run old pipelines which were developed on an old version of Ubuntu and unfortunately they have these directories hardcoded all over the place. Can anyone tell me how to either fix the binding on /srv or disable the automatic binding of $HOME so that I can bind /srv manually myself.

Thanks.

**Comment by ArangoGutierrez** [comment]
Hi @bkemish for 
> "Can anyone tell me how to either fix the binding on /srv or disable the automatic binding of $HOME so that I can bind /srv manually myself." 

Take a loot at 
```/usr/local/etc/singularity/singularity.conf```
```bash
# SINGULARITY.CONF
# This is the global configuration file for Singularity. This file controls
# what the container is allowed to do on a particular host, and as a result
# this file must be owned by root.
```

Also for the rest of the issue, would you give it a to the ```development``` branch and see if it works. I don' t have those folders on network, and  
```bash
singularity shell --bind /srv/ my.img
```
Worked in my host

**Comment by vsoch** [comment]
hey @bkemish !

When you bind the base of /srv, by way of project and share being in the image, they are included under that bind. However if /srv/home is bound first to home, it's going to skip /srv all together. For example, here I have a folder "gitlab" in my /srv folder:
```
ls /srv
gitlab
```
Here I am sheling into ubuntu, binding my home to srv/home
 ```
vanessa@vanessa-ThinkPad-T450s:~$ singularity shell -B /home/vanessa:/srv/home/vanessa docker://ubuntu
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /home/vanessa/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:c62795f78da9ad31d9669cb4feb4e8fba995a299a0b2bd0f05b10fdc05b1f35e.tar.gz
Exploding layer: sha256:d4fceeeb758e5103c39daf44c73404bf476ef6fd6b7a9a11e2260fcc1797c806.tar.gz
Exploding layer: sha256:5c9125a401ae0cf5a5b4128633e7a4e84230d3eb4c541c661618a70e5d29aeff.tar.gz
Exploding layer: sha256:0062f774e9942f61d13928855ab8111adc27def6f41bd6f7902c329ec836882b.tar.gz
Exploding layer: sha256:6b33fd031facf4d7dd97afeea8a93260c2f15c3e795eeccd8969198a3d52678d.tar.gz
Exploding layer: sha256:fe44851d529f465f9aa107b32351c8a0a722fc0619a2a7c22b058084fac068a4.tar.gz
Singularity: Invoking an interactive shell within container...
```
and now we see home is there, gitlabis not.
 ```
Singularity ubuntu:~> ls /srv
home
Singularity ubuntu:~> 
```
A similar thing happens when you specify Home instead of bind:
```
singularity shell -H /home/vanessa:/srv/home/vanessa docker://ubuntu
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /home/vanessa/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:c62795f78da9ad31d9669cb4feb4e8fba995a299a0b2bd0f05b10fdc05b1f35e.tar.gz
Exploding layer: sha256:d4fceeeb758e5103c39daf44c73404bf476ef6fd6b7a9a11e2260fcc1797c806.tar.gz
Exploding layer: sha256:5c9125a401ae0cf5a5b4128633e7a4e84230d3eb4c541c661618a70e5d29aeff.tar.gz
Exploding layer: sha256:0062f774e9942f61d13928855ab8111adc27def6f41bd6f7902c329ec836882b.tar.gz
Exploding layer: sha256:6b33fd031facf4d7dd97afeea8a93260c2f15c3e795eeccd8969198a3d52678d.tar.gz
Exploding layer: sha256:fe44851d529f465f9aa107b32351c8a0a722fc0619a2a7c22b058084fac068a4.tar.gz
Singularity: Invoking an interactive shell within container...
Singularity ubuntu:/home/vanessa> ls /srv/
home
Singularity ubuntu:/home/vanessa> ls /home
vanessa
Singularity ubuntu:/home/vanessa> 
```

So this bug probably comes down to what gets bound first, what is specified as defaults for the container to bind, and if your configuring lets you create directories on the fly. If users have their homes under srv, and the setting in the configure binds this automatically, this means by default /srv/home/username is probably bound to the container's home, and the rest goes away (as we saw above).

So the warning that you get:
```
If I try "singularity shell --bind /srv my.img" I get the warning
WARNING: Not mounting requested bind point (already mounted in container): /srv
 ```
Is related to that point.

The other two error messages are related to the fact that you are asking to bind directories that don't exist in the container. There is a setting in the config that will have something along the lines of "create non existing directories by default" and this is likely turned off. For example, when I ask singularity to bind to a non existing point in my container on my local machine:
```
:~$ singularity shell -B /srv/gitlab:/scratch docker://ubuntu
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /home/vanessa/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:c62795f78da9ad31d9669cb4feb4e8fba995a299a0b2bd0f05b10fdc05b1f35e.tar.gz
Exploding layer: sha256:d4fceeeb758e5103c39daf44c73404bf476ef6fd6b7a9a11e2260fcc1797c806.tar.gz
Exploding layer: sha256:5c9125a401ae0cf5a5b4128633e7a4e84230d3eb4c541c661618a70e5d29aeff.tar.gz
Exploding layer: sha256:0062f774e9942f61d13928855ab8111adc27def6f41bd6f7902c329ec836882b.tar.gz
Exploding layer: sha256:6b33fd031facf4d7dd97afeea8a93260c2f15c3e795eeccd8969198a3d52678d.tar.gz
Exploding layer: sha256:fe44851d529f465f9aa107b32351c8a0a722fc0619a2a7c22b058084fac068a4.tar.gz
Singularity: Invoking an interactive shell within container...

Singularity ubuntu:~> ls /scratch/
config data logs
```
It works fine because /scratch was created on the fly! If I try this one my cluster where I can't do this, or even if I run a container that doesn't have some "automatically mounted" directores inside I get that message:
```
singularity shell docker://ubuntu:latest
library/ubuntu:latest
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Downloading layer: sha256:6b33fd031facf4d7dd97afeea8a93260c2f15c3e795eeccd8969198a3d52678d
Downloading layer: sha256:0062f774e9942f61d13928855ab8111adc27def6f41bd6f7902c329ec836882b
Downloading layer: sha256:5c9125a401ae0cf5a5b4128633e7a4e84230d3eb4c541c661618a70e5d29aeff
Downloading layer: sha256:d4fceeeb758e5103c39daf44c73404bf476ef6fd6b7a9a11e2260fcc1797c806
Downloading layer: sha256:c62795f78da9ad31d9669cb4feb4e8fba995a299a0b2bd0f05b10fdc05b1f35e
WARNING: Non exista
There could be a bug that it is mounting home at /srv/home/, and then skipping the mount of /srv because it already finds home. I would play around with the -H option to try mounting home where it traditionally is (/home) and see if that helps to resolve some of the issues.
nt bind point (directory) in container: '/share/PI'
WARNING: Non existant bind point (directory) in container: '/scratch'
WARNING: Non existant bind point (directory) in container: '/local-scratch'
Singularity: Invoking an interactive shell within container...
```
and this is because I am not allowed to create mounts for directories in the container that don't exist. The setting that controls that is the following:

```
# ENABLE OVERLAY: [BOOL]
# DEFAULT: yes
# Enabling this option will make it possible to specify bind paths to locations
# that do not currently exist within the container. Some limitations still exist
# when running in completely non-privileged mode. (note: this option is only
# supported on hosts that support overlay file systems).
# note: currently disabled because RHEL7 kernel crashes with it... :(
enable overlay = no
```
(note this is version 2.2 above) 2.3 now looks like this:
```
# ENABLE OVERLAY: [BOOL]
# DEFAULT: yes
# Enabling this option will make it possible to specify bind paths to locations
# that do not currently exist within the container. note: this only works when
# using the standard SUID mode (not user-namespaces)).
enable overlay = yes
```

So given that you have control over the setup / config file and want to allow users to bind directories and have them automatically created, you can change this setting. If not, then in your bootstrap spec you could just make:
```
mkdir -p /srv/project
mkdir -p /srv/share
```
and then I would specify home to be bound to /home instead, and just bind those two directories to themselves. Eg:
```
singularity -H /srv/home/vanessa:/home -B /srv/project:/srv/project -B /srv/share/srv/share container.img
```
I don't think you need to specify the host:mount if it's the same, I just like doing that so I'm clear about my intentions, to myself, lol.

An easier route would just be to bind /srv, given that it exists in the container, it should include the subdirectores. The reason I didn't suggest this first is because it might already be detected as mounted given that home is mounted by default in the settings. You could play around with doing this and mount home elsewhere, or prevent it from being mounted.

Hopefully this gives some insight and things to try! If you are still having trouble, please show the commands that you've tried with --debug and we should be able to see exactly what is going on there.

**Comment by bkemish** [comment]
Thanks everybody! 

The various solutions you offered all seem to work. My mistake using the -H option was that I tried to use /srv/home, when I should have used /srv/home/username. The command  "singularity shell -H $HOME:/home/${HOME##*/} -bind /srv image" works fine. However, I have elected to follow the other advice and have changed "mount home = yes" to "mount home = no" in /usr/local/etc/singularity/singularity.conf.

**Comment by vsoch** [comment]
Great to hear!

**Comment by gmkurtzer** [comment]
@bkemish In the `singularity.conf` you may also find it adventageous to not only disable the automatic mounting of home, but add a `bind point` to /srv/home and ensure that `enable overlay` is set to `yes`. That way you don't have to do the bind by hand.

**Comment by bkemish** [comment]
Perfect! Thanks Gregory.
