### ISSUE TITLE
shell command doesn't read .bashrc

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#643]
This is a fairly minor issue, but a little annoying.

In the latest development branch (I didn't test earlier versions), using the 'shell' command and --containall and --home where the mapped in home directory contains a .bashrc and the login shell is bash, bash does not read the .bashrc.  If I do 'exec $SHELL' inside the container, it then works.  If I use exec bash on the command line instead of shell, that also works.

**Comment by gmkurtzer** [comment]
This is a "feature"! HAH

It came originally because I would always use `/bin/sh` for shell, but not all sh'es are equal (e.g. some are links to bash, sometimes dash, sometimes zsh, etc). It made the most sense to use Bash by default if present, but, when calling Bash directly, it automatically sources all of it's own login and dot files. Thus, if nothing else is passed, we call it with `--norc` option:

```
$ singularity shell -p /tmp/centos.img 
Singularity: Invoking an interactive shell within container...

Singularity centos.img:~/git/singularity> ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
gmk          1  0.0  0.0  12884   156 pts/4    S    23:24   0:00 /usr/local/libexec/singularity/bin/action-suid
gmk          2  0.0  0.3  15208  3120 pts/4    S    23:24   0:00 /bin/bash --norc
gmk          3  0.0  0.3  50880  3240 pts/4    R+   23:24   0:00  \_ ps auxf
Singularity centos.img:~/git/singularity> 
```

If you specify `SINGULARITY_SHELL` in your environment, or use `exec` as you pointed out, you can bypass this default behavior.

Hope that helps!

**Comment by DrDaveD** [comment]
Ok.  How about documenting this surprising behavior in the shell help?  I think normally people would expect it to run the shell from /etc/passwd.  That's what I expected.  I see the help says it will run /bin/sh, but that's not actually what it does.

I also see the -s option can be used to set SINGULARITY_SHELL.

**Comment by vsoch** [comment]
good idea. Do you mean the --help with the software, the docs, or both?

**Comment by DrDaveD** [comment]
I meant the --help with the software; I didn't see other docs.
