### ISSUE TITLE
use of /mnt

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#70]
It seems to me that /mnt shouldn't be used as the mount point, e.g. in bootstrap.  It's quite likely to have something manually mounted on it, or possibly be in use by another singularity instance.
Could a temporary directory be used instead (mktemp -d)?

**Comment by gmkurtzer** [comment]
I don't want to use a tmpdir, but we can use the localstatedir/singularity/mnt directory that I'm using for container mounts. I'll fix that up.

Good catch!

**Comment by gmkurtzer** [comment]
Committed in [master 759c7d5]. Thanks for the idea!

**Comment by loveshack** [comment]
You wrote: 

> I don't want to use a tmpdir,

For information, as it might be relevant to hacking, what's the problem
with it?

> but we can use the
> localstatedir/singularity/mnt directory that I'm using for container
> mounts. I'll fix that up.

**Comment by gmkurtzer** [comment]
I have a weird feeling about mounting other directories and files within everybody writable directories (even with stickybit set).. I don't know if there is any tangible risk, but since other options exist I'd prefer just to use those other options.

Because of namespaces, we won't have any mount space clashes in a common directories that are root owned like /mnt or even /var/singularity/mnt so that seems to make the most sense to me.
