### ISSUE TITLE
SESSIONDIR_PREFIX in 2.3

### ISSUE THREAD

**Issue by kcgthb** [apptainer/singularity#704]
Hi!

It looks like the `SESSIONDIR_PREFIX` configuration directive disappeared from `etc/singularity.conf` in 2.3, and I'm curious about the rationale.

As far as I can see, the session directory is now set to `<singularity_install_dir>/var/singularity/mnt/session`. I understand that this comes from the `localstatedir` option of the `configure` script.

We're typically installing Singularity on a shared NFS directory, alongside other applications, and in that case, the `localstatedir`, as well as the session directory, will end up on NFS. I recall from previous versions that those needed to be local to each machine. Is that not the case anymore?

**Comment by AdamSimpson** [comment]
I am intersted in knowing more about this change as well.

**Comment by gmkurtzer** [comment]
Heyas.

The reason for this change was to remove the necessity for a cleanup process/daemon with every run. Now the session directory is a volatile mounted tmpfs at the defined location. Once the mount namespace goes away via the foreground process, this location magically goes away. Also, because it is within the mount namespace, multiple Singularity processes, each within their own namespaces, will not collide with a shared location.

Now, where this does end up being an issue is because items being within the `/var` file system as you pointed out (`localstatedir`) should always be local. So when Singularity is built, it should be managed such that this location is local. Will it work if over NFS, yes, as long as `root_squash` is not enabled via NFS options.

Hope that helps!

Greg

**Comment by dtrudg** [comment]
Closing this as it was raised against Singularity 2.3 and there has been no further feedback. Please feel free to re-open if you are having problems with the latest version of Singularity. Thanks!
