### ISSUE TITLE
problems with multiple Includes in bootstrap definition

### ISSUE THREAD

**Issue by myourshaw** [apptainer/singularity#706]
## Version of Singularity:

2.3

### Expected behavior

def file that has multiple includes will build correctly, e.g.

```
BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

UpdateURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/updates/$basearch/

# additional packages
Include: bzip2

%post
  echo "Installing EPEL"
  yum -y install epel-release
```

### Actual behavior

def file that has multiple includes fails.

```
...
Complete!
Running post scriptlet
+ echo 'Installing EPEL'
Installing EPEL
+ yum -y install epel-release
/bin/sh: line 3: yum: command not found
ABORT: Aborting with RETVAL=255
```

### Steps to reproduce behavior

run singularity bootstrap with the above def file

**Comment by akkornel** [comment]
Hi @myourshaw, what happens if you put `yum` and `bzip2` on the same `Include:` line, at the top of the file?

**Comment by bauerm97** [comment]
@myourshaw As @akkornel has said, if you change `Include: yum` into `Include: yum bzip2` your def file should work as expected. Could you try this out and see if that solves your issue?

This arises because of how the code in [the keyval parser](https://github.com/singularityware/singularity/blob/master/src/bootstrap-lib/keyval.c) parses the `Include:` lines, where it looks one line at a time through the bootdef file and unfortunately overwrites the environment variable at each pass (when there are multiple lines present).

**Comment by vsoch** [comment]
@akkornel your a debian/rhel/yum/all-the-linux-things badass!! :D

**Comment by gmkurtzer** [comment]
I would assume it would work if it was all in a single line, but this should not cause an error condition. The second Include should either be used as one would expect, ignored, or warned. I haven't considered which is the correct behavior for this scenario yet. Does anyone care to voice an opinion or desire?

**Comment by vsoch** [comment]
I don't think we should have multiple include lines - it would be inconsistent with our current approach which has one header per field or section. Being able to define multiple of the same thing is more akin to a Dockerfile, and so to have BOTH in our standard would just be confusing. If the `include: yum bzip2` is a workable solution, we should do that. If we allow for multiple Include: then we should talk about which other tags warrant multiple. Eg:

```
Bootstrap: docker
From: ubuntu:latest
From: ubuntu:14.04
```

I say... don't go there :)

**Comment by akkornel** [comment]
The nice thing is, if you really want multiple `Include:` lines, you can turn the subsequent `Include:` lines into either `apt-get install` or `yum install` lines, and get exactly the same effect.

And similarly, if you want to start with `ubuntu:14.04` and end up at `ubuntu:latest`, you can do that through manipulation of sources files and invocations of `apt-get`.

I did consider pushing for allowing multiple `MirrorURL`, `UpdateURL`, and `GPG` lines, but I decided not to: You can easily do the same thing in the rest of the bootstrap

**Comment by truatpasteurdotfr** [comment]
In order of personnal choice:
1) a error message if multiple include: are listed (KISS)
2) +include: to add to the include list? but why would we need that feature? 
3) warning message, using only the 1st include: and ignoring the subsequent one(s)
4) include: concatenation (avoid delay the possible conflicts to the later process)

**Comment by gmkurtzer** [comment]
I dug into this a bit, and it is failing because in a case of duplicates, the last line wins.

There are several options for how this issue can/should be handled and I'm open to opinions:

1. Last entry takes precedence (like declaring multiple variables in shell, the last one is the one that persists.
2. The first entry persists and subsequent duplicate entries fail. 
3. The entires are somehow concatenated (perhaps comma delim, but this behavior will have unpredictable results (e.g. the `From:` Vs. `Includes:`).

I am inclined to leave the behavior as it stands now, but perhaps throw a warning (or error) if it encounters a duplicate key.

Thoughts?

**Comment by akkornel** [comment]
I'd suggest a fourth option:

4. Fail with an error if you see a duplicate entry of any type.

Allowing duplicates, in my opinion, just makes things more complicated for future people who are trying to understand how a bootstrap file works.  If multiple `Includes` lines are allowed, I imagine that very few bootstrap files would ever use them, making them that much more confusing for others.

**Comment by gmkurtzer** [comment]
Bombing out with an error is a reasonable suggestion and very easy to implement. I second it. :)

**Comment by vsoch** [comment]
+1.

**Comment by gmkurtzer** [comment]
Here is what it is doing now:

```
$ sudo singularity bootstrap /tmp/1.img  /tmp/docker.def 
Sanitizing environment
Building from bootstrap definition recipe
ERROR  : Duplicate bootstrap entry found: 'From'
ABORT  : Retval = 255
```

If that looks good, let's close this issue.

Thanks!

**Comment by dtrudg** [comment]
Closing this issue, as it appears fixed by the PR referenced above. Let us know if there are any outstanding problems on the latest version of Singularity. Thanks!
