### ISSUE TITLE
urlparse is buggy in Python 2.6

### ISSUE THREAD

**Issue by hra0031** [apptainer/singularity#724]
## Version of Singularity:

Singularity 2.3

### Expected behavior

Docker repository on nonstandart port should work: `docker://testdomain.cz:5000/centos/test`

### Actual behavior

If a Docker Image is on repository with nondefault port e.g. docker://testdomain.cz:5000/ this function return "testdomain.cz" as scheme.

### Steps to reproduce behavior

Use Docker repository with nonstandard port e.g.  `singularity --debug shell docker://testdomain.cz:5000/centos/test`

**Comment by hra0031** [comment]
Bug: https://bugs.python.org/issue754016

**Comment by vsoch** [comment]
Ok I did the following to try and reproduce the error:

 - working in an older Ubuntu (12.04) Docker image
 - downloaded and install Python 2.6.0 (it needed first zlib binaries)
 - installed Singularity 2.3
 - ran the command provided to reproduce

The first bug I hit is "no module named datetime" (did you get this as well? What version of 2.6.* were you running?). I'm having trouble reproducing the error beyond that, I keep seeing (at least what looks to be) correct:

```
*** STARTING DOCKER IMPORT PYTHON  ****
DEBUG Docker layers and (env,labels,runscript) will be written to: /tmp/.singularity-layers.TIGJABZ9
VERBOSE2 SINGULARITY_DOCKER_USERNAME not defined (None)
VERBOSE2 SINGULARITY_DOCKER_PASSWORD found
DEBUG Starting Docker IMPORT, includes environment, runscript, and metadata.
VERBOSE Docker image: testdomain.cz:5000/centos/test
VERBOSE2 Specified Docker ENTRYPOINT as %runscript.
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: testdomain.cz:5000
VERBOSE Namespace: centos
VERBOSE Repo Name: test
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://testdomain.cz:5000/v2/centos/test/tags/list
DEBUG GET https://testdomain.cz:5000/v2/centos/test/tags/list
```

Could you either give me a Dockerfile /other steps to set up the host as you have it, or give me the `--debug` location where the url is wrong? We do use urlparse once in the dinky function to add https, and it would be trivial to remove it. Testing (Without actually having a registry at some non standard port) with python 2.7.6 the first part to get the image at least look ok to me:

```
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: testdomain.cz:5000
VERBOSE Namespace: centos
VERBOSE Repo Name: test
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://testdomain.cz:5000/v2/centos/test/tags/list
DEBUG GET https://testdomain.cz:5000/v2/centos/test/tags/list
```

Again the above is with python 2.7.6, so that might be it. If you know the debug line that is wrong I can try to tweak that part of the code to not use urlparse, otherwise I can try to find an actual non standard registry to test. But I definitely need to know how to install your environment with 2.6 because I had quite a bit of trouble, haha. Let me know!

**Comment by vsoch** [comment]
I just had another idea and ran that part of the function manually - is this what you are seeing?

```
from urlparse import urlparse
>>> url='registry.io:4000/api/manifest/tags'
>>> parsed=urlparse(url)
>>> parsed
ParseResult(scheme='registry.io', netloc='', path='4000/api/manifest/tags', params='', query='', fragment='')
>>> scheme='https'    
>>> "%s%s" %(scheme,"".join(parsed[1:]).rstrip('/'))
'https4000/api/manifest/tags'
```

**Comment by hra0031** [comment]
@vsoch We are using Centos 6.7 and 6.9 with Python 2.6.6 on our cluster. I know this is a really old implementation of Python but Centos 6 is pretty common in HPC centers.
You reproduce it right in the second post. Next time I will try to describe the problem in more detail.

**Comment by hra0031** [comment]
I think this is resolved... closing
