### ISSUE TITLE
RFE: Make images stand alone

### ISSUE THREAD

**Issue by opoplawski** [apptainer/singularity#73]
Currently .singularity files require run-singularity to be installed on the target machine.  Perhaps something could be done like in AppImage: https://github.com/probonopd/AppImageKit/blob/master/README.md where it prefixes the archive with an ELF stub that can unpack and run it.  This is just wild speculation at this point without having dug too much into the structure of either tool.

**Comment by gmkurtzer** [comment]
I have actually played with this a bit, and even built a static ELF binary loader prefixing the image and using an offset to the image payload. But... the caveat's include: Some distribution vendors have actually disabled the ability to produce static binaries which means we have to custom build the header and distribute in binary form within the source, and it will still require Singularity to be installed on the host system because of the SUID bits.

I'm happy to keep this open for further consideration and discussion but I don't see a method at this point. If you (or anyone else) has more ideas, I am certainly open to them!

Thank you!

**Comment by gmkurtzer** [comment]
This is theoretically possible now with use namespace support in Singularity (and of course the host system). Granted, with some distributions making completely statically linking impossible not sure this is always going to be possible! <bad distros>....

**Comment by gmkurtzer** [comment]
While this is a great idea, I am closing it for now. The only possible way to do this would be the user namespace, and it is not moving fast enough or being adopted equally among the distributions. Additionally, the user namespace won't support using images in the foreseeable future. Love the idea, but not possible with today's technology. If/when things change, we will implement.
