### ISSUE TITLE
Mounting of top level directories (/) that do not exist is not possible

### ISSUE THREAD

**Issue by bgruening** [apptainer/singularity#762]
## Version of Singularity:

```
singularity --version
2.3-master.g044a991b
```

### Expected behavior

Mounting and writing to top level dir as well.

### Actual behavior

```
% singularity exec -B /foo:/foo:rw singularity_import/samtools:1.4.1--0 touch /foo/file.txt 

ERROR  : There was an error binding the path /foo: No such file or directory
ABORT  : Retval = 255
```

We would like to create container that are reusable by many different people and different deployments. Many users mount in data in top level directories, aka `-B /import/:/import`, but this is currently only possible if I create the folder `import` in advance in the container. I can not predict which folder a user needs so it would be great to support this feature to make containers really exchangeable.

**Comment by gmkurtzer** [comment]
I don't think this error should be silent because you are requesting an option that is failing. What I would recommend instead is to create some logic to automatically do this for people and include it in Singularity proper.

Please take a look at the file `$sysconfdir/singularity/init`. In there you can create some logic that can look for particular directories and conditionally enable certain features. For example if you add a shell snippet into that file like:

```
if test -d /foo; then
    SINGULARITY_BINDPATH="/foo"
    export SINGULARITY_BINDPATH
fi
```

Hope that helps!

**Comment by bgruening** [comment]
@gmkurtzer this was not about warning or error messages - that was an other issue. But I think my problem was solved in latest master dev versioni :)

Thanks!
