### ISSUE TITLE
Legacy Testing for 2.2

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#765]
If you look in the `.travis.yml` we have legacy testing for 2.1:

https://github.com/singularityware/singularity/blob/master/.travis.yml

We need to add this for 2.2 as well.

**Comment by GodloveD** [comment]
How far do we want to go back on this?  When I first wrote it, I envisioned only testing the last release.  Do we want to keep testing all the way back to 2.1 or just dump it in favor of 2.2?

**Comment by GodloveD** [comment]
@vsoch Actually I just went back and had another look at this and I'm confused.  It looks like I actually (mistakenly?) installed 2.2 and used that for legacy testing when I first wrote these tests?
  I think I did this because at the time 2.2 was latest stable and we were working on development. 
 Maybe I actually need to add 2.3 to the tests so that development branch is doing legacy testing. 
 
Also, it looks like I'm doing all of this backward.  I'm testing images that were made in the latest Singularity running in older versions of Singularity.  That's not guaranteed to work right?  Shouldn't we be testing images created in older versions of Singularity against newer Singularity runtimes?  That's the direction that backward compatibility should be expected right?

If I have all of this correct, I'm happy to work on it.  Just need a bit of clarification first.

**Comment by vsoch** [comment]
I think we want to assure users that if they create an image with version N, it works for new releases N+1, and I think that's backwards compatibility (new software is backwards compatible because it doesn't break old images). What we can't guarantee is that if we create some new feature for version 2.9, that feature will be available for an image created with 2.1. But installing 2.9 won't break being able to use 2.1.

So given this, I don't think we can have every version of singularity software tested against every version image (that wouldn't work and it would take a looong time once we have many versions.) I think what we **do** want is a simple folder that has an image representative (built by) each version. The tests would need to be run with updates / new versions against all those images. 

We would expect there to be some cases when new features aren't supported for older images. We still want to test those cases because the software should fail gracefully (like "255 this feature is not supported for this image."  A good example is with inspect - for some images they don't have the labels, so we just exit with a reasonable error.

**Comment by GodloveD** [comment]
Exactly!  What I'm doing now is taking an image built using N and testing it in N-1.  Which is not right.  And if we just create some standard containers using legacy builders on the shub we can pull them and use them for testing.  It also means we can get rid of that ugly-ness in the .travis.yml where I install an older version of Singularity.  Win win!  I'll get working on it.

**Comment by vsoch** [comment]
@GodloveD we aren't doing this anymore right?

**Comment by GodloveD** [comment]
No we are not.
