### ISSUE TITLE
Import command order

### ISSUE THREAD

**Issue by remyd1** [apptainer/singularity#779]
## Version of Singularity:

Any

### Expected behavior

IMHO, it should be:

```singularity import docker://ubuntu test.img```
Instead of the opposite:
```singularity import test.img docker://ubuntu```

Because, the logic should be in that order:
```singularity import source destination```

Like `cp` and many other programs...

Moreover an error message should inform that is not the right order.

### Actual behavior

If you enter previous command (that is to say the one which is not currently working), it will fail silently.

**Comment by vsoch** [comment]
This makes a lot of sense, given the cp command as you mentioned, and it having better readability to say "import this docker image to this singularity image." I think the current approach is probably taken because it assumes "the stuff following the image is what I want to import." @gmkurtzer what are your thoughts? If we remove old functionality, that would of course potentially break pre-existing tools/pipelines. We could extend functionality to allow for the above, but that might be hairy for you to implement (or not given the uri).

**Comment by gmkurtzer** [comment]
While this makes a lot of sense... there is some legacy-ness at play here and typically, the image always follows the "verb", not sure if it makes sense to break that standard but again, I do follow your logic.

Also, if we make a change at this point, we risk breaking people that have written script wrappers and additional tools.

**Comment by remyd1** [comment]
Well, even if a lots of tools use this format (`cp`, `mv`, `scp`, `rsync`...), there are some counter examples (not totally src-dst form), eg:

`tar -cvf file.tar dir/...` or `ln -s dest symlink`

So it could stay like that, but what is really annoying is that there is no error message / warning.

So it would be useful if there is a string analysis or if it fails it returns the command usage.

Otherwise, maybe you can include this change in singularity 3.0 ?

**Comment by gmkurtzer** [comment]
@remyd1, a warning or error should be possible assuming that it can be caught. Can you give an example CLI mock up of what you are thinking?

Thanks!

**Comment by dtrudg** [comment]
Closing this - we now use `singularity build` instead of `singularity import`. Error message is:

```
singularity build docker://ubuntu test.img
ERROR: Unknown container build Singularity recipe format: test.img
ABORT: Aborting with RETVAL=255
```

Let us know if any further issues. Thanks.
