### ISSUE TITLE
Bootstrap for other distro types

### ISSUE THREAD

**Issue by remyd1** [apptainer/singularity#80]
Hi;

I am trying to bootstrap some images, but I could not do it right now because the DistType is not known in singularity. I can not put any of debian or redhat DistType; In fact, I am talking about OpenSuse, ArchLinux, gentoo, but I think you can think about others distros. I think you can just update the code to allow that kind of DistType, it should work "as is".

Regards,
Remy

**Comment by gmkurtzer** [comment]
Hi,

I only supported "redhat" and "debian" DistTypes so far because those are
what I am familiar with. The interface is modular so I am hoping others
will contribute other distribution types with time.

If you are interested I can point you in the right direction of where to
look.

Thanks!

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by gmkurtzer** [comment]
Pinging @czka on this thread for the Arch Linux support...

**Comment by czka** [comment]
@remyd1 

I have added Arch Linux bootstrapping support to 2.x and master branches recently.

>  I think you can just update the code to allow that kind of DistType, it should work "as is".

Each distro needs its own bootstrap script. But those scripts have a lot in common and use the underlying Singularity's bootstrapping Bash code. Have a look at libexec/bootstrap/modules-v2/dist-*.sh and their respective examples/*.def in the source code for an idea how to add more.

**Comment by remyd1** [comment]
Great ! Ok I ll a take a look at this distro script :)

**Comment by gmkurtzer** [comment]
Closing legacy ticket.
