### ISSUE TITLE
import docker image error

### ISSUE THREAD

**Issue by yangyang-zhang** [apptainer/singularity#801]
## Version of Singularity:

[root@c031 intel_caffe]# singularity --version
2.3.1-dist

### Expected behavior

The docker image tar is  Make it yourself，Docker is in normal use

### Actual behavior

[root@c031 intel_caffe]# ll ~/docker/intel_caffe_v4.0.tar 
-rw------- 1 root root 2176706048 Jul 11 19:17 /root/docker/intel_caffe_v4.0.tar
[root@c031 intel_caffe]# cat ~/docker/intel_caffe_v4.0.tar  | singularity  import intelcaffe.img 
/usr/bin/tar: manifest.json: implausibly old time stamp 1970-01-01 08:00:00
/usr/bin/tar: repositories: implausibly old time stamp 1970-01-01 08:00:00

### Steps to reproduce behavior

Write here.

**Comment by vsoch** [comment]
This seems to be an issue with tar, suggesting something about the archive is weird. Did you try this command with `--warning=no-timestamp` to disregard the warning? Also, why are you importing with tar instead of just using the docker uri? Eg:

```
singularity import container.img docker://intel/caffee:4.0
```

I also notice that you are running as root? Be careful with this because it could produce an image with different permissions than you would expect.

**Comment by vsoch** [comment]
And [here](https://www.gnu.org/software/tar/manual/html_section/tar_27.html#warnings) are the docs for using tar. I'd be curious how that tar was made to produce an old timestamp.

**Comment by yangyang-zhang** [comment]
thank you very much, I will pay attention to it
