### ISSUE TITLE
Re-bootstrapping removes previous %environment variables

### ISSUE THREAD

**Issue by DeepHorizons** [apptainer/singularity#828]
## Version of Singularity:

2.3

### Expected behavior

When re-bootstrapping an image that has used the `%environment` section with a definition that does not have that section, the variables defined should still exist

### Actual behavior

When re-bootstrapping, the `/.singularity.d/environment` seems to be cleared even if the new definition file doesnt contain a `%environtment` section

### Steps to reproduce behavior

* 1.def
```
BootStrap: docker
From: ubuntu

%environment
    TEST='Hello World!'
    export TEST

%post
    echo "Running first bootstrap"
```

* 2.def
```
%post
    echo "Running second bootstrap"
```

* commands:
    * singularity create test.img
    * singularity bootstrap test.img 1.def
    * singularity exec test.img cat /.singularity.d/environment
    * singularity bootstrap test.img 2.def
    * singularity exec test.img cat /.singularity.d/environment

### Comments
Maybe this is expected behavior, but I didn't seem to see anything about this in the docs or anywhere else. I'm guessing that the entire `%environment` section is copied into `/.singularity.d/environment`, whether its empty or not.

Ideally it would be nice if new `%environment` sections added into whats already there, but I've read over #800 so I understand that it's still a work in progress. Should the `%environment` section be used for this kind of thing, or should `$SINGULARITY_ENVIRONMENT` be used?

Also, is the `export` needed at the end of the `%environment` section? I saw it used in the one example I found but not in the docs.

Thanks

**Comment by vsoch** [comment]
This is expected behavior - bootstrap of an image is a one time initial build, and in fact can lead to some weird errors when a directory is made (and then exit 255 because it already exists when you try to make it). if you want to add content after the fact, then you can use import. if you want to extend / change a bootstrap, you might want to consider doing it again. We are definitely in the process of developing a more modular method to avoid conflicts if the user wants to do what might look like a second bootstrap (not sure what to call this). But for now, those two things are my suggestion. What do others think?

For `SINGULARITY_ENVIRONMENT`, this is intended for adding variables to the image environment that aren't known before runtime. These two things would be equivalent:

```
echo "ONE=TWO" >> $SINGULARITY_ENVIRONMENT

%environment
ONE=TWO
```
but likely you wouldn't need the first if you knew that one=two in advance :) Also note that this is added to development, not released master, and this is why it's not well documented - most users won't find they have that functionality.

The environment script is just sourced, so it's up to you if you want to export or not.

**Comment by DeepHorizons** [comment]
Ahh, ok. If that's the case then I'll go back to my old way of doing it, dumping them into a file and sourcing it at the start.

Thanks for the update.
