### ISSUE TITLE
Can't shell into container without using Sudo

### ISSUE THREAD

**Issue by c-guzman** [apptainer/singularity#866]
## Version of Singularity:

2.3.1

### Expected behavior

Run 'singularity shell [image]' and be able to move around container.

### Actual behavior

'singularity shell [image]

bash: __bp_precmd_invoke_cmd: command not found
bash: __bp_interactive_mode: command not found

if I do 'sudo singularity shell [image]' I am able to do everything normally and I don't get this problem.

### Steps to reproduce behavior

Same as above.

**Comment by vsoch** [comment]
I think this issue might have to do with some software installed (that root has access to) but a user would not, which perhaps is sourced / called for the runscript? Could you show me it's definition file, or runscript, or other stuffs?

**Comment by c-guzman** [comment]
```
Bootstrap: docker
From: bioconductor/release_core2

%labels
Maintainer cag104@ucsd.edu
Version 1.0

%environment
export PATH="/root/anaconda2/bin:$PATH"

%post

	apt-get update

	apt-get install -y wget
	
	R --slave -e "source('https://bioconductor.org/biocLite.R'); \
		      biocLite('ChIPQC')"

	R --slave -e "source('https://bioconductor.org/biocLite.R'); \
                      biocLite('groHMM')"

	R --slave -e "source('https://bioconductor.org/biocLite.R'); \
                      biocLite('RUVSeq')"

	R --slave -e "source('https://bioconductor.org/biocLite.R'); \
                      biocLite('edgeR')"

	R --slave -e "source('https://bioconductor.org/biocLite.R'); \
                      biocLite('DESeq2')"

	R --slave -e "source('https://bioconductor.org/biocLite.R'); \
                      biocLite('ChIPseeker')"

	R --slave -e 'install.packages(c("ggplot2", "data.table", "RColorBrewer"), repos="https://cloud.r-project.org/")'

	R --slave -e 'install.packages("http://hartleys.github.io/QoRTs/QoRTs_LATEST.tar.gz", repos=NULL, type="source")'

	wget https://repo.continuum.io/archive/Anaconda2-4.4.0-Linux-x86_64.sh
	bash Anaconda2-4.4.0-Linux-x86_64.sh -b -p $HOME/anaconda2
	export PATH="/root/anaconda2/bin:$PATH"

	conda install -c bioconda --yes  bbmap samtools epic sambamba deeptools macs2 bedtools bedops multiqc subread stringtie nextflow bowtie2 bwa hisat2 star fastqc gimmemotifs

```

**Comment by vsoch** [comment]
First can you try this fix, to unset `PROMPT_COMMAND` ?

https://superuser.com/questions/1007647/bash-how-to-remove-bp-precmd-invoke-cmd-error

you could debug by shelling in as sudo, changing the `/.singularity.d/actions/shell` file to echo that variable, and then seeing what it is. If it's something you don't want, then it should be unset before opening up the shell.

Then I would try installing anaconda to somewhere other than root, somewhere that the user has access to.

**Comment by c-guzman** [comment]
Unsetting the PROMPT_COMMAND let me shell into the container without sudo.

Could you tell me how to install anaconda somewhere other than root? If $HOME == /root/ then i'm not entirely sure where else to place it.

**Comment by vsoch** [comment]
Great!

I'm guessing you want to install to root's home to be consistent with the container you are bootstrapping?
 You are correct that the [container base we trace back to](https://github.com/Bioconductor/bioc_docker/blob/master/out/release_base/Dockerfile) references `$HOME`, and given it already being generated you don't have much say in that. However that's for the R bits, probably you will be having having that and then installing anaconda elsewhere. You can just set a prefix like `-p /opt/anaconda3` instead of `$HOME` (and I don't remember if the directory needs to exist first). Another good place is `/usr/local`.

If there is some dependency on R/python needing to be in the same place, what you could do is start with the rocker rstudio image (linked above) and then make the `.Rprofile` install somewhere else. It's just echoing a `library()` command, so it's not such a crazy idea to just not use the base at all.

**Comment by c-guzman** [comment]
Was able to solve this by installing to a directory other than root as suggested. You can consider this resolved!

**Comment by vsoch** [comment]
Awesome! I'll close the issue. Please ping again if you have trouble.
