### ISSUE TITLE
bootstrap RunCmd and RunScript need clarifying

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#91]
It seems as if RunCmd is meant only to take a single arg.
Also RunScript potentially will have problems with shell expansion/word splitting unless the args are appropriately quoted.
I think that needs documenting.

**Comment by gmkurtzer** [comment]
Yeah, I was messing with this a bit last night. Notice my change to the
example/debian.def.

Because this is all happening and being passed through shell I don't see a
way to do it that doesn't loose some quoting or use <<< which alpine
Linux's implementation of Bash does not support.

If it must be a single argument, so be it and it will be documented
appropriately.... But I dislike that.

Any other ideas?

On Friday, June 24, 2016, Dave Love notifications@github.com wrote:

> It seems as if RunCmd is meant only to take a single arg.
> Also RunScript potentially will have problems with shell expansion/word
> splitting unless the args are appropriately quoted.
> I think that needs documenting.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/gmkurtzer/singularity/issues/91, or mute the thread
> https://github.com/notifications/unsubscribe/ANVkxYNbp5tFJOgxpFeuRwvS8PYlxngGks5qO9RDgaJpZM4I9ve7
> .

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by loveshack** [comment]
I removed this when I saw the RunCmd change.  It's clearly more
difficult quoting-wise if you use sh -c; is that necessary?

```
--- a/libexec/mods/linux_build.smod
+++ b/libexec/mods/linux_build.smod
@@ -157,7 +157,11 @@ RunScript() {
         chmod +x "$SINGULARITY_BUILD_ROOT/singularity"
     fi

-    echo "$@" >> "$SINGULARITY_BUILD_ROOT/singularity"
+    for arg in "$@"; do
+        local qq="'\''"
+        printf "'%s' " "${arg//\'/$qq}" >> "$SINGULARITY_BUILD_ROOT/singularity"
+    done
+    echo >> "$SINGULARITY_BUILD_ROOT/singularity"

     return 0
 }
```

I don't know why <<< is necessary, but it's been in bash since the last
v2 release which can't be in any current distribution.  Even Solaris 10
has v3.

**Comment by gmkurtzer** [comment]
Yes, that's right.. the /bin/sh -c ... really did make it extra complex and considering chroot calls execvp(), /bin/sh -c ... is already getting called, so there wasn't really any need to do it again.

Does your patch resolve some of the quoting issues that the current echo "$@" still has? I am happy to integrate it if so.

I liked <<< because it fixed several cases of quoting complexities.

**Comment by loveshack** [comment]
You wrote: 

> Yes, that's right.. the /bin/sh -c ... really did make it extra
> complex and considering chroot calls execvp(), /bin/sh -c ... is
> already getting called, so there wasn't really any need to do it
> again.
> 
> Does your patch resolve some of the quoting issues that the current
> echo "$@" still has? I am happy to integrate it if so.

I hope so.  I tried to break it, but no warranty.

> I liked <<< because it fixed several cases of quoting complexities.

I can believe it, and I don't understand why you can't use it as I doubt
there's any distribution with bash 2 that will run Singularity.  I'd
have though you could use << in most places, but it's definitely more
awkward.

**Comment by gmkurtzer** [comment]
I will integrate your patch, thanks!

I had to remove the <<< because whatever version of bash that Alpine Linux uses didn't support it... This was reported in a previous ticket by @truatpasteurdotfr so I removed all of the instances of <<< (which was a shame, and one of the primary reasons I switched #!/bin/sh to #!/bin/bash).

**Comment by gmkurtzer** [comment]
@loveshack The patch you provided doesn't seem to work as I would expect. This is what is in the definition file:

```
RunScript echo "Hello: $@"
RunScript "echo byes"
```

And this is what it produces in /singularity:

```
'echo' 'Hello: ' 
'echo byes' 
```

I will provide more info as I debug.

**Comment by loveshack** [comment]
You wrote: 

> @loveshack The patch you provided doesn't seem to work as I would
> expect. This is what is in the definition file:
> 
> ```
> RunScript echo "Hello: $@"
> RunScript "echo byes"
> ```

It looks as is it's working as intended (for multiple arguments, not a
single string.  The expansion of $@ happens when RunScript is executed.)

**Comment by gmkurtzer** [comment]
I spent some time rewriting how the RunScript gets parsed to ensure that nothing gets changed or modified by the shell. Take a look at the code if you want to, but I am pretty sure (at least for RunScript) it will get pushed into /singularity without an issue now.

If I am wrong, comment on this issue, and I'll reopen it.

Thanks!

**Comment by loveshack** [comment]
You wrote: 

> I spent some time rewriting how the RunScript gets parsed to ensure
> that nothing gets changed or modified by the shell. Take a look at the
> code if you want to, but I am pretty sure (at least for RunScript) it
> will get pushed into /singularity without an issue now.

Is it supposed to take a single argument or multiple words now?  The
documentation doesn't say.

**Comment by gmkurtzer** [comment]
It shouldn't matter as it no longer parses them from a shell syntax.
Whatever is there, will be transferred to /singularity verbatim.

On Fri, Jul 8, 2016 at 6:23 AM, Dave Love notifications@github.com wrote:

> You wrote:
> 
> > I spent some time rewriting how the RunScript gets parsed to ensure
> > that nothing gets changed or modified by the shell. Take a look at the
> > code if you want to, but I am pretty sure (at least for RunScript) it
> > will get pushed into /singularity without an issue now.
> 
> Is it supposed to take a single argument or multiple words now? The
> documentation doesn't say.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/gmkurtzer/singularity/issues/91#issuecomment-231357974,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANVkxa0-f26kWNaDa88JFBzktq56oSwXks5qTk9LgaJpZM4I9ve7
> .

## 

Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720
