### ISSUE TITLE
The --home option may accidentally copy files to the host system

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#956]
## Version of Singularity:
2.3.9-development.ga10e269

### Expected behavior
If you use the `--home` option it should not change the data on your host system.

### Actual behavior
Depending on how you call it and what directory you happen to be in, the home option may inadvertently copy data from one directory to another on your host system.  
 
### Steps to reproduce behavior
First create some directories and touch some files.
```
$ sudo mkdir /data
$ sudo chown $USER:$USER /data
$ touch /data/foo
$ mkdir ~/somedir
```
Now cd into the second directory and start a singularity shell session using the first directory as your `$HOME` location.
```
$ cd ~/somedir
$ singularity shell --home /data:/home/$USER container.img
$ exit
```
Now you will find that `~/somdir` has been copied to `/data` on your host system.
```
$ ls /data
foo  somedir
```

**Comment by cclerget** [comment]
@GodloveD it's because following code is reached: https://github.com/singularityware/singularity/blob/c25f8e7399d6aa215346f45f609f6394dffb796e/src/lib/runtime/mounts/cwd/cwd.c#L134 but the main problem here is with check_mounted function: https://github.com/singularityware/singularity/blob/c25f8e7399d6aa215346f45f609f6394dffb796e/src/lib/runtime/mounts/cwd/cwd.c#L91 which failed at looking already mounted path. You can trigger this bug with old versions too

If you create a file when you are in the directory in container, it will not appear in /data/somedir so singularity just create the CWD directory on host filesystem because /data has been mounted as HOME just before

In this case check_mounted take cwd_path = /home/$USER/somedir
/home/$USER is already mounted but since check_mounted search path name in /proc/mounts for /home/$USER/somedir, it failed

check_mounted fails in this case but fails too when symlinks are used in binding paths. Fix should be there soon, I hope for 2.4 release

**Comment by cclerget** [comment]
Seems it's related, just leave that here :

# Version of Singularity

2.3.9 and below

# Expected behavior

```
$ cd ~/
$ singularity shell -H /data:/home/$USER
```

PWD=$HOME, $HOME directory is mounted in container in place of /data

**Comment by GodloveD** [comment]
Hey @cclerget and @gmkurtzer I just tried this out again with latest development branch and it is still causing the same bug.

**Comment by gmkurtzer** [comment]
I think this is fixed now, @GodloveD, can you try again?

Thanks!

**Comment by GodloveD** [comment]
Yup.  Looks fixed!  Closing.  Thanks.

**Comment by gmkurtzer** [comment]
Squashing bugs left and right!
